package
{
   public class GameRes_DefenceTechXml
   {
      
      public static var data:XML = <DefenceTech Name="EN-防御科技">
  <List GroupID="70" Name="Ship Defense Tech" Comment="Increase base shield, structure, agility, defense of ships and ship stability; Lv1: +2% base shield, structure, agility, defense of ships and +5% ship stability." Kind="0" Tech="" ImageFileName="Tech70" Title="0/2" TechMemo="">
    <Level1 GroupLV="1" Comment="Current Level: +2% base shield, structure, agility, defense of ships and +5% ship stability; Next level: +5% base shield, structure, agility, defense of ships and +10% ship stability." Title="1/2" Money="2846 " Time="3240" Shield="0.02" Endure="0.02" Yare="0.02" Defend="0.02" Stability="0.05"/>
    <Level2 GroupLV="2" Comment="Current Level: &lt;font color='#00FF00'&gt;+5%&lt;/font&gt; base shield, structure, agility, defense of ships and &lt;font color='#00FF00'&gt;+10%&lt;/font&gt; ship stability." Title="2" Money="3295 " Time="4343" Shield="0.05" Endure="0.05" Yare="0.05" Defend="0.05" Stability="0.1"/>
  </List>
  <List GroupID="71" Name="Shield Research" Comment="Increase base shield of ships; Lv1: +1% base shield of ships." Kind="0" Tech="70:1" ImageFileName="Tech71" Title="0/5" TechMemo="Requires Ship Defense Tech Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: Increase base shield of ships by 1%; Next level: +2% base shield of ships." Title="1/5" Money="10392 " Time="2700" Shield="0.01"/>
    <Level2 GroupLV="2" Comment="Current Level: Increase base shield of ships by 2%; Next level: +3% base shield of ships." Title="2/5" Money="12032 " Time="3619" Shield="0.02"/>
    <Level3 GroupLV="3" Comment="Current Level: Increase base shield of ships by 3%; Next level: +4% base shield of ships." Title="3/5" Money="18407 " Time="8470" Shield="0.03"/>
    <Level4 GroupLV="4" Comment="Current Level: Increase base shield of ships by 4%; Next level: +5% base shield of ships." Title="4/5" Money="28158 " Time="19822" Shield="0.04"/>
    <Level5 GroupLV="5" Comment="Current Level: Increase base shield of ships by &lt;font color='#00FF00'&gt;5%&lt;/font&gt;." Title="5" Money="43076 " Time="46389" Shield="0.05"/>
  </List>
  <List GroupID="72" Name="Energy Diffusion Tech" Comment="Enable each shield module to reduce damage; Lv1: Enable each shield module to reduce damage taken by 1." Kind="0" Tech="70:2;71:3" ImageFileName="Tech72" Title="0/3" TechMemo="Requires Ship Defense Tech Lv 2, Shield Research Lv 3">
    <Level1 GroupLV="1" Comment="Current Level: Enable each shield module to reduce damage taken by 1; Next level: Enable each shield module to reduce damage taken by 2." Title="1/3" Money="46765 " Time="10800" Counteract="1"/>
    <Level2 GroupLV="2" Comment="Current Level: Enable each shield module to reduce damage taken by 2; Next level: Enable each shield module to reduce damage taken by 3." Title="2/3" Money="54142 " Time="14476" Counteract="2"/>
    <Level3 GroupLV="3" Comment="Current Level: Enable each shield module to reduce damage taken by &lt;font color='#00FF00'&gt;3&lt;/font&gt;." Title="3" Money="82828 " Time="33879" Counteract="3"/>
  </List>
  <List GroupID="73" Name="Penetration Resistance" Comment="Reduce an enemy's chance of penetrating shield; Lv1: Decrease enemy's chance of penetrating shield by 3%. " Kind="0" Tech="71:5;72:1" ImageFileName="Tech73" Title="0/2" TechMemo="Requires Shield Research Lv 5, Energy Diffusion Tech Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: Decrease enemy's chance of penetrating shield by 3%; Next level: Decrease enemy's chance of penetrating shield by 7%." Title="1/2" Money="117576 " Time="21600" CounteractCross="0.03"/>
    <Level2 GroupLV="2" Comment="Current Level: Decrease enemy's chance of penetrating shield by &lt;font color='#00FF00'&gt;7%&lt;/font&gt;." Title="2" Money="136122 " Time="28952" CounteractCross="0.07"/>
  </List>
  <List GroupID="74" Name="Augment Shield" Comment="Increase base shield of ships; Lv1: +6% base shield of ships." Kind="0" Tech="72:2;73:1" ImageFileName="Tech74" Title="0/3" TechMemo="Requires Energy Diffusion Tech Lv 2, Penetration Resistance 1">
    <Level1 GroupLV="1" Comment="Current Level: Increase base shield of ships by 6%; Next level: +13% base shield of ships." Title="1/3" Money="248747 " Time="39600" Shield="0.06"/>
    <Level2 GroupLV="2" Comment="Current Level: Increase base shield of ships by 13%; Next level: +20% base shield of ships." Title="2/3" Money="287983 " Time="53078" Shield="0.13"/>
    <Level3 GroupLV="3" Comment="Current Level: Increase base shield of ships by &lt;font color='#00FF00'&gt;20%&lt;/font&gt;." Title="3" Money="440562 " Time="124221" Shield="0.2"/>
  </List>
  <List GroupID="75" Name="Restoration" Comment="Allows ships to restore 30% more Shields at the beginning of each round, if there is a module equipped that restores Shields. Also increases anti-aircraft modules' interception chance by 1%. Stackable with Commander skills." Kind="0" Tech="72:3;74:2" ImageFileName="Tech75" Title="0/2" TechMemo="Requires Energy Diffusion Tech Lv 3, Augment Shield Lv 2">
    <Level1 GroupLV="1" Comment="Allows ships to restore 30% more Shields at the beginning of each round, if there is a module equipped that restores Shields. Also increases anti-aircraft modules' interception chance by 1%. Stackable with Commander skills; Next Level: Allows ships to restore 60% more Shields at the beginning of each round, if there is a module equipped that restores Shields. Also increases anti-aircraft modules' interception chance by 2%. Stackable with Commander skills." Title="1/2" Money="540000 " Time="90000" RepairShieldBout="0.3" Intercept="0.01"/>
    <Level2 GroupLV="2" Comment="Current Level: Allows ships to restore &lt;font color='#00FF00'&gt;60%&lt;/font&gt; more Shields at the beginning of each round, if there is a module equipped that restores Shields. Also, increases anti-aircraft modules' interception chance by &lt;font color='#00FF00'&gt;+2%&lt;/font&gt;. Stackable with Commander skills." Title="2" Money="625178 " Time="120632" RepairShieldBout="0.6" Intercept="0.02"/>
  </List>
  <List GroupID="76" Name="Augment Absorption" Comment="Enable each shield module to reduce damage; Lv1: Enable shield modules to reduce damage taken by 2 points." Kind="0" Tech="71:5;72:1" ImageFileName="Tech76" Title="0/2" TechMemo="Requires Shield Research Lv 5, Energy Diffusion Tech Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: Enable shield modules to reduce damage taken by 2 points; Next level: Enable shield modules to reduce damage taken by 5 points." Title="1/2" Money="117576 " Time="21600" Counteract="2"/>
    <Level2 GroupLV="2" Comment="Current Level: Enable shield modules to reduce damage taken by &lt;font color='#00FF00'&gt;5&lt;/font&gt; points." Title="2" Money="136122 " Time="28952" Counteract="5"/>
  </List>
  <List GroupID="77" Name="Energy Conservation" Comment="Grant modules chance of absorbing damage without using He3; Lv1: +3% chance of absorbing damage without using He3." Kind="0" Tech="72:2;76:1" ImageFileName="Tech77" Title="0/3" TechMemo="Requires Energy Diffusion Tech Lv 2, Augment Absorption Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: +3% chance of absorbing damage without using He3; Next level: +6% chance of absorbing damage without using He3." Title="1/3" Money="248747 " Time="39600" NoConsumeHe3="0.03"/>
    <Level2 GroupLV="2" Comment="Current Level: +6% chance of absorbing damage without using He3; Next level: +10% chance of absorbing damage without using He3." Title="2/3" Money="287983 " Time="53078" NoConsumeHe3="0.06"/>
    <Level3 GroupLV="3" Comment="Current Level: &lt;font color='#00FF00'&gt;+10%&lt;/font&gt; chance of absorbing damage without using He3." Title="3" Money="440562 " Time="124221" NoConsumeHe3="0.1"/>
  </List>
  <List GroupID="78" Name="Electronic Barrier" Comment="Allow fleet to reflect damage taken back at attacker before shield drops to 0; Lv1: Allow fleet to reflect 5% damage taken back at attacker before shield drops to 0." Kind="0" Tech="72:3;77:2" ImageFileName="Tech78" Title="0/2" TechMemo="Requires Energy Diffusion Tech Lv 3, Energy Conservation Lv 2">
    <Level1 GroupLV="1" Comment="Current Level: Allow fleet to reflect 5% damage taken back at attacker before shield drops to 0; Next level: Allow fleet to reflect 10% damage taken back at attacker before shield drops to 0." Title="1/2" Money="540000 " Time="90000" Reflex="0.05"/>
    <Level2 GroupLV="2" Comment="Current Level: Allow fleet to reflect &lt;font color='#00FF00'&gt;10%&lt;/font&gt; damage taken back at attacker before shield drops to 0." Title="2" Money="625178 " Time="120632" Reflex="0.1"/>
  </List>
  <List GroupID="79" Name="Damage Mitigation" Comment="Allow damage absorbing modules to absorb double damage when activated. Also lower collateral damage taken when shield receives scattering or penetration attacks; Lv1: 10% chance of absorbing double damage and 15% chance of lowering collateral damage." Kind="0" Tech="74:3;75:2;77:3;78:2" ImageFileName="Tech79" Title="0/3" TechMemo="Requires Augment Shield Lv 3, Restoration Lv 2, Energy Conservation Lv 3, Electronic Barrier2">
    <Level1 GroupLV="1" Comment="Current Level: 10% chance of absorbing double damage and 15% chance of lowering collateral damage; Next level: 20% chance of absorbing double damage and 30% chance of lowering collateral damage." Title="1/3" Money="805152 " Time="108000" Double="0.1" ShieldLowerScattering="0.15"/>
    <Level2 GroupLV="2" Comment="Current Level: 20% chance of absorbing double damage and 30% chance of lowering collateral damage; Next level: 30% chance of absorbing double damage and 45% chance of lowering collateral damage." Title="2/3" Money="932153 " Time="144758" Double="0.2" ShieldLowerScattering="0.3"/>
    <Level3 GroupLV="3" Comment="Current Level: &lt;font color='#00FF00'&gt;30%&lt;/font&gt; chance of absorbing double damage and &lt;font color='#00FF00'&gt;45%&lt;/font&gt; chance of lowering collateral damage." Title="3" Money="1426024 " Time="338783" Double="0.3" ShieldLowerScattering="0.45"/>
  </List>
  <List GroupID="80" Name="Ship Structural Analysis" Comment="Increase base structure of ships; Lv1: +1% base structure of ships." Kind="0" Tech="70:1" ImageFileName="Tech80" Title="0/5" TechMemo="Requires Ship Defense Tech Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: Increase base structure of ships by 1%; Next level: +2% base structure of ships." Title="1/5" Money="10392 " Time="2700" Endure="0.01"/>
    <Level2 GroupLV="2" Comment="Current Level: Increase base structure of ships by 2%; Next level: +3% base structure of ships." Title="2/5" Money="12032 " Time="3619" Endure="0.02"/>
    <Level3 GroupLV="3" Comment="Current Level: Increase base structure of ships by 3%; Next level: +4% base structure of ships." Title="3/5" Money="18407 " Time="8470" Endure="0.03"/>
    <Level4 GroupLV="4" Comment="Current Level: Increase base structure of ships by 4%; Next level: +5% base structure of ships." Title="4/5" Money="28158 " Time="19822" Endure="0.04"/>
    <Level5 GroupLV="5" Comment="Current Level: Increase base structure of ships by &lt;font color='#00FF00'&gt;5%&lt;/font&gt;." Title="5" Money="43076 " Time="46389" Endure="0.05"/>
  </List>
  <List GroupID="81" Name="Ship Reinforcement Tech" Comment="Increase ship stability; Lv1: Increase ship stability by 8%." Kind="0" Tech="70:2;80:3" ImageFileName="Tech81" Title="0/3" TechMemo="Requires Ship Defense Tech Lv 2, Ship Structural Analysis Lv 3">
    <Level1 GroupLV="1" Comment="Current Level: Increase ship stability by 8%; Next level: +16% ship stability." Title="1/3" Money="46765 " Time="10800" Stability="0.08"/>
    <Level2 GroupLV="2" Comment="Current Level: Increase ship stability by 16%; Next level: +25% ship stability." Title="2/3" Money="54142 " Time="14476" Stability="0.16"/>
    <Level3 GroupLV="3" Comment="Current Level: Increase ship stability by &lt;font color='#00FF00'&gt;25%&lt;/font&gt;." Title="3" Money="82828 " Time="33879" Stability="0.25"/>
  </List>
  <List GroupID="82" Name="Resilience" Comment="Increase agility of fleet and reduce enemy's critical strike damage; Lv1: +5% agility of fleet and -7% enemy's critical strike damage." Kind="0" Tech="80:5;81:1" ImageFileName="Tech82" Title="0/2" TechMemo="Requires Ship Structural Analysis Lv 5, Ship Reinforcement Tech Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: +5% agility of fleet and -7% enemy's critical strike damage; Next level: +10% agility of fleet and -15% enemy's critical strike damage." Title="1/2" Money="117576 " Time="21600" Yare="0.05" LowerBlastHurt="0.07"/>
    <Level2 GroupLV="2" Comment="Current Level: &lt;font color='#00FF00'&gt;+10%&lt;/font&gt; agility of fleet and &lt;font color='#00FF00'&gt;-15%&lt;/font&gt; enemy's critical strike damage." Title="2" Money="136122 " Time="28952" Yare="0.1" LowerBlastHurt="0.15"/>
  </List>
  <List GroupID="83" Name="Structure Improvement" Comment="Increase base structure of ships; Lv1: +5% base structure of ships" Kind="0" Tech="81:2;82:1" ImageFileName="Tech83" Title="0/3" TechMemo="Requires Ship Reinforcement Tech Lv 2, Resilience Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: Increase base structure of ships by 5%; Next level: +10% base structure of ships." Title="1/3" Money="248747 " Time="39600" Endure="0.05"/>
    <Level2 GroupLV="2" Comment="Current Level: Increase base structure of ships by 10%; Next level: +15% base structure of ships." Title="2/3" Money="287983 " Time="53078" Endure="0.1"/>
    <Level3 GroupLV="3" Comment="Current Level: &lt;font color='#00FF00'&gt;+15%&lt;/font&gt; base structure of ships." Title="3" Money="440562 " Time="124221" Endure="0.15"/>
  </List>
  <List GroupID="84" Name="Fast Repair Tech" Comment="Allows ships to restore 30% more Structure at the beginning of each round, if there is a module equipped that restores Structure. Also, increases anti-aircraft modules' interception chance by 1%. Stackable with Commander skills." Kind="0" Tech="81:3;83:2" ImageFileName="Tech84" Title="0/2" TechMemo="Requires Ship Reinforcement Tech Lv 3, Structure Improvement Lv 2">
    <Level1 GroupLV="1" Comment="Allows ships to restore 30% more Structure at the beginning of each round, if there is a module equipped that can restore Structure. Also, increases anti-aircraft modules' interception chance by 1%. Stackable with Commander skills; Next Level: Allows ships to restore 60% more Structure at the beginning of each round, if there is a module equipped that can restore Structure. Also, increases anti-aircraft modules' interception chance by 2%. Stackable with Commander skills." Title="1/2" Money="540000 " Time="90000" Intercept="0.01" ComebackDurability="0.3"/>
    <Level2 GroupLV="2" Comment="Current Level: Allows ships to restore &lt;font color='#00FF00'&gt;60%&lt;/font&gt; more Structure at the beginning of each round, if there is a module equipped that can restore Structure. Also, increases anti-aircraft modules' interception chance by &lt;font color='#00FF00'&gt;+2%&lt;/font&gt;." Title="2" Money="625178 " Time="120632" Intercept="0.02" ComebackDurability="0.6"/>
  </List>
  <List GroupID="85" Name="Reaction Armor Improvement" Comment="Enable reaction armor to reduce damage and increase ship stability; Lv1: Reduce damage taken from reaction armor by 10% and +10% to ship stability." Kind="0" Tech="80:5;81:1" ImageFileName="Tech85" Title="0/2" TechMemo="Requires Ship Structural Analysis Lv 5, Ship Reinforcement Tech Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: Reduce damage taken from reaction armor by 10% and +10% to ship stability; Next level: Reduce damage taken from reaction armor by 20% and +20% to ship stability." Title="1/2" Money="117576 " Time="21600" Stability="0.1" HarmReduction="0.1"/>
    <Level2 GroupLV="2" Comment="Current Level: Reduce damage taken from reaction armor by &lt;font color='#00FF00'&gt;20%&lt;/font&gt; and &lt;font color='#00FF00'&gt;+20%&lt;/font&gt; to ship stability." Title="2" Money="136122 " Time="28952" Stability="0.2" HarmReduction="0.2"/>
  </List>
  <List GroupID="86" Name="Defense Improvement" Comment="Increase defense of ships and enable all armors to reduce damage; Lv1: +5% to ship defense and decrease damage taken by all armors by 3%. " Kind="0" Tech="81:2;85:1" ImageFileName="Tech86" Title="0/3" TechMemo="Requires Ship Reinforcement Tech Lv 2, Reaction Armor Improvement Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: +5% to ship defense and decrease damage taken by all armors by 3%; Next level: +10% to ship defense and decrease damage taken by all armors by 6%." Title="1/3" Money="248747 " Time="39600" Defend="0.05" ArmorHurt="1:0.03;2:0.03;3:0.03;4:0.03;5:0.03;6:0.03"/>
    <Level2 GroupLV="2" Comment="Current Level: +10% to ship defense and decrease damage taken by all armors by 6%; Next level: +15% to ship defense and decrease damage taken by all armors by 10%." Title="2/3" Money="287983 " Time="53078" Defend="0.1" ArmorHurt="1:0.06;2:0.06;3:0.06;4:0.06;5:0.06;6:0.06"/>
    <Level3 GroupLV="3" Comment="Current Level: &lt;font color='#00FF00'&gt;+15%&lt;/font&gt; to ship defense and decrease damage taken by all armors by &lt;font color='#00FF00'&gt;10%&lt;/font&gt;." Title="3" Money="440562 " Time="124221" Defend="0.15" ArmorHurt="1:0.1;2:0.1;3:0.1;4:0.1;5:0.1;6:0.1"/>
  </List>
  <List GroupID="87" Name="Reflection Mastery" Comment="Enable reactivation of armor modules to reflect damage; Lv1: Enable reactivation of armor modules to reflect damage after 2 rounds of reloading." Kind="0" Tech="81:3;86:2" ImageFileName="Tech87" Title="0/2" TechMemo="Requires Ship Reinforcement Tech 3, Defense Improvement Lv 2">
    <Level1 GroupLV="1" Comment="Current Level: Enable reactivation of armor modules to reflect damage after 2 rounds of reloading; Next level: Enable reactivation of armor modules to reflect damage after 1 rounds of reloading." Title="1/2" Money="540000 " Time="90000" CD="2"/>
    <Level2 GroupLV="2" Comment="Current Level: Enable reactivation of armor modules to reflect damage after &lt;font color='#00FF00'&gt;1&lt;/font&gt; rounds of reloading." Title="2" Money="625178 " Time="120632" CD="1"/>
  </List>
  <List GroupID="88" Name="Stability Mastery" Comment="When the Daedelus Control System is activated by an attack, this level of proficiency provides a chance to increase ship stability by 100%, reduces damage taken from the attack by 40% and reduces the attacker's critical strike chance by 5%. Also reduces dispersion and piercing damage to the fleet's durability and increases chance to intercept airborne weapons; Next level: Provides a 10% chance to increase ship stability by 100%, reduces damage taken from the attack by 40% and reduces the attacker's critical strike chance by 5%. Also reduces dispersion and piercing damage to the fleet's durability by 5% and increases chance to intercept airborne weapons by 2%." Kind="0" Tech="83:3;84:2;86:3;87:2" ImageFileName="Tech88" Title="0/3" TechMemo="Requires Structure Improvement Lv 3, Fast Repair Tech Lv 2, Defense Improvement Lv 3, Reflection Mastery Lv 2">
    <Level1 GroupLV="1" Comment="When the Daedelus Control System is activated by an attack, this level of proficiency provides a 10% chance to increase ship stability by 100%, reduces damage taken from the attack by 40% and reduces the attacker's critical strike chance by 5%. Also reduces dispersion and piercing damage to the fleet's durability by 5% and increases chance to intercept airborne weapons by 2%; Next level: Provides a 20% chance to increase ship stability by 100%, reduces damage taken from the attack by 40% and reduces the attacker's critical strike chance by 5%. Also reduces dispersion and piercing damage to the fleet's durability by 10% and increases chance to intercept airborne weapons by 4%." Title="1/3" Money="805152 " Time="108000" Intercept="0.02" LowerBlastHurt="0.05" StabilityOdds="0.1" AugmentStability="1" LowerDamage="0.4" LowerScattering="0.05"/>
    <Level2 GroupLV="2" Comment="When the Daedelus Control System is activated by an attack, this level of proficiency provides a 20% chance to increase ship stability by 100%, reduces damage taken from the attack by 40% and reduces the attacker's critical strike chance by 5%. Also reduces dispersion and piercing damage to the fleet's durability by 10% and increases chance to intercept airborne weapons by 4%; Next level: Provides a 30% chance to increase ship stability by 100%, reduces damage taken from the attack by 40% and reduces the attacker's critical strike chance by 5%. Also reduces dispersion and piercing damage to the fleet's durability by 15% and increases chance to intercept airborne weapons by 6%." Title="2/3" Money="932153 " Time="144758" Intercept="0.04" LowerBlastHurt="0.05" StabilityOdds="0.2" AugmentStability="1" LowerDamage="0.4" LowerScattering="0.1"/>
    <Level3 GroupLV="3" Comment="When the Daedelus Control System is activated by an attack, this level of proficiency provides a &lt;font color='#00FF00'&gt;30%&lt;/font&gt; chance to increase ship stability by &lt;font color='#00FF00'&gt;100%&lt;/font&gt;, reduces damage taken from the attack by &lt;font color='#00FF00'&gt;40%&lt;/font&gt; and reduces the attacker's critical strike chance by &lt;font color='#00FF00'&gt;5%&lt;/font&gt; Also reduces dispersion and piercing damage to the fleet's durability by &lt;font color='#00FF00'&gt;15%&lt;/font&gt; and increases chance to intercept airborne weapons by &lt;font color='#00FF00'&gt;+6%&lt;/font&gt;." Title="3" Money="1426024 " Time="338783" Intercept="0.06" LowerBlastHurt="0.05" StabilityOdds="0.3" AugmentStability="1" LowerDamage="0.4" LowerScattering="0.15"/>
  </List>
  <List GroupID="89" Name="Energy Control" Comment="Reduces the amount of resources needed to build defensive structures; Lv1: Reduces the amount of resources needed to build defensive structures by 1%." Kind="1" Tech="" ImageFileName="Tech89" Title="0/10" TechMemo="">
    <Level1 GroupLV="1" Comment="Current Level: Reduces the amount of resources needed to build defensive structures by 1%; Next level: Reduces the amount of resources needed to build defensive structures by 2%." Title="1/10" Money="2500 " Time="500" DecreaseMetalConsume="1" DecreaseHe3Consume="1" DecreaseMoneyConsume="1"/>
    <Level2 GroupLV="2" Comment="Current Level: Reduces the amount of resources needed to build defensive structures by 2%; Next level: Reduces the amount of resources needed to build defensive structures by 3%." Title="2/10" Money="5000 " Time="1000" DecreaseMetalConsume="2" DecreaseHe3Consume="2" DecreaseMoneyConsume="2"/>
    <Level3 GroupLV="3" Comment="Current Level: Reduces the amount of resources needed to build defensive structures by 3%; Next level: Reduces the amount of resources needed to build defensive structures by 4%." Title="3/10" Money="10000 " Time="2000" DecreaseMetalConsume="3" DecreaseHe3Consume="3" DecreaseMoneyConsume="3"/>
    <Level4 GroupLV="4" Comment="Current Level: Reduces the amount of resources needed to build defensive structures by 4%; Next level: Reduces the amount of resources needed to build defensive structures by 5%." Title="4/10" Money="20000 " Time="4000" DecreaseMetalConsume="4" DecreaseHe3Consume="4" DecreaseMoneyConsume="4"/>
    <Level5 GroupLV="5" Comment="Current Level: Reduces the amount of resources needed to build defensive structures by 5%; Next level: Reduces the amount of resources needed to build defensive structures by 6%." Title="5/10" Money="40000 " Time="8000" DecreaseMetalConsume="5" DecreaseHe3Consume="5" DecreaseMoneyConsume="5"/>
    <Level6 GroupLV="6" Comment="Current Level: Reduces the amount of resources needed to build defensive structures by 6%; Next level: Reduces the amount of resources needed to build defensive structures by 7%." Title="6/10" Money="80000 " Time="16000" DecreaseMetalConsume="6" DecreaseHe3Consume="6" DecreaseMoneyConsume="6"/>
    <Level7 GroupLV="7" Comment="Current Level: Reduces the amount of resources needed to build defensive structures by 7%; Next level: Reduces the amount of resources needed to build defensive structures by 8%." Title="7/10" Money="160000 " Time="32000" DecreaseMetalConsume="7" DecreaseHe3Consume="7" DecreaseMoneyConsume="7"/>
    <Level8 GroupLV="8" Comment="Current Level: Reduces the amount of resources needed to build defensive structures by 8%; Next level: Reduces the amount of resources needed to build defensive structures by 9%." Title="8/10" Money="320000 " Time="64000" DecreaseMetalConsume="8" DecreaseHe3Consume="8" DecreaseMoneyConsume="8"/>
    <Level9 GroupLV="9" Comment="Current Level: Reduces the amount of resources needed to build defensive structures by 9%; Next level: Reduces the amount of resources needed to build defensive structures by 10%." Title="9/10" Money="640000 " Time="128000" DecreaseMetalConsume="9" DecreaseHe3Consume="9" DecreaseMoneyConsume="9"/>
    <Level10 GroupLV="10" Comment="Current Level: Reduces the amount of resources needed to build defensive structures by &lt;font color='#00FF00'&gt;10%&lt;/font&gt;." Title="10" Money="1280000 " Time="256000" DecreaseMetalConsume="10" DecreaseHe3Consume="10" DecreaseMoneyConsume="10"/>
  </List>
  <List GroupID="90" Name="Rapid Defense Buildup" Comment="Increases construction speed of Defensive structures; Lv1: Increases construction speed of Defensive structures by 1%." Kind="1" Tech="89:1" ImageFileName="Tech90" Title="0/10" TechMemo="Requires Energy Control Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: Increases construction speed of Defensive structures by 1%; Next level: Increases construction speed of Defensive structures by 2%." Title="1/10" Money="3000 " Time="600" IncreaseBuilding="1"/>
    <Level2 GroupLV="2" Comment="Current Level: Increases construction speed of Defensive structures by 2%; Next level: Increases construction speed of Defensive structures by 3%." Title="2/10" Money="6000 " Time="1200" IncreaseBuilding="2"/>
    <Level3 GroupLV="3" Comment="Current Level: Increases construction speed of Defensive structures by 3%; Next level: Increases construction speed of Defensive structures by 4%." Title="3/10" Money="12000 " Time="2400" IncreaseBuilding="3"/>
    <Level4 GroupLV="4" Comment="Current Level: Increases construction speed of Defensive structures by 4%; Next level: Increases construction speed of Defensive structures by 5%." Title="4/10" Money="24000 " Time="4800" IncreaseBuilding="4"/>
    <Level5 GroupLV="5" Comment="Current Level: Increases construction speed of Defensive structures by 5%; Next level: Increases construction speed of Defensive structures by 6%." Title="5/10" Money="48000 " Time="9600" IncreaseBuilding="5"/>
    <Level6 GroupLV="6" Comment="Current Level: Increases construction speed of Defensive structures by 6%; Next level: Increases construction speed of Defensive structures by 7%." Title="6/10" Money="96000 " Time="19200" IncreaseBuilding="6"/>
    <Level7 GroupLV="7" Comment="Current Level: Increases construction speed of Defensive structures by 7%; Next level: Increases construction speed of Defensive structures by 8%." Title="7/10" Money="192000 " Time="38400" IncreaseBuilding="7"/>
    <Level8 GroupLV="8" Comment="Current Level: Increases construction speed of Defensive structures by 8%; Next level: Increases construction speed of Defensive structures by 9%." Title="8/10" Money="384000 " Time="76800" IncreaseBuilding="8"/>
    <Level9 GroupLV="9" Comment="Current Level: Increases construction speed of Defensive structures by 9%; Next level: Increases construction speed of Defensive structures by 10%." Title="9/10" Money="768000 " Time="153600" IncreaseBuilding="9"/>
    <Level10 GroupLV="10" Comment="Current Level: Increases construction speed of Defensive structures by &lt;font color='#00FF00'&gt;10%&lt;/font&gt;." Title="10" Money="1536000 " Time="307200" IncreaseBuilding="10"/>
  </List>
  <List GroupID="91" Name="Defense Enhancement" Comment="Increases the defensive value of all structures; Lv1: Increases the defensive value of all structures by 1%." Kind="1" Tech="89:3;90:3" ImageFileName="Tech91" Title="0/10" TechMemo="Requires Energy Control Lv 3, Rapid Defense Buildup Lv 3">
    <Level1 GroupLV="1" Comment="Current Level: Increases the defense value of all structures by 1%; Next level: Increases the defense value of all structures by 2%." Title="1/10" Money="1500 " Time="300" AddDefend="0.01"/>
    <Level2 GroupLV="2" Comment="Current Level: Increases the defense value of all structures by 2%; Next level: Increases the defense value of all structures by 3%." Title="2/10" Money="3000 " Time="600" AddDefend="0.02"/>
    <Level3 GroupLV="3" Comment="Current Level: Increases the defense value of all structures by 3%; Next level: Increases the defense value of all structures by 4%." Title="3/10" Money="6000 " Time="1200" AddDefend="0.03"/>
    <Level4 GroupLV="4" Comment="Current Level: Increases the defense value of all structures by 4%; Next level: Increases the defense value of all structures by 5%." Title="4/10" Money="12000 " Time="2400" AddDefend="0.04"/>
    <Level5 GroupLV="5" Comment="Current Level: Increases the defense value of all structures by 5%; Next level: Increases the defense value of all structures by 6%." Title="5/10" Money="24000 " Time="4800" AddDefend="0.05"/>
    <Level6 GroupLV="6" Comment="Current Level: Increases the defense value of all structures by 6%; Next level: Increases the defense value of all structures by 7%." Title="6/10" Money="48000 " Time="9600" AddDefend="0.06"/>
    <Level7 GroupLV="7" Comment="Current Level: Increases the defense value of all structures by 7%; Next level: Increases the defense value of all structures by 8%." Title="7/10" Money="96000 " Time="19200" AddDefend="0.07"/>
    <Level8 GroupLV="8" Comment="Current Level: Increases the defense value of all structures by 8%; Next level: Increases the defense value of all structures by 9%." Title="8/10" Money="192000 " Time="38400" AddDefend="0.08"/>
    <Level9 GroupLV="9" Comment="Current Level: Increases the defense value of all structures by 9%; Next level: Increases the defense value of all structures by 10%." Title="9/10" Money="384000 " Time="76800" AddDefend="0.09"/>
    <Level10 GroupLV="10" Comment="Current Level: Increases the defense value of all structures by &lt;font color='#00FF00'&gt;10%&lt;/font&gt;." Title="10" Money="768000 " Time="153600" AddDefend="0.1"/>
  </List>
  <List GroupID="92" Name="Emplacement Mastery" Comment="Increases the Attack of all defensive structures; Lv1: Increases the Attack of all defensive structures by 1%." Kind="1" Tech="90:5" ImageFileName="Tech92" Title="0/10" TechMemo="Requires Rapid Defense Buildup Lv 5">
    <Level1 GroupLV="1" Comment="Current Level: Increases the Attack of all defensive structures by 1%; Next level: Increases the Attack of all defensive structures by 2%." Title="1/10" Money="2250 " Time="450" AddAssault="0.01"/>
    <Level2 GroupLV="2" Comment="Current Level: Increases the Attack of all defensive structures by 2%; Next level: Increases the Attack of all defensive structures by 3%." Title="2/10" Money="4500 " Time="900" AddAssault="0.02"/>
    <Level3 GroupLV="3" Comment="Current Level: Increases the Attack of all defensive structures by 3%; Next level: Increases the Attack of all defensive structures by 4%." Title="3/10" Money="9000 " Time="1800" AddAssault="0.03"/>
    <Level4 GroupLV="4" Comment="Current Level: Increases the Attack of all defensive structures by 4%; Next level: Increases the Attack of all defensive structures by 5%." Title="4/10" Money="18000 " Time="3600" AddAssault="0.04"/>
    <Level5 GroupLV="5" Comment="Current Level: Increases the Attack of all defensive structures by 5%; Next level: Increases the Attack of all defensive structures by 6%." Title="5/10" Money="36000 " Time="7200" AddAssault="0.05"/>
    <Level6 GroupLV="6" Comment="Current Level: Increases the Attack of all defensive structures by 6%; Next level: Increases the Attack of all defensive structures by 7%." Title="6/10" Money="72000 " Time="14400" AddAssault="0.06"/>
    <Level7 GroupLV="7" Comment="Current Level: Increases the Attack of all defensive structures by 7%; Next level: Increases the Attack of all defensive structures by 8%." Title="7/10" Money="144000 " Time="28800" AddAssault="0.07"/>
    <Level8 GroupLV="8" Comment="Current Level: Increases the Attack of all defensive structures by 8%; Next level: Increases the Attack of all defensive structures by 9%." Title="8/10" Money="288000 " Time="57600" AddAssault="0.08"/>
    <Level9 GroupLV="9" Comment="Current Level: Increases the Attack of all defensive structures by 9%; Next level: Increases the Attack of all defensive structures by 10%." Title="9/10" Money="576000 " Time="115200" AddAssault="0.09"/>
    <Level10 GroupLV="10" Comment="Current Level: Increases the attack power of all emplacements by &lt;font color='#00FF00'&gt;10%&lt;/font&gt;." Title="10" Money="1152000 " Time="230400" AddAssault="0.1"/>
  </List>
  <List GroupID="93" Name="Utmost Defense Buildup" Comment="Increases the maximum number of Defensive structures; Lv1: Increases the maximum number of Defensive structures by 1%." Kind="1" Tech="89:5;91:5;92:3" ImageFileName="Tech93" Title="0/10" TechMemo="Requires Energy Control Lv 5, Defense Enhancement Lv 5, Emplacement Mastery Lv 3">
    <Level1 GroupLV="1" Comment="Current Level: Increases the maximum number of Defensive structures by 1%; Next level: Increases the maximum number of Defensive structures by 2%." Title="1/10" Money="1750 " Time="350" AddBuiltNum="0.01"/>
    <Level2 GroupLV="2" Comment="Current Level: Increases the maximum number of Defensive structures by 2%; Next level: Increases the maximum number of Defensive structures by 3%." Title="2/10" Money="3500 " Time="700" AddBuiltNum="0.02"/>
    <Level3 GroupLV="3" Comment="Current Level: Increases the maximum number of Defensive structures by 3%; Next level: Increases the maximum number of Defensive structures by 4%." Title="3/10" Money="7000 " Time="1400" AddBuiltNum="0.03"/>
    <Level4 GroupLV="4" Comment="Current Level: Increases the maximum number of Defensive structures by 4%; Next level: Increases the maximum number of Defensive structures by 5%." Title="4/10" Money="14000 " Time="2800" AddBuiltNum="0.04"/>
    <Level5 GroupLV="5" Comment="Current Level: Increases the maximum number of Defensive structures by 5%; Next level: Increases the maximum number of Defensive structures by 6%." Title="5/10" Money="28000 " Time="5600" AddBuiltNum="0.05"/>
    <Level6 GroupLV="6" Comment="Current Level: Increases the maximum number of Defensive structures by 6%; Next level: Increases the maximum number of Defensive structures by 7%." Title="6/10" Money="56000 " Time="11200" AddBuiltNum="0.06"/>
    <Level7 GroupLV="7" Comment="Current Level: Increases the maximum number of Defensive structures by 7%; Next level: Increases the maximum number of Defensive structures by 8%." Title="7/10" Money="112000 " Time="22400" AddBuiltNum="0.07"/>
    <Level8 GroupLV="8" Comment="Current Level: Increases the maximum number of Defensive structures by 8%; Next level: Increases the maximum number of Defensive structures by 9%." Title="8/10" Money="224000 " Time="44800" AddBuiltNum="0.08"/>
    <Level9 GroupLV="9" Comment="Current Level: Increases the maximum number of Defensive structures by 9%; Next level: Increases the maximum number of Defensive structures by 10%." Title="9/10" Money="448000 " Time="89600" AddBuiltNum="0.09"/>
    <Level10 GroupLV="10" Comment="Current Level: Increases the maximum number of Defensive structures by &lt;font color='#00FF00'&gt;10%&lt;/font&gt;." Title="10" Money="896000 " Time="179200" AddBuiltNum="0.1"/>
  </List>
  <List GroupID="94" Name="Range Extension" Comment="Increases the attack range of Particle Cannons and Anti-Aircraft Guns; Lv1: Increases the attack range of Particle Cannons and Anti-Aircraft Guns by 1." Kind="1" Tech="90:8;92:5" ImageFileName="Tech94" Title="0/2" TechMemo="Requires Rapid Defense Buildup Lv 8, Emplacement Mastery Lv 5">
    <Level1 GroupLV="1" Comment="Current Level: Increases the attack range of Particle Cannons and Anti-aircraft Guns by 1; Next level: Increases the attack range of Particle Cannons and Anti-aircraft Guns by 2." Title="1/2" Money="300000 " Time="60000" AddRange="1"/>
    <Level2 GroupLV="2" Comment="Current Level: Increases the attack range of Particle Cannons and Anti-aircraft Guns by &lt;font color='#00FF00'&gt;2&lt;/font&gt;." Title="2" Money="600000 " Time="120000" AddRange="2"/>
  </List>
  <List GroupID="95" Name="Thor Buildup" Comment="Increases the maximum number of Thors by 1." Kind="1" Tech="89:8;93:5;94:1" ImageFileName="Tech95" Title="0/1" TechMemo="Requires Energy Control Lv 8, Utmost defense buildup Lv 5, Range Extension Lv 1">
    <Level1 GroupLV="1" Comment="Increases the maximum number of Thors by &lt;font color='#00FF00'&gt;1&lt;/font&gt;." Title="1" Money="800000 " Time="160000" AddThorNum="1"/>
  </List>
  <List GroupID="96" Name="Augment Propulsion" Comment="Increases Movement of all fleets when stationed in your Home Planet; Lv1: Increases Movement of all fleets by 1 when stationed in your Home Planet. " Kind="1" Tech="92:8;95:1" ImageFileName="Tech96" Title="0/2" TechMemo="Requires Emplacement Mastery Lv 8, Thor Buildup Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: Increases Movement of all fleets by 1 when stationed in your Home Planet. ; Next level: Increases Movement of all fleets by 2 when stationed in your Home Planet. " Title="1/2" Money="400000 " Time="80000" AddMove="1"/>
    <Level2 GroupLV="2" Comment="Current Level: Increases Movement of all fleets by &lt;font color='#00FF00'&gt;2&lt;/font&gt; when stationed in your Home Planet." Title="2" Money="900000 " Time="180000" AddMove="2"/>
  </List>
</DefenceTech>;
      
      public function GameRes_DefenceTechXml()
      {
         super();
      }
   }
}

