package
{
   public class GameRes_ExtendTaskXml
   {
      
      public static var data:XML = <Task Name="其它">
  <List TaskID="500" TaskClass="1" HideFlag="0">
    <Level TaskName="Harvest Time 1" Comment1="To monitor productivity rate, click on the blue arrow beneath the Resource Quantity Window at the top right corner of your screen. Metal is the most needed resource in the development of any colony. Gather as much as you can, for there is never enough." Comment2="Increase Metal Productivity to 2,180." MetalAward="500" ItemAward="-1" MainTaskDepend="107" TotalOutMetal="2180"/>
    <Level TaskName="Harvest Time 2" Comment1="To monitor productivity rate, click on the blue arrow beneath the Resource Quantity Window at the top right corner of your screen. Metal is the most needed resource in the development of any colony. Gather as much as you can, for there is never enough." Comment2="Increase Metal Productivity to 3,365." MetalAward="800" ItemAward="-1" MainTaskDepend="6" TotalOutMetal="3365"/>
    <Level TaskName="Harvest Time 3" Comment1="To monitor productivity rate, click on the blue arrow beneath the Resource Quantity Window at the top right corner of your screen. Metal is the most needed resource in the development of any colony. Gather as much as you can, for there is never enough." Comment2="Increase Metal Productivity to 4,670." MetalAward="1000" ItemAward="-1" MainTaskDepend="12" TotalOutMetal="4670"/>
    <Level TaskName="Harvest Time 4" Comment1="To monitor productivity rate, click on the blue arrow beneath the Resource Quantity Window at the top right corner of your screen. Metal is the most needed resource in the development of any colony. Gather as much as you can, for there is never enough." Comment2="Increase Metal Productivity to 4,950." MetalAward="2000" ItemAward="-1" MainTaskDepend="22" TotalOutMetal="4950"/>
    <Level TaskName="Harvest Time 5" Comment1="To monitor productivity rate, click on the blue arrow beneath the Resource Quantity Window at the top right corner of your screen. Metal is the most needed resource in the development of any colony. Gather as much as you can, for there is never enough." Comment2="Increase Metal Productivity to 6,560." MetalAward="5000" ItemAward="-1" MainTaskDepend="30" TotalOutMetal="6560"/>
    <Level TaskName="Harvest Time 6" Comment1="To monitor productivity rate, click on the blue arrow beneath the Resource Quantity Window at the top right corner of your screen. Metal is the most needed resource in the development of any colony. Gather as much as you can, for there is never enough." Comment2="Increase Metal Productivity to 7,090." MetalAward="10000" ItemAward="-1" MainTaskDepend="42" TotalOutMetal="7090"/>
    <Level TaskName="Harvest Time 7" Comment1="To monitor productivity rate, click on the blue arrow beneath the Resource Quantity Window at the top right corner of your screen. Metal is the most needed resource in the development of any colony. Gather as much as you can, for there is never enough." Comment2="Increase Metal Productivity to 9,190." MetalAward="15000" ItemAward="-1" MainTaskDepend="49" TotalOutMetal="9190"/>
    <Level TaskName="Harvest Time 8" Comment1="To monitor productivity rate, click on the blue arrow beneath the Resource Quantity Window at the top right corner of your screen. Metal is the most needed resource in the development of any colony. Gather as much as you can, for there is never enough." Comment2="Increase Metal Productivity to 10,120." MetalAward="30000" ItemAward="-1" MainTaskDepend="60" TotalOutMetal="10120"/>
    <Level TaskName="Harvest Time 9" Comment1="To monitor productivity rate, click on the blue arrow beneath the Resource Quantity Window at the top right corner of your screen. Metal is the most needed resource in the development of any colony. Gather as much as you can, for there is never enough." Comment2="Increase Metal Productivity to 12,970." MetalAward="40000" ItemAward="-1" MainTaskDepend="67" TotalOutMetal="12970"/>
    <Level TaskName="Harvest Time 10" Comment1="To monitor productivity rate, click on the blue arrow beneath the Resource Quantity Window at the top right corner of your screen. Metal is the most needed resource in the development of any colony. Gather as much as you can, for there is never enough." Comment2="Increase Metal Productivity to 14,550." MetalAward="50000" ItemAward="-1" MainTaskDepend="77" TotalOutMetal="14550"/>
    <Level TaskName="Harvest Time 11" Comment1="To monitor productivity rate, click on the blue arrow beneath the Resource Quantity Window at the top right corner of your screen. Metal is the most needed resource in the development of any colony. Gather as much as you can, for there is never enough." Comment2="Increase Metal Productivity to 18,630." MetalAward="60000" ItemAward="-1" MainTaskDepend="84" TotalOutMetal="18630"/>
    <Level TaskName="Harvest Time 12" Comment1="To monitor productivity rate, click on the blue arrow beneath the Resource Quantity Window at the top right corner of your screen. Metal is the most needed resource in the development of any colony. Gather as much as you can, for there is never enough." Comment2="Increase Metal Productivity to 21,250." MetalAward="70000" ItemAward="-1" MainTaskDepend="95" TotalOutMetal="21250"/>
    <Level TaskName="Harvest Time 13" Comment1="To monitor productivity rate, click on the blue arrow beneath the Resource Quantity Window at the top right corner of your screen. Metal is the most needed resource in the development of any colony. Gather as much as you can, for there is never enough." Comment2="Increase Metal Productivity to 27,250." MetalAward="80000" ItemAward="-1" MainTaskDepend="121" TotalOutMetal="27250"/>
    <Level TaskName="Harvest Time 14" Comment1="To monitor productivity rate, click on the blue arrow beneath the Resource Quantity Window at the top right corner of your screen. Metal is the most needed resource in the development of any colony. Gather as much as you can, for there is never enough." Comment2="Increase Metal Productivity to 31,640." MetalAward="90000" ItemAward="-1" MainTaskDepend="132" TotalOutMetal="31640"/>
    <Level TaskName="Harvest Time 15" Comment1="To monitor productivity rate, click on the blue arrow beneath the Resource Quantity Window at the top right corner of your screen. Metal is the most needed resource in the development of any colony. Gather as much as you can, for there is never enough." Comment2="Increase Metal Productivity to 40,780." MetalAward="150000" ItemAward="-1" MainTaskDepend="139" TotalOutMetal="40780"/>
    <Level TaskName="Harvest Time 16" Comment1="To monitor productivity rate, click on the blue arrow beneath the Resource Quantity Window at the top right corner of your screen. Metal is the most needed resource in the development of any colony. Gather as much as you can, for there is never enough." Comment2="Increase Metal Productivity to 48,150." MetalAward="210000" ItemAward="-1" MainTaskDepend="150" TotalOutMetal="48150"/>
    <Level TaskName="Harvest Time 17" Comment1="To monitor productivity rate, click on the blue arrow beneath the Resource Quantity Window at the top right corner of your screen. Metal is the most needed resource in the development of any colony. Gather as much as you can, for there is never enough." Comment2="Increase Metal Productivity to 62,510." MetalAward="270000" ItemAward="-1" MainTaskDepend="157" TotalOutMetal="62510"/>
    <Level TaskName="Harvest Time 18" Comment1="To monitor productivity rate, click on the blue arrow beneath the Resource Quantity Window at the top right corner of your screen. Metal is the most needed resource in the development of any colony. Gather as much as you can, for there is never enough." Comment2="Increase Metal Productivity to 75,080." MetalAward="330000" ItemAward="-1" MainTaskDepend="168" TotalOutMetal="75080"/>
    <Level TaskName="Harvest Time 19" Comment1="To monitor productivity rate, click on the blue arrow beneath the Resource Quantity Window at the top right corner of your screen. Metal is the most needed resource in the development of any colony. Gather as much as you can, for there is never enough." Comment2="Increase Metal Productivity to 98,280." MetalAward="390000" ItemAward="-1" MainTaskDepend="175" TotalOutMetal="98280"/>
    <Level TaskName="Harvest Time 20" Comment1="To monitor productivity rate, click on the blue arrow beneath the Resource Quantity Window at the top right corner of your screen. Metal is the most needed resource in the development of any colony. Gather as much as you can, for there is never enough." Comment2="Increase Metal Productivity to 120,010." MetalAward="450000" ItemAward="-1" MainTaskDepend="186" TotalOutMetal="120010"/>
  </List>
  <List TaskID="501" TaskClass="1" HideFlag="0">
    <Level TaskName="Gathering He3 1" Comment1="He3 is an important element. It helps ships maneuver on planets with different gravity fields." Comment2="Increase He3 Productivity to 2,380." He3Award="500" ItemAward="-1" MainTaskDepend="115" TotalOutHe3="2380"/>
    <Level TaskName="Gathering He3 2" Comment1="He3 is an important element. It helps ships maneuver on planets with different gravity fields." Comment2="Increase He3 Productivity to 3,680." He3Award="800" ItemAward="-1" MainTaskDepend="7" TotalOutHe3="3680"/>
    <Level TaskName="Gathering He3 3" Comment1="He3 is an important element. It helps ships maneuver on planets with different gravity fields." Comment2="Increase He3 Productivity to 5,100." He3Award="1000" ItemAward="-1" MainTaskDepend="13" TotalOutHe3="5100"/>
    <Level TaskName="Gathering He3 4" Comment1="He3 is an important element. It helps ships maneuver on planets with different gravity fields." Comment2="Increase He3 Productivity to 5,410." He3Award="2000" ItemAward="-1" MainTaskDepend="23" TotalOutHe3="5410"/>
    <Level TaskName="Gathering He3 5" Comment1="He3 is an important element. It helps ships maneuver on planets with different gravity fields." Comment2="Increase He3 Productivity to 7,170." He3Award="5000" ItemAward="-1" MainTaskDepend="31" TotalOutHe3="7170"/>
    <Level TaskName="Gathering He3 6" Comment1="He3 is an important element. It helps ships maneuver on planets with different gravity fields." Comment2="Increase He3 Productivity to 7,750." He3Award="10000" ItemAward="-1" MainTaskDepend="43" TotalOutHe3="7750"/>
    <Level TaskName="Gathering He3 7" Comment1="He3 is an important element. It helps ships maneuver on planets with different gravity fields." Comment2="Increase He3 Productivity to 10,040." He3Award="15000" ItemAward="-1" MainTaskDepend="50" TotalOutHe3="10040"/>
    <Level TaskName="Gathering He3 8" Comment1="He3 is an important element. It helps ships maneuver on planets with different gravity fields." Comment2="Increase He3 Productivity to 11,050." He3Award="30000" ItemAward="-1" MainTaskDepend="61" TotalOutHe3="11050"/>
    <Level TaskName="Gathering He3 9" Comment1="He3 is an important element. It helps ships maneuver on planets with different gravity fields." Comment2="Increase He3 Productivity to 14,180." He3Award="40000" ItemAward="-1" MainTaskDepend="68" TotalOutHe3="14180"/>
    <Level TaskName="Gathering He3 10" Comment1="He3 is an important element. It helps ships maneuver on planets with different gravity fields." Comment2="Increase He3 Productivity to 15,900." He3Award="50000" ItemAward="-1" MainTaskDepend="78" TotalOutHe3="15900"/>
    <Level TaskName="Gathering He3 11" Comment1="He3 is an important element. It helps ships maneuver on planets with different gravity fields." Comment2="Increase He3 Productivity to 20,350." He3Award="60000" ItemAward="-1" MainTaskDepend="85" TotalOutHe3="20350"/>
    <Level TaskName="Gathering He3 12" Comment1="He3 is an important element. It helps ships maneuver on planets with different gravity fields." Comment2="Increase He3 Productivity to 23,218." He3Award="70000" ItemAward="-1" MainTaskDepend="96" TotalOutHe3="23218"/>
    <Level TaskName="Gathering He3 13" Comment1="He3 is an important element. It helps ships maneuver on planets with different gravity fields." Comment2="Increase He3 Productivity to 29,780." He3Award="80000" ItemAward="-1" MainTaskDepend="122" TotalOutHe3="29780"/>
    <Level TaskName="Gathering He3 14" Comment1="He3 is an important element. It helps ships maneuver on planets with different gravity fields." Comment2="Increase He3 Productivity to 34,570." He3Award="90000" ItemAward="-1" MainTaskDepend="133" TotalOutHe3="34570"/>
    <Level TaskName="Gathering He3 15" Comment1="He3 is an important element. It helps ships maneuver on planets with different gravity fields." Comment2="Increase He3 Productivity to 44,550." He3Award="150000" ItemAward="-1" MainTaskDepend="140" TotalOutHe3="44550"/>
    <Level TaskName="Gathering He3 16" Comment1="He3 is an important element. It helps ships maneuver on planets with different gravity fields." Comment2="Increase He3 Productivity to 52,610." He3Award="210000" ItemAward="-1" MainTaskDepend="151" TotalOutHe3="52610"/>
    <Level TaskName="Gathering He3 17" Comment1="He3 is an important element. It helps ships maneuver on planets with different gravity fields." Comment2="Increase He3 Productivity to 68,290." He3Award="270000" ItemAward="-1" MainTaskDepend="158" TotalOutHe3="68290"/>
    <Level TaskName="Gathering He3 18" Comment1="He3 is an important element. It helps ships maneuver on planets with different gravity fields." Comment2="Increase He3 Productivity to 82,030." He3Award="330000" ItemAward="-1" MainTaskDepend="169" TotalOutHe3="82030"/>
    <Level TaskName="Gathering He3 19" Comment1="He3 is an important element. It helps ships maneuver on planets with different gravity fields." Comment2="Increase He3 Productivity to 107,380." He3Award="390000" ItemAward="-1" MainTaskDepend="176" TotalOutHe3="107380"/>
    <Level TaskName="Gathering He3 20" Comment1="He3 is an important element. It helps ships maneuver on planets with different gravity fields." Comment2="Increase He3 Productivity to 131,120." He3Award="450000" ItemAward="-1" MainTaskDepend="187" TotalOutHe3="131120"/>
  </List>
  <List TaskID="502" TaskClass="1" HideFlag="0">
    <Level TaskName="Raising Morale 1" Comment1="Gold is the most seductive and motivating agent in the Universe. Use it to raise morale… and win the hearts of both friend and foe." Comment2="Increase Gold Productivity to 2620." MoneyAward="500" ItemAward="-1" MainTaskDepend="116" TotalOutMoney="2620"/>
    <Level TaskName="Raising Morale 2" Comment1="Gold is the most seductive and motivating agent in the Universe. Use it to raise morale… and win the hearts of both friend and foe." Comment2="Increase Gold Productivity to 4,050." MoneyAward="800" ItemAward="-1" MainTaskDepend="8" TotalOutMoney="4050"/>
    <Level TaskName="Raising Morale 3" Comment1="Gold is the most seductive and motivating agent in the Universe. Use it to raise morale… and win the hearts of both friend and foe." Comment2="Increase Gold Productivity to 5,620." MoneyAward="1000" ItemAward="-1" MainTaskDepend="14" TotalOutMoney="5620"/>
    <Level TaskName="Raising Morale 4" Comment1="Gold is the most seductive and motivating agent in the Universe. Use it to raise morale… and win the hearts of both friend and foe." Comment2="Increase Gold Productivity to 5,960." MoneyAward="2000" ItemAward="-1" MainTaskDepend="24" TotalOutMoney="5960"/>
    <Level TaskName="Raising Morale 5" Comment1="Gold is the most seductive and motivating agent in the Universe. Use it to raise morale… and win the hearts of both friend and foe." Comment2="Increase Gold Productivity to 7,900." MoneyAward="5000" ItemAward="-1" MainTaskDepend="32" TotalOutMoney="7900"/>
    <Level TaskName="Raising Morale 6" Comment1="Gold is the most seductive and motivating agent in the Universe. Use it to raise morale… and win the hearts of both friend and foe." Comment2="Increase Gold Productivity to 8,530." MoneyAward="10000" ItemAward="-1" MainTaskDepend="44" TotalOutMoney="8530"/>
    <Level TaskName="Raising Morale 7" Comment1="Gold is the most seductive and motivating agent in the Universe. Use it to raise morale… and win the hearts of both friend and foe." Comment2="Increase Gold Productivity to 11,060." MoneyAward="15000" ItemAward="-1" MainTaskDepend="51" TotalOutMoney="11060"/>
    <Level TaskName="Raising Morale 8" Comment1="Gold is the most seductive and motivating agent in the Universe. Use it to raise morale… and win the hearts of both friend and foe." Comment2="Increase Gold Productivity to 12,180." MoneyAward="30000" ItemAward="-1" MainTaskDepend="62" TotalOutMoney="12180"/>
    <Level TaskName="Raising Morale 9" Comment1="Gold is the most seductive and motivating agent in the Universe. Use it to raise morale… and win the hearts of both friend and foe." Comment2="Increase Gold Productivity to 15,630." MoneyAward="40000" ItemAward="-1" MainTaskDepend="69" TotalOutMoney="15630"/>
    <Level TaskName="Raising Morale 10" Comment1="Gold is the most seductive and motivating agent in the Universe. Use it to raise morale… and win the hearts of both friend and foe." Comment2="Increase Gold Productivity to 17,520." MoneyAward="50000" ItemAward="-1" MainTaskDepend="79" TotalOutMoney="17520"/>
    <Level TaskName="Raising Morale 11" Comment1="Gold is the most seductive and motivating agent in the Universe. Use it to raise morale… and win the hearts of both friend and foe." Comment2="Increase Gold Productivity to 22,420." MoneyAward="60000" ItemAward="-1" MainTaskDepend="86" TotalOutMoney="22420"/>
    <Level TaskName="Raising Morale 12" Comment1="Gold is the most seductive and motivating agent in the Universe. Use it to raise morale… and win the hearts of both friend and foe." Comment2="Increase Gold Productivity to 25,580." MoneyAward="70000" ItemAward="-1" MainTaskDepend="97" TotalOutMoney="25580"/>
    <Level TaskName="Raising Morale 13" Comment1="Gold is the most seductive and motivating agent in the Universe. Use it to raise morale… and win the hearts of both friend and foe." Comment2="Increase Gold Productivity to 32,800." MoneyAward="80000" ItemAward="-1" MainTaskDepend="123" TotalOutMoney="32800"/>
    <Level TaskName="Raising Morale 14" Comment1="Gold is the most seductive and motivating agent in the Universe. Use it to raise morale… and win the hearts of both friend and foe." Comment2="Increase Gold Productivity to 38,080." MoneyAward="90000" ItemAward="-1" MainTaskDepend="134" TotalOutMoney="38080"/>
    <Level TaskName="Raising Morale 15" Comment1="Gold is the most seductive and motivating agent in the Universe. Use it to raise morale… and win the hearts of both friend and foe." Comment2="Increase Gold Productivity to 49,090." MoneyAward="150000" ItemAward="-1" MainTaskDepend="141" TotalOutMoney="49090"/>
    <Level TaskName="Raising Morale 16" Comment1="Gold is the most seductive and motivating agent in the Universe. Use it to raise morale… and win the hearts of both friend and foe." Comment2="Increase Gold Productivity to 57,970." MoneyAward="210000" ItemAward="-1" MainTaskDepend="152" TotalOutMoney="57970"/>
    <Level TaskName="Raising Morale 17" Comment1="Gold is the most seductive and motivating agent in the Universe. Use it to raise morale… and win the hearts of both friend and foe." Comment2="Increase Gold Productivity to 75,240." MoneyAward="270000" ItemAward="-1" MainTaskDepend="159" TotalOutMoney="75240"/>
    <Level TaskName="Raising Morale 18" Comment1="Gold is the most seductive and motivating agent in the Universe. Use it to raise morale… and win the hearts of both friend and foe." Comment2="Increase Gold Productivity to 90,380." MoneyAward="330000" ItemAward="-1" MainTaskDepend="170" TotalOutMoney="90380"/>
    <Level TaskName="Raising Morale 19" Comment1="Gold is the most seductive and motivating agent in the Universe. Use it to raise morale… and win the hearts of both friend and foe." Comment2="Increase Gold Productivity to 118,300." MoneyAward="390000" ItemAward="-1" MainTaskDepend="177" TotalOutMoney="118300"/>
    <Level TaskName="Raising Morale 20" Comment1="Gold is the most seductive and motivating agent in the Universe. Use it to raise morale… and win the hearts of both friend and foe." Comment2="Increase Gold Productivity to 144,470." MoneyAward="450000" ItemAward="-1" MainTaskDepend="188" TotalOutMoney="144470"/>
  </List>
  <List TaskID="503" TaskClass="1" HideFlag="0">
    <Level TaskName="Building Ships  1" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 3 ships " MetalAward="200" He3Award="200" MoneyAward="200" ItemAward="758" ItemNum="1" MainTaskDepend="101" ShipNum="3"/>
    <Level TaskName="Building Ships  2" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 5 ships " MetalAward="500" He3Award="500" MoneyAward="500" ItemAward="-1" MainTaskDepend="101" ShipNum="5"/>
    <Level TaskName="Building Ships  3" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 8 ships " MetalAward="1000" He3Award="1000" MoneyAward="1000" ItemAward="770" ItemNum="1" MainTaskDepend="9" ShipNum="8"/>
    <Level TaskName="Building Ships  4" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 10 ships " MetalAward="2000" He3Award="2000" MoneyAward="2000" ItemAward="-1" MainTaskDepend="9" ShipNum="10"/>
    <Level TaskName="Building Ships  5" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 30 ships " MetalAward="3000" He3Award="3000" MoneyAward="3000" ItemAward="-1" MainTaskDepend="25" ShipNum="30"/>
    <Level TaskName="Building Ships  6" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 50 ships " MetalAward="4000" He3Award="4000" MoneyAward="4000" ItemAward="-1" MainTaskDepend="25" ShipNum="50"/>
    <Level TaskName="Building Ships  7" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 80 ships " MetalAward="5000" He3Award="5000" MoneyAward="5000" ItemAward="-1" MainTaskDepend="28" ShipNum="80"/>
    <Level TaskName="Building Ships  8" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 100 ships " MetalAward="6000" He3Award="6000" MoneyAward="6000" ItemAward="-1" MainTaskDepend="28" ShipNum="100"/>
    <Level TaskName="Building Ships  9" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 200 ships " MetalAward="10000" He3Award="15000" MoneyAward="10000" ItemAward="-1" MainTaskDepend="37" ShipNum="200"/>
    <Level TaskName="Building Ships  10" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 300 ships " MetalAward="15000" He3Award="20000" MoneyAward="15000" ItemAward="-1" MainTaskDepend="37" ShipNum="300"/>
    <Level TaskName="Building Ships  11" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 500 ships " MetalAward="20000" He3Award="25000" MoneyAward="20000" ItemAward="-1" MainTaskDepend="47" ShipNum="500"/>
    <Level TaskName="Building Ships  12" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 800 ships " MetalAward="25000" He3Award="30000" MoneyAward="25000" ItemAward="-1" MainTaskDepend="47" ShipNum="800"/>
    <Level TaskName="Building Ships  13" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 1,000 ships " MetalAward="30000" He3Award="35000" MoneyAward="30000" ItemAward="-1" MainTaskDepend="55" ShipNum="1000"/>
    <Level TaskName="Building Ships  14" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 2,000 ships " MetalAward="35000" He3Award="40000" MoneyAward="35000" ItemAward="-1" MainTaskDepend="55" ShipNum="2000"/>
    <Level TaskName="Building Ships  15" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 3,000 ships " MetalAward="40000" He3Award="45000" MoneyAward="40000" ItemAward="-1" MainTaskDepend="65" ShipNum="3000"/>
    <Level TaskName="Building Ships  16" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 5,000 ships " MetalAward="45000" He3Award="50000" MoneyAward="45000" ItemAward="-1" MainTaskDepend="65" ShipNum="5000"/>
    <Level TaskName="Building Ships  17" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 6,000 ships " MetalAward="50000" He3Award="60000" MoneyAward="50000" ItemAward="-1" MainTaskDepend="78" ShipNum="6000"/>
    <Level TaskName="Building Ships  18" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 7,000 ships " MetalAward="55000" He3Award="70000" MoneyAward="55000" ItemAward="-1" MainTaskDepend="78" ShipNum="7000"/>
    <Level TaskName="Building Ships  19" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 9,000 ships " MetalAward="60000" He3Award="80000" MoneyAward="60000" ItemAward="-1" MainTaskDepend="82" ShipNum="9000"/>
    <Level TaskName="Building Ships  20" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 12,000 ships " MetalAward="65000" He3Award="90000" MoneyAward="65000" ItemAward="-1" MainTaskDepend="82" ShipNum="12000"/>
    <Level TaskName="Building Ships  21" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 16,000 ships " MetalAward="70000" He3Award="100000" MoneyAward="70000" ItemAward="-1" MainTaskDepend="90" ShipNum="16000"/>
    <Level TaskName="Building Ships  22" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 20,000 ships " MetalAward="75000" He3Award="110000" MoneyAward="75000" ItemAward="-1" MainTaskDepend="90" ShipNum="20000"/>
    <Level TaskName="Building Ships  23" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 25,000 ships " MetalAward="100000" He3Award="200000" MoneyAward="100000" ItemAward="-1" MainTaskDepend="100" ShipNum="25000"/>
    <Level TaskName="Building Ships  24" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 30,000 ships " MetalAward="200000" He3Award="300000" MoneyAward="200000" ItemAward="-1" MainTaskDepend="100" ShipNum="30000"/>
    <Level TaskName="Building Ships  25" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 35,000 ships " MetalAward="250000" He3Award="350000" MoneyAward="250000" ItemAward="-1" MainTaskDepend="127" ShipNum="35000"/>
    <Level TaskName="Building Ships  26" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 40,000 ships " MetalAward="300000" He3Award="400000" MoneyAward="300000" ItemAward="-1" MainTaskDepend="127" ShipNum="40000"/>
    <Level TaskName="Building Ships  27" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 50,000 ships " MetalAward="350000" He3Award="450000" MoneyAward="350000" ItemAward="-1" MainTaskDepend="137" ShipNum="50000"/>
    <Level TaskName="Building Ships  28" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 60,000 ships " MetalAward="400000" He3Award="500000" MoneyAward="400000" ItemAward="-1" MainTaskDepend="137" ShipNum="60000"/>
    <Level TaskName="Building Ships  29" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 80,000 ships " MetalAward="450000" He3Award="550000" MoneyAward="450000" ItemAward="-1" MainTaskDepend="145" ShipNum="80000"/>
    <Level TaskName="Building Ships  30" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 100,000 ships " MetalAward="500000" He3Award="600000" MoneyAward="500000" ItemAward="-1" MainTaskDepend="145" ShipNum="100000"/>
    <Level TaskName="Building Ships  31" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 150,000 ships " MetalAward="550000" He3Award="650000" MoneyAward="550000" ItemAward="-1" MainTaskDepend="155" ShipNum="150000"/>
    <Level TaskName="Building Ships  32" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 200,000 ships " MetalAward="600000" He3Award="700000" MoneyAward="600000" ItemAward="-1" MainTaskDepend="155" ShipNum="200000"/>
    <Level TaskName="Building Ships  33" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 300,000 ships " MetalAward="650000" He3Award="750000" MoneyAward="650000" ItemAward="-1" MainTaskDepend="163" ShipNum="300000"/>
    <Level TaskName="Building Ships  34" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 400,000 ships " MetalAward="700000" He3Award="800000" MoneyAward="700000" ItemAward="-1" MainTaskDepend="163" ShipNum="400000"/>
    <Level TaskName="Building Ships  35" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 500,000 ships " MetalAward="750000" He3Award="850000" MoneyAward="750000" ItemAward="-1" MainTaskDepend="173" ShipNum="500000"/>
    <Level TaskName="Building Ships  36" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 600,000 ships " MetalAward="800000" He3Award="900000" MoneyAward="800000" ItemAward="-1" MainTaskDepend="173" ShipNum="600000"/>
    <Level TaskName="Building Ships  37" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 700,000 ships " MetalAward="850000" He3Award="950000" MoneyAward="850000" ItemAward="-1" MainTaskDepend="181" ShipNum="700000"/>
    <Level TaskName="Building Ships  38" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 800,000 ships " MetalAward="900000" He3Award="1000000" MoneyAward="900000" ItemAward="-1" MainTaskDepend="181" ShipNum="800000"/>
    <Level TaskName="Building Ships  39" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 900,000 ships " MetalAward="1000000" He3Award="1500000" MoneyAward="1000000" ItemAward="-1" MainTaskDepend="191" ShipNum="900000"/>
    <Level TaskName="Building Ships  40" Comment1="Nothing inspires cooperative attitude more efficiently than a formidable military force. When it comes to fleet size, bigger is better." Comment2="Own 1,000,000 ships " MetalAward="2000000" He3Award="2500000" MoneyAward="2000000" ItemAward="-1" MainTaskDepend="191" ShipNum="1000000"/>
  </List>
  <List TaskID="504" TaskClass="1" HideFlag="0">
    <Level TaskName="Plentiful Resources 1" Comment1="Balance and abundance in every resource are key to long term success in all aspects of planetary development." Comment2="Store 10,000 Metal, He3 and Gold" MetalAward="500" He3Award="500" MoneyAward="600" ItemAward="-1" MainTaskDepend="10" MetalNum="10000" He3Num="10000" MoneyNum="10000"/>
    <Level TaskName="Plentiful Resources 2" Comment1="Balance and abundance in every resource are key to long term success in all aspects of planetary development." Comment2="Store 30,000 Metal, He3 and Gold" MetalAward="700" He3Award="700" MoneyAward="800" ItemAward="-1" MainTaskDepend="15" MetalNum="30000" He3Num="30000" MoneyNum="30000"/>
    <Level TaskName="Plentiful Resources 3" Comment1="Balance and abundance in every resource are key to long term success in all aspects of planetary development." Comment2="Store 50,000 Metal, He3 and Gold" MetalAward="900" He3Award="900" MoneyAward="1000" ItemAward="-1" MainTaskDepend="27" MetalNum="50000" He3Num="50000" MoneyNum="50000"/>
    <Level TaskName="Plentiful Resources 4" Comment1="Balance and abundance in every resource are key to long term success in all aspects of planetary development." Comment2="Store 70,000 Metal, He3 and Gold" MetalAward="1100" He3Award="1100" MoneyAward="1200" ItemAward="-1" MainTaskDepend="33" MetalNum="70000" He3Num="70000" MoneyNum="70000"/>
    <Level TaskName="Plentiful Resources 5" Comment1="Balance and abundance in every resource are key to long term success in all aspects of planetary development." Comment2="Store 100,000 Metal, He3 and Gold" MetalAward="1300" He3Award="1300" MoneyAward="1500" ItemAward="-1" MainTaskDepend="46" MetalNum="100000" He3Num="100000" MoneyNum="100000"/>
    <Level TaskName="Plentiful Resources 6" Comment1="Balance and abundance in every resource are key to long term success in all aspects of planetary development." Comment2="Store 130,000 Metal, He3 and Gold" MetalAward="2000" He3Award="2000" MoneyAward="2500" ItemAward="-1" MainTaskDepend="52" MetalNum="130000" He3Num="130000" MoneyNum="130000"/>
    <Level TaskName="Plentiful Resources 7" Comment1="Balance and abundance in every resource are key to long term success in all aspects of planetary development." Comment2="Store 170,000 Metal, He3 and Gold" MetalAward="3000" He3Award="3000" MoneyAward="3000" ItemAward="-1" MainTaskDepend="64" MetalNum="170000" He3Num="170000" MoneyNum="170000"/>
    <Level TaskName="Plentiful Resources 8" Comment1="Balance and abundance in every resource are key to long term success in all aspects of planetary development." Comment2="Store 300,000 Metal, He3 and Gold" MetalAward="5000" He3Award="5000" MoneyAward="5000" ItemAward="-1" MainTaskDepend="70" MetalNum="300000" He3Num="300000" MoneyNum="300000"/>
    <Level TaskName="Plentiful Resources 9" Comment1="Balance and abundance in every resource are key to long term success in all aspects of planetary development." Comment2="Store 500,000 Metal, He3 and Gold" MetalAward="20000" He3Award="20000" MoneyAward="30000" ItemAward="-1" MainTaskDepend="81" MetalNum="500000" He3Num="500000" MoneyNum="500000"/>
    <Level TaskName="Plentiful Resources 10" Comment1="Balance and abundance in every resource are key to long term success in all aspects of planetary development." Comment2="Store 1,000,000 Metal, He3 and Gold" MetalAward="50000" He3Award="50000" MoneyAward="50000" ItemAward="-1" MainTaskDepend="87" MetalNum="1000000" He3Num="1000000" MoneyNum="1000000"/>
    <Level TaskName="Plentiful Resources 11" Comment1="Balance and abundance in every resource are key to long term success in all aspects of planetary development." Comment2="Store 2,000,000 Metal, He3 and Gold" MetalAward="100000" He3Award="100000" MoneyAward="100000" ItemAward="-1" MainTaskDepend="99" MetalNum="2000000" He3Num="2000000" MoneyNum="2000000"/>
    <Level TaskName="Plentiful Resources 12" Comment1="Balance and abundance in every resource are key to long term success in all aspects of planetary development." Comment2="Store 3,000,000 Metal, He3 and Gold" MetalAward="300000" He3Award="300000" MoneyAward="300000" ItemAward="-1" MainTaskDepend="124" MetalNum="3000000" He3Num="3000000" MoneyNum="3000000"/>
    <Level TaskName="Plentiful Resources 13" Comment1="Balance and abundance in every resource are key to long term success in all aspects of planetary development." Comment2="Store 5,000,000 Metal, He3 and Gold" MetalAward="500000" He3Award="500000" MoneyAward="500000" ItemAward="-1" MainTaskDepend="136" MetalNum="5000000" He3Num="5000000" MoneyNum="5000000"/>
    <Level TaskName="Plentiful Resources 14" Comment1="Balance and abundance in every resource are key to long term success in all aspects of planetary development." Comment2="Store 10,000,000 Metal, He3 and Gold" MetalAward="600000" He3Award="600000" MoneyAward="600000" ItemAward="-1" MainTaskDepend="142" MetalNum="10000000" He3Num="10000000" MoneyNum="10000000"/>
    <Level TaskName="Plentiful Resources 15" Comment1="Balance and abundance in every resource are key to long term success in all aspects of planetary development." Comment2="Store 20,000,000 Metal, He3 and Gold" MetalAward="700000" He3Award="700000" MoneyAward="700000" ItemAward="-1" MainTaskDepend="154" MetalNum="20000000" He3Num="20000000" MoneyNum="20000000"/>
    <Level TaskName="Plentiful Resources 16" Comment1="Balance and abundance in every resource are key to long term success in all aspects of planetary development." Comment2="Store 30,000,000 Metal, He3 and Gold" MetalAward="800000" He3Award="800000" MoneyAward="800000" ItemAward="-1" MainTaskDepend="160" MetalNum="30000000" He3Num="30000000" MoneyNum="30000000"/>
    <Level TaskName="Plentiful Resources 17" Comment1="Balance and abundance in every resource are key to long term success in all aspects of planetary development." Comment2="Store 50,000,000 Metal, He3 and Gold" MetalAward="900000" He3Award="900000" MoneyAward="900000" ItemAward="-1" MainTaskDepend="172" MetalNum="50000000" He3Num="50000000" MoneyNum="50000000"/>
    <Level TaskName="Plentiful Resources 18" Comment1="Balance and abundance in every resource are key to long term success in all aspects of planetary development." Comment2="Store 100,000,000 Metal, He3 and Gold" MetalAward="1000000" He3Award="1000000" MoneyAward="1000000" ItemAward="-1" MainTaskDepend="178" MetalNum="100000000" He3Num="100000000" MoneyNum="100000000"/>
    <Level TaskName="Plentiful Resources 19" Comment1="Balance and abundance in every resource are key to long term success in all aspects of planetary development." Comment2="Store 200,000,000 Metal, He3 and Gold" MetalAward="1200000" He3Award="1200000" MoneyAward="1200000" ItemAward="-1" MainTaskDepend="178" MetalNum="200000000" He3Num="200000000" MoneyNum="200000000"/>
    <Level TaskName="Plentiful Resources 20" Comment1="Balance and abundance in every resource are key to long term success in all aspects of planetary development." Comment2="Store 300,000,000 Metal, He3 and Gold" MetalAward="1500000" He3Award="1500000" MoneyAward="1500000" ItemAward="-1" MainTaskDepend="190" MetalNum="300000000" He3Num="300000000" MoneyNum="300000000"/>
  </List>
  <List TaskID="505" TaskClass="1" HideFlag="0">
    <Level TaskName="Ship Research 1" Comment1="Technology never stops moving forward, and the same goes for a good fleet. Frequent upgrades will keep your warships at the forefront of military power. Enter the Weapon Research Center and select Ship Blueprint Research to upgrade specfic ships." Comment2="Upgrade 1 ship." MetalAward="5000" He3Award="10000" MoneyAward="4000" ItemAward="-1" MainTaskDepend="5" UpgradeShipNum="1"/>
    <Level TaskName="Parts Research 1" Comment1="A ship is only as strong as its weakest link, so be sure to invest in the strength of every detail. (Go to the Ground Base and find the Weapon Research Ctr. Click Enter and choose Module Blueprint Research)" Comment2="Upgrade 1 set of parts." MetalAward="5000" He3Award="10000" MoneyAward="4000" ItemAward="-1" MainTaskDepend="5" UpgradeComponentsNum="1"/>
    <Level TaskName="Ship Research 2" Comment1="Technology never stops moving forward, and the same goes for a good fleet. Frequent upgrades will keep your warships at the forefront of military power. Enter the Weapon Research Center and select Ship Blueprint Research to upgrade specfic ships." Comment2="Upgrade 5 ships." MetalAward="10000" He3Award="20000" MoneyAward="8000" ItemAward="-1" MainTaskDepend="18" UpgradeShipNum="5"/>
    <Level TaskName="Parts Research 2" Comment1="A ship is only as strong as its weakest link, so be sure to invest in the strength of every detail. (Go to the Ground Base and find the Weapon Research Ctr. Click Enter and choose Module Blueprint Research)" Comment2="Upgrade 5 sets of parts." MetalAward="10000" He3Award="20000" MoneyAward="8000" ItemAward="-1" MainTaskDepend="18" UpgradeComponentsNum="5"/>
    <Level TaskName="Ship Research 3" Comment1="Technology never stops moving forward, and the same goes for a good fleet. Frequent upgrades will keep your warships at the forefront of military power. Enter the Weapon Research Center and select Ship Blueprint Research to upgrade specfic ships." Comment2="Upgrade 10 ships." MetalAward="30000" He3Award="40000" MoneyAward="20000" ItemAward="-1" MainTaskDepend="38" UpgradeShipNum="10"/>
    <Level TaskName="Parts Research 3" Comment1="A ship is only as strong as its weakest link, so be sure to invest in the strength of every detail. (Go to the Ground Base and find the Weapon Research Ctr. Click Enter and choose Module Blueprint Research)" Comment2="Upgrade 10 sets of parts." MetalAward="30000" He3Award="40000" MoneyAward="20000" ItemAward="-1" MainTaskDepend="38" UpgradeComponentsNum="10"/>
    <Level TaskName="Ship Research 4" Comment1="Technology never stops moving forward, and the same goes for a good fleet. Frequent upgrades will keep your warships at the forefront of military power. Enter the Weapon Research Center and select Ship Blueprint Research to upgrade specfic ships." Comment2="Upgrade 20 ships." MetalAward="70000" He3Award="100000" MoneyAward="80000" ItemAward="-1" MainTaskDepend="56" UpgradeShipNum="20"/>
    <Level TaskName="Parts Research 4" Comment1="A ship is only as strong as its weakest link, so be sure to invest in the strength of every detail. (Go to the Ground Base and find the Weapon Research Ctr. Click Enter and choose Module Blueprint Research)" Comment2="Upgrade 20 sets of parts." MetalAward="70000" He3Award="100000" MoneyAward="80000" ItemAward="-1" MainTaskDepend="56" UpgradeComponentsNum="20"/>
    <Level TaskName="Ship Research 5" Comment1="Technology never stops moving forward, and the same goes for a good fleet. Frequent upgrades will keep your warships at the forefront of military power. Enter the Weapon Research Center and select Ship Blueprint Research to upgrade specfic ships." Comment2="Upgrade 30 ships." MetalAward="500000" He3Award="500000" MoneyAward="500000" ItemAward="-1" MainTaskDepend="102" UpgradeShipNum="30"/>
    <Level TaskName="Parts Research 5" Comment1="A ship is only as strong as its weakest link, so be sure to invest in the strength of every detail. (Go to the Ground Base and find the Weapon Research Ctr. Click Enter and choose Module Blueprint Research)" Comment2="Upgrade 30 sets of parts." MetalAward="500000" He3Award="500000" MoneyAward="500000" ItemAward="-1" MainTaskDepend="102" UpgradeComponentsNum="30"/>
    <Level TaskName="Ship Research 6" Comment1="Technology never stops moving forward, and the same goes for a good fleet. Frequent upgrades will keep your warships at the forefront of military power. Enter the Weapon Research Center and select Ship Blueprint Research to upgrade specfic ships." Comment2="Upgrade 40 ships." MetalAward="800000" He3Award="800000" MoneyAward="800000" ItemAward="-1" MainTaskDepend="91" UpgradeShipNum="40"/>
    <Level TaskName="Parts Research 6" Comment1="A ship is only as strong as its weakest link, so be sure to invest in the strength of every detail. (Go to the Ground Base and find the Weapon Research Ctr. Click Enter and choose Module Blueprint Research)" Comment2="Upgrade 40 sets of parts." MetalAward="800000" He3Award="800000" MoneyAward="800000" ItemAward="-1" MainTaskDepend="91" UpgradeComponentsNum="40"/>
    <Level TaskName="Ship Research 7" Comment1="Technology never stops moving forward, and the same goes for a good fleet. Frequent upgrades will keep your warships at the forefront of military power. Enter the Weapon Research Center and select Ship Blueprint Research to upgrade specfic ships." Comment2="Upgrade 50 ships." MetalAward="1000000" He3Award="1000000" MoneyAward="1000000" ItemAward="-1" MainTaskDepend="128" UpgradeShipNum="50"/>
    <Level TaskName="Parts Research 7" Comment1="A ship is only as strong as its weakest link, so be sure to invest in the strength of every detail. (Go to the Ground Base and find the Weapon Research Ctr. Click Enter and choose Module Blueprint Research)" Comment2="Upgrade 50 sets of parts." MetalAward="1000000" He3Award="1000000" MoneyAward="1000000" ItemAward="-1" MainTaskDepend="128" UpgradeComponentsNum="50"/>
    <Level TaskName="Ship Research 8" Comment1="Technology never stops moving forward, and the same goes for a good fleet. Frequent upgrades will keep your warships at the forefront of military power. Enter the Weapon Research Center and select Ship Blueprint Research to upgrade specfic ships." Comment2="Upgrade 60 ships." MetalAward="1500000" He3Award="1500000" MoneyAward="1500000" ItemAward="-1" MainTaskDepend="146" UpgradeShipNum="60"/>
    <Level TaskName="Parts Research 8" Comment1="A ship is only as strong as its weakest link, so be sure to invest in the strength of every detail. (Go to the Ground Base and find the Weapon Research Ctr. Click Enter and choose Module Blueprint Research)" Comment2="Upgrade 60 sets of parts." MetalAward="1500000" He3Award="1500000" MoneyAward="1500000" ItemAward="-1" MainTaskDepend="146" UpgradeComponentsNum="60"/>
    <Level TaskName="Ship Research 9" Comment1="Technology never stops moving forward, and the same goes for a good fleet. Frequent upgrades will keep your warships at the forefront of military power. Enter the Weapon Research Center and select Ship Blueprint Research to upgrade specfic ships." Comment2="Upgrade 70 ships." MetalAward="2000000" He3Award="2000000" MoneyAward="2000000" ItemAward="-1" MainTaskDepend="164" UpgradeShipNum="70"/>
    <Level TaskName="Parts Research 9" Comment1="A ship is only as strong as its weakest link, so be sure to invest in the strength of every detail. (Go to the Ground Base and find the Weapon Research Ctr. Click Enter and choose Module Blueprint Research)" Comment2="Upgrade 70 sets of parts." MetalAward="2000000" He3Award="2000000" MoneyAward="2000000" ItemAward="-1" MainTaskDepend="164" UpgradeComponentsNum="70"/>
    <Level TaskName="Ship Research 10" Comment1="Technology never stops moving forward, and the same goes for a good fleet. Frequent upgrades will keep your warships at the forefront of military power. Enter the Weapon Research Center and select Ship Blueprint Research to upgrade specfic ships." Comment2="Upgrade 90 ships." MetalAward="3000000" He3Award="3000000" MoneyAward="3000000" ItemAward="-1" MainTaskDepend="182" UpgradeShipNum="90"/>
    <Level TaskName="Parts Research 10" Comment1="A ship is only as strong as its weakest link, so be sure to invest in the strength of every detail. (Go to the Ground Base and find the Weapon Research Ctr. Click Enter and choose Module Blueprint Research)" Comment2="Upgrade 90 sets of parts." MetalAward="3000000" He3Award="3000000" MoneyAward="3000000" ItemAward="-1" MainTaskDepend="182" UpgradeComponentsNum="90"/>
  </List>
  <List TaskID="506" TaskClass="1" HideFlag="0">
    <Level TaskName="Recruitment 1" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 2 Commanders." MetalAward="500" He3Award="700" MoneyAward="500" ItemAward="-1" MainTaskDepend="1" CommanderNum="2"/>
    <Level TaskName="Recruitment 2" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 4 Commanders." MetalAward="600" He3Award="800" MoneyAward="600" ItemAward="-1" MainTaskDepend="1" CommanderNum="4"/>
    <Level TaskName="Recruitment 3" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 6 Commanders." MetalAward="700" He3Award="1000" MoneyAward="700" ItemAward="-1" MainTaskDepend="1" CommanderNum="6"/>
    <Level TaskName="Recruitment 4" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 8 Commanders." MetalAward="800" He3Award="1500" MoneyAward="800" ItemAward="-1" MainTaskDepend="35" CommanderNum="8"/>
    <Level TaskName="Recruitment 5" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 10 Commanders." MetalAward="1000" He3Award="2000" MoneyAward="1000" ItemAward="-1" MainTaskDepend="35" CommanderNum="10"/>
    <Level TaskName="Recruitment 6" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 12 Commanders." MetalAward="2000" He3Award="3000" MoneyAward="2000" ItemAward="-1" MainTaskDepend="35" CommanderNum="12"/>
    <Level TaskName="Recruitment 7" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 14 Commanders." MetalAward="3000" He3Award="4000" MoneyAward="3000" ItemAward="-1" MainTaskDepend="54" CommanderNum="14"/>
    <Level TaskName="Recruitment 8" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 16 Commanders." MetalAward="4000" He3Award="5000" MoneyAward="4000" ItemAward="-1" MainTaskDepend="54" CommanderNum="16"/>
    <Level TaskName="Recruitment 9" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 18 Commanders." MetalAward="5000" He3Award="6000" MoneyAward="5000" ItemAward="-1" MainTaskDepend="54" CommanderNum="18"/>
    <Level TaskName="Recruitment 10" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 20 Commanders." MetalAward="8000" He3Award="10000" MoneyAward="8000" ItemAward="-1" MainTaskDepend="72" CommanderNum="20"/>
    <Level TaskName="Recruitment 11" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 22 Commanders." MetalAward="10000" He3Award="20000" MoneyAward="10000" ItemAward="-1" MainTaskDepend="72" CommanderNum="22"/>
    <Level TaskName="Recruitment 12" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 24 Commanders." MetalAward="20000" He3Award="30000" MoneyAward="20000" ItemAward="-1" MainTaskDepend="72" CommanderNum="24"/>
    <Level TaskName="Recruitment 13" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 26 Commanders." MetalAward="30000" He3Award="40000" MoneyAward="30000" ItemAward="-1" MainTaskDepend="89" CommanderNum="26"/>
    <Level TaskName="Recruitment 14" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 28 Commanders." MetalAward="40000" He3Award="50000" MoneyAward="40000" ItemAward="-1" MainTaskDepend="89" CommanderNum="28"/>
    <Level TaskName="Recruitment 15" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 30 Commanders." MetalAward="50000" He3Award="70000" MoneyAward="50000" ItemAward="-1" MainTaskDepend="89" CommanderNum="30"/>
    <Level TaskName="Recruitment 16" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 32 Commanders." MetalAward="70000" He3Award="100000" MoneyAward="70000" ItemAward="-1" MainTaskDepend="120" CommanderNum="32"/>
    <Level TaskName="Recruitment 17" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 34 Commanders." MetalAward="90000" He3Award="130000" MoneyAward="90000" ItemAward="-1" MainTaskDepend="120" CommanderNum="34"/>
    <Level TaskName="Recruitment 18" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 36 Commanders." MetalAward="110000" He3Award="160000" MoneyAward="110000" ItemAward="-1" MainTaskDepend="126" CommanderNum="36"/>
    <Level TaskName="Recruitment 19" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 38 Commanders." MetalAward="130000" He3Award="190000" MoneyAward="130000" ItemAward="-1" MainTaskDepend="126" CommanderNum="38"/>
    <Level TaskName="Recruitment 20" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 40 Commanders." MetalAward="150000" He3Award="220000" MoneyAward="150000" ItemAward="-1" MainTaskDepend="144" CommanderNum="40"/>
    <Level TaskName="Recruitment 21" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 42 Commanders." MetalAward="170000" He3Award="250000" MoneyAward="170000" ItemAward="-1" MainTaskDepend="144" CommanderNum="42"/>
    <Level TaskName="Recruitment 22" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 44 Commanders." MetalAward="190000" He3Award="280000" MoneyAward="190000" ItemAward="-1" MainTaskDepend="162" CommanderNum="44"/>
    <Level TaskName="Recruitment 23" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 46 Commanders." MetalAward="210000" He3Award="310000" MoneyAward="210000" ItemAward="-1" MainTaskDepend="162" CommanderNum="46"/>
    <Level TaskName="Recruitment 24" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 48 Commanders." MetalAward="230000" He3Award="340000" MoneyAward="230000" ItemAward="-1" MainTaskDepend="180" CommanderNum="48"/>
    <Level TaskName="Recruitment 25" Comment1="Good leadership is the key to bringing out the best in the troops." Comment2="Successfully recruit 50 Commanders." MetalAward="250000" He3Award="370000" MoneyAward="250000" ItemAward="-1" MainTaskDepend="180" CommanderNum="50"/>
  </List>
  <List TaskID="507" TaskClass="1" HideFlag="0">
    <Level TaskName="Joining Forces" Comment1="In the vast loneliness of space, there is safety and companionship in numbers. Finding a solid team will open doors to more power and friendship than you can ever imagine." Comment2="Join or create a Corps." MetalAward="500" He3Award="500" MoneyAward="500" ItemAward="-1" MainTaskDepend="21" CreateJoinUnion="1"/>
    <Level TaskName="Friendly Faces 1" Comment1="A true leader is one who understands the power of friendship. " Comment2="Add 2 friends" MetalAward="1000" He3Award="1000" MoneyAward="1000" ItemAward="-1" MainTaskDepend="21" FriendNum="2"/>
    <Level TaskName="Friendly Faces 2" Comment1="A true leader is one who understands the power of friendship. " Comment2="Add 4 friends" MetalAward="5000" He3Award="5000" MoneyAward="5000" ItemAward="-1" MainTaskDepend="41" FriendNum="4"/>
    <Level TaskName="Contribution 1" Comment1="Both successful commanders and savvy businessmen know the value of investment: The more you contribute to your team, the more you'll get in return.(Click on Social at the lower right. Then click on Corps, followed by  My Corps. Finally, click on the Corps Contribution at the lower left.）" Comment2="Contribute up to 100 points" MetalAward="10000" He3Award="30000" MoneyAward="15000" ItemAward="-1" MainTaskDepend="41" Contribution="100"/>
    <Level TaskName="Friendly Faces 3" Comment1="A true leader is one who understands the power of friendship. " Comment2="Add 6 friends" MetalAward="9000" He3Award="9000" MoneyAward="9000" ItemAward="-1" MainTaskDepend="59" FriendNum="6"/>
    <Level TaskName="Contribution 2" Comment1="Both successful commanders and savvy businessmen know the value of investment: The more you contribute to your team, the more you'll get in return.(Click on Social at the lower right. Then click on Corps, followed by  My Corps. Finally, click on the Corps Contribution at the lower left.）" Comment2="Contribute up to 500 points" MetalAward="50000" He3Award="70000" MoneyAward="55000" ItemAward="-1" MainTaskDepend="59" Contribution="500"/>
    <Level TaskName="Friendly Faces 4" Comment1="A true leader is one who understands the power of friendship. " Comment2="Add 8 friends" MetalAward="13000" He3Award="13000" MoneyAward="13000" ItemAward="-1" MainTaskDepend="76" FriendNum="8"/>
    <Level TaskName="Contribution 3" Comment1="Both successful commanders and savvy businessmen know the value of investment: The more you contribute to your team, the more you'll get in return.(Click on Social at the lower right. Then click on Corps, followed by  My Corps. Finally, click on the Corps Contribution at the lower left.）" Comment2="Contribute up to 1,000 points" MetalAward="100000" He3Award="200000" MoneyAward="120000" ItemAward="-1" MainTaskDepend="76" Contribution="1000"/>
    <Level TaskName="Friendly Faces 5" Comment1="A true leader is one who understands the power of friendship. " Comment2="Add 10 friends" MetalAward="17000" He3Award="17000" MoneyAward="17000" ItemAward="-1" MainTaskDepend="94" FriendNum="10"/>
    <Level TaskName="Contribution 4" Comment1="Both successful commanders and savvy businessmen know the value of investment: The more you contribute to your team, the more you'll get in return.(Click on Social at the lower right. Then click on Corps, followed by  My Corps. Finally, click on the Corps Contribution at the lower left.）" Comment2="Contribute up to 2,000 points" MetalAward="200000" He3Award="300000" MoneyAward="220000" ItemAward="-1" MainTaskDepend="94" Contribution="2000"/>
    <Level TaskName="Friendly Faces 6" Comment1="A true leader is one who understands the power of friendship. " Comment2="Add 30 friends" MetalAward="30000" He3Award="30000" MoneyAward="30000" ItemAward="-1" MainTaskDepend="131" FriendNum="30"/>
    <Level TaskName="Contribution 5" Comment1="Both successful commanders and savvy businessmen know the value of investment: The more you contribute to your team, the more you'll get in return.(Click on Social at the lower right. Then click on Corps, followed by  My Corps. Finally, click on the Corps Contribution at the lower left.）" Comment2="Contribute up to 3,000 points" MetalAward="300000" He3Award="400000" MoneyAward="320000" ItemAward="923" ItemNum="1" MainTaskDepend="131" Contribution="3000"/>
    <Level TaskName="Friendly Faces 7" Comment1="A true leader is one who understands the power of friendship. " Comment2="Add 50 friends" MetalAward="50000" He3Award="50000" MoneyAward="50000" ItemAward="-1" MainTaskDepend="149" FriendNum="50"/>
    <Level TaskName="Contribution 6" Comment1="Both successful commanders and savvy businessmen know the value of investment: The more you contribute to your team, the more you'll get in return.(Click on Social at the lower right. Then click on Corps, followed by  My Corps. Finally, click on the Corps Contribution at the lower left.）" Comment2="Contribute up to 5,000 points" MetalAward="500000" He3Award="600000" MoneyAward="500000" ItemAward="900" ItemNum="1" MainTaskDepend="149" Contribution="5000"/>
    <Level TaskName="Friendly Faces 8" Comment1="A true leader is one who understands the power of friendship. " Comment2="Add 70 friends" MetalAward="80000" He3Award="80000" MoneyAward="80000" ItemAward="-1" MainTaskDepend="167" FriendNum="70"/>
    <Level TaskName="Contribution 7" Comment1="Both successful commanders and savvy businessmen know the value of investment: The more you contribute to your team, the more you'll get in return.(Click on Social at the lower right. Then click on Corps, followed by  My Corps. Finally, click on the Corps Contribution at the lower left.）" Comment2="Contribute up to 10,000 points" MetalAward="800000" He3Award="1000000" MoneyAward="800000" ItemAward="926" ItemNum="1" MainTaskDepend="167" Contribution="10000"/>
    <Level TaskName="Friendly Faces 9" Comment1="A true leader is one who understands the power of friendship. " Comment2="Add 100 friends" MetalAward="150000" He3Award="150000" MoneyAward="150000" ItemAward="-1" MainTaskDepend="185" FriendNum="100"/>
    <Level TaskName="Contribution 8" Comment1="Both successful commanders and savvy businessmen know the value of investment: The more you contribute to your team, the more you'll get in return.(Click on Social at the lower right. Then click on Corps, followed by  My Corps. Finally, click on the Corps Contribution at the lower left.）" Comment2="Contribute up to 20,000 points" MetalAward="1000000" He3Award="1500000" MoneyAward="1000000" ItemAward="901" ItemNum="1" MainTaskDepend="185" Contribution="20000"/>
  </List>
  <List TaskID="509" TaskClass="1" HideFlag="0">
    <Level TaskName="Technological Advancement 2" Comment1="Technological advancement preceeds Colonial expansion. Do your research to always stay ahead of the game." Comment2="Research High Yield Mining Lv1" MetalAward="1400" He3Award="1400" MoneyAward="1400" ItemAward="-1" MainTaskDepend="107" HighYieldMetalLV="0"/>
    <Level TaskName="Technological Advancement 3" Comment1="Technological advancement preceeds Colonial expansion. Do your research to always stay ahead of the game." Comment2="Research Construction Boost Lv1" MetalAward="1400" He3Award="1400" MoneyAward="1400" ItemAward="-1" MainTaskDepend="5" OptimizationBuildLV="0"/>
    <Level TaskName="Technological Advancement 4" Comment1="Technological advancement preceeds Colonial expansion. Do your research to always stay ahead of the game." Comment2="High Yield Chemistry Lv1" MetalAward="1750" He3Award="1750" MoneyAward="1750" ItemAward="-1" MainTaskDepend="26" HighYieldHe3LV="0"/>
    <Level TaskName="Technological Advancement 5" Comment1="Technological advancement preceeds Colonial expansion. Do your research to always stay ahead of the game." Comment2="Ship Building Boost Lv1" MetalAward="1800" He3Award="1800" MoneyAward="1800" ItemAward="-1" MainTaskDepend="26" ShipBuildingTechLV="0"/>
    <Level TaskName="Technological Advancement 6" Comment1="Technological advancement preceeds Colonial expansion. Do your research to always stay ahead of the game." Comment2="Ship Building Logistics Lv1" MetalAward="1850" He3Award="1850" MoneyAward="1850" ItemAward="-1" MainTaskDepend="26" OptimizationShipLV="0"/>
    <Level TaskName="Technological Advancement 7" Comment1="Technological advancement preceeds Colonial expansion. Do your research to always stay ahead of the game." Comment2="Quality Materials Lv1" MetalAward="3000" He3Award="3000" MoneyAward="3000" ItemAward="-1" MainTaskDepend="26" ImprovedMaterialsLV="0"/>
    <Level TaskName="Technological Advancement 8" Comment1="Technological advancement preceeds Colonial expansion. Do your research to always stay ahead of the game." Comment2="High Yield Investing Lv1" MetalAward="20000" He3Award="20000" MoneyAward="20000" ItemAward="-1" MainTaskDepend="45" HighYieldMoneyLV="0"/>
    <Level TaskName="Technological Advancement 9" Comment1="Technological advancement preceeds Colonial expansion. Do your research to always stay ahead of the game." Comment2="Sync Shipbuilding Lv1" MetalAward="100000" He3Award="100000" MoneyAward="100000" ItemAward="-1" MainTaskDepend="45" ParalleShip="0"/>
    <Level TaskName="Technological Advancement 10" Comment1="Technological advancement preceeds Colonial expansion. Do your research to always stay ahead of the game." Comment2="Expand Capacity Lv1" MetalAward="150000" He3Award="150000" MoneyAward="150000" ItemAward="-1" MainTaskDepend="45" OptimizationStorageLV="0"/>
  </List>
  <List TaskID="510" TaskClass="1" HideFlag="0">
    <Level TaskName="Staying Green 1" Comment1="Pollution killed the Earth, and continues to threaten every remaining planet. Stay green and recycle your waste. It will generate good returns for you." Comment2="Recycle 1 ship" MetalAward="1000" He3Award="1500" MoneyAward="1000" ItemAward="-1" MainTaskDepend="19" ShipReclaimNum="1"/>
    <Level TaskName="Staying Green 2" Comment1="Pollution killed the Earth, and continues to threaten every remaining planet. Stay green and recycle your waste. It will generate good returns for you." Comment2="Recycle 30 ships" MetalAward="1500" He3Award="2000" MoneyAward="1500" ItemAward="-1" MainTaskDepend="19" ShipReclaimNum="30"/>
    <Level TaskName="Staying Green 3" Comment1="Pollution killed the Earth, and continues to threaten every remaining planet. Stay green and recycle your waste. It will generate good returns for you." Comment2="Recycle 50 ships" MetalAward="2000" He3Award="3000" MoneyAward="2000" ItemAward="-1" MainTaskDepend="39" ShipReclaimNum="50"/>
    <Level TaskName="Staying Green 4" Comment1="Pollution killed the Earth, and continues to threaten every remaining planet. Stay green and recycle your waste. It will generate good returns for you." Comment2="Recycle 70 ships" MetalAward="3000" He3Award="4000" MoneyAward="3000" ItemAward="-1" MainTaskDepend="39" ShipReclaimNum="70"/>
    <Level TaskName="Staying Green 5" Comment1="Pollution killed the Earth, and continues to threaten every remaining planet. Stay green and recycle your waste. It will generate good returns for you." Comment2="Recycle 100 ships" MetalAward="4000" He3Award="6000" MoneyAward="4000" ItemAward="-1" MainTaskDepend="57" ShipReclaimNum="100"/>
    <Level TaskName="Staying Green 6" Comment1="Pollution killed the Earth, and continues to threaten every remaining planet. Stay green and recycle your waste. It will generate good returns for you." Comment2="Recycle 200 ships" MetalAward="6000" He3Award="8000" MoneyAward="6000" ItemAward="-1" MainTaskDepend="57" ShipReclaimNum="200"/>
    <Level TaskName="Staying Green 7" Comment1="Pollution killed the Earth, and continues to threaten every remaining planet. Stay green and recycle your waste. It will generate good returns for you." Comment2="Recycle 500 ships" MetalAward="8000" He3Award="10000" MoneyAward="8000" ItemAward="-1" MainTaskDepend="74" ShipReclaimNum="500"/>
    <Level TaskName="Staying Green 8" Comment1="Pollution killed the Earth, and continues to threaten every remaining planet. Stay green and recycle your waste. It will generate good returns for you." Comment2="Recycle 800 ships" MetalAward="20000" He3Award="20000" MoneyAward="20000" ItemAward="-1" MainTaskDepend="74" ShipReclaimNum="800"/>
    <Level TaskName="Staying Green 9" Comment1="Pollution killed the Earth, and continues to threaten every remaining planet. Stay green and recycle your waste. It will generate good returns for you." Comment2="Recycle 1,000 ships" MetalAward="40000" He3Award="40000" MoneyAward="40000" ItemAward="-1" MainTaskDepend="92" ShipReclaimNum="1000"/>
    <Level TaskName="Staying Green 10" Comment1="Pollution killed the Earth, and continues to threaten every remaining planet. Stay green and recycle your waste. It will generate good returns for you." Comment2="Recycle 5,000 ships" MetalAward="70000" He3Award="70000" MoneyAward="70000" ItemAward="-1" MainTaskDepend="92" ShipReclaimNum="5000"/>
    <Level TaskName="Staying Green 11" Comment1="Pollution killed the Earth, and continues to threaten every remaining planet. Stay green and recycle your waste. It will generate good returns for you." Comment2="Recycle 10,000 ships" MetalAward="100000" He3Award="100000" MoneyAward="100000" ItemAward="-1" MainTaskDepend="147" ShipReclaimNum="10000"/>
    <Level TaskName="Staying Green 12" Comment1="Pollution killed the Earth, and continues to threaten every remaining planet. Stay green and recycle your waste. It will generate good returns for you." Comment2="Recycle 30,000 ships" MetalAward="200000" He3Award="200000" MoneyAward="200000" ItemAward="-1" MainTaskDepend="147" ShipReclaimNum="30000"/>
    <Level TaskName="Staying Green 13" Comment1="Pollution killed the Earth, and continues to threaten every remaining planet. Stay green and recycle your waste. It will generate good returns for you." Comment2="Recycle 50,000 ships" MetalAward="300000" He3Award="300000" MoneyAward="300000" ItemAward="-1" MainTaskDepend="165" ShipReclaimNum="50000"/>
    <Level TaskName="Staying Green 14" Comment1="Pollution killed the Earth, and continues to threaten every remaining planet. Stay green and recycle your waste. It will generate good returns for you." Comment2="Recycle 100,000 ships" MetalAward="500000" He3Award="500000" MoneyAward="500000" ItemAward="-1" MainTaskDepend="165" ShipReclaimNum="100000"/>
    <Level TaskName="Staying Green 15" Comment1="Pollution killed the Earth, and continues to threaten every remaining planet. Stay green and recycle your waste. It will generate good returns for you." Comment2="Recycle 200,000 ships" MetalAward="800000" He3Award="1000000" MoneyAward="800000" ItemAward="-1" MainTaskDepend="183" ShipReclaimNum="200000"/>
  </List>
  <List TaskID="511" TaskClass="1" HideFlag="0">
    <Level TaskName="Free Trade  1" Comment1="One man's trash is another man's treasure - so long as it's not complete garbage." Comment2="Trading volume reaches 1" MetalAward="1000" He3Award="2000" MoneyAward="1000" ItemAward="-1" MainTaskDepend="20" TradeNum="1"/>
    <Level TaskName="Free Trade  2" Comment1="One man's trash is another man's treasure - so long as it's not complete garbage." Comment2="Trading volume reaches 5" MetalAward="1500" He3Award="3000" MoneyAward="1500" ItemAward="-1" MainTaskDepend="20" TradeNum="5"/>
    <Level TaskName="Free Trade  3" Comment1="One man's trash is another man's treasure - so long as it's not complete garbage." Comment2="Trading volume reaches 30" MetalAward="2000" He3Award="5000" MoneyAward="2000" ItemAward="-1" MainTaskDepend="40" TradeNum="30"/>
    <Level TaskName="Free Trade  4" Comment1="One man's trash is another man's treasure - so long as it's not complete garbage." Comment2="Trading volume reaches 70" MetalAward="5000" He3Award="8000" MoneyAward="5000" ItemAward="-1" MainTaskDepend="40" TradeNum="70"/>
    <Level TaskName="Free Trade  5" Comment1="One man's trash is another man's treasure - so long as it's not complete garbage." Comment2="Trading volume reaches 150" MetalAward="8000" He3Award="10000" MoneyAward="8000" ItemAward="-1" MainTaskDepend="58" TradeNum="150"/>
    <Level TaskName="Free Trade  6" Comment1="One man's trash is another man's treasure - so long as it's not complete garbage." Comment2="Trading volume reaches 500" MetalAward="10000" He3Award="20000" MoneyAward="10000" ItemAward="-1" MainTaskDepend="75" TradeNum="500"/>
    <Level TaskName="Free Trade  7" Comment1="One man's trash is another man's treasure - so long as it's not complete garbage." Comment2="Trading volume reaches 1,000" MetalAward="30000" He3Award="50000" MoneyAward="30000" ItemAward="-1" MainTaskDepend="93" TradeNum="1000"/>
    <Level TaskName="Free Trade  8" Comment1="One man's trash is another man's treasure - so long as it's not complete garbage." Comment2="Trading volume reaches 3,000" MetalAward="50000" He3Award="80000" MoneyAward="50000" ItemAward="-1" MainTaskDepend="130" TradeNum="3000"/>
    <Level TaskName="Free Trade  9" Comment1="One man's trash is another man's treasure - so long as it's not complete garbage." Comment2="Trading volume reaches 10,000" MetalAward="80000" He3Award="100000" MoneyAward="80000" ItemAward="-1" MainTaskDepend="148" TradeNum="10000"/>
    <Level TaskName="Free Trade  10" Comment1="One man's trash is another man's treasure - so long as it's not complete garbage." Comment2="Trading volume reaches 30,000" MetalAward="150000" He3Award="200000" MoneyAward="150000" ItemAward="-1" MainTaskDepend="166" TradeNum="30000"/>
    <Level TaskName="Free Trade  11" Comment1="One man's trash is another man's treasure - so long as it's not complete garbage." Comment2="Trading volume reaches 50,000" MetalAward="200000" He3Award="300000" MoneyAward="200000" ItemAward="-1" MainTaskDepend="184" TradeNum="50000"/>
  </List>
  <List TaskID="512" TaskClass="1" HideFlag="0">
    <Level TaskName="Construction Speedup" Comment1="The most seasoned warlords know that a strong defense is the first step to greatness. Find a building that is currently under construction and click on the Arrow button next to the construction queue to build it faster." Comment2="Speed up Construction" MetalAward="2500" He3Award="4000" MoneyAward="2800" CoinsAward="5" ItemAward="-1" MainTaskDepend="4"/>
    <Level TaskName="Tech Advancement Speedup" Comment1="The study of science will lead to various technological breakthroughs, which will bolster development efforts. To speed up research, click on the Arrow button next to the research queue. The effects will be immediate." Comment2="Speed up Tech Advancement" MetalAward="2000" He3Award="3000" MoneyAward="2200" CoinsAward="5" ItemAward="-1" MainTaskDepend="111"/>
    <Level TaskName="Speed up Module Research" Comment1="Galactic warloards who invest in the latest and most powerful weapon technology will have a brutal edge on the battlefield! Check your Weapon Research Center for any ongoing Module Blueprint research and speed it up for faster completion." Comment2="Speed up Module Blueprint Research" MetalAward="2600" He3Award="4200" MoneyAward="3000" CoinsAward="5" ItemAward="-1" MainTaskDepend="5"/>
    <Level TaskName="Time To Build" Comment1="The (Construction Card) is an ambitious Commander's best friend. Find them in the Web Mall or win them via the Lucky Wheel to really get things cranking! (You have one in the bag.)" Comment2="Use a Construction Card" MetalAward="3000" He3Award="4500" MoneyAward="3200" ItemAward="-1" MainTaskDepend="5"/>
  </List>
  <List TaskID="513" TaskClass="1" HideFlag="0">
    <Level TaskName="Commander Card Combination" Comment1="Combine abilities from different commanders to create a commander that best supports your strategy!" Comment2="Combine Commander Cards at the Compounding Center" MetalAward="10000" He3Award="20000" MoneyAward="12000" ItemAward="-1" MainTaskDepend="36" CommanderLevel="1"/>
    <Level TaskName="Military Ranks 1" Comment1="Military ranks directly reflect that soldier's experience, contributions and capabilities. The higher the rank, the better that commander will be when leading troops into battle." Comment2="Obtain a 3 Star Commander" MetalAward="20000" He3Award="30000" MoneyAward="22000" ItemAward="-1" MainTaskDepend="36" CommanderLevel="2"/>
    <Level TaskName="Military Ranks 2" Comment1="Military ranks directly reflect that soldier's experience, contributions and capabilities. The higher the rank, the better that commander will be when leading troops into battle." Comment2="Obtain a 4 Star Commander" MetalAward="30000" He3Award="45000" MoneyAward="32000" ItemAward="-1" MainTaskDepend="36" CommanderLevel="3"/>
    <Level TaskName="Military Ranks 3" Comment1="Military ranks directly reflect that soldier's experience, contributions and capabilities. The higher the rank, the better that commander will be when leading troops into battle." Comment2="Obtain a 5 Star Commander" MetalAward="60000" He3Award="75000" MoneyAward="62000" ItemAward="-1" MainTaskDepend="36" CommanderLevel="4"/>
    <Level TaskName="Military Ranks 4" Comment1="Military ranks directly reflect that soldier's experience, contributions and capabilities. The higher the rank, the better that commander will be when leading troops into battle." Comment2="Obtain a 6 Star Commander" MetalAward="100000" He3Award="150000" MoneyAward="120000" CoinsAward="10" ItemAward="-1" MainTaskDepend="36" CommanderLevel="5"/>
    <Level TaskName="Military Ranks 5" Comment1="Military ranks directly reflect that soldier's experience, contributions and capabilities. The higher the rank, the better that commander will be when leading troops into battle." Comment2="Obtain a 7 Star Commander" MetalAward="200000" He3Award="300000" MoneyAward="200000" CoinsAward="30" ItemAward="-1" MainTaskDepend="36" CommanderLevel="6"/>
    <Level TaskName="Military Ranks 6" Comment1="Military ranks directly reflect that soldier's experience, contributions and capabilities. The higher the rank, the better that commander will be when leading troops into battle." Comment2="Obtain a 8 Star Commander" MetalAward="500000" He3Award="600000" MoneyAward="500000" CoinsAward="50" ItemAward="-1" MainTaskDepend="36" CommanderLevel="7"/>
    <Level TaskName="Military Ranks 7" Comment1="Military ranks directly reflect that soldier's experience, contributions and capabilities. The higher the rank, the better that commander will be when leading troops into battle." Comment2="Obtain a 9 Star Commander" MetalAward="10000000" He3Award="15000000" MoneyAward="1100000" CoinsAward="100" ItemAward="-1" MainTaskDepend="36" CommanderLevel="8"/>
  </List>
  <List TaskID="514" TaskClass="1" HideFlag="0">
    <Level TaskName="Speedy Shipbuilding" Comment1="Speedy development is often the difference between success and failure. Maintain a military advantage over your foes by speeding up the shipbuilding process. You can do this by clicking the Arrow key next to your shipyard's build queue." Comment2="Speed up shipbuilding" MetalAward="2200" He3Award="3500" MoneyAward="2500" CoinsAward="5" ItemAward="-1" MainTaskDepend="2"/>
  </List>
  <List TaskID="515" TaskClass="1" HideFlag="0">
    <Level TaskName="Beefing Up Defenses 2" Comment1="Having strong defenses is often the best deterrant for would-be aggressors. (Click on &lt;a href='event:10'&gt;(Space Base)&lt;/a&gt; located at the bottom of the main interface to access your outer defenses, then click on &lt;a href='event:1'&gt;(Build)&lt;/a&gt; located at the bottom right corner and select &lt;a href='event:2'&gt;(Construct Buildings)&lt;/a&gt;. Select Defenses from the pop up box.)" Comment2="Construct 5 Defensive Structures" MetalAward="2000" He3Award="3000" MoneyAward="2100" ItemAward="-1" MainTaskDepend="11" DefenceNum="5"/>
    <Level TaskName="Beefing Up Defenses 3" Comment1="Having strong defenses is often the best deterrant for would-be aggressors. (Click on &lt;a href='event:10'&gt;(Space Base)&lt;/a&gt; located at the bottom of the main interface to access your outer defenses, then click on &lt;a href='event:1'&gt;(Build)&lt;/a&gt; located at the bottom right corner and select &lt;a href='event:2'&gt;(Construct Buildings)&lt;/a&gt;. Select Defenses from the pop up box.)" Comment2="Construct 10 Defensive Structures" MetalAward="3500" He3Award="5000" MoneyAward="3800" ItemAward="-1" MainTaskDepend="29" DefenceNum="10"/>
    <Level TaskName="Beefing Up Defenses 4" Comment1="Having strong defenses is often the best deterrant for would-be aggressors. (Click on &lt;a href='event:10'&gt;(Space Base)&lt;/a&gt; located at the bottom of the main interface to access your outer defenses, then click on &lt;a href='event:1'&gt;(Build)&lt;/a&gt; located at the bottom right corner and select &lt;a href='event:2'&gt;(Construct Buildings)&lt;/a&gt;. Select Defenses from the pop up box.)" Comment2="Construct 15 Defensive Structures" MetalAward="6000" He3Award="10000" MoneyAward="5000" ItemAward="-1" MainTaskDepend="48" DefenceNum="15"/>
    <Level TaskName="Beefing Up Defenses 5" Comment1="Having strong defenses is often the best deterrant for would-be aggressors. (Click on &lt;a href='event:10'&gt;(Space Base)&lt;/a&gt; located at the bottom of the main interface to access your outer defenses, then click on &lt;a href='event:1'&gt;(Build)&lt;/a&gt; located at the bottom right corner and select &lt;a href='event:2'&gt;(Construct Buildings)&lt;/a&gt;. Select Defenses from the pop up box.)" Comment2="Construct 20 Defensive Structures" MetalAward="10000" He3Award="20000" MoneyAward="6000" ItemAward="-1" MainTaskDepend="66" DefenceNum="20"/>
    <Level TaskName="Beefing Up Defenses 6" Comment1="Having strong defenses is often the best deterrant for would-be aggressors. (Click on &lt;a href='event:10'&gt;(Space Base)&lt;/a&gt; located at the bottom of the main interface to access your outer defenses, then click on &lt;a href='event:1'&gt;(Build)&lt;/a&gt; located at the bottom right corner and select &lt;a href='event:2'&gt;(Construct Buildings)&lt;/a&gt;. Select Defenses from the pop up box.)" Comment2="Construct 30 Defensive Structures" MetalAward="20000" He3Award="35000" MoneyAward="12000" ItemAward="-1" MainTaskDepend="83" DefenceNum="30"/>
    <Level TaskName="Beefing Up Defenses 7" Comment1="Having strong defenses is often the best deterrant for would-be aggressors. (Click on &lt;a href='event:10'&gt;(Space Base)&lt;/a&gt; located at the bottom of the main interface to access your outer defenses, then click on &lt;a href='event:1'&gt;(Build)&lt;/a&gt; located at the bottom right corner and select &lt;a href='event:2'&gt;(Construct Buildings)&lt;/a&gt;. Select Defenses from the pop up box.)" Comment2="Construct 40 Defensive Structures" MetalAward="60000" He3Award="70000" MoneyAward="55000" ItemAward="-1" MainTaskDepend="120" DefenceNum="40"/>
    <Level TaskName="Beefing Up Defenses 8" Comment1="Having strong defenses is often the best deterrant for would-be aggressors. (Click on &lt;a href='event:10'&gt;(Space Base)&lt;/a&gt; located at the bottom of the main interface to access your outer defenses, then click on &lt;a href='event:1'&gt;(Build)&lt;/a&gt; located at the bottom right corner and select &lt;a href='event:2'&gt;(Construct Buildings)&lt;/a&gt;. Select Defenses from the pop up box.)" Comment2="Construct 50 Defensive Structures" MetalAward="80000" He3Award="100000" MoneyAward="70000" ItemAward="-1" MainTaskDepend="138" DefenceNum="50"/>
    <Level TaskName="Beefing Up Defenses 9" Comment1="Having strong defenses is often the best deterrant for would-be aggressors. (Click on &lt;a href='event:10'&gt;(Space Base)&lt;/a&gt; located at the bottom of the main interface to access your outer defenses, then click on &lt;a href='event:1'&gt;(Build)&lt;/a&gt; located at the bottom right corner and select &lt;a href='event:2'&gt;(Construct Buildings)&lt;/a&gt;. Select Defenses from the pop up box.)" Comment2="Construct 60 Defensive Structures" MetalAward="300000" He3Award="400000" MoneyAward="300000" ItemAward="-1" MainTaskDepend="156" DefenceNum="60"/>
    <Level TaskName="Beefing Up Defenses 10" Comment1="Having strong defenses is often the best deterrant for would-be aggressors. (Click on &lt;a href='event:10'&gt;(Space Base)&lt;/a&gt; located at the bottom of the main interface to access your outer defenses, then click on &lt;a href='event:1'&gt;(Build)&lt;/a&gt; located at the bottom right corner and select &lt;a href='event:2'&gt;(Construct Buildings)&lt;/a&gt;. Select Defenses from the pop up box.)" Comment2="Construct 72 Defensive Structures" MetalAward="800000" He3Award="1000000" MoneyAward="800000" ItemAward="-1" MainTaskDepend="156" DefenceNum="72"/>
    <Level TaskName="Beefing Up Defenses 11" Comment1="Having strong defenses is often the best deterrant for would-be aggressors. (Click on &lt;a href='event:10'&gt;(Space Base)&lt;/a&gt; located at the bottom of the main interface to access your outer defenses, then click on &lt;a href='event:1'&gt;(Build)&lt;/a&gt; located at the bottom right corner and select &lt;a href='event:2'&gt;(Construct Buildings)&lt;/a&gt;. Select Defenses from the pop up box.)" Comment2="Construct 86 Defensive Structures" MetalAward="2000000" He3Award="3000000" MoneyAward="2000000" ItemAward="-1" MainTaskDepend="174" DefenceNum="86"/>
  </List>
  <List TaskID="516" TaskClass="1" HideFlag="0">
    <Level TaskName="Instances 2" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete Deadzone " MetalAward="10000" He3Award="10000" MoneyAward="10000" ItemAward="-1" MainTaskDepend="26" EctypeID="1"/>
    <Level TaskName="Instances 3" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete Bravery" MetalAward="15000" He3Award="15000" MoneyAward="15000" ItemAward="-1" MainTaskDepend="26" EctypeID="2"/>
    <Level TaskName="Instances 4" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete Ambush" MetalAward="20000" He3Award="20000" MoneyAward="20000" ItemAward="-1" MainTaskDepend="26" EctypeID="3"/>
    <Level TaskName="Instances 5" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete Defending Yourself" MetalAward="25000" He3Award="25000" MoneyAward="25000" ItemAward="-1" MainTaskDepend="26" EctypeID="4"/>
    <Level TaskName="Instances 6" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete To Victory" MetalAward="30000" He3Award="30000" MoneyAward="30000" ItemAward="-1" MainTaskDepend="26" EctypeID="5"/>
    <Level TaskName="Instances 7" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete Annihilation" MetalAward="35000" He3Award="35000" MoneyAward="35000" ItemAward="-1" MainTaskDepend="26" EctypeID="6"/>
    <Level TaskName="Instances 8" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete Hellish Ventures" MetalAward="40000" He3Award="40000" MoneyAward="40000" ItemAward="-1" MainTaskDepend="26" EctypeID="7"/>
    <Level TaskName="Instances 9" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete Duel" MetalAward="45000" He3Award="45000" MoneyAward="45000" ItemAward="-1" MainTaskDepend="26" EctypeID="8"/>
    <Level TaskName="Instances 10" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete Lost" MetalAward="50000" He3Award="50000" MoneyAward="50000" ItemAward="905" ItemNum="1" MainTaskDepend="26" EctypeID="9"/>
    <Level TaskName="Instances 11" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete Wonderland" MetalAward="55000" He3Award="55000" MoneyAward="55000" ItemAward="-1" MainTaskDepend="26" EctypeID="10"/>
    <Level TaskName="Instances 12" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete Dead or Alive" MetalAward="60000" He3Award="60000" MoneyAward="60000" ItemAward="-1" MainTaskDepend="26" EctypeID="11"/>
    <Level TaskName="Instances 13" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete Ship Graveyard" MetalAward="65000" He3Award="65000" MoneyAward="65000" ItemAward="-1" MainTaskDepend="26" EctypeID="12"/>
    <Level TaskName="Instances 14" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete E.C.R" MetalAward="70000" He3Award="70000" MoneyAward="70000" ItemAward="-1" MainTaskDepend="26" EctypeID="13"/>
    <Level TaskName="Instances 15" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete Free Flight " MetalAward="75000" He3Award="75000" MoneyAward="75000" ItemAward="906" ItemNum="1" MainTaskDepend="26" EctypeID="14"/>
    <Level TaskName="Instances 16" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete Spell Break" MetalAward="80000" He3Award="80000" MoneyAward="80000" ItemAward="-1" MainTaskDepend="26" EctypeID="15"/>
    <Level TaskName="Instances 17" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete Lucky Zodiac" MetalAward="85000" He3Award="85000" MoneyAward="85000" ItemAward="-1" MainTaskDepend="26" EctypeID="16"/>
    <Level TaskName="Instances 18" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete The Blackest Hole" MetalAward="90000" He3Award="90000" MoneyAward="90000" ItemAward="-1" MainTaskDepend="26" EctypeID="17"/>
    <Level TaskName="Instances 19" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete The Matrix Returned" MetalAward="95000" He3Award="95000" MoneyAward="95000" ItemAward="-1" MainTaskDepend="26" EctypeID="18"/>
    <Level TaskName="Instances 20" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete Timewhirl" MetalAward="100000" He3Award="100000" MoneyAward="100000" ItemAward="907" ItemNum="1" MainTaskDepend="26" EctypeID="19"/>
    <Level TaskName="Instances 21" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete Bushwhacked" MetalAward="110000" He3Award="110000" MoneyAward="110000" ItemAward="-1" MainTaskDepend="26" EctypeID="20"/>
    <Level TaskName="Instances 22" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete The Gathering" MetalAward="120000" He3Award="120000" MoneyAward="120000" ItemAward="-1" MainTaskDepend="26" EctypeID="21"/>
    <Level TaskName="Instances 23" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete Saving Grace" MetalAward="130000" He3Award="130000" MoneyAward="130000" ItemAward="-1" MainTaskDepend="26" EctypeID="22"/>
    <Level TaskName="Instances 24" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete Prowler" MetalAward="140000" He3Award="140000" MoneyAward="140000" ItemAward="-1" MainTaskDepend="26" EctypeID="23"/>
    <Level TaskName="Instances 25" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete Faceoff-I" MetalAward="150000" He3Award="150000" MoneyAward="150000" ItemAward="926" ItemNum="1" MainTaskDepend="26" EctypeID="24"/>
    <Level TaskName="Instances 26" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete Faceoff-II" MetalAward="160000" He3Award="160000" MoneyAward="160000" ItemAward="-1" MainTaskDepend="26" EctypeID="25"/>
    <Level TaskName="Instances 27" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete Broken Pact" MetalAward="170000" He3Award="170000" MoneyAward="170000" ItemAward="-1" MainTaskDepend="26" EctypeID="26"/>
    <Level TaskName="Instances 28" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete Smashing" MetalAward="180000" He3Award="180000" MoneyAward="180000" ItemAward="-1" MainTaskDepend="26" EctypeID="27"/>
    <Level TaskName="Instances 29" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete B.P" MetalAward="190000" He3Award="190000" MoneyAward="190000" ItemAward="-1" MainTaskDepend="26" EctypeID="28"/>
    <Level TaskName="Instances 30" Comment1="With a sizeable fleet constructed, it's time to get into the action! (Click on (Space Base), located at the bottom of the main interface, then click on (Space Station). Select (Instances) from the pop up box to start!)" Comment2="Successfully complete Triumphant Glory" MetalAward="200000" He3Award="200000" MoneyAward="200000" ItemAward="901" ItemNum="1" MainTaskDepend="26" EctypeID="29"/>
  </List>
  <List TaskID="517" TaskClass="1" HideFlag="0">
    <Level TaskName="Peace Agreement" Comment1="Prevent future attacks with a Truce Card. A Truce Card will prevent all attacks for a period of 12 hours, starting when it is activated. (Truce Cards cannot be used before or during an imminent attack, and no attacks may be made by a player protected by a Truce Card). " Comment2="Click the &quot;Collect Rewards&quot; button to claim a Truce Card." ItemAward="902" ItemNum="1" MainTaskDepend="0"/>
  </List>
</Task>;
      
      public function GameRes_ExtendTaskXml()
      {
         super();
      }
   }
}

