package
{
   public class GameRes_InstanceChallenge
   {
      
      public static var data:XML = <InstanceChallenge Name="挑戰副本" MC="CopydianPlan1" LineColor="0x774701" FreeTime="2" Prop="1" Context="">
  <Ectype0 ID="1" X="37" Y="45" Name="1.Calvin's Riches" EctypeID="30" NeedID="-1" Repeat="2" UserTeam="10" MaxGate="1" Treasure="931" Number="10" Treasure2="1540" Exp="10000" Comment="Destroy all enemy warships in this round." Comment2="Calvin is a notorious pirate who has earned a reputation for robbing wealthy merchants along the commercial trade routes the past few decades. Over the years he has amassed quite the store of treasure. In addition, it seems his ambitions are expanding, as he has been implicated in a more than a few recent battles with government troops. These attacks must stop. Whoever manages to kill Calvin will be richly rewarded."/>
  <Ectype1 ID="2" X="77" Y="186" Name="2.The Prodigal Prince Returns" EctypeID="31" NeedID="-1" Repeat="2" UserTeam="12" MaxGate="1" Treasure="931" Number="13" Treasure2="1541" Exp="20000" Comment="Destroy all enemy warships in this round." Comment2="The empire of Rayman has been in disorder and chaos since the death of the Emperor and the disintegration of the Empire. Fortunately, Prince Rekacel has at long last returned with a strong fleet and is hoping to reunify the once sprawling Empire. Despite his high hopes, most citizens are skeptical of his chances for success. TO be successful, Prince Rekacel needs the help of every strong commander he can find. Would you like to help him out?"/>
  <Ectype2 ID="3" X="28" Y="256" Name="3.The Danger Zone" EctypeID="32" NeedID="-1" Repeat="2" UserTeam="15" MaxGate="1" Treasure="931" Number="16" Treasure2="1542" Exp="30000" Comment="Destroy all enemy warships in this round." Comment2="Adars is known far and wide as a no-go zone. Unbelievably dangerous and home to some of the most violent forces in the galaxy, both natural and unnatural, those who brave this area must contend with collapsing red giants, and abnormal magnetic and  gravitational fields, just to name a few. A few older veterans even whisper of a super massive black hole at the center of the region that devours all that ventures in, but none have been able to prove it. Countless warships have vanished here, never to be seen or heard from again. You would think this would discourage exploration, but instead it has encouraged it. "/>
  <Ectype3 ID="4" X="70" Y="352" Name="4.Rofilla Ruins Resurrected" EctypeID="33" NeedID="-1" Repeat="2" UserTeam="18" MaxGate="1" Treasure="931" Number="20" Treasure2="1543" Exp="40000" Comment="Destroy all enemy warships in this round." Comment2="The Rofilla Consortium has earned great wealth through the buying and selling of information and arms during the war. They then used these funds to construct an immense base, known as Cuirass Fortress. Though the fortress was designed to withstand any attack, it was eventually undone by a natural catastrophe and abandoned. Recently reports have been coming in of an evil force of pirates that has been repairing it, hoping to turn it into an impregnable hideout and the launch pad of an invasion of the Federation. We cannot just stand by idly, or they will continue to grow in strength until we cannot act without great losses. The time to strike is now. Destroy the fortress completely."/>
  <Ectype4 ID="5" X="160" Y="315" Name="5.Helping Helukar" EctypeID="34" NeedID="-1" Repeat="2" UserTeam="20" MaxGate="1" Treasure="931" Number="23" Treasure2="1544" Exp="50000" Comment="Destroy all enemy warships in this round." Comment2="You received a secret letter from the planet Helukar, detailing a vicious attack by an unknown species and a request help in defeating them. Helukar was originally a scientific research base that belonged to the Kadry Group. However, there has been no news about this long neglected outpost since the fall of the Kadry Group. This secret letter seems very strange, but we cannot just ignore a plea for help. Lead a force to help out Helukar. After arriving, you were trapped. Giant bulwarks have suddenly appeared and are blocking your retreat. How will you escape?"/>
  <Ectype5 ID="6" X="205" Y="358" Name="6.An Intriguing Opportunity" EctypeID="35" NeedID="-1" Repeat="2" UserTeam="20" MaxGate="1" Treasure="931" Number="26" Treasure2="1545" Exp="60000" Comment="Destroy all enemy warships in this round." Comment2="Our investigation shows that it was Murphy, a Federation Councilor, who was behind the ambush against you in Helukar. He intended to eliminate you and steal your fortune. Fortunately for us, Murphy plans to attend a Council conference tomorrow on the planet Darna. Now is the chance for us to strike back and show him who he's messing with. Take this opportunity to attack his base. "/>
  <Ectype6 ID="7" X="333" Y="323" Name="7.The Thorn" EctypeID="36" NeedID="-1" Repeat="2" UserTeam="20" MaxGate="1" Treasure="931" Number="30" Treasure2="1546" Exp="70000" Comment="Destroy all enemy warships in this round." Comment2="What? We've been assaulted? Who dares to attack my main base? Weikes? You mean a swarm of Weikes are attacking us right now? Damn those pesky bugs, smash them all!"/>
  <Ectype7 ID="8" X="356" Y="215" Name="8.The Final Attack" EctypeID="37" NeedID="-1" Repeat="2" UserTeam="21" MaxGate="1" Treasure="931" Number="33" Treasure2="1547" Exp="80000" Comment="Destroy all enemy warships in this round." Comment2="Prince Rekacel has planned a massive offensive against Calmet, the last major fortress occupied by the rebel army."/>
  <Ectype8 ID="9" X="231" Y="236" Name="9.The Decision" EctypeID="38" NeedID="-1" Repeat="2" UserTeam="25" MaxGate="1" Treasure="931" Number="36" Treasure2="1548" Exp="90000" Comment="Destroy all enemy warships in this round." Comment2="The Federation has charged you with high treason and declared war on your forces. Under orders from the Federation, fleets handpicked by Murphy are right now laying siege to your home planet. Will you fight or flee?"/>
  <Ectype9 ID="10" X="185" Y="164" Name="10.Judgment Day " EctypeID="39" NeedID="-1" Repeat="2" UserTeam="25" MaxGate="1" Treasure="931" Number="40" Treasure2="1549" Exp="100000" Comment="Destroy all enemy warships in this round." Comment2="This is the final battle. The outcome here will decide it all. Return victorious or not all!"/>
</InstanceChallenge>;
      
      public function GameRes_InstanceChallenge()
      {
         super();
      }
   }
}

