package
{
   public class GameRes_WeaponTechXml
   {
      
      public static var data:XML = <WeaponTech Name="EN-武器科技">
  <List GroupID="0" Name="Ballistics" Comment="Increases base damage of Ballistic weapons; Lv1: Increases base damage by 5%." Kind="12" Tech="" ImageFileName="Tech0" Title="0/10" TechMemo="">
    <Level1 GroupLV="1" Comment="Current Level: Increases base damage of Ballistic weapons by 5%; Next level: Increases base damage by 10%." Title="1/10" Hit="0.05" Money="541" Time="117"/>
    <Level2 GroupLV="2" Comment="Current Level: Increases base damage of Ballistic weapons by 10%; Next level: Increases base damage by 15%." Title="2/10" Hit="0.1" Money="628" Time="158"/>
    <Level3 GroupLV="3" Comment="Current Level: Increases base damage of Ballistic weapons by 15%; Next level: Increases base damage by 20%." Title="3/10" Hit="0.15" Money="959" Time="368"/>
    <Level4 GroupLV="4" Comment="Current Level: Increases base damage of Ballistic weapons by 20%; Next level: Increases base damage by 25%." Title="4/10" Hit="0.2" Money="1467" Time="861"/>
    <Level5 GroupLV="5" Comment="Current Level: Increases base damage of Ballistic weapons by 25%; Next level: Increases base damage by 30%." Title="5/10" Hit="0.25" Money="2244" Time="2015"/>
    <Level6 GroupLV="6" Comment="Current Level: Increases base damage of Ballistic weapons by 30%; Next level: Increases base damage by 35%." Title="6/10" Hit="0.3" Money="3434" Time="4717"/>
    <Level7 GroupLV="7" Comment="Current Level: Increases base damage of Ballistic weapons by 35%; Next level: Increases base damage by 40%." Title="7/10" Hit="0.35" Money="5253" Time="11039"/>
    <Level8 GroupLV="8" Comment="Current Level: Increases base damage of Ballistic weapons by 40%; Next level: Increases base damage by 45%." Title="8/10" Hit="0.4" Money="8036" Time="25834"/>
    <Level9 GroupLV="9" Comment="Current Level: Increases base damage of Ballistic weapons by 45%; Next level: Increases base damage by 50%." Title="9/10" Hit="0.45" Money="12294" Time="60461"/>
    <Level10 GroupLV="10" Comment="Current Level: Increases base damage of Ballistic weapons by &lt;font color='#00FF00'&gt;50%&lt;/font&gt;." Title="10" Hit="0.5" Money="18808" Time="141501"/>
  </List>
  <List GroupID="1" Name="Ballistic Malice" Comment="Increases critical hit rate of Ballistic weapons; Lv1: Increases critical hit rate by 1%." Kind="12" Tech="0:3" ImageFileName="Tech1" Title="0/5" TechMemo="Requires Ballistics Lv 3 ">
    <Level1 GroupLV="1" Comment="Current Level: Increases critical hit rate of Ballistic weapons by 1%; Next level: Increases critical hit rate by 2%." Title="1/5" Blast="0.01" Money="7558" Time="1428"/>
    <Level2 GroupLV="2" Comment="Current Level: Increases critical hit rate of Ballistic weapons by 2%; Next level: Increases critical hit rate by 3%." Title="2/5" Blast="0.02" Money="8752" Time="1915"/>
    <Level3 GroupLV="3" Comment="Current Level: Increases critical hit rate of Ballistic weapons by 3%; Next level: Increases critical hit rate by 4%." Title="3/5" Blast="0.03" Money="13385" Time="4479"/>
    <Level4 GroupLV="4" Comment="Current Level: Increases critical hit rate of Ballistic weapons by 4%; Next level: Increases critical hit rate by 5%." Title="4/5" Blast="0.04" Money="20477" Time="10483"/>
    <Level5 GroupLV="5" Comment="Current Level: Increases critical hit rate of Ballistic weapons by &lt;font color='#00FF00'&gt;5%&lt;/font&gt;." Title="5" Blast="0.05" Money="31327" Time="24535"/>
  </List>
  <List GroupID="2" Name="Ballistic Crackdown" Comment="Increases critical damage of Ballistic weapons; Lv1: Increases critical damage by 10%." Kind="12" Tech="0:6;1:3" ImageFileName="Tech2" Title="0/2" TechMemo="Requires Ballistics Lv 6, Ballistic Malice Lv 3">
    <Level1 GroupLV="1" Comment="Current Level: Increases critical damage of Ballistic weapons by 10%; Next level: Increases critical damage by 20%." Title="1/2" BlastHurt="0.1" Money="29628" Time="4335"/>
    <Level2 GroupLV="2" Comment="Current Level: Increases critical damage of Ballistic weapons by &lt;font color='#00FF00'&gt;20%&lt;/font&gt;." Title="2" BlastHurt="0.2" Money="34303" Time="5811"/>
  </List>
  <List GroupID="3" Name="Steady Control Tech" Comment="Reduces space occupied by Ballistic weapons; Lv1: Reduces space occupied by 2%." Kind="12" Tech="0:6;1:3" ImageFileName="Tech3" Title="0/5" TechMemo="Requires Ballistics Lv 6, Ballistic Malice Lv 3">
    <Level1 GroupLV="1" Comment="Current Level: Reduces space occupied by Ballistic weapons by 2%; Next level: Reduces space occupied by 4%." Title="1/5" LowCubage="0.02" Money="26108" Time="3366"/>
    <Level2 GroupLV="2" Comment="Current Level: Reduces space occupied by Ballistic weapons by 4%; Next level: Reduces space occupied by 6%." Title="2/5" LowCubage="0.04" Money="30227" Time="4512"/>
    <Level3 GroupLV="3" Comment="Current Level: Reduces space occupied by Ballistic weapons by 6%; Next level: Reduces space occupied by 8%." Title="3/5" LowCubage="0.06" Money="46241" Time="10559"/>
    <Level4 GroupLV="4" Comment="Current Level: Reduces space occupied by Ballistic weapons by 8%; Next level: Reduces space occupied by 10%." Title="4/5" LowCubage="0.08" Money="70739" Time="24711"/>
    <Level5 GroupLV="5" Comment="Current Level: Reduces space occupied by Ballistic weapons by &lt;font color='#00FF00'&gt;10%&lt;/font&gt;." Title="5" LowCubage="0.1" Money="108217" Time="57832"/>
  </List>
  <List GroupID="4" Name="Precise Ballistics" Comment="Increases hit rate of Ballistic weapons; Lv1: Increase hit rate by 1%." Kind="12" Tech="0:8;3:3" ImageFileName="Tech4" Title="0/5" TechMemo="Requires Ballistics Lv 8, Steady Control Tech Lv 3">
    <Level1 GroupLV="1" Comment="Current Level: Increases hit rate of Ballistic weapons by 1%; Next level: Increase hit rate by 2%." Title="1/5" Ratio="0.01" Money="51100" Time="4080"/>
    <Level2 GroupLV="2" Comment="Current Level: Increases hit rate of Ballistic weapons by 2%; Next level: Increase hit rate by 3%." Title="2/5" Ratio="0.02" Money="59162" Time="5469"/>
    <Level3 GroupLV="3" Comment="Current Level: Increases hit rate of Ballistic weapons by 3%; Next level: Increase hit rate by 4%." Title="3/5" Ratio="0.03" Money="90506" Time="12799"/>
    <Level4 GroupLV="4" Comment="Current Level: Increases hit rate of Ballistic weapons by 4%; Next level: Increase hit rate by 5%." Title="4/5" Ratio="0.04" Money="138453" Time="29952"/>
    <Level5 GroupLV="5" Comment="Current Level: Increases hit rate of Ballistic weapons by &lt;font color='#00FF00'&gt;5%&lt;/font&gt;." Title="5" Ratio="0.05" Money="211811" Time="70100"/>
  </List>
  <List GroupID="5" Name="Shield Penetration" Comment="Enables your Ballistic weapons to penetrate enemy shields and directly damage the enemy hull for &lt;font color='#00FF00'&gt;15%&lt;/font&gt; of the damage caused by your Ballistic weapons." Kind="12" Tech="1:5;2:1;4:1" ImageFileName="Tech5" Title="0/1" TechMemo="Requires Ballistic Malice Lv 5, Ballistic Crackdown Lv 1, Precise Ballistics Lv 1">
    <Level1 GroupLV="1" Comment="Enables your Ballistic weapons to penetrate enemy shields and directly damage the enemy hull for &lt;font color='#00FF00'&gt;15%&lt;/font&gt; of the damage caused by your Ballistic weapons." Title="1" CrossShield="0.15" Money="154616" Time="15300"/>
  </List>
  <List GroupID="6" Name="Depleted Uranium Bomb Research" Comment="Increases damage dealt by Kinetic Energy type Ballistic weapon against Neutral and Light armor types;  Lv1: +10% damage against Neutral armor and +1% damage against Light armor." Kind="12" Tech="2:2;5:1" ImageFileName="Tech6" Title="0/3" TechMemo="Requires Ballistic Crackdown Lv 2, Shield Penetration Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: Increases Kinetic energy type Ballistic weapon damage against Neutral armor by 10% and against Light armor by 1%; Next level: +20% damage against Neutral armor and +2% damage against Light armor." Title="1/3" HurtType="11" ArmorHurt="3:0.1;5:0.01;6:0.01" Money="203249" Time="12750"/>
    <Level2 GroupLV="2" Comment="Current Level: Increases Kinetic energy type Ballistic weapon damage against Neutral armor by 20% and against Light armor by 2%; Next level: +30% damage against Neutral armor and +3% damage against Light armor." Title="2/3" HurtType="11" ArmorHurt="3:0.2;5:0.02;6:0.02" Money="235312" Time="17090"/>
    <Level3 GroupLV="3" Comment="Current Level: Increases Kinetic energy type Ballistic weapon damage against Neutral armor by &lt;font color='#00FF00'&gt;30%&lt;/font&gt; and against Light armor by &lt;font color='#00FF00'&gt;3%&lt;/font&gt;." Title="3" HurtType="11" ArmorHurt="3:0.3;5:0.03;6:0.03" Money="359977" Time="39995"/>
  </List>
  <List GroupID="7" Name="Fire Bomb Research" Comment="Increases damage dealt by Light Energy type Ballistic weapons against Compound and Light armor types; Lv1: +10% damage against Compound armor and +1% damage against Light armor." Kind="12" Tech="2:2;5:1" ImageFileName="Tech7" Title="0/3" TechMemo="Requires Ballistic Crackdown Lv 2, Shield Penetration Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: Increases Light energy type Ballistic weapon damage against Regen armor by 10% and against Light armor by 1%; Next level: +20% damage against Regen armor and +2% damage against Light armor." Title="1/3" HurtType="13" ArmorHurt="4:0.1;5:0.01;6:0.01" Money="203249" Time="12750"/>
    <Level2 GroupLV="2" Comment="Current Level: Increases Light energy type Ballistic weapon damage against Regen armor by 20% and against Light armor by 2%; Next level: +30% damage against Regen armor and +3% damage against Light armor." Title="2/3" HurtType="13" ArmorHurt="4:0.2;5:0.02;6:0.02" Money="235312" Time="17090"/>
    <Level3 GroupLV="3" Comment="Current Level: Increases Light energy type Ballistic weapon damage against Regen armor by &lt;font color='#00FF00'&gt;30%&lt;/font&gt; and against Light armor by &lt;font color='#00FF00'&gt;3%&lt;/font&gt;." Title="3" HurtType="13" ArmorHurt="4:0.3;5:0.03;6:0.03" Money="359977" Time="39995"/>
  </List>
  <List GroupID="8" Name="Improved Penetration" Comment="Increases Ballistic weapon damage against Light armor type and increases chance of penetrating enemy shields ; Lv1: +1% damage against Light armor and +3% chance to penetrate shields." Kind="12" Tech="6:1;7:1" ImageFileName="Tech8" Title="0/3" TechMemo="Requires Depleted Uranium Bomb Research Lv 1, Fire Bomb Research Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: Increases Ballistic weapon damage against Light armor by 1% and grants a 3% chance to penetrate enemy shields; Next level: +2% damage against Light armor and +6% chance to penetrate shields." Title="1/3" CrossShield="0.03" ArmorHurt="5:0.01;6:0.01" Money="484776" Time="22950"/>
    <Level2 GroupLV="2" Comment="Current Level: Increases Ballistic weapon damage against Light armor by 2% and grants a 6% chance to penetrate enemy shields; Next level: +3% damage against Light armor and +10% chance to penetrate shields." Title="2/3" CrossShield="0.06" ArmorHurt="5:0.02;6:0.02" Money="561242" Time="30761"/>
    <Level3 GroupLV="3" Comment="Current Level: Increases Ballistic weapon damage against Light armor by &lt;font color='#00FF00'&gt;3%&lt;/font&gt; and grants a &lt;font color='#00FF00'&gt;10%&lt;/font&gt; chance to penetrate shields. " Title="3" CrossShield="0.1" ArmorHurt="5:0.03;6:0.03" Money="858602" Time="71992"/>
  </List>
  <List GroupID="9" Name="Victory Rush" Comment="Increase Ballistic weapon damage depending on the weapon's range &lt;font color='#00FF00'&gt;1-4&lt;/font&gt; damages are: &lt;font color='#00FF00'&gt;220%, 180%, 150%, 120%&lt;/font&gt; damage with no technique research &lt;font color='#00FF00'&gt;150%, 120%&lt;/font&gt;, Also improves &lt;font color='#00FF00'&gt;5%&lt;/font&gt; critical hit rate and &lt;font color='#00FF00'&gt;5%&lt;/font&gt; critical damage." Kind="12" Tech="6:3;7:3;8:3" ImageFileName="Tech9" Title="0/1" TechMemo="Requires Depleted Uranium Bomb Research Lv 3, Fire Bomb Research Lv 3, Improved Penetration Lv 3">
    <Level1 GroupLV="1" Comment="Increase Ballistic weapon damage depending on the weapon's range &lt;font color='#00FF00'&gt;1-4&lt;/font&gt; damages are: &lt;font color='#00FF00'&gt;220%, 180%, 150%, 120%&lt;/font&gt; damage with no technique research &lt;font color='#00FF00'&gt;150%, 120%&lt;/font&gt;, Also improves &lt;font color='#00FF00'&gt;5%&lt;/font&gt; critical hit rate and &lt;font color='#00FF00'&gt;5%&lt;/font&gt; critical damage." Title="1" Blast="0.05" BlastHurt="0.05" CarryHurt="1:2.2;2:1.8;3:1.5;4:1.2" Money="1918521" Time="224400"/>
  </List>
  <List GroupID="10" Name="Ballistic Scattering" Comment="Enables Ballistic weapons to inflict Scattering rate to ships located in the same vertical row as the target ship; Lv1: Scattering rate is equal to 5% of weapon damage" Kind="12" Tech="0:10;1:5;3:5;4:3" ImageFileName="Tech10" Title="0/5" TechMemo="Requires Ballistics Lv 10, Ballistic Malice Lv 5, Steady Control Tech Lv 5, Precise Ballistics Lv 3">
    <Level1 GroupLV="1" Comment="Current Level: Enables your Ballistic weapons to Scattering rate is equal to 5% of weapon damage as the target; Next level: Scattering rate is equal to 10% of weapon damage" Title="1/5" Dispersion="0.05" Money="119765" Time="9180"/>
    <Level2 GroupLV="2" Comment="Current Level: Enables your Ballistic weapons to Scattering rate is equal to 10% of weapon damage as the target; Next level: Scattering rate is equal to 15% of weapon damage." Title="2/5" Dispersion="0.1" Money="138660" Time="12305"/>
    <Level3 GroupLV="3" Comment="Current Level: Enables your Ballistic weapons to Scattering rate is equal to 15% of weapon damage as the target; Next level: Scattering rate is equal to 20% of weapon damage." Title="3/5" Dispersion="0.15" Money="212117" Time="28796"/>
    <Level4 GroupLV="4" Comment="Current Level: Enables your Ballistic weapons to Scattering rate is equal to 20% of weapon damage as the target; Next level: Scattering rate is equal to 25% of weapon damage." Title="4/5" Dispersion="0.2" Money="324504" Time="67394"/>
    <Level5 GroupLV="5" Comment="Current Level: Enables your Ballistic weapons to Scattering rate is equal to &lt;font color='#00FF00'&gt;25%&lt;/font&gt; of weapon damage as the target. " Title="5" Dispersion="0.25" Money="496433" Time="157725"/>
  </List>
  <List GroupID="11" Name="Improved Ballistic Scattering" Comment="Increases Scattering rate of Ballistic weapons; Lv1: Increases Scattering rate by 8%." Kind="12" Tech="4:5;10:3" ImageFileName="Tech11" Title="0/3" TechMemo="Requires Precise Ballistics Lv 5, Ballistic Scattering Lv 3">
    <Level1 GroupLV="1" Comment="Current Level: Enables Ballistic weapons to increases Scattering rate by 8%; Next level: Increases Scattering rate by 16%." Title="1/3" Dispersion="0.08" Money="240487" Time="17850"/>
    <Level2 GroupLV="2" Comment="Current Level: Enables Ballistic weapons to increases Scattering rate by 16%; Next level: Increases Scattering rate by 25%." Title="2/3" Dispersion="0.16" Money="278425" Time="23926"/>
    <Level3 GroupLV="3" Comment="Current Level: Enables Ballistic weapons to increases Scattering rate by &lt;font color='#00FF00'&gt;25%&lt;/font&gt;. " Title="3" Dispersion="0.25" Money="425931" Time="55993"/>
  </List>
  <List GroupID="12" Name="Hop Bomb Research" Comment="Enables Ballistic weapons to have a chance of dealing scattering damage that is 100% of its weapon damage; Lv1: Provides a 3% chance to deal scattering damage that is 100% of weapon damage." Kind="12" Tech="10:5;11:2" ImageFileName="Tech12" Title="0/5" TechMemo="Requires Ballistic Scattering Lv 5, Improved Ballistic Scattering Lv 2">
    <Level1 GroupLV="1" Comment="Current Level: Grants Ballistic weapons a 3% chance to deal Scattering damage that is equal to 100% of weapon damage; Next level: Provides a 6% chance to deal scattering damage that is 100% of weapon damage." Title="1/5" DispersionRate="0.02" DispersionPer="1" Money="349930" Time="20400"/>
    <Level2 GroupLV="2" Comment="Current Level: Grants Ballistic weapons a 6% chance to deal Scattering damage that is equal to 100% of weapon damage; Next level: Provides a 9% chance to deal scattering damage that is 100% of weapon damage." Title="2/5" DispersionRate="0.04" DispersionPer="1" Money="405133" Time="27344"/>
    <Level3 GroupLV="3" Comment="Current Level: Grants Ballistic weapons a 9% chance to deal Scattering damage that is equal to 100% of weapon damage; Next level: Provides a 12% chance to deal scattering damage that is 100% of weapon damage." Title="3/5" DispersionRate="0.06" DispersionPer="1" Money="619768" Time="63992"/>
    <Level4 GroupLV="4" Comment="Current Level: Grants Ballistic weapons a 12% chance to deal Scattering damage that is equal to 100% of weapon damage; Next level: Provides a 15% chance to deal scattering damage that is 100% of weapon damage." Title="4/5" DispersionRate="0.08" DispersionPer="1" Money="948134" Time="149764"/>
    <Level5 GroupLV="5" Comment="Current Level: Grants Ballistic weapons a &lt;font color='#00FF00'&gt;15%&lt;/font&gt; chance to deal Scattering damage that is equal to &lt;font color='#00FF00'&gt;100%&lt;/font&gt; of weapon damage." Title="5" DispersionRate="0.1" DispersionPer="1" Money="1450474" Time="350500"/>
  </List>
  <List GroupID="13" Name="Demolition Warhead Research" Comment="Increases base damage of Ballistic weapons by &lt;font color='#00FF00'&gt;20%&lt;/font&gt; when the target's HP is at &lt;font color='#00FF00'&gt;30%&lt;/font&gt; or less." Kind="12" Tech="11:3;12:3" ImageFileName="Tech13" Title="0/1" TechMemo="Requires Improved Ballistic Scattering Lv 3, Hop Bomb Research Lv 3">
    <Level1 GroupLV="1" Comment="Increases base damage of Ballistic weapons by &lt;font color='#00FF00'&gt;20%&lt;/font&gt; when the target's HP is at &lt;font color='#00FF00'&gt;30%&lt;/font&gt; or less." Title="1" HpHit="0.2" Hp="0.3" Money="885076" Time="76500"/>
  </List>
  <List GroupID="14" Name="Range Extension" Comment="Increases attack range of Ballistic weapons; Lv1: Increases attack range by 1." Kind="12" Tech="12:5;13:1" ImageFileName="Tech14" Title="0/2" TechMemo="Requires Hop Bomb Research Lv 5, Demolition Warhead Research Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: Increases attack range of Ballistic weapons by 1; Next level: Increases attack range by 2." Title="1/2" BoostCarry="1" Money="1735367" Time="183600"/>
    <Level2 GroupLV="2" Comment="Current Level: Increases attack range of Ballistic weapons by &lt;font color='#00FF00'&gt;2&lt;/font&gt;." Title="2" BoostCarry="2" Money="2009094" Time="246088"/>
  </List>
  <List GroupID="15" Name="Artillery Specialization" Comment="This science increases damage boost of the Demolition Warhead Research and Victory Rush sciences, increases damage against armor modules, enables Hop Bomb Research that gives Ballistic weapons an additional chance to deal 100% dispersion damage, while reducing the chance of penetrating shield modules; Next Level: Increases damage boost of the Demolition Warhead Research and Victory Rush sciences by 10%, increases damage against armor modules by 3%, enables Hop Bomb Research that gives Ballistic weapons a 1% increase in the chance to deal 100% dispersion damage, but reduces the chance of penetrating shield modules by 3%." Kind="12" Tech="9:1;14:2" ImageFileName="Tech15" Title="0/4" TechMemo="Requires Victory Rush Lv 1, Range Extension Lv 2">
    <Level1 GroupLV="1" Comment="This level of proficiency increases the damage boost of the Demolition Warhead Research and Victory Rush sciences by 10%, increases damage against armor modules by 3%, enables Hop Bomb Research that gives Ballistic weapons a 1% better chance at dealing 100% dispersion damage, but reducing the chance of penetrating shield modules by 3%; Next Level: Increases damage boost of the Demolition Warhead Research and Victory Rush sciences by 15%, increases damage against armor modules by 5%, enables Hop Bomb Research that gives Ballistic weapons a 2% better chance of dealing 100% dispersion damage, but reducing the chance of penetrating shield modules by 5%." Title="1/4" CrossShield="-0.03" ArmorHurt="1:0.03;2:0.03;3:0.03;4:0.03;5:0.03;6:0.03" CarryHurt="1:2.3;2:1.9;3:1.6;4:1.3" DispersionRate="0.01" HpHit="0.1" Money="10000000" Time="399952"/>
    <Level2 GroupLV="2" Comment="This level of proficiency increases damage boost of the Demolition Warhead Research and Victory Rush sciences by 15%, increases damage against armor modules by 5%, enables Hop Bomb Research that gives Ballistic weapons a 2% better chance of dealing 100% dispersion damage, but reducing the chance of penetrating shield modules by 5%; Next Level: Increases damage boost of the Demolition Warhead Research and Victory Rush sciences by 20%, increases damage against armor modules by 7%, enables Hop Bomb Research that gives Ballistic weapons a 3% better chance of dealing 100% dispersion damage, but reducing the chance of penetrating shield modules by 7%." Title="2/4" CrossShield="-0.05" ArmorHurt="1:0.05;2:0.05;3:0.05;4:0.05;5:0.05;6:0.05" CarryHurt="1:2.35;2:1.95;3:1.65;4:1.35" DispersionRate="0.02" HpHit="0.15" Money="30000000" Time="599952"/>
    <Level3 GroupLV="3" Comment="This level of proficiency increases damage boost of the Demolition Warhead Research and Victory Rush sciences by 20%, increases damage against armor modules by 7%, enables Hop Bomb Research that gives Ballistic weapons a 3% better chance of dealing 100% dispersion damage, but reducing the chance of penetrating shield modules by 7%; Next Level: Increases damage boost of the Demolition Warhead Research and Victory Rush sciences by 30%, increases damage against armor modules by 10%, enables Hop Bomb Research that give Ballistic weapons a 5% better chance of dealing 100% dispersion damage, but reducing the chance of penetrating shield modules by 10%." Title="3/4" CrossShield="-0.07" ArmorHurt="1:0.07;2:0.07;3:0.07;4:0.07;5:0.07;6:0.07" CarryHurt="1:2.4;2:2.0;3:1.7;4:1.4" DispersionRate="0.03" HpHit="0.2" Money="80000000" Time="729952"/>
    <Level4 GroupLV="4" Comment="This level of proficiency increases damage boost of the Demolition Warhead Research by &lt;font color='#00FF00'&gt;+30%&lt;/font&gt; and damage boost of the Victory Rush science by &lt;font color='#00FF00'&gt;+30%&lt;/font&gt;, increases damage against armor modules by &lt;font color='#00FF00'&gt;10%&lt;/font&gt;, enables Hop Bomb Research that gives Ballistic weapons a &lt;font color='#00FF00'&gt;5%&lt;/font&gt; better chance of dealing 100% dispersion damage, but reducing the chance of penetrating shield modules by &lt;font color='#00FF00'&gt;10%&lt;/font&gt;." Title="4" CrossShield="-0.1" ArmorHurt="1:0.1;2:0.1;3:0.1;4:0.1;5:0.1;6:0.1" CarryHurt="1:2.5;2:2.1;3:1.8;4:1.5" DispersionRate="0.05" HpHit="0.3" Money="150000000" Time="936026"/>
  </List>
  <List GroupID="16" Name="Optics" Comment="Increases damage dealt by Directional weapons; Lv1: Increases damage dealt by Directional weapons by 5%." Kind="13" Tech="" ImageFileName="Tech16" Title="0/10" TechMemo="">
    <Level1 GroupLV="1" Comment="Current Level: Increases damage dealt by Directional weapons by 5%; Next level: Increases damage dealt by Directional weapons by 10%." Title="1/10" Hit="0.05" Money="541" Time="117"/>
    <Level2 GroupLV="2" Comment="Current Level: Increases damage dealt by Directional weapons by 10%; Next level: Increases damage dealt by Directional weapons by 15%." Title="2/10" Hit="0.1" Money="628" Time="158"/>
    <Level3 GroupLV="3" Comment="Current Level: Increases damage dealt by Directional weapons by 15%; Next level: Increases damage dealt by Directional weapons by 20%." Title="3/10" Hit="0.15" Money="959" Time="368"/>
    <Level4 GroupLV="4" Comment="Current Level: Increases damage dealt by Directional weapons by 20%; Next level: Increases damage dealt by Directional weapons by 25%." Title="4/10" Hit="0.2" Money="1467" Time="861"/>
    <Level5 GroupLV="5" Comment="Current Level: Increases damage dealt by Directional weapons by 25%; Next level: Increases damage dealt by Directional weapons by 30%." Title="5/10" Hit="0.25" Money="2244" Time="2015"/>
    <Level6 GroupLV="6" Comment="Current Level: Increases damage dealt by Directional weapons by 30%; Next level: Increases damage dealt by Directional weapons by 35%." Title="6/10" Hit="0.3" Money="3434" Time="4717"/>
    <Level7 GroupLV="7" Comment="Current Level: Increases damage dealt by Directional weapons by 35%; Next level: Increases damage dealt by Directional weapons by 40%." Title="7/10" Hit="0.35" Money="5253" Time="11039"/>
    <Level8 GroupLV="8" Comment="Current Level: Increases damage dealt by Directional weapons by 40%; Next level: Increases damage dealt by Directional weapons by 45%." Title="8/10" Hit="0.4" Money="8036" Time="25834"/>
    <Level9 GroupLV="9" Comment="Current Level: Increases damage dealt by Directional weapons by 45%; Next level: Increases damage dealt by Directional weapons by 50%." Title="9/10" Hit="0.45" Money="12294" Time="60461"/>
    <Level10 GroupLV="10" Comment="Current Level: Increases damage dealt by Directional weapons by &lt;font color='#00FF00'&gt;50%&lt;/font&gt;." Title="10" Hit="0.5" Money="18808" Time="141501"/>
  </List>
  <List GroupID="17" Name="Directional Malice" Comment="Increases critical hit rate of Directional weapons; Lv1: Increase critical hit rate of Directional weapons by 1%." Kind="13" Tech="16:3" ImageFileName="Tech17" Title="0/5" TechMemo="Requires Optics Lv 3">
    <Level1 GroupLV="1" Comment="Current Level: Increase critical hit rate of Directional weapons by 1%; Next level: Increase critical hit rate of Directional weapons by 2%." Title="1/5" Blast="0.01" Money="7558" Time="1428"/>
    <Level2 GroupLV="2" Comment="Current Level: Increase critical hit rate of Directional weapons by 2%; Next level: Increase critical hit rate of Directional weapons by 3%." Title="2/5" Blast="0.02" Money="8752" Time="1915"/>
    <Level3 GroupLV="3" Comment="Current Level: Increase critical hit rate of Directional weapons by 3%; Next level: Increase critical hit rate of Directional weapons by 4%." Title="3/5" Blast="0.03" Money="13385" Time="4479"/>
    <Level4 GroupLV="4" Comment="Current Level: Increase critical hit rate of Directional weapons by 4%; Next level: Increase critical hit rate of Directional weapons by 5%." Title="4/5" Blast="0.04" Money="20477" Time="10483"/>
    <Level5 GroupLV="5" Comment="Current Level: Increase critical hit rate of Directional weapons by &lt;font color='#00FF00'&gt;5%&lt;/font&gt;." Title="5" Blast="0.05" Money="31327" Time="24535"/>
  </List>
  <List GroupID="18" Name="Pierce" Comment="Enables Directional weapons to pierce the target ship and deal piercing damage to ships located in the same vertical row as the target; Lv1: Pierces target ship and deals 3% piercing damage to ships in the same vertical row as the target. " Kind="13" Tech="16:10;17:5;22:5;26:1" ImageFileName="Tech18" Title="0/5" TechMemo="Requires Optics Lv 10, Directional Malice Lv 5, Directional Accuracy Lv 5, Energy Penetration Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: Pierces target ship and deals 3% piercing damage to ships in the same vertical row as the target; Next level: Pierces target ship and deals 6% piercing damage to ships in the same vertical row as the target." Title="1/5" Dispersion="0.03" Money="87919" Time="4947"/>
    <Level2 GroupLV="2" Comment="Current Level: Pierces target ship and deals 6% piercing damage to ships in the same vertical row as the target; Next level: Pierces target ship and deals 9% piercing damage to ships in the same vertical row as the target." Title="2/5" Dispersion="0.06" Money="101789" Time="6631"/>
    <Level3 GroupLV="3" Comment="Current Level: Pierces target ship and deals 9% piercing damage to ships in the same vertical row as the target; Next level: Pierces target ship and deals 12% piercing damage to ships in the same vertical row as the target." Title="3/5" Dispersion="0.09" Money="155714" Time="15518"/>
    <Level4 GroupLV="4" Comment="Current Level: Pierces target ship and deals 12% piercing damage to ships in the same vertical row as the target; Next level: Pierces target ship and deals 15% piercing damage to ships in the same vertical row as the target." Title="4/5" Dispersion="0.12" Money="238216" Time="36318"/>
    <Level5 GroupLV="5" Comment="Current Level: Pierces target ship and deals &lt;font color='#00FF00'&gt;15%&lt;/font&gt; piercing damage to ships in the same vertical row as the target." Title="5" Dispersion="0.15" Money="364426" Time="84996"/>
  </List>
  <List GroupID="19" Name="Improved Pierce" Comment="Enables Directional weapons to pierce the target ship and deal additional piercing damage; Lv1: Pierces target ship and deals 5% additional piercing damage." Kind="13" Tech="18:3;25:2" ImageFileName="Tech19" Title="0/2" TechMemo="Requires Pierce Lv 3, Eagle Eye Lv 2">
    <Level1 GroupLV="1" Comment="Current Level: Pierces target ship and deals 5% additional piercing damage; Next level: Pierces target ship and deals 10% additional piercing damage." Title="1/2" Dispersion="0.05" Money="240487" Time="17850"/>
    <Level2 GroupLV="2" Comment="Current Level: Pierces target ship and deals &lt;font color='#00FF00'&gt;10%&lt;/font&gt; additional piercing damage." Title="2" Dispersion="0.1" Money="278425" Time="23926"/>
  </List>
  <List GroupID="20" Name="Piercing Crit" Comment="Enables Directional weapons to critically strike the ships in the same horizontal row as a pierced target." Kind="13" Tech="18:5;19:1" ImageFileName="Tech20" Title="0/1" TechMemo="Requires Pierce Lv 5, Improved Pierce Lv 1">
    <Level1 GroupLV="1" Comment="Enables Directional weapons to critically strike the ships in the same horizontal row as a pierced target." Title="1" DispersionBlast="1" Money="391234" Time="25500"/>
  </List>
  <List GroupID="21" Name="Particle Impact Tech" Comment="Reduces the attack power of all enemy ships that take Piercing damage; Lv1: Reduces the attack power of all enemy ships that take piercing damage by 10% of the total piercing damage taken in the round. Lasts 2 rounds. (Note: This effect does not stack and will be replaced if a more powerful effect is activated)." Kind="13" Tech="19:2;20:1" ImageFileName="Tech21" Title="0/3" TechMemo="Requires Improved Pierce Lv 2, Piercing Crit Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: Reduces the attack power of all enemy ships that take piercing damage by 10% of the total piercing damage taken in the round. Lasts 2 rounds. (Note: This effect does not stack and will be replaced if a more powerful effect is activated); Next level: Reduces the attack power of all enemy ships that take piercing damage by 20% of the total piercing damage taken in the round." Title="1/3" DecObjHurt="0.1" DecObjHurtBout="2" Money="646368" Time="40800"/>
    <Level2 GroupLV="2" Comment="Current Level: Reduces the attack power of all enemy ships that take piercing damage by 20% of the total piercing damage taken in the round. Lasts 2 rounds. (Note: This effect does not stack and will be replaced if a more powerful effect is activated); Next level: Reduces the attack power of all enemy ships that take piercing damage by 30% of the total piercing damage taken in the round." Title="2/3" DecObjHurt="0.2" DecObjHurtBout="2" Money="748328" Time="54687"/>
    <Level3 GroupLV="3" Comment="Current Level: Reduces the attack power of all enemy ships that take piercing damage by &lt;font color='#00FF00'&gt;30%&lt;/font&gt; of the total piercing damage taken in the round. Lasts &lt;font color='#00FF00'&gt;2&lt;/font&gt; rounds. (Note: This effect does not stack and will be replaced if a more powerful effect is activated)." Title="3" DecObjHurt="0.3" DecObjHurtBout="2" Money="1144795" Time="127984"/>
  </List>
  <List GroupID="22" Name="Directional Accuracy" Comment="Increases the hit rate of Directional weapons; Lv1: +1% to hit rate." Kind="13" Tech="16:3" ImageFileName="Tech22" Title="0/5" TechMemo="Requires Optics Lv 3">
    <Level1 GroupLV="1" Comment="Current Level: Increases the hit rate of Directional weapons by 1%; Next level: +2% to hit rate." Title="1/5" Ratio="0.01" Money="7558" Time="1428"/>
    <Level2 GroupLV="2" Comment="Current Level: Increases the hit rate of Directional weapons by 2%; Next level: +3% to hit rate." Title="2/5" Ratio="0.02" Money="8752" Time="1915"/>
    <Level3 GroupLV="3" Comment="Current Level: Increases the hit rate of Directional weapons by 3%; Next level: +4% to hit rate." Title="3/5" Ratio="0.03" Money="13385" Time="4479"/>
    <Level4 GroupLV="4" Comment="Current Level: Increases the hit rate of Directional weapons by 4%; Next level: +5% to hit rate." Title="4/5" Ratio="0.04" Money="20477" Time="10483"/>
    <Level5 GroupLV="5" Comment="Current Level: Increases the hit rate of Directional weapons by &lt;font color='#00FF00'&gt;5%&lt;/font&gt;." Title="5" Ratio="0.05" Money="31327" Time="24535"/>
  </List>
  <List GroupID="23" Name="Radiative Interference" Comment="Enables Directional weapons to reduce the enemy fleet's hit rate; Lv1: +2% chance to reduce enemy fleet's hit rate. This effect can be stacked to a maximum of 25%. The effect will disappear when the target completes an attack." Kind="13" Tech="16:6;22:2" ImageFileName="Tech23" Title="0/5" TechMemo="Requires Optics Lv 6, Directional Accuracy Lv 2">
    <Level1 GroupLV="1" Comment="Current Level: +2% chance to reduce enemy fleet's hit rate. This effect can be stacked to a maximum of 25%. The effect will disappear when the target completes an attack; Next level: +4% chance to reduce enemy fleet's hit rate." Title="1/5" DecObjRatio="0.02" DecObjRatioMax="0.25" Money="43116" Time="9180"/>
    <Level2 GroupLV="2" Comment="Current Level: +4% chance to reduce enemy fleet's hit rate. This effect can be stacked to a maximum of 25%. The effect will disappear when the target completes an attack; Next level: +6% chance to reduce enemy fleet's hit rate." Title="2/5" DecObjRatio="0.04" DecObjRatioMax="0.25" Money="49918" Time="12305"/>
    <Level3 GroupLV="3" Comment="Current Level: +6% chance to reduce enemy fleet's hit rate. This effect can be stacked to a maximum of 25%. The effect will disappear when the target completes an attack; Next level: +8% chance to reduce enemy fleet's hit rate." Title="3/5" DecObjRatio="0.06" DecObjRatioMax="0.25" Money="76362" Time="28796"/>
    <Level4 GroupLV="4" Comment="Current Level: +8% chance to reduce enemy fleet's hit rate. This effect can be stacked to a maximum of 25%. The effect will disappear when the target completes an attack; Next level: +10% chance to reduce enemy fleet's hit rate." Title="4/5" DecObjRatio="0.08" DecObjRatioMax="0.25" Money="116822" Time="67394"/>
    <Level5 GroupLV="5" Comment="Current Level: &lt;font color='#00FF00'&gt;+8%&lt;/font&gt; chance to reduce enemy fleet's hit rate. This effect can be stacked to a maximum of &lt;font color='#00FF00'&gt;25%&lt;/font&gt;. The effect will disappear when the target completes an attack." Title="5" DecObjRatio="0.1" DecObjRatioMax="0.25" Money="178716" Time="157725"/>
  </List>
  <List GroupID="24" Name="Electronic Interference" Comment="Grants Directional weapons a chance to reduce enemy steering power by 10%. This effect is not stackable and will fade after the target deals 1 attack. This skill also reduces the space occupied by Directional weapons; Lv1: +5% chance to reduce enemy steering power by 10%. Also reduces space occupied by Directional weapons by 3%." Kind="13" Tech="22:2;23:3" ImageFileName="Tech24" Title="0/3" TechMemo="Requires Directional Accuracy Lv 2, Radiative Interference Lv 3">
    <Level1 GroupLV="1" Comment="Current Level: +5% chance to reduce enemy steering power by 10%. Also reduces space occupied by Directional weapons by 3%; Next level: +10% chance to reduce enemy steering power by 10%. Also reduces space occupied by Directional weapons by 6%." Title="1/3" LowCubage="0.03" DecObjTurnRate="0.05" DecObjTurn="0.1" Money="87581" Time="11985"/>
    <Level2 GroupLV="2" Comment="Current Level: +10% chance to reduce enemy steering power by 10%. Also reduces space occupied by Directional weapons by 6%; Next level: +15% chance to reduce enemy steering power by 10%. Also reduces space occupied by Directional weapons by 9%." Title="2/3" LowCubage="0.06" DecObjTurnRate="0.1" DecObjTurn="0.1" Money="101398" Time="16065"/>
    <Level3 GroupLV="3" Comment="Current Level: &lt;font color='#00FF00'&gt;+15%&lt;/font&gt; chance to reduce enemy steering power by &lt;font color='#00FF00'&gt;10%&lt;/font&gt;. Also reduces space occupied by Directional weapons by &lt;font color='#00FF00'&gt;9%;&lt;/font&gt;." Title="3" LowCubage="0.09" DecObjTurnRate="0.15" DecObjTurn="0.1" Money="155115" Time="37595"/>
  </List>
  <List GroupID="25" Name="Eagle Eye" Comment="Increases the steering power of Directional weapons; Lv1: +10% to steering power." Kind="13" Tech="16:6;22:1" ImageFileName="Tech25" Title="0/2" TechMemo="Requires Optics Lv 6, Directional Accuracy Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: Increases the steering power of Directional weapons by 10%; Next level: +20% to steering power." Title="1/2" Turn="0.1" Money="22724" Time="2550"/>
    <Level2 GroupLV="2" Comment="Current Level: Increases the steering power of Directional weapons by &lt;font color='#00FF00'&gt;20%&lt;/font&gt;." Title="2" Turn="0.2" Money="26309" Time="3418"/>
  </List>
  <List GroupID="26" Name="Energy Penetration" Comment="Increases the hit rate of Directional weapons by &lt;font color='#00FF00'&gt;+5%&lt;/font&gt; and grant them a &lt;font color='#00FF00'&gt;8%&lt;/font&gt; chance to penetrate enemy shields." Kind="13" Tech="22:2;25:1" ImageFileName="Tech26" Title="0/1" TechMemo="Requires Directional Accuracy Lv 2, Eagle Eye Lv 1">
    <Level1 GroupLV="1" Comment="Increases the hit rate of Directional weapons by &lt;font color='#00FF00'&gt;+5%&lt;/font&gt; and grant them a &lt;font color='#00FF00'&gt;8%&lt;/font&gt; chance to penetrate enemy shields." Title="1" Ratio="0.05" CrossShield="0.08" Money="62584" Time="6120"/>
  </List>
  <List GroupID="27" Name="Energy Accumulation" Comment="Increases the critical hit rate of Directional weapons whenever your fleet moves 1 step; Lv1: +2% to critical hit rate." Kind="13" Tech="25:2;26:1" ImageFileName="Tech27" Title="0/3" TechMemo="Requires Eagle Eye Lv 2, Energy Penetration Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: Increases the critical hit rate of Directional weapons by 2% when your fleet moves 1 step; Next level: Increases the critical hit rate of Directional weapons by 4% when your fleet moves 1 step." Title="1/3" OneGridBlast="0.02" Money="136845" Time="11985"/>
    <Level2 GroupLV="2" Comment="Current Level: Increases the critical hit rate of Directional weapons by 4% when your fleet moves 1 step; Next level: Increases the critical hit rate of Directional weapons by 6% when your fleet moves 1 step." Title="2/3" OneGridBlast="0.04" Money="158435" Time="16065"/>
    <Level3 GroupLV="3" Comment="Current Level: Increases the critical hit rate of Directional weapons by &lt;font color='#00FF00'&gt;6%&lt;/font&gt; when your fleet moves &lt;font color='#00FF00'&gt;1&lt;/font&gt; step." Title="3" OneGridBlast="0.06" Money="242368" Time="37595"/>
  </List>
  <List GroupID="28" Name="Weakness Detection" Comment="Increases the base damage of Directional weapons and increases chances of applying the maximum base hit rate; Lv1: +5% to the base damage of Directional weapons and grants a 3% chance to apply the maximum base hit rate." Kind="13" Tech="24:3;27:3" ImageFileName="Tech28" Title="0/3" TechMemo="Requires Electronic Interference Lv 3, Energy Accumulation Lv 3">
    <Level1 GroupLV="1" Comment="Current Level: +5% to the base damage of Directional weapons and grants a 3% chance to apply the maximum base hit rate; Next level: +10% to the base damage of Directional weapons and grants a 6% chance to apply the maximum base hit rate." Title="1/3" Hit="0.05" MaxratioRate="0.03" Money="349054" Time="20298"/>
    <Level2 GroupLV="2" Comment="Current Level: +10% to the base damage of Directional weapons and grants a 6% chance to apply the maximum base hit rate; Next level: +15% to the base damage of Directional weapons and grants a 10% chance to apply the maximum base hit rate." Title="2/3" Hit="0.1" MaxratioRate="0.06" Money="404116" Time="27207"/>
    <Level3 GroupLV="3" Comment="Current Level: &lt;font color='#00FF00'&gt;+15%&lt;/font&gt; to the base damage of Directional weapons and grants a &lt;font color='#00FF00'&gt;10%&lt;/font&gt; chance to apply the maximum base hit rate." Title="3" Hit="0.15" MaxratioRate="0.1" Money="618216" Time="63672"/>
  </List>
  <List GroupID="29" Name="Magnetic Impact" Comment="Grants Directional weapons a chance to ignore the enemy's agility; Lv1: +10% chance for Directional weapons to ignore 8% of the target's agility." Kind="13" Tech="22:5;23:5;28:2" ImageFileName="Tech29" Title="0/3" TechMemo="Requires Directional Accuracy Lv 5, Radiative Interference Lv 5, Weakness Detection Lv 2">
    <Level1 GroupLV="1" Comment="Current Level: +10% chance for Directional weapons to ignore 8% of the target's agility; Next level: +20% chance for Directional weapons to ignore 16% of the target's agility." Title="1/3" IgnoreYareRate="0.1" IgnoreYare="0.08" Money="996120" Time="96900"/>
    <Level2 GroupLV="2" Comment="Current Level: +20% chance for Directional weapons to ignore 16% of the target's agility; Next level: +30% chance for Directional weapons to ignore 25% of the target's agility." Title="2/3" IgnoreYareRate="0.2" IgnoreYare="0.16" Money="1153244" Time="129880"/>
    <Level3 GroupLV="3" Comment="Current Level: &lt;font color='#00FF00'&gt;+30%&lt;/font&gt; chance for Directional weapons to ignore &lt;font color='#00FF00'&gt;25%&lt;/font&gt; of the target's agility." Title="3" IgnoreYareRate="0.3" IgnoreYare="0.25" Money="1764254" Time="303964"/>
  </List>
  <List GroupID="30" Name="Dynamic Impairment" Comment="Enables Directional weapons to ignore the target's Defense. Also grants a chance to reduce the target's movement by 1 when dealing damage. Target cannot be slowed below a speed of 1; Lv1: Ignores 8% of the target's defense and grants a 6% chance to reduce the target's movement. Lasts for 1 round only." Kind="13" Tech="21:3;28:3;29:3" ImageFileName="Tech30" Title="0/3" TechMemo="Requires Particle Impact Tech Lv 3, Weakness Detection Lv 3, Magnetic Impact Lv 3">
    <Level1 GroupLV="1" Comment="Current Level: Ignores 8% of the target's defense and grants a 6% chance to reduce the target's movement. Lasts for 1 round only; Next level: Ignores 16% of the target's defense and grants a 13% chance to reduce the target's movement by 2. Lasts for 1 round only." Title="1/3" IgnoreDefend="0.08" DecLocomotivityRate="0.06" DecLocomotivity="1" Money="1431605" Time="124950"/>
    <Level2 GroupLV="2" Comment="Current Level: Ignores 16% of the target's defense and grants a 13% chance to reduce the target's movement by 2. Lasts for 1 round only; Next level: Ignores 25% of the target's defense and grants a 20% chance to reduce the target's movement by 3. Lasts for 1 round only" Title="2/3" IgnoreDefend="0.16" DecLocomotivityRate="0.13" DecLocomotivity="2" Money="1657420" Time="167477"/>
    <Level3 GroupLV="3" Comment="Current Level: Ignores &lt;font color='#00FF00'&gt;25%&lt;/font&gt; of the target's defense and grants a &lt;font color='#00FF00'&gt;20%&lt;/font&gt; chance to reduce the target's movement by &lt;font color='#00FF00'&gt;3&lt;/font&gt;. Lasts for &lt;font color='#00FF00'&gt;1&lt;/font&gt; round only" Title="3" IgnoreDefend="0.25" DecLocomotivityRate="0.2" DecLocomotivity="3" Money="2535549" Time="391953"/>
  </List>
  <List GroupID="31" Name="Artillery Trajectory Research" Comment="This science gives Dynamic Impairment an additional chance to reduce enemy fleet movement, increases the chance to penetrate shields, and increases hit chance, base attack power, piercing damage, maximum attack range of Directional weapons and the effect of Particle Impact Tech; Next Level: Gives Dynamic Impairment 5% better chance to reduce enemy fleet movement, increases the chance to penetrate shields by 1%, and increases hit chance by 2%, base attack power by 3%, piercing damage by 3%, the effect of Particle Impact Tech by 15% and the maximum attack range of Directional weapons by 1." Kind="13" Tech="30:3" ImageFileName="Tech31" Title="0/4" TechMemo="Requires Dynamic Impairment Lv 3">
    <Level1 GroupLV="1" Comment="This level of proficiency gives Dynamic Impairment 5% better chance to reduce enemy fleet movement, increases the chance to penetrate shields by 1%, and increases hit chance by 2%, base attack power by 3%, piercing damage by 3%, the effect of Particle Impact Tech by 15% and the maximum attack range of Directional weapons by 1; Next Level: Gives Dynamic Impairment a 10% better chance to reduce enemy fleet movement, increases the chance to penetrate shields by 2%, and increases hit chance by 4%, base attack power by 7%, piercing damage by 7%, the effect of Particle Impact Tech by 25% and maximum attack range of Directional weapons by 1." Title="1/4" Hit="0.03" Ratio="0.02" CrossShield="0.01" Dispersion="0.03" BoostCarry="1" DecObjHurt="0.15" DecLocomotivityRate="0.05" Money="10000000" Time="399952"/>
    <Level2 GroupLV="2" Comment="This level of proficiency gives Dynamic Impairment a 10% better chance to reduce enemy fleet movement, increases the chance to penetrate shields by 2%, and increases hit chance by 4%, base attack power by 7%, piercing damage by 7%, the effect of Particle Impact Tech by 25% and maximum attack range of Directional weapons by 1; Next Level: Gives Dynamic Impairment a 15% better chance to reduce enemy fleet movement, increases the chance to penetrate shields by 3%, and increases hit chance by 6%, base attack power by 11%, piercing damage by 11%, the effect of Particle Impact Tech by 35% and maximum attack range of Directional weapons by 1." Title="2/4" Hit="0.07" Ratio="0.04" CrossShield="0.02" Dispersion="0.07" BoostCarry="1" DecObjHurt="0.25" DecLocomotivityRate="0.1" Money="30000000" Time="599952"/>
    <Level3 GroupLV="3" Comment="This level of proficiency gives Dynamic Impairment a 15% better chance to reduce enemy fleet movement, increases the chance to penetrate shields by 3%, and increases hit chance by 6%, base attack power by 11%, piercing damage by 11%, the effect of Particle Impact Tech by 35% and maximum attack range of Directional weapons by 1; Next Level: Gives Dynamic Impairment a 20% better chance to reduce enemy fleet movement, increases the chance to penetrate shields by 4%, and increases hit chance by 8%, base attack power by 15%, piercing damage by 15%, the effect of Particle Impact Tech by 50% and maximum attack range of Directional weapons by 1." Title="3/4" Hit="0.11" Ratio="0.06" CrossShield="0.03" Dispersion="0.11" BoostCarry="1" DecObjHurt="0.35" DecLocomotivityRate="0.15" Money="80000000" Time="729952"/>
    <Level4 GroupLV="4" Comment="This level of proficiency gives Dynamic Impairment a &lt;font color='#00FF00'&gt;20%&lt;/font&gt; better chance to reduce enemy fleet movement, increases the chance to penetrate shields by &lt;font color='#00FF00'&gt;4%&lt;/font&gt;, and increases hit chance by &lt;font color='#00FF00'&gt;+8%&lt;/font&gt;, base attack power by &lt;font color='#00FF00'&gt;+15%&lt;/font&gt;, piercing damage by &lt;font color='#00FF00'&gt;+15%&lt;/font&gt;, the effect of Particle Impact Tech by &lt;font color='#00FF00'&gt;50%&lt;/font&gt; and maximum attack range of Directional weapons by &lt;font color='#00FF00'&gt;+1&lt;/font&gt;." Title="4" Hit="0.15" Ratio="0.08" CrossShield="0.04" Dispersion="0.15" BoostCarry="1" DecObjHurt="0.5" DecLocomotivityRate="0.2" Money="150000000" Time="936026"/>
  </List>
  <List GroupID="32" Name="Missile Theory" Comment="Increases the damage of Guided weapons; Lv1: +4% damage of Guided weapons." Kind="14" Tech="" ImageFileName="Tech32" Title="0/10" TechMemo="">
    <Level1 GroupLV="1" Comment="Current Level: Increases the damage of Guided weapons by 4%; Next level: +8% damage of Guided weapons." Title="1/10" Hit="0.04" Money="541" Time="117"/>
    <Level2 GroupLV="2" Comment="Current Level: Increases the damage of Guided weapons by 8%; Next level: +12% damage of Guided weapons." Title="2/10" Hit="0.08" Money="628" Time="158"/>
    <Level3 GroupLV="3" Comment="Current Level: Increases the damage of Guided weapons by 12%; Next level: +16% damage of Guided weapons." Title="3/10" Hit="0.12" Money="959" Time="368"/>
    <Level4 GroupLV="4" Comment="Current Level: Increases the damage of Guided weapons by 16%; Next level: +20% damage of Guided weapons." Title="4/10" Hit="0.16" Money="1467" Time="861"/>
    <Level5 GroupLV="5" Comment="Current Level: Increases the damage of Guided weapons by 20%; Next level: +24% damage of Guided weapons." Title="5/10" Hit="0.2" Money="2244" Time="2015"/>
    <Level6 GroupLV="6" Comment="Current Level: Increases the damage of Guided weapons by 24%; Next level: +28% damage of Guided weapons." Title="6/10" Hit="0.24" Money="3434" Time="4717"/>
    <Level7 GroupLV="7" Comment="Current Level: Increases the damage of Guided weapons by 28%; Next level: +32% damage of Guided weapons." Title="7/10" Hit="0.28" Money="5253" Time="11039"/>
    <Level8 GroupLV="8" Comment="Current Level: Increases the damage of Guided weapons by 32%; Next level: +36% damage of Guided weapons." Title="8/10" Hit="0.32" Money="8036" Time="25834"/>
    <Level9 GroupLV="9" Comment="Current Level: Increases the damage of Guided weapons by 36%; Next level: +40% damage of Guided weapons." Title="9/10" Hit="0.36" Money="12294" Time="60461"/>
    <Level10 GroupLV="10" Comment="Current Level: Increases the damage of Guided weapons by &lt;font color='#00FF00'&gt;+40%&lt;/font&gt;." Title="10" Hit="0.4" Money="18808" Time="141501"/>
  </List>
  <List GroupID="33" Name="Missile Accuracy" Comment="Increase the hit rate of Guided weapons; Lv1: +2% to hit rate." Kind="14" Tech="32:3" ImageFileName="Tech33" Title="0/5" TechMemo="Requires Missile Theory Lv 3">
    <Level1 GroupLV="1" Comment="Current Level: Increase the hit rate of Guided weapons by 2%; Next level: +4% to hit rate." Title="1/5" Ratio="0.02" Money="7558" Time="1428"/>
    <Level2 GroupLV="2" Comment="Current Level: Increase the hit rate of Guided weapons by 4%; Next level: +6% to hit rate." Title="2/5" Ratio="0.04" Money="8752" Time="1915"/>
    <Level3 GroupLV="3" Comment="Current Level: Increase the hit rate of Guided weapons by 6%; Next level: +8% to hit rate." Title="3/5" Ratio="0.06" Money="13385" Time="4479"/>
    <Level4 GroupLV="4" Comment="Current Level: Increase the hit rate of Guided weapons by 8%; Next level: +10% to hit rate." Title="4/5" Ratio="0.08" Money="20477" Time="10483"/>
    <Level5 GroupLV="5" Comment="Current Level: Increase the hit rate of Guided weapons by &lt;font color='#00FF00'&gt;+10%&lt;/font&gt;." Title="5" Ratio="0.1" Money="31327" Time="24535"/>
  </List>
  <List GroupID="34" Name="Multidirectional Assault" Comment="Enable Guided weapons to scatter portion of rate onto all enemy ships; Lv1: Scatter 6% of rate dealt to target enemy ships." Kind="14" Tech="32:10;33:3;41:2;42:3" ImageFileName="Tech34" Title="0/5" TechMemo="Requires Missile Theory Lv 10, Missile Accuracy Lv 3, Cruise Dynamics Lv 2, Missile Research Lv 3">
    <Level1 GroupLV="1" Comment="Current Level: Scatter 6% of rate dealt to target enemy ships; Next level: Scatter 12% of rate dealt to target enemy ships." Title="1/5" Dispersion="0.06" Money="80796" Time="10200"/>
    <Level2 GroupLV="2" Comment="Current Level: Scatter 12% of rate dealt to target enemy ships; Next level: Scatter 18% of rate dealt to target enemy ships." Title="2/5" Dispersion="0.12" Money="93542" Time="13672"/>
    <Level3 GroupLV="3" Comment="Current Level: Scatter 18% of rate dealt to target enemy ships; Next level: Scatter 24% of rate dealt to target enemy ships." Title="3/5" Dispersion="0.18" Money="143099" Time="31996"/>
    <Level4 GroupLV="4" Comment="Current Level: Scatter 24% of rate dealt to target enemy ships; Next level: Scatter 30% of rate dealt to target enemy ships." Title="4/5" Dispersion="0.24" Money="218917" Time="74882"/>
    <Level5 GroupLV="5" Comment="Current Level: Scatter &lt;font color='#00FF00'&gt;30%&lt;/font&gt; of rate dealt to target enemy ships." Title="5" Dispersion="0.3" Money="334903" Time="175250"/>
  </List>
  <List GroupID="35" Name="Shrapnel Research" Comment="Enable Guided weapons to deal additional scattering rate; Lv1: Deal 2% more scattering rate." Kind="14" Tech="33:5;34:3" ImageFileName="Tech35" Title="0/2" TechMemo="Requires Missile Accuracy Lv 5, Multidirectional Assault Lv 3">
    <Level1 GroupLV="1" Comment="Current Level: Deal 2% more scattering rate; Next level: Deal 4% more scattering rate." Title="1/2" Dispersion="0.02" Money="157172" Time="15810"/>
    <Level2 GroupLV="2" Comment="Current Level: Deal &lt;font color='#00FF00'&gt;4%&lt;/font&gt; more scattering rate." Title="2" Dispersion="0.04" Money="181964" Time="21191"/>
  </List>
  <List GroupID="36" Name="Exaltation" Comment="Increase scattering damage of Guided weaspons when attacking an enemy fleet with lower structure. Also grant a chance to reduce He3 cost; Lv1: +20% scattering damage when attacking an enemy fleet with lower structure. Grant 2% chance to reduce He3 cost." Kind="14" Tech="34:5;35:1" ImageFileName="Tech36" Title="0/4" TechMemo="Requires Multidirectional Assault Lv 5, Shrapnel Research Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: +20% scattering damage when attacking an enemy fleet with lower structure. Grant 2% chance to reduce He3 cost; Next level: +40% scattering damage when attacking an enemy fleet with lower structure. Grant 4% chance to reduce He3 cost." Title="1/4" LowDispersion="0.2" EconomizeGasRate="0.02" Money="224495" Time="15555"/>
    <Level2 GroupLV="2" Comment="Current Level: +40% scattering damage when attacking an enemy fleet with lower structure. Grant 4% chance to reduce He3 cost; Next level: +60% scattering damage when attacking an enemy fleet with lower structure. Grant 6% chance to reduce He3 cost." Title="2/4" LowDispersion="0.4" EconomizeGasRate="0.04" Money="259912" Time="20850"/>
    <Level3 GroupLV="3" Comment="Current Level: +60% scattering damage when attacking an enemy fleet with lower structure. Grant 6% chance to reduce He3 cost; Next level: +80% scattering damage when attacking an enemy fleet with lower structure. Grant 8% chance to reduce He3 cost." Title="3/4" LowDispersion="0.6" EconomizeGasRate="0.06" Money="397609" Time="48794"/>
    <Level4 GroupLV="4" Comment="Current Level: &lt;font color='#00FF00'&gt;+80%&lt;/font&gt; scattering damage when attacking an enemy fleet with lower structure. Grant &lt;font color='#00FF00'&gt;8%&lt;/font&gt; chance to reduce He3 cost. " Title="4" LowDispersion="0.8" EconomizeGasRate="0.08" Money="608270" Time="114195"/>
  </List>
  <List GroupID="37" Name="Suppression" Comment="Increase scattering rate of Guided weapons when attacking an enemy fleet with higher structure. Also increase the critical strike chance of Guided weapons; Lv1: +3% scattering rate when attacking an enemy fleet with higher structure. Increase 3% chance of critical strike." Kind="14" Tech="35:2;36:4" ImageFileName="Tech37" Title="0/4" TechMemo="Requires Shrapnel Research Lv 2, Exaltation Lv 4">
    <Level1 GroupLV="1" Comment="Current Level: +3% scattering rate when attacking an enemy fleet with higher structure. Increase 3% chance of critical strike; Next level: +6% scattering rate when attacking an enemy fleet with higher structure. Increase 6% chance of critical strike." Title="1/4" Blast="0.03" HighDispersion="0.03" Money="484776" Time="22950"/>
    <Level2 GroupLV="2" Comment="Current Level: +6% scattering rate when attacking an enemy fleet with higher structure. Increase 6% chance of critical strike; Next level: +9% scattering rate when attacking an enemy fleet with higher structure. Increase 9% chance of critical strike." Title="2/4" Blast="0.06" HighDispersion="0.06" Money="561242" Time="30761"/>
    <Level3 GroupLV="3" Comment="Current Level: +9% scattering rate when attacking an enemy fleet with higher structure. Increase 9% chance of critical strike; Next level: +12% scattering rate when attacking an enemy fleet with higher structure. Increase 12% chance of critical strike." Title="3/4" Blast="0.09" HighDispersion="0.09" Money="858602" Time="71992"/>
    <Level4 GroupLV="4" Comment="Current Level: &lt;font color='#00FF00'&gt;+12%&lt;/font&gt; scattering rate when attacking an enemy fleet with higher structure. Increase &lt;font color='#00FF00'&gt;12%&lt;/font&gt; chance of critical strike." Title="4" Blast="0.12" HighDispersion="0.12" Money="1313502" Time="168485"/>
  </List>
  <List GroupID="38" Name="Nuclear Radiation Research" Comment="Grant Guided weapons a chance to increase target fleet's damage. This effect is not stackable but will last until the battle ends; Lv1: +4% chance to increase 2% target fleet's damage." Kind="14" Tech="33:4;34:1" ImageFileName="Tech38" Title="0/5" TechMemo="Requires Missile Accuracy Lv 4, Multidirectional Assault Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: +4% chance to increase 2% target fleet's damage; Next level: +8% chance to increase 4% target fleet's damage." Title="1/5" IncDamageRate="0.04" IncDamage="0.02" Money="112916" Time="8160"/>
    <Level2 GroupLV="2" Comment="Current Level: +8% chance to increase 4% target fleet's damage; Next level: +12% chance to increase 6% target fleet's damage." Title="2/5" IncDamageRate="0.08" IncDamage="0.04" Money="130731" Time="10938"/>
    <Level3 GroupLV="3" Comment="Current Level: +12% chance to increase 6% target fleet's damage; Next level: +16% chance to increase 8% target fleet's damage." Title="3/5" IncDamageRate="0.12" IncDamage="0.06" Money="199988" Time="25597"/>
    <Level4 GroupLV="4" Comment="Current Level: +16% chance to increase 8% target fleet's damage; Next level: +20% chance to increase 10% target fleet's damage." Title="4/5" IncDamageRate="0.16" IncDamage="0.08" Money="305944" Time="59905"/>
    <Level5 GroupLV="5" Comment="Current Level: &lt;font color='#00FF00'&gt;+20%&lt;/font&gt; chance to increase &lt;font color='#00FF00'&gt;10%&lt;/font&gt; target fleet's damage." Title="5" IncDamageRate="0.2" IncDamage="0.1" Money="468041" Time="140200"/>
  </List>
  <List GroupID="39" Name="Break Armor" Comment="Enable Guided weapons to deal &lt;font color='#00FF00'&gt;5%&lt;/font&gt; more damage to all armors." Kind="14" Tech="34:2;38:3" ImageFileName="Tech39" Title="0/1" TechMemo="Requires Multidirectional Assault Lv 2, Nuclear Radiation Research Lv 3">
    <Level1 GroupLV="1" Comment="Enable Guided weapons to deal &lt;font color='#00FF00'&gt;5%&lt;/font&gt; more damage to all armors." Title="1" ArmorHurt="1:0.05;2:0.05;3:0.05;4:0.05;5:0.05;6:0.05" Money="287437" Time="25500"/>
  </List>
  <List GroupID="40" Name="Energy Conservation" Comment="Grant Guided weapons a chance to reduce 50% cost of He3; Lv1: +4% chance to reduce 50% cost of He3." Kind="14" Tech="34:3;38:5;39:1" ImageFileName="Tech40" Title="0/4" TechMemo="Requires Multidirectional Assault Lv 3, Nuclear Radiation Research Lv 5, Break Armor Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: +4% chance to reduce 50% cost of He3; Next level: +8% chance to reduce 50% cost of He3." Title="1/4" EconomizeGasRate="0.04" EconomizeGas="0.5" Money="428575" Time="30600"/>
    <Level2 GroupLV="2" Comment="Current Level: +8% chance to reduce 50% cost of He3; Next level: +12% chance to reduce 50% cost of He3." Title="2/4" EconomizeGasRate="0.08" EconomizeGas="0.5" Money="496178" Time="41015"/>
    <Level3 GroupLV="3" Comment="Current Level: +12% chance to reduce 50% cost of He3; Next level: +18% chance to reduce 50% cost of He3." Title="3/4" EconomizeGasRate="0.12" EconomizeGas="0.5" Money="759061" Time="95989"/>
    <Level4 GroupLV="4" Comment="Current Level: &lt;font color='#00FF00'&gt;+18%&lt;/font&gt; chance to reduce &lt;font color='#00FF00'&gt;50%&lt;/font&gt; cost of He3." Title="4" EconomizeGasRate="0.18" EconomizeGas="0.5" Money="1161222" Time="224646"/>
  </List>
  <List GroupID="41" Name="Cruise Dynamics" Comment="Increase the steering power of Guided weapons; Lv1: +10% steering power of Guided weapons." Kind="14" Tech="32:3" ImageFileName="Tech41" Title="0/2" TechMemo="Requires Missile Theory Lv 3">
    <Level1 GroupLV="1" Comment="Current Level: +10% steering power of Guided weapons; Next level: +20% steering power of Guided weapons." Title="1/2" Turn="0.1" Money="11603" Time="3366"/>
    <Level2 GroupLV="2" Comment="Current Level: &lt;font color='#00FF00'&gt;+20%&lt;/font&gt; steering power of Guided weapons." Title="2" Turn="0.2" Money="13434" Time="4512"/>
  </List>
  <List GroupID="42" Name="Missile Research" Comment="Increase the base damage of Guided weapons and grant a chance to penetrate shield; Lv1: +3% base damage of Guided weapons and grant 1% chance to penetrate shield." Kind="14" Tech="32:6;41:1" ImageFileName="Tech42" Title="0/3" TechMemo="Requires Missile Theory Lv 6, Cruise Dynamics Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: +3% base damage of Guided weapons and grant 1% chance to penetrate shield; Next level: +6% base damage of Guided weapons and grant 3% chance to penetrate shield." Title="1/3" Hit="0.03" CrossShield="0.01" Money="38831" Time="7446"/>
    <Level2 GroupLV="2" Comment="Current Level: +6% base damage of Guided weapons and grant 3% chance to penetrate shield; Next level: +10% base damage of Guided weapons and grant 5% chance to penetrate shield." Title="2/3" Hit="0.06" CrossShield="0.03" Money="44957" Time="9981"/>
    <Level3 GroupLV="3" Comment="Current Level: &lt;font color='#00FF00'&gt;+10%&lt;/font&gt; base damage of Guided weapons and grant &lt;font color='#00FF00'&gt;5%&lt;/font&gt; chance to penetrate shield." Title="3" Hit="0.1" CrossShield="0.05" Money="68773" Time="23357"/>
  </List>
  <List GroupID="43" Name="Missile Elusion" Comment="Reduce intercepting rate and increase hit rate of Guided weapons; Lv1: -3% intercepting rate and +3% hit rate." Kind="14" Tech="41:2;42:1" ImageFileName="Tech43" Title="0/3" TechMemo="Requires Cruise Dynamics Lv 2, Missile Research Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: -3% intercepting rate and +3% hit rate; Next level: -6% intercepting rate and +6% hit rate." Title="1/3" Ratio="0.03" DecHeadoff="0.03" Money="78750" Time="9690"/>
    <Level2 GroupLV="2" Comment="Current Level: -6% intercepting rate and +6% hit rate; Next level: -10% intercepting rate and +9% hit rate." Title="2/3" Ratio="0.06" DecHeadoff="0.06" Money="91172" Time="12988"/>
    <Level3 GroupLV="3" Comment="Current Level: &lt;font color='#00FF00'&gt;-10%&lt;/font&gt; intercepting rate and &lt;font color='#00FF00'&gt;+9%&lt;/font&gt; hit rate." Title="3" Ratio="0.09" DecHeadoff="0.1" Money="139478" Time="30397"/>
  </List>
  <List GroupID="44" Name="Missile Space Optimization" Comment="Reduce space occupied by Guided weapons; Lv1: -5% space occupied by Guided weapons." Kind="14" Tech="42:2;43:2" ImageFileName="Tech44" Title="0/4" TechMemo="Requires Missile Research Lv 2, Missile Elusion Lv 2">
    <Level1 GroupLV="1" Comment="Current Level: -5% space occupied by Guided weapons; Next level: -10% space occupied by Guided weapons." Title="1/4" LowCubage="0.05" Money="233515" Time="16830"/>
    <Level2 GroupLV="2" Comment="Current Level: -10% space occupied by Guided weapons; Next level: -15% space occupied by Guided weapons." Title="2/4" LowCubage="0.1" Money="270354" Time="22559"/>
    <Level3 GroupLV="3" Comment="Current Level: -15% space occupied by Guided weapons; Next level: -20% space occupied by Guided weapons." Title="3/4" LowCubage="0.15" Money="413581" Time="52793"/>
    <Level4 GroupLV="4" Comment="Current Level: &lt;font color='#00FF00'&gt;-20%&lt;/font&gt; space occupied by Guided weapons." Title="4" LowCubage="0.2" Money="632710" Time="123556"/>
  </List>
  <List GroupID="45" Name="Missile Concussion" Comment="Grant Guilded weapons &lt;font color='#00FF00'&gt;25%&lt;/font&gt; chance to force the target fleet to fall back by &lt;font color='#00FF00'&gt;2&lt;/font&gt; slot when doing damage. Can be activated once per round." Kind="14" Tech="40:2;42:3;43:3;44:4" ImageFileName="Tech45" Title="0/1" TechMemo="Requires Energy Conservation Lv 2, Missile Research Lv 3, Missile Elusion Lv 3, Missile Space Optimization Lv 4">
    <Level1 GroupLV="1" Comment="Grant Guilded weapons &lt;font color='#00FF00'&gt;25%&lt;/font&gt; chance to force the target fleet to fall back by &lt;font color='#00FF00'&gt;2&lt;/font&gt; slot when doing damage. Can be activated once per round." Title="1" RepelRangeRate="0.2" RepelRange="2" Money="1351976" Time="178500"/>
  </List>
  <List GroupID="46" Name="Rapid Loading" Comment="Enable Guided weapons to finish reloading &lt;font color='#00FF00'&gt;1&lt;/font&gt; round faster. Also increase &lt;font color='#00FF00'&gt;10%&lt;/font&gt; chance of triggering a concussion effect and forcing target fleet to fall by &lt;font color='#00FF00'&gt;1&lt;/font&gt; slot." Kind="14" Tech="37:4;40:4;45:1" ImageFileName="Tech46" Title="0/1" TechMemo="Requires Suppression Lv 4, Energy Conservation Lv 4, Missile Concussion Lv 1">
    <Level1 GroupLV="1" Comment="Enable Guided weapons to finish reloading &lt;font color='#00FF00'&gt;1&lt;/font&gt; round faster. Also increase &lt;font color='#00FF00'&gt;10%&lt;/font&gt; chance of triggering a concussion effect and forcing target fleet to fall by &lt;font color='#00FF00'&gt;1&lt;/font&gt; slot." Title="1" RepelRangeRate="0.1" RepelRange="1" DecBackfill="1" Money="1961639" Time="234600"/>
  </List>
  <List GroupID="47" Name="Perfect Storm" Comment="This science increases the chance of guided weapons' penetrating armor modules, and the effect of Multi-directional Assault, while also gives Missile Concussion an additional chance to force enemy fleets to fall back and Energy Conservation an additional chance to reduce He3 cost by 50%. Lastly, it increases the range of attack for guided weapons when studied to a certain degree, but increases guided weapons' chance to be intercepted; Next Level: Increases the chance of guided weapons' penetrating armor modules by 2%, and the effect of Multi-directional Assault by 2%, while also gives Missile Concussion a 5% better chance to force enemy fleets to fall back and Energy Conservation a 5% better chance to reduce He3 cost by 50%. Lastly, it increases guided weapons' chance of being intercepted by 2%." Kind="14" Tech="46:1" ImageFileName="Tech47" Title="0/4" TechMemo="Requires Rapid Loading Lv 1">
    <Level1 GroupLV="1" Comment="This level of proficiency increases the chance of guided weapons' penetrating armor modules by 2%, and the effect of Multi-directional Assault by 2%, while also gives Missile Concussion a 5% better chance to force enemy fleets to fall back and Energy Conservation a 5% better chance to reduce He3 cost by 50%. Lastly, it increases guided weapons' chance of being intercepted by 2%; Next Level: Increases the chance of guided weapons' penetrating armor modules by 4%, and the effect of Multi-directional Assault by 4%, while also gives Missile Concussion an 8% better chance to force enemy fleets to fall back and Energy Conservation a 10% better chance to reduce He3 cost by 50%. Lastly, it increases guided weapons' chance of being intercepted by 4%." Title="1/4" CrossShield="0.02" Dispersion="0.02" EconomizeGasRate="0.5" DecHeadoff="-0.02" RepelRangeRate="0.05" Money="10000000" Time="399952"/>
    <Level2 GroupLV="2" Comment="This level of proficiency increases the chance of guided weapons' penetrating armor modules by 4%, and the effect of Multi-directional Assault by 4%, while also gives Missile Concussion an 8% better chance to force enemy fleets to fall back and Energy Conservation a 10% chance to reduce He3 cost by 50%. Lastly, it increases guided weapons' chance of being intercepted by 4%; Next Level: Increases the chance of guided weapons' penetrating armor modules by 6%, and the effect of Multi-directional Assault by 6%, while also gives Missile Concussion a 11% better chance to force enemy fleets to fall back and Energy Conservation a 15% better chance to reduce He3 cost by 50%, and increases maximum range of guided weapons by 2. Lastly, it increases guided weapons' chance of being intercepted by 6%." Title="2/4" CrossShield="0.04" Dispersion="0.04" BoostCarry="1" EconomizeGasRate="0.1" DecHeadoff="-0.04" RepelRangeRate="0.08" Money="30000000" Time="599952"/>
    <Level3 GroupLV="3" Comment="This level of proficiency increases the chance of guided weapons' penetrating armor modules by 6%, and the effect of Multi-directional Assault by 6%, while also gives Missile Concussion a 11% better chance to force enemy fleets to fall back and Energy Conservation a 15% better chance to reduce He3 cost by 50%, and increases maximum range of guided weapons by 2. Lastly, it increases guided weapons' chance of being intercepted by 6%; Next Level: Increases the chance of guided weapons' penetrating armor modules by 8%, and the effect of Multi-directional Assault by 8%, while also gives Missile Concussion a 15% better chance to force enemy fleets to fall back and Energy Conservation a 22% better chance to reduce He3 cost by 50%, and increases maximum range of guided weapons by 3. Lastly, it increases guided weapons' chance of being intercepted by 8%." Title="3/4" CrossShield="0.06" Dispersion="0.06" BoostCarry="2" EconomizeGasRate="0.15" DecHeadoff="-0.05" RepelRangeRate="0.11" Money="80000000" Time="729952"/>
    <Level4 GroupLV="4" Comment="This level of proficiency increases the chance of guided weapons' penetrating armor modules by &lt;font color='#00FF00'&gt;8%&lt;/font&gt;, and the effect of Multi-directional Assault by &lt;font color='#00FF00'&gt;8%&lt;/font&gt;, while also gives Missile Concussion a &lt;font color='#00FF00'&gt;15%&lt;/font&gt; 15% better chance to force enemy fleets to fall back and Energy Conservation a &lt;font color='#00FF00'&gt;22%&lt;/font&gt; better chance to reduce He3 cost by 50%, and increases maximum range of guided weapons by &lt;font color='#00FF00'&gt;+3&lt;/font&gt;. Lastly, it increases guided weapons' chance of being intercepted by &lt;font color='#00FF00'&gt;8%&lt;/font&gt;." Title="4" CrossShield="0.08" Dispersion="0.08" BoostCarry="3" EconomizeGasRate="0.22" DecHeadoff="-0.08" RepelRangeRate="0.15" Money="150000000" Time="936026"/>
  </List>
  <List GroupID="48" Name="Fighter Weapons Theory" Comment="Increase damage of Fighter-based weapons; Lv1: +3% damange of Fighter-based weapons." Kind="15" Tech="" ImageFileName="Tech48" Title="0/10" TechMemo="">
    <Level1 GroupLV="1" Comment="Current Level: Increase damage of Fighter-based weapons 3%; Next level: +6% damange of Fighter-based weapons." Title="1/10" Hit="0.03" Money="541" Time="117"/>
    <Level2 GroupLV="2" Comment="Current Level: Increase damage of Fighter-based weapons 6%; Next level: +9% damange of Fighter-based weapons." Title="2/10" Hit="0.06" Money="628" Time="158"/>
    <Level3 GroupLV="3" Comment="Current Level: Increase damage of Fighter-based weapons 9%; Next level: +12% damange of Fighter-based weapons." Title="3/10" Hit="0.09" Money="959" Time="368"/>
    <Level4 GroupLV="4" Comment="Current Level: Increase damage of Fighter-based weapons 12%; Next level: +15% damange of Fighter-based weapons." Title="4/10" Hit="0.12" Money="1467" Time="861"/>
    <Level5 GroupLV="5" Comment="Current Level: Increase damage of Fighter-based weapons 15%; Next level: +18% damange of Fighter-based weapons." Title="5/10" Hit="0.15" Money="2244" Time="2015"/>
    <Level6 GroupLV="6" Comment="Current Level: Increase damage of Fighter-based weapons 18%; Next level: +21% damange of Fighter-based weapons." Title="6/10" Hit="0.18" Money="3434" Time="4717"/>
    <Level7 GroupLV="7" Comment="Current Level: Increase damage of Fighter-based weapons 21%; Next level: +24% damange of Fighter-based weapons." Title="7/10" Hit="0.21" Money="5253" Time="11039"/>
    <Level8 GroupLV="8" Comment="Current Level: Increase damage of Fighter-based weapons 24%; Next level: +27% damange of Fighter-based weapons." Title="8/10" Hit="0.24" Money="8036" Time="25834"/>
    <Level9 GroupLV="9" Comment="Current Level: Increase damage of Fighter-based weapons 27%; Next level: +30% damange of Fighter-based weapons." Title="9/10" Hit="0.27" Money="12294" Time="60461"/>
    <Level10 GroupLV="10" Comment="Current Level: Increase damage of Fighter-based weapons &lt;font color='#00FF00'&gt;+30%&lt;/font&gt;." Title="10" Hit="0.3" Money="18808" Time="141501"/>
  </List>
  <List GroupID="49" Name="Reconnaissance" Comment="Increase steering power of Fighter-based weapons; Lv1: +10% steering power of Fighter-based weapons." Kind="15" Tech="48:3" ImageFileName="Tech49" Title="0/2" TechMemo="Requires Fighter Weapons Theory Lv 3">
    <Level1 GroupLV="1" Comment="Current Level: Increase steering power of Fighter-based weapons by 10%; Next level: +20% steering power of Fighter-based weapons." Title="1/2" Turn="0.1" Money="11603" Time="3366"/>
    <Level2 GroupLV="2" Comment="Current Level: Increase steering power of Fighter-based weapons by &lt;font color='#00FF00'&gt;+20%&lt;/font&gt;." Title="2" Turn="0.2" Money="13434" Time="4512"/>
  </List>
  <List GroupID="50" Name="Fuel Optimization" Comment="Reduce the He3 cost of Fighter-based weapons; Lv1: -1% He3 cost of Fighter-based weapons." Kind="15" Tech="48:6;49:1" ImageFileName="Tech50" Title="0/5" TechMemo="Requires Fighter Weapons Theory Lv 6, Reconnaissance Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: Reduce the He3 cost of Fighter-based weapons by 1%; Next level: -2% He3 cost of Fighter-based weapons." Title="1/5" DecHes="0.01" Money="22724" Time="2550"/>
    <Level2 GroupLV="2" Comment="Current Level: Reduce the He3 cost of Fighter-based weapons by 2%; Next level: -3% He3 cost of Fighter-based weapons." Title="2/5" DecHes="0.02" Money="26309" Time="3418"/>
    <Level3 GroupLV="3" Comment="Current Level: Reduce the He3 cost of Fighter-based weapons by 3%; Next level: -4% He3 cost of Fighter-based weapons." Title="3/5" DecHes="0.03" Money="40247" Time="7999"/>
    <Level4 GroupLV="4" Comment="Current Level: Reduce the He3 cost of Fighter-based weapons by 4%; Next level: -5% He3 cost of Fighter-based weapons." Title="4/5" DecHes="0.04" Money="61571" Time="18721"/>
    <Level5 GroupLV="5" Comment="Current Level: Reduce the He3 cost of Fighter-based weapons by &lt;font color='#00FF00'&gt;-5%&lt;/font&gt;He3." Title="5" DecHes="0.05" Money="94191" Time="43812"/>
  </List>
  <List GroupID="51" Name="Fighter Tech Upgrades" Comment="Reduces the He3 cost of ship-based weapons and increases base damage when attacking an enemy protected by shields; Lv 1: -2% He3 cost and +3% base damage." Kind="15" Tech="49:2;50:5" ImageFileName="Tech51" Title="0/3" TechMemo="Requires Reconnaissance Lv 2, Fuel Optimization Lv 5">
    <Level1 GroupLV="1" Comment="Current Level: -2% He3 cost of Fighter-based weapons and +3% base damage when attacking an enemy protected by shields; Next level: -4% He3 cost of Fighter-based weapons and +6% base damage when attacking an enemy protected by shields." Title="1/3" DecHes="0.02" ShieldHurt="0.03" Money="174015" Time="19380"/>
    <Level2 GroupLV="2" Comment="Current Level: -4% He3 cost of Fighter-based weapons and +6% base damage when attacking an enemy protected by shields; Next level: -6% He3 cost of Fighter-based weapons and +10% base damage when attacking an enemy protected by shields." Title="2/3" DecHes="0.04" ShieldHurt="0.06" Money="201463" Time="25976"/>
    <Level3 GroupLV="3" Comment="Current Level: &lt;font color='#00FF00'&gt;-6%&lt;/font&gt; He3 cost of Fighter-based weapons and &lt;font color='#00FF00'&gt;+10%&lt;/font&gt; base damage when attacking an enemy protected by shields." Title="3" DecHes="0.06" ShieldHurt="0.1" Money="308203" Time="60793"/>
  </List>
  <List GroupID="52" Name="Armor Structural Analysis" Comment="&lt;font color='#00FF00'&gt;+10%&lt;/font&gt; base damage of Fighter-based weapons when attacking ships and &lt;font color='#00FF00'&gt;+10%&lt;/font&gt; Fighter-based weapons damage against any type of shield" Kind="15" Tech="51:3" ImageFileName="Tech52" Title="0/1" TechMemo="Requires Fighter Tech Upgrades Lv 3">
    <Level1 GroupLV="1" Comment="&lt;font color='#00FF00'&gt;+10%&lt;/font&gt; base damage of Fighter-based weapons when attacking ships and &lt;font color='#00FF00'&gt;+10%&lt;/font&gt; Fighter-based weapons damage against any type of shield" Title="1" Hit="0.15" ArmorHurt="1:0.1;2:0.1;3:0.1;4:0.1;5:0.1;6:0.1" Money="363582" Time="40800"/>
  </List>
  <List GroupID="53" Name="Fighter-based Weapons Efficiency" Comment="Grant Fighter-based weapons a chance to finish reloading right after attacks; Lv1: +10% chance to finish reloading right after attacks. The effect will last until the battle ends." Kind="15" Tech="48:10;52:1" ImageFileName="Tech53" Title="0/3" TechMemo="Requires Fighter Weapons Theory Lv 10, Armor Structural Analysis Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: +10% chance to finish reloading right after attacks. The effect will last until the battle ends; Next level: +20% chance to finish reloading right after attacks." Title="1/3" UnBackfillRate="0.1" Money="740249" Time="91290"/>
    <Level2 GroupLV="2" Comment="Current Level: +20% chance to finish reloading right after attacks. The effect will last until the battle ends; Next level: +30% chance to finish reloading right after attacks." Title="2/3" UnBackfillRate="0.2" Money="857013" Time="122361"/>
    <Level3 GroupLV="3" Comment="Current Level: &lt;font color='#00FF00'&gt;+30%&lt;/font&gt; chance to finish reloading right after attacks. The effect will last until the battle ends." Title="3" UnBackfillRate="0.3" Money="1311071" Time="286365"/>
  </List>
  <List GroupID="54" Name="Thruster Optimization" Comment="Reduce the intercept rate of Figher-based weapons; Lv1: -1% intercept rate of Fighter-based weapons." Kind="15" Tech="48:3" ImageFileName="Tech54" Title="0/5" TechMemo="Requires Fighter Weapons Theory Lv 3">
    <Level1 GroupLV="1" Comment="Current Level: -1% intercept rate of Fighter-based weapons; Next level: -2% intercept rate of Fighter-based weapons." Title="1/5" DecHeadoff="0.01" Money="6387" Time="1020"/>
    <Level2 GroupLV="2" Comment="Current Level: -2% intercept rate of Fighter-based weapons; Next level: -3% intercept rate of Fighter-based weapons." Title="2/5" DecHeadoff="0.02" Money="7397" Time="1368"/>
    <Level3 GroupLV="3" Comment="Current Level: -3% intercept rate of Fighter-based weapons; Next level: -4% intercept rate of Fighter-based weapons." Title="3/5" DecHeadoff="0.03" Money="11312" Time="3199"/>
    <Level4 GroupLV="4" Comment="Current Level: -4% intercept rate of Fighter-based weapons; Next level: -5% intercept rate of Fighter-based weapons." Title="4/5" DecHeadoff="0.04" Money="17307" Time="7488"/>
    <Level5 GroupLV="5" Comment="Current Level: &lt;font color='#00FF00'&gt;-5%&lt;/font&gt; intercept rate of Fighter-based weapons." Title="5" DecHeadoff="0.05" Money="26476" Time="17525"/>
  </List>
  <List GroupID="55" Name="Long-ranged Strike" Comment="&lt;font color='#00FF00'&gt;+3%, +6% , +9%, +12% or +15%&lt;/font&gt; base attack power of Fighter-based weapons when fleet is &lt;font color='#00FF00'&gt;6, 7, 8, 9 or 10&lt;/font&gt; slots away from target." Kind="15" Tech="50:3;54:3;58:1" ImageFileName="Tech55" Title="0/1" TechMemo="Requires Fuel Optimization Lv 3, Thruster Optimization Lv 3, Fighter Mastery Lv 1">
    <Level1 GroupLV="1" Comment="&lt;font color='#00FF00'&gt;+3%, +6% , +9%, +12% or +15%&lt;/font&gt; base attack power of Fighter-based weapons when fleet is &lt;font color='#00FF00'&gt;6, 7, 8, 9 or 10&lt;/font&gt; slots away from target." Title="1" DistanceATK="6:0.03;7:0.06;8:0.09;9:0.12;10:0.15" Money="98955" Time="15300"/>
  </List>
  <List GroupID="56" Name="Fortune" Comment="Grant Fighter-based weapons a chance to deal double damage during long-ranged attacks and increase critical strike rate; Lv1: +10% chance to deal double damage during long-ranged attacked and +10% critical strike rate." Kind="15" Tech="54:5;55:1;61:3" ImageFileName="Tech56" Title="0/3" TechMemo="Requires Thruster Optimization Lv 5, Long-ranged Strike Lv 1, Swarm Lv 3">
    <Level1 GroupLV="1" Comment="Current Level: +10% chance to deal double damage during long-ranged attacked and +10% critical strike rate; Next level: +20% chance to deal double damage during long-ranged attacked and +20% critical strike rate." Title="1/3" AddDistanceATK="0.1" ImproveBlast="0.1" Money="885076" Time="76500"/>
    <Level2 GroupLV="2" Comment="Current Level: +20% chance to deal double damage during long-ranged attacked and +20% critical strike rate; Next level: +30% chance to deal double damage during long-ranged attacked and +30% critical strike rate." Title="2/3" AddDistanceATK="0.2" ImproveBlast="0.2" Money="1024685" Time="102537"/>
    <Level3 GroupLV="3" Comment="Current Level: &lt;font color='#00FF00'&gt;+30%&lt;/font&gt; chance to deal double damage during long-ranged attacked and &lt;font color='#00FF00'&gt;+30%&lt;/font&gt; critical strike rate." Title="3" AddDistanceATK="0.3" ImproveBlast="0.3" Money="1567579" Time="239971"/>
  </List>
  <List GroupID="57" Name="Navigation" Comment="Increase hit rate of Fighter-based weapons; Lv1: +1% hit rate of Fighter-based weapons." Kind="15" Tech="48:3" ImageFileName="Tech57" Title="0/5" TechMemo="Requires Fighter Weapons Theory Lv 3">
    <Level1 GroupLV="1" Comment="Current Level: Increase hit rate of Fighter-based weapons by 1%; Next level: +2% hit rate of Fighter-based weapons." Title="1/5" Ratio="0.01" Money="6850" Time="1173"/>
    <Level2 GroupLV="2" Comment="Current Level: Increase hit rate of Fighter-based weapons by 2%; Next level: +3% hit rate of Fighter-based weapons." Title="2/5" Ratio="0.02" Money="7932" Time="1573"/>
    <Level3 GroupLV="3" Comment="Current Level: Increase hit rate of Fighter-based weapons by 3%; Next level: +4% hit rate of Fighter-based weapons." Title="3/5" Ratio="0.03" Money="12131" Time="3679"/>
    <Level4 GroupLV="4" Comment="Current Level: Increase hit rate of Fighter-based weapons by 4%; Next level: +5% hit rate of Fighter-based weapons." Title="4/5" Ratio="0.04" Money="18560" Time="8612"/>
    <Level5 GroupLV="5" Comment="Current Level: Increase hit rate of Fighter-based weapons by &lt;font color='#00FF00'&gt;5%&lt;/font&gt;." Title="5" Ratio="0.05" Money="28392" Time="20153"/>
  </List>
  <List GroupID="58" Name="Fighter Mastery" Comment="&lt;font color='#00FF00'&gt;+5%&lt;/font&gt; base attack power of Fighter-based weapons." Kind="15" Tech="48:6;57:3" ImageFileName="Tech58" Title="0/1" TechMemo="Requires Fighter Weapons Theory Lv 6, Navigation Lv 3">
    <Level1 GroupLV="1" Comment="&lt;font color='#00FF00'&gt;+5%&lt;/font&gt; base attack power of Fighter-based weapons." Title="1" Hit="0.05" Money="48737" Time="11730"/>
  </List>
  <List GroupID="59" Name="Fighter Interception Countermeasures" Comment="Reduces the chance of fighter-based weapons being intercepted; Lv1: -1% intercept rate of Fighter-based weapons." Kind="15" Tech="54:3;57:5;58:1" ImageFileName="Tech59" Title="0/5" TechMemo="Requires Thruster Optimization Lv 3, Navigation Lv 5, Fighter Mastery Lv 1">
    <Level1 GroupLV="1" Comment="Current Level: -1% intercept rate of Fighter-based weapons; Next level: -2% intercept rate of Fighter-based weapons." Title="1/5" DecHeadoff="0.01" Money="135381" Time="11730"/>
    <Level2 GroupLV="2" Comment="Current Level: -2% intercept rate of Fighter-based weapons; Next level: -3% intercept rate of Fighter-based weapons." Title="2/5" DecHeadoff="0.02" Money="156739" Time="15723"/>
    <Level3 GroupLV="3" Comment="Current Level: -3% intercept rate of Fighter-based weapons; Next level: -4% intercept rate of Fighter-based weapons." Title="3/5" DecHeadoff="0.03" Money="239775" Time="36795"/>
    <Level4 GroupLV="4" Comment="Current Level: -4% intercept rate of Fighter-based weapons; Next level: -5% intercept rate of Fighter-based weapons." Title="4/5" DecHeadoff="0.04" Money="366817" Time="86115"/>
    <Level5 GroupLV="5" Comment="Current Level: &lt;font color='#00FF00'&gt;-5%&lt;/font&gt; intercept rate of Fighter-based weapons." Title="5" DecHeadoff="0.05" Money="561161" Time="201537"/>
  </List>
  <List GroupID="60" Name="Formation Optimization" Comment="Increase critical strike damage of Fighter-based weapons and reduce occupied space; Lv1: +5% critical strike damage of Fighter-based weapons and -5% occupied space." Kind="15" Tech="59:5" ImageFileName="Tech60" Title="0/2" TechMemo="Requires Fighter Interception Countermeasures Lv 5">
    <Level1 GroupLV="1" Comment="Current Level: +5% critical strike damage of Fighter-based weapons and -5% occupied space; Next level: +10% critical strike damage of Fighter-based weapons and -10% occupied space." Title="1/2" BlastHurt="0.05" LowCubage="0.05" Money="287437" Time="25500"/>
    <Level2 GroupLV="2" Comment="Current Level: &lt;font color='#00FF00'&gt;+10%&lt;/font&gt; critical strike damage of Fighter-based weapons and &lt;font color='#00FF00'&gt;-10%&lt;/font&gt; occupied space." Title="2" BlastHurt="0.1" LowCubage="0.1" Money="332776" Time="34179"/>
  </List>
  <List GroupID="61" Name="Swarm" Comment="Grant Fighter-based weapons a chance to increase base attack power with additional He3; Lv1: Grants fighter-based weapons a 10% chance of increasing their base attack power by 8% at the cost of 15% more He3." Kind="15" Tech="48:10;60:2" ImageFileName="Tech61" Title="0/3" TechMemo="Requires Fighter Weapons Theory Lv 10, Formation Optimization Lv 2">
    <Level1 GroupLV="1" Comment="Current Level: Grants fighter-based weapons a 10% chance of increasing their base attack power by 8% at the cost of 15% more He3; Next level: Grants fighter-based weapons a 20% chance of increasing their base attack power by 16% at the cost of 25% more He3." Title="1/3" ImproveHitOdds="0.1" ImproveHit="0.08" ImproveHe3="0.15" Money="630845" Time="66300"/>
    <Level2 GroupLV="2" Comment="Current Level: Grants fighter-based weapons a 20% chance of increasing their base attack power by 16% at the cost of 25% more He3; Next level: Grants fighter-based weapons a 30% chance of increasing their base attack power by 25% at the cost of 35% more He3." Title="2/3" ImproveHitOdds="0.2" ImproveHit="0.16" ImproveHe3="0.25" Money="730355" Time="88866"/>
    <Level3 GroupLV="3" Comment="Current Level: Grants fighter-based weapons a &lt;font color='#00FF00'&gt;30%&lt;/font&gt; chance of increasing their base attack power by &lt;font color='#00FF00'&gt;25%&lt;/font&gt; at the cost of &lt;font color='#00FF00'&gt;35%&lt;/font&gt; more He3." Title="3" ImproveHitOdds="0.3" ImproveHit="0.25" ImproveHe3="0.35" Money="1117305" Time="207975"/>
  </List>
  <List GroupID="62" Name="Ingenuity" Comment="&lt;font color='#00FF00'&gt;+5%&lt;/font&gt; chance of triggering a swarm effect, &lt;font color='#00FF00'&gt;+5%&lt;/font&gt; base attack power of Fighter-based weapons, &lt;font color='#00FF00'&gt;-5%&lt;/font&gt; He3 cost &lt;font color='#00FF00'&gt;+20%&lt;/font&gt; intercept rate and &lt;font color='#00FF00'&gt;+10%&lt;/font&gt; base attack power against ships without shield protection." Kind="15" Tech="53:3;56:3" ImageFileName="Tech62" Title="0/1" TechMemo="Requires Fighter-based Weapons Efficiency Lv 3, Fortune Lv 3">
    <Level1 GroupLV="1" Comment="&lt;font color='#00FF00'&gt;+5%&lt;/font&gt; chance of triggering a swarm effect, &lt;font color='#00FF00'&gt;+5%&lt;/font&gt; base attack power of Fighter-based weapons, &lt;font color='#00FF00'&gt;-5%&lt;/font&gt; He3 cost &lt;font color='#00FF00'&gt;+20%&lt;/font&gt; intercept rate and &lt;font color='#00FF00'&gt;+10%&lt;/font&gt; base attack power against ships without shield protection." Title="1" UnShieldHurt="0.1" ImproveHitOdds="0.05" ImproveHit="0.05" LowerHe3="0.05" Intercept="0.2" Money="2045150" Time="255000"/>
  </List>
  <List GroupID="63" Name="Heavy Gear Research" Comment="This science grants Fighter-based Weapons Efficiency an additional chance to finish reloading ship-based weapons immediately after attacks, and increases the damage of ship-based weapons against enemies that have shields and maximum attack range of ship-based weapons. It also increases ship-based weapons' chance of interception, but enables ship-based weapons to reload faster; Next Level: Gives Fighter-based Weapons Efficiency a 5% better chance of reloading ship-based weapons immediately after attacks, and increases damage of ship-based weapons against enemies that have shields by 3% and maximum attack range of ship-based weapons by 1. It also increases ship-based weapons' chance of interception by 3%, but enables ship-based weapons to finish reloading with 1 less round." Kind="15" Tech="62:1" ImageFileName="Tech63" Title="0/4" TechMemo="Requires Ingenuity Lv 1">
    <Level1 GroupLV="1" Comment="This level of proficiency gives Fighter-based Weapons Efficiency a 5% better chance of reloading ship-based weapons immediately after attacks, and increases damage of ship-based weapons against enemies that have shields by 3% and maximum attack range of ship-based weapons by 1. It also increases ship-based weapons' chance of interception by 3%, but enables ship-based weapons to finish reloading with 1 less round; Next Level: Gives Fighter-based Weapons Efficiency a 10% better chance of reloading ship-based weapons immediately after attacks, and increases damage of ship-based weapons against enemies that have shields by 7% and maximum attack range of ship-based weapons by 2. It also increases ship-based weapons' chance of interception by 5%, but enables ship-based weapons to finish reloading with 1 less round." Title="1/4" BoostCarry="1" DecHeadoff="-0.03" DecBackfill="1" ShieldHurt="0.03" UnBackfillRate="0.03" Money="10000000" Time="399952"/>
    <Level2 GroupLV="2" Comment="This level of proficiency gives Fighter-based Weapons Efficiency a 10% better chance of reloading ship-based weapons immediately after attacks, and increases damage of ship-based weapons against enemies that have shields by 7% and maximum attack range of ship-based weapons by 2. It also increases ship-based weapons' chance of interception by 5%, but enables ship-based weapons to finish reloading with 1 less round; Next Level: Gives Fighter-based Weapons Efficiency a 15% better chance of reloading ship-based weapons immediately after attacks, and increases damage of ship-based weapons against enemies that have shields by 11% and maximum attack range of ship-based weapons by 3. It also increases ship-based weapons' chance of interception by 7%, but enables ship-based weapons to finish reloading with 1 less round. " Title="2/4" BoostCarry="2" DecHeadoff="-0.05" DecBackfill="1" ShieldHurt="0.07" UnBackfillRate="0.05" Money="30000000" Time="599952"/>
    <Level3 GroupLV="3" Comment="This level of proficiency gives Fighter-based Weapons Efficiency a 15% better chance of reloading ship-based weapons immediately after attacks, and increases damage of ship-based weapons against enemies that have shields by 11% and maximum attack range of ship-based weapons by 3. It also increases ship-based weapons' chance of interception by 7%, but enables ship-based weapons to finish reloading with 1 less round; Next Level: Gives Fighter-based Weapons Efficiency a 20% better chance of reloading ship-based weapons immediately after attacks, and increases damage of ship-based weapons against enemies that have shields by 15% and maximum attack range of ship-based weapons by 5. It also increases ship-based weapons' chance of interception by 10%, but enables ship-based weapons to finish reloading with 1 less round." Title="3/4" BoostCarry="3" DecHeadoff="-0.07" DecBackfill="1" ShieldHurt="0.11" UnBackfillRate="0.07" Money="80000000" Time="729952"/>
    <Level4 GroupLV="4" Comment="This level of proficiency gives Fighter-based Weapons Efficiency a &lt;font color='#00FF00'&gt;20%&lt;/font&gt; better chance of reloading ship-based weapons immediately after attacks, and increases damage of ship-based weapons against enemies that have shields by &lt;font color='#00FF00'&gt;15%&lt;/font&gt; and maximum attack range of ship-based weapons by &lt;font color='#00FF00'&gt;+5&lt;/font&gt;. It also enables ship-based weapons to finish reloading with &lt;font color='#00FF00'&gt;1&lt;/font&gt; less round but increases ship-based weapons' chance of interception by &lt;font color='#00FF00'&gt;10%&lt;/font&gt;." Title="4" BoostCarry="5" DecHeadoff="-0.1" DecBackfill="1" ShieldHurt="0.15" UnBackfillRate="0.1" Money="150000000" Time="936026"/>
  </List>
</WeaponTech>;
      
      public function GameRes_WeaponTechXml()
      {
         super();
      }
   }
}

