package
{
   public class GameRes_InstanceXml
   {
      
      public static var data:XML = <Instance Name="戰鬥副本" MC="CopydianPlan" LineColor="0x00BFED">
	<Ectype0 ID="1" X="36" Y="30" Name="01. Ancestral Recall" Repeat="2" Type="3" MaxUser="1" UserTeam="3" NeedID="-1" UserShip="90000" Count="6" EctypeID="0" MaxGate="1" Exp="180" Treasure="1500" Comment="Destroy all enemy warships in this round." Comment2="Technology and its advancements have always been a double-edged sword. Millenia of neglect and depletion of the Earth and its resources have brought about catastrophic seismic changes, releasing primal energy locked within the depths of the planet into the far reaches of the universe, creating terrible forcefields known as Black Holes at strategically mineral-rich planets."/>
	<Ectype1 ID="2" X="78" Y="66" Name="02. Deadzone" Repeat="3" Type="3" MaxUser="1" UserTeam="4" NeedID="0" UserShip="120000" Count="6" EctypeID="1" MaxGate="1" Exp="500" Treasure="1501" Comment="Destroy all enemy warships in this round." Comment2="Planet R - a world so terrible that no name could adequately describe it. Magnetic fields surrounding the planet can suddenly go into disarray, causing nearby warships and spacecraft to implode like crushed cans, obliterating entire fleets in an instant."/>
	<Ectype2 ID="3" X="30" Y="138" Name="03. Bravery" Repeat="3" Type="3" MaxUser="1" UserTeam="4" NeedID="1" UserShip="120000" Count="6" EctypeID="2" MaxGate="1" Exp="1000" Treasure="1502" Comment="Destroy all enemy warships in this round." Comment2="The harsh environment and scorching sands of this planet have been home to outlandish pirates for many ages. They are veteran fighters, known for their resilience and hardiness. Only by conquering these pirates can one truly claim to be the master of the galaxy."/>
	<Ectype3 ID="4" X="96" Y="114" Name="04. Ambush" Repeat="3" Type="3" MaxUser="1" UserTeam="5" NeedID="2" UserShip="150000" Count="6" EctypeID="3" MaxGate="1" Exp="1540" Treasure="1503" Comment="Destroy all enemy warships in this round." Comment2="Stay alert and be ready to act at any second, for the pirates are far superior in numbers and cunning. Our resources have been severely compromised at various locations and are dwindling at an alarming rate. Our losses are piling up much faster than we can reduce their numbers. This is a dire situation indeed."/>
	<Ectype4 ID="5" X="150" Y="42" Name="05. Defending Yourself" Repeat="3" Type="3" MaxUser="1" UserTeam="5" NeedID="3" UserShip="150000" Count="6" EctypeID="4" MaxGate="1" Exp="1820" Treasure="1504" Comment="Destroy all enemy warships in this round." Comment2="This defensive system was a legend in its time, fortified by the best technology then available. The empire behind its design may have long ago perished, but the system that remains today is still a formidable barrier capable of deterring potential aggressors."/>
	<Ectype5 ID="6" X="162" Y="108" Name="06. To Victory" Repeat="3" Type="3" MaxUser="1" UserTeam="6" NeedID="4" UserShip="180000" Count="6" EctypeID="5" MaxGate="1" Exp="2310" Treasure="1505" Comment="Destroy all enemy warships in this round." Comment2="The Syndicate is commonly associated with all manners of dirty dealings and wrongdoings within the galaxy to satisfy both their nefarious plans and deranged personalities. Will you be the one to bring the hammer of justice down on these villians?"/>
	<Ectype6 ID="7" X="150" Y="168" Name="07. Annihilation" Repeat="3" Type="3" MaxUser="1" UserTeam="8" NeedID="5" UserShip="240000" Count="6" EctypeID="6" MaxGate="1" Exp="3220" Treasure="1506" Comment="Destroy all enemy warships in this round." Comment2="Beep ... beep beep ...,A coded transmission is coming in. The translated message contains a strategical report from one of the frontline scouts: The enemy is planning an attack on us. Coordinates of their deployment are ..."/>
	<Ectype7 ID="8" X="72" Y="186" Name="08. Hellish Ventures" Repeat="3" Type="3" MaxUser="1" UserTeam="8" NeedID="6" UserShip="240000" Count="6" EctypeID="7" MaxGate="1" Exp="4340" Treasure="1507" Comment="Destroy all enemy warships in this round." Comment2="Countless heroes have come, tried, and failed. Those few who survived walked away with unimaginable riches. Will you be one such legend, or just another statistic?"/>
	<Ectype8 ID="9" X="36" Y="258" Name="09. Duel" Repeat="3" Type="3" MaxUser="1" UserTeam="8" NeedID="7" UserShip="240000" Count="6" EctypeID="8" MaxGate="1" Exp="5250" Treasure="1508" Comment="Destroy all enemy warships in this round." Comment2="The seven major powers of the galaxy are about to convene for an interplanetary negotiation. Unfortunately, a certain terrorist group is gathering its forces for the sole purpose of wiping out all the leaders involved in this peaceful exchange. If successful, their attack will sow chaos throughout the galaxy. Can you stop them?"/>
	<Ectype9 ID="10" X="30" Y="324" Name="10. Lost" Repeat="3" Type="3" MaxUser="1" UserTeam="10" NeedID="8" UserShip="300000" Count="6" EctypeID="9" MaxGate="1" Exp="6300" Treasure="1509" Comment="Destroy all enemy warships in this round." Comment2="A.D. 206: A smallish spacecraft crash-landed on an abandoned planet with 48 passengers aboard. Without means to summon aid, these 48 passengers await their fate in these desolate and barren lands."/>
	<Ectype10 ID="11" X="66" Y="366" Name="11. Wonderland" Repeat="3" Type="3" MaxUser="1" UserTeam="10" NeedID="9" UserShip="300000" Count="6" EctypeID="10" MaxGate="1" Exp="8400" Treasure="1510" Comment="Destroy all enemy warships in this round." Comment2="An alien fleet of warships has been detected by our radar. Analysis indicates they are coming in fast, with aggressive intent. To be forewarned is to be forearmed; time to get ready for some violent confrontations! "/>
	<Ectype11 ID="12" X="84" Y="300" Name="12. Dead or Alive" Repeat="3" Type="3" MaxUser="1" UserTeam="10" NeedID="10" UserShip="300000" Count="6" EctypeID="11" MaxGate="1" Exp="10500" Treasure="1511" Comment="Destroy all enemy warships in this round." Comment2="A dangerous convict recently escaped from a maximum security prison, and is now believed to have joined forces with a notorious band of pirates. Under the leadership of this convict, the pirates have managed to combine their efforts to become a mightier fighting force than any previously sighted. They are now hellbent on bringing chaos and instability to the galaxy. They must be stopped at all costs."/>
	<Ectype12 ID="13" X="138" Y="348" Name="13. Ship Graveyard" Repeat="3" Type="3" MaxUser="1" UserTeam="10" NeedID="11" UserShip="300000" Count="6" EctypeID="12" MaxGate="1" Exp="14000" Treasure="1512" Comment="Destroy all enemy warships in this round." Comment2="Gloom surrounds this eerie place where ships have been abandoned for millenia. They have been shut down and put to rest forever in this forbidding place, where even light fails to penetrate. An unshakable air of death and doom fills this graveyard of behemoths."/>
	<Ectype12 ID="14" X="204" Y="372" Name="14. E.C.R" Repeat="3" Type="3" MaxUser="1" UserTeam="10" NeedID="12" UserShip="300000" Count="6" EctypeID="13" MaxGate="1" Exp="17500" Treasure="1513" Comment="Destroy all enemy warships in this round." Comment2="Every commander must take part in a real battle before graduating from the Galaxy College. This year, the performance in the real battle will affect the overall evaluation of a commander more when they graduate.  The enemies in the E.C.R event are bearing down menacingly, take care!"/>
	<Ectype12 ID="15" X="138" Y="240" Name="15. Free Flight" Repeat="3" Type="3" MaxUser="1" UserTeam="12" NeedID="13" UserShip="3000000" Count="6" EctypeID="14" MaxGate="1" Exp="21000" Treasure="1514" Comment="Destroy all enemy warships in this round." Comment2="There are some issues left over from history. In the past years, a group ruled the galaxy tyrannically. During the period, innumerous common people were oppressed severely. Even though the galaxy has been out of the tyrannical reign, some of the common people have been attempting to give vent to their pent-up anger by attacking the fleets passing by the galaxy."/>
	<Ectype12 ID="16" X="210" Y="216" Name="16. Spell Break" Repeat="3" Type="3" MaxUser="1" UserTeam="12" NeedID="14" UserShip="3000000" Count="6" EctypeID="15" MaxGate="1" Exp="24500" Treasure="1515" Comment="Destroy all enemy warships in this round." Comment2="The galaxy has been divided into two independent empires by a war before. At the middle of the two empires there are still a lot of evil groups that don't submit themselves to any of the empires. To unify the galaxy again, we must first conquer the groups."/>
	<Ectype12 ID="17" X="228" Y="156" Name="17. Lucky Zodiac" Repeat="3" Type="3" MaxUser="1" UserTeam="12" NeedID="15" UserShip="3000000" Count="6" EctypeID="16" MaxGate="1" Exp="28000" Treasure="1516" Comment="Destroy all enemy warships in this round." Comment2="Enjoy a cup of good wine before you start the journey. I believe it will be a fantastic journey even though there may be some unknown perils. Anyway, do everything to beat down the enemies."/>
	<Ectype12 ID="18" X="210" Y="84" Name="18. The Blackest Hole" Repeat="3" Type="3" MaxUser="1" UserTeam="12" NeedID="16" UserShip="3000000" Count="6" EctypeID="17" MaxGate="1" Exp="31500" Treasure="1517" Comment="Destroy all enemy warships in this round." Comment2="The Queen Anne has been out of sight for five years. The universe is always filled with mystery. Five years ago, when the Queen Anne passed by Missipi, the center of Missipi suddenly shrunk fast and turned into a black hole which finally swallowed the Queen Anne. By far, the black hole is still mystic and sounds horrific."/>
	<Ectype12 ID="19" X="258" Y="36" Name="19. The Matrix Returned" Repeat="3" Type="3" MaxUser="1" UserTeam="12" NeedID="17" UserShip="3000000" Count="6" EctypeID="18" MaxGate="1" Exp="35000" Treasure="1518" Comment="Destroy all enemy warships in this round." Comment2="Since the Yolyano planetoid began to move stably along the lunar orbit, the galaxy has entered a harmonious era. However, when Yolyano deviated from the orbit, there appeared a matrix sinuous zone with abundant resources. Anyone who manages to occupy the zone is obliged sooner or later the overlord in the galaxy."/>
	<Ectype12 ID="20" X="330" Y="30" Name="20. Timewhirl" Repeat="3" Type="3" MaxUser="1" UserTeam="12" NeedID="18" UserShip="3000000" Count="6" EctypeID="19" MaxGate="1" Exp="38500" Treasure="1519" Comment="Destroy all enemy warships in this round." Comment2="Z zone is a very mystic zone in the galaxy. In the zone, there are lots of planets which reflect sunshine in most of the time. As the result, Z zone looks so beautiful. However, most people who approached the zone have been lost mystically. What a terrible zone!"/>
	<Ectype12 ID="21" X="348" Y="66" Name="21. Bushwhacked" Repeat="3" Type="3" MaxUser="1" UserTeam="15" NeedID="19" UserShip="3000000" Count="6" EctypeID="20" MaxGate="1" Exp="42000" Treasure="1520" Comment="Destroy all enemy warships in this round." Comment2="In any battle, the side that acts faster will take more advantages. The Doltt pirates have always acted fast in battles. Are you able to act faster than them?"/>
	<Ectype12 ID="22" X="282" Y="96" Name="22. The Gathering" Repeat="3" Type="3" MaxUser="1" UserTeam="15" NeedID="20" UserShip="3000000" Count="6" EctypeID="21" MaxGate="1" Exp="45500" Treasure="1521" Comment="Destroy all enemy warships in this round." Comment2="Watch out for the bloodthirsty Selm pirates. You'd better not fight against them recklessly. Also, try your best to calm down when encountering them. "/>
	<Ectype12 ID="23" X="330" Y="132" Name="23. Saving Grace" Repeat="3" Type="3" MaxUser="1" UserTeam="15" NeedID="21" UserShip="3000000" Count="6" EctypeID="22" MaxGate="1" Exp="49000" Treasure="1522" Comment="Destroy all enemy warships in this round." Comment2="A flock of adventurers were attacked by pirates when they approached their starting planet, planet X, and they had to land on planet X. They are suffering from exhaustion, wound, lack of oxygen and more. Please rescue them as soon as possible."/>
	<Ectype12 ID="24" X="276" Y="186" Name="24. Prowler" Repeat="3" Type="3" MaxUser="1" UserTeam="15" NeedID="22" UserShip="3000000" Count="6" EctypeID="23" MaxGate="1" Exp="52500" Treasure="1523" Comment="Destroy all enemy warships in this round." Comment2="There are a lot of smart pirates. They don't have the most advanced weapons. They are not very brutal either. But they have the most advanced anti-radar facilities. As a result, they've managed to plunder lots of trade caravans. Please carefully organize your warships and beat them."/>
	<Ectype12 ID="25" X="264" Y="246" Name="25. Faceoff-I" Repeat="3" Type="3" MaxUser="1" UserTeam="15" NeedID="23" UserShip="3000000" Count="6" EctypeID="24" MaxGate="1" Exp="56000" Treasure="1524" Comment="Destroy all enemy warships in this round." Comment2="There is no time to consider more. Our latest attacks against the pirates have driven them crazy and they've even organized a large-scale counterattack."/>
	<Ectype12 ID="26" X="210" Y="294" Name="26. Faceoff-II" Repeat="3" Type="3" MaxUser="1" UserTeam="15" NeedID="24" UserShip="3000000" Count="6" EctypeID="25" MaxGate="1" Exp="59500" Treasure="1525" Comment="Destroy all enemy warships in this round." Comment2="The pirates suffered high casualties last battle. They are now  gathering their force to counterattack. This time, we must give them a severe lesson. Launch an attack and end the annoying battle as soon as possible!"/>
	<Ectype12 ID="27" X="264" Y="354" Name="27. Broken Pact" Repeat="3" Type="3" MaxUser="1" UserTeam="15" NeedID="25" UserShip="3000000" Count="6" EctypeID="26" MaxGate="1" Exp="63000" Treasure="1526" Comment="Destroy all enemy warships in this round." Comment2="Planet M is rich in resources and sell resources to gain benefits. They also signed an agreement with the pirates to avoid offense from the pirates by offering the pirates some protection fees. However, the pirates have raised the amount of yearly protection fees time and again. So the two sides have not yet reached an agreement. Then the pirates have kidnapped the lord of planet M. It is of great urgency. Please rescue the lord."/>
	<Ectype12 ID="28" X="324" Y="246" Name="28. Smashing" Repeat="3" Type="3" MaxUser="1" UserTeam="15" NeedID="26" UserShip="3000000" Count="6" EctypeID="27" MaxGate="1" Exp="66500" Treasure="1527" Comment="Destroy all enemy warships in this round." Comment2="Tukubu tribe has gradually got out of last century's decadence and attempted to occupy unmanned areas to get more resources for future development. However, they've been oppressed by the pirates for a long time and they are still not strong enough to beat down the pirates."/>
	<Ectype12 ID="29" X="336" Y="300" Name="29. B.P" Repeat="3" Type="3" MaxUser="1" UserTeam="15" NeedID="27" UserShip="3000000" Count="6" EctypeID="28" MaxGate="1" Exp="70000" Treasure="1528" Comment="Destroy all enemy warships in this round." Comment2="All good forces in the galaxy  have signed Plan B.P for future development. However, the plan will impossibly be carried out before the largest pirate group has been eliminated. "/>
	<Ectype12 ID="30" X="342" Y="366" Name="30. Triumphant Glory" Repeat="3" Type="3" MaxUser="1" UserTeam="15" NeedID="28" UserShip="3000000" Count="6" EctypeID="29" MaxGate="1" Exp="73500" Treasure="1529" Comment="Destroy all enemy warships in this round." Comment2="Mogrini is one of the most prestigious lords in the galaxy. However he was once captured by pirates and were almost killed. From then on, some people often studiously mentioned the dishonorable history no matter how hard Mogrini worked. However, Mogrini have not given a response but focused on making preparations for eliminating the pirates to prove himself."/>
</Instance>;
      
      public function GameRes_InstanceXml()
      {
         super();
      }
   }
}

