package
{
   public class GameRes_InstanceChallenge
   {
      
      public static var data:XML = <InstanceChallenge Name="挑戰副本" MC="CopydianPlan1" LineColor="0x774701" FreeTime="3" Prop="1" Context="">
  <Ectype0 ID="1" X="37" Y="45" Name="1. El botín de Calvin" EctypeID="30" NeedID="-1" Repeat="2" UserTeam="10" MaxGate="1" Treasure="931" Number="10" Treasure2="1540" Exp="10000" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="El infame pirata Calvin es conocido por haber asaltado a gran número de importantes mercaderes a su paso por la ruta comercial durante las últimas décadas. Con el paso de los años su fortuna ha aumentado considerablemente. Sus ansias de poder parecen haber aumentado y le han llevado a implicarse en algunas batallas recientes contra tropas gubernamentales. Alguien debe pararle los pies y aquel que lo consiga recibirá una más que generosa recompensa."/>
  <Ectype1 ID="2" X="77" Y="186" Name="2. El regreso del hijo pródigo" EctypeID="31" NeedID="-1" Repeat="2" UserTeam="12" MaxGate="1" Treasure="931" Number="13" Treasure2="1541" Exp="20000" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Desde el fallecimiento de su último emperador y su posterior escisión, en el imperio de Rayman reinan el caos y la anarquía. Por suerte, el príncipe Rekacel ha regresado de su largo exilio al mando de una poderosa flota y con la intención de reunir de nuevo a su otrora esplendoroso pueblo. A pesar de haber puesto grandes esperanzas en ello, la mayoría de los ciudadanos se muestran escépticos. Rekacel necesita la ayuda de todo comandante de élite disponible. ¿Te gustaría ayudarlo?"/>
  <Ectype2 ID="3" X="28" Y="256" Name="3. Zona de peligro" EctypeID="32" NeedID="-1" Repeat="2" UserTeam="15" MaxGate="1" Treasure="931" Number="16" Treasure2="1542" Exp="30000" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Adars es considerada por todos como una zona prohibida que alberga algunas de las fuerzas más violentas de la galaxia, tanto naturales como sobrenaturales. Todo aquel que ose cruzar sus fronteras deberá hacer frente a inestables gigantes rojas , campos magnéticos y gravitacionales anómalos y muchos más peligros. Los aventureros más veteranos incluso hablan de un enorme agujero negro en el centro de la región que devora todo lo que encuentra a su paso. Numerosas naves han desaparecido aquí sin dejar ni rastro ya que, aunque resulte contradictorio, sus misterios han atraído a no pocos aventureros."/>
  <Ectype3 ID="4" X="70" Y="352" Name="4. El resurgir de las ruinas de Rofilla" EctypeID="33" NeedID="-1" Repeat="2" UserTeam="18" MaxGate="1" Treasure="931" Number="20" Treasure2="1543" Exp="40000" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="El Consorcio de Rofilla acumuló grandes riquezas gracias a la compraventa de información y armas durante períodos de guerra. Esta fortuna les sirvió para construir una inmensa base conocida como la Fortaleza Impenetrable. A pesar de que dicho bastión se diseñó con la intención de repeler cualquier ataque, una catástrofe natural hizo que sus ocupantes tuvieran que desalojarlo. Según informes recientes, un malvado ejército de piratas está tratando de reparar el fuerte, convertirlo en su base y lanzar un asalto contra la Federación. No podemos quedarnos quietos o sus fuerzas seguirán creciendo hasta que no podamos hacerles frente. Es hora de acabar con ellos y destruir el fuerte por completo."/>
  <Ectype4 ID="5" X="160" Y="315" Name="5. Ayuda a Helukar" EctypeID="34" NeedID="-1" Repeat="2" UserTeam="20" MaxGate="1" Treasure="931" Number="23" Treasure2="1544" Exp="50000" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="El planeta Helukar te envió un mensaje secreto para comunicarte el brutal ataque de una especie desconocida a la que no son capaces de hacer frente. Helukar fue en sus orígenes una base de investigación científica construida por el grupo Kadry, aunque hoy en día permanece desocupada desde la caída de dicho grupo. Por rara que te pareciese, no podías desatender una llamada de auxilio, así que te dirigiste con tu ejército a inspeccionar el lugar. Tras llegar al planeta, caes en una trampa: una enorme flota te impide la retirada. ¿Cómo lograrás escapar de esta?"/>
  <Ectype5 ID="6" X="205" Y="358" Name="6. Una oportunidad única" EctypeID="35" NeedID="-1" Repeat="2" UserTeam="20" MaxGate="1" Treasure="931" Number="26" Treasure2="1545" Exp="60000" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Según parece, el responsable de la emboscada en Helukar es Murphy, un Consejero de la Federación que planea acabar contigo y quedarse con tu fortuna. Por suerte, sabemos que planea asistir a la conferencia del Consejo que se celebrará mañana el planeta Darna. Es tu oportunidad de demostrarle con quién se las está viendo. Aprovéchala y ataca su base."/>
  <Ectype6 ID="7" X="333" Y="323" Name="7. El conflicto" EctypeID="36" NeedID="-1" Repeat="2" UserTeam="20" MaxGate="1" Treasure="931" Number="30" Treasure2="1546" Exp="70000" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="¡Nos asaltan! ¿Quién osa atacar mi base principal? ¿Wicos? ¿Un ejército de Wicos trata de asaltarnos? ¡Acabad con esos insectos y no dejéis ni uno!."/>
  <Ectype7 ID="8" X="356" Y="215" Name="8. El ataque final" EctypeID="37" NeedID="-1" Repeat="2" UserTeam="21" MaxGate="1" Treasure="931" Number="33" Treasure2="1547" Exp="80000" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="El príncipe Rekacel ha preparado una inmensa ofensiva contra Calmet, el último de los bastiones del ejército rebelde que aún se mantiene en pie. ¡Ayúdale a acabar con ellos!"/>
  <Ectype8 ID="9" X="231" Y="236" Name="9. La decisión" EctypeID="38" NeedID="-1" Repeat="2" UserTeam="25" MaxGate="1" Treasure="931" Number="36" Treasure2="1548" Exp="90000" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="La Federación te ha condenado por alta traición y ha declarado la guerra contra tu ejército. Un gran número de flotas enviadas por el mismo Murphy se dirigen hacia tu planeta con la intención de destruirlo. ¿Harás frente a la batalla o huirás de ella?"/>
  <Ectype9 ID="10" X="185" Y="164" Name="10. Día del Juicio Final" EctypeID="39" NeedID="-1" Repeat="2" UserTeam="25" MaxGate="1" Treasure="931" Number="40" Treasure2="1549" Exp="100000" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Esta es la batalla final que decidirá quién se alza victorioso. ¡Hazle frente de una vez por todas! "/>
</InstanceChallenge>;
      
      public function GameRes_InstanceChallenge()
      {
         super();
      }
   }
}

