package
{
   public class GameRes_MainTaskXml
   {
      
      public static var data:XML = <Task Name="主线任务">
  <List TaskClass="0">
    <Level TaskID="0" TaskName="Collecting Resources" Comment1="Your planet is rich in natural resources, and a good Commander must know how to control their inventory space. Regularly collect resources from your Resource Warehouse to make space for more. " Comment2="Harvest your Resource Warehouse" MetalAward="450" He3Award="950" MoneyAward="500" CoinsAward="20" ItemAward="921" ItemNum="20" MetalLV="0"/>
    <Level TaskID="119" TaskName="Loud and Clear" Comment1="With a Loudspeaker, you can make your presence in the galaxy felt by chatting in the World Channel! Give a shout-out to friends in the GO universe or challenge a rival! What you say is up to you! (Click on the chat window in the lower left corner and choose World. Enter some text and start chatting!)" Comment2="Say something in the World Channel" MetalAward="460" He3Award="980" MoneyAward="520" ItemAward="-1"/>
    <Level TaskID="4" TaskName="Lv1 Technology Center" Comment1="Technology drives progress. Only through dilligent research can society hope to move forward. Construct a Technology Center to enable the research of the latest sciences. (Click on &lt;a href='event:1'&gt;(Build)&lt;/a&gt; located in the lower right corner, and select &lt;a href='event:2'&gt;(Construct Buildings)&lt;/a&gt;" Comment2="Build a Lv1 Technology Center" MetalAward="2250" He3Award="2100" MoneyAward="3250" ItemAward="921" ItemNum="20" TechCenterLV="0"/>
    <Level TaskID="111" TaskName="Lv1 Technological Research" Comment1="Invest in research so that your base can grow with much more efficiency. Research Concurrent Construction in your Technology Center first to increase your capacity for simultaneous construction." Comment2="Concurrent Construction Lv1" MetalAward="500" He3Award="480" MoneyAward="600" ItemAward="900" ItemNum="1"/>
    <Level TaskID="107" TaskName="Metal Production" Comment1="The discovery and mining of Metal is crucial to laying the sturdy foundations of an empire for the ages. (Click on &lt;a href='event:1'&gt;(Build)&lt;/a&gt; located in the lower right corner, and select &lt;a href='event:2'&gt;(Construct Buildings)&lt;/a&gt;, then click on Resources, and start constructing your first Metal Collector!" Comment2="Construct Metal Collector Lv1" MetalAward="425" He3Award="530" MoneyAward="425" ItemAward="829" ItemNum="1"/>
    <Level TaskID="110" TaskName="Blueprints 1" Comment1="You must first learn and acquire the contents listed in a blueprint  before it can be used. (Click on &lt;a href='event:3'&gt;(My Tools)&lt;/a&gt; located in the lower right corner, then click on &lt;a href='event:4'&gt;(Bag)&lt;/a&gt;, and use the Super Transmission Engine contained within.)" Comment2="Use Blueprint  (Super Transmission Engine)" MetalAward="515" He3Award="1190" MoneyAward="575" ItemAward="902" ItemNum="1"/>
    <Level TaskID="115" TaskName="He3 Production" Comment1="He3 is crucial to the continued development and progress of colonies, as well as being indispensable in the construction of warships.  (Click on &lt;a href='event:1'&gt;(Build)&lt;/a&gt; located in the lower right corner, and select &lt;a href='event:2'&gt;(Construct Buildings)&lt;/a&gt;, then click on Resources, and start constructing your first He3 mine!" Comment2="Construct He3 Extractor Lv1" MetalAward="475" He3Award="400" MoneyAward="475" ItemAward="741" ItemNum="1"/>
    <Level TaskID="118" TaskName="Blueprints 2" Comment1="You must first learn and acquire the contents listed in a blueprint  before it can be used. (Click on &lt;a href='event:3'&gt;(My Tools)&lt;/a&gt; located in the lower right corner, then click on &lt;a href='event:4'&gt;(Bag)&lt;/a&gt;, and use the Estrella contained within.)" Comment2="Use Blueprint  (Estrella)" MetalAward="520" He3Award="1150" MoneyAward="585" ItemAward="805" ItemNum="1"/>
    <Level TaskID="116" TaskName="Creating A Residential Area" Comment1="Providing a comfortable living environment for your people serves to boost the economy of your colonies and generate more Gold. (Click on &lt;a href='event:1'&gt;(Build)&lt;/a&gt; located in the lower right corner, and select &lt;a href='event:2'&gt;(Construct Buildings)&lt;/a&gt;, then click on Resources, and start constructing your first Residential Area!" Comment2="Construct Residential Area Lv1" MetalAward="390" He3Award="360" MoneyAward="325" ItemAward="921" ItemNum="20"/>
    <Level TaskID="3" TaskName="Lv1 Ship Factory" Comment1="To embark upon a journey toward greatness, every aspiring commander must have an awe-inspiring fleet. Everything starts small! (Click on &lt;a href='event:1'&gt;(Build)&lt;/a&gt; located in the lower right corner, and select &lt;a href='event:2'&gt;(Construct Buildings)&lt;/a&gt;" Comment2="Construct a Ship Factory Lv1" MetalAward="600" He3Award="475" MoneyAward="550" ItemAward="730" ItemNum="1" ShipyardLV="0"/>
    <Level TaskID="17" TaskName="Lv1 Command Center" Comment1="Even the strongest force is doomed to fail if it lacks a strong leader. Build a Command Center to recruit and maintain commanders. (Click on &lt;a href='event:1'&gt;(Build)&lt;/a&gt; located in the lower right corner, and select &lt;a href='event:2'&gt;(Construct Buildings)&lt;/a&gt;" Comment2="Construct a Command Center Lv1" MetalAward="3000" He3Award="2250" MoneyAward="2500" ItemAward="812" ItemNum="1" ComanderCenterLV="0"/>
    <Level TaskID="102" TaskName="Recruit Commanders" Comment1="A capable commander can make the difference between life and death. Recruit one from your Command Center and watch your forces grow exponentially in potential and ability!" Comment2="Recruit 1 Commander" MetalAward="605" He3Award="1250" MoneyAward="685" ItemAward="903" ItemNum="1"/>
    <Level TaskID="1" TaskName="Design a Ship" Comment1="To build a powerful ship, you must choose all the right components. We suggest selecting the Estrella-I warship for the hull, and adding 4x Cluster Laser Transmitters and 3x Super Transmission Engines to make it super strong. (Click &lt;a href='event:5'&gt;(Military)&lt;/a&gt;->&lt;a href='event:6'&gt;(Ship Design)&lt;/a&gt; to begin adding components.) There are a lot of parts to choose from, so be thorough!" Comment2="Design a Ship" MetalAward="585" He3Award="1235" MoneyAward="650" ItemAward="921" ItemNum="20"/>
    <Level TaskID="2" TaskName="Ship Building" Comment1="Spare no effort in creating each and every ship, for a fleet needs each of its parts to be at its absolute best. Go to Build -> Build Warship to begin constructing ships for your fleet." Comment2="Build a Lv1 Ship" MetalAward="600" He3Award="1200" MoneyAward="680" ItemAward="824" ItemNum="1"/>
    <Level TaskID="101" TaskName="Build a Fleet" Comment1="Coordination and unity are key to all forms of success. Build your first fleet by going to Military -> Create Fleet. Remember to appoint a  Commander to man your crew." Comment2="Build 1 Fleet" MetalAward="610" He3Award="1300" MoneyAward="690" ItemAward="921" ItemNum="20"/>
    <Level TaskID="117" TaskName="Wartime Logistics" Comment1="Having sufficient ammunition and supplies for your troops must always be a top priority. Even a sure victory can quickly turn to disaster if the logistical side of warfare isn't handled properly. (Click on &lt;a href='event:5'&gt;(Military)&lt;/a&gt; located at the lower right corner and select &lt;a href='event:13'&gt;(Fleet Supplies)&lt;/a&gt;. Then, click on (Supply All)." Comment2="Replenish Ammunition" MetalAward="2000" He3Award="3000" MoneyAward="2000" ItemAward="902" ItemNum="1"/>
    <Level TaskID="5" TaskName="Lv1 Weapon Research Ctr" Comment1="The best defense is to have great offense. You should make sure you are prepared for battle by investing in the quality and power of your weapons. (Click on &lt;a href='event:1'&gt;(Build)&lt;/a&gt; -> &lt;a href='event:2'&gt;(Construct Buildings)&lt;/a&gt; to find your Weapon Research Center." Comment2="Own a Weapon Research Ctr Lv1" MetalAward="2500" He3Award="1500" MoneyAward="2250" ItemAward="782" ItemNum="1" WeaponResearchLV="0"/>
    <Level TaskID="105" TaskName="Bigger Bags" Comment1="Prosperity calls for more accomodation, and a jam-packed storage will only limit you from reaching your full potential. Find a locked slot in your bag and click on it to activate. Paying a small amount of gold is well worth the investment!" Comment2="Increase Your Bag Slot By 1" MetalAward="620" He3Award="1310" MoneyAward="700" ItemAward="912" ItemNum="1"/>
    <Level TaskID="108" TaskName="Resource Pack" Comment1="Resource packs contain extra Metal, Gold or He3 and provide relief during hard times. Find one in your Bag and use it to increase your resource supply." Comment2="Use a Resource Pack" MetalAward="680" He3Award="1450" MoneyAward="750" ItemAward="923" ItemNum="1"/>
    <Level TaskID="109" TaskName="Growing Resources" Comment1="Growing your own resources on Comsats within your Subsidiary Territory is often the best way to reduce cost and become self-sufficient! [Click on My Tools, Subsidiary Territory, Build. Select one of the Comsats and set it in the empty space.]" Comment2="Grow Your Own Resources" MetalAward="700" He3Award="1480" MoneyAward="780" ItemAward="904" ItemNum="1"/>
    <Level TaskID="112" TaskName="Adding Friends" Comment1="Never underestimate the importance of having friends, because you never know when opportunity will come knocking. (Click on &lt;a href='event:11'&gt;(Social)&lt;/a&gt; and select &lt;a href='event:12'&gt;(Rankings)&lt;/a&gt;. Click on a player of choice, and then click Add Friend)" Comment2="Add 1 Friend" MetalAward="710" He3Award="1500" MoneyAward="800" ItemAward="-1"/>
    <Level TaskID="113" TaskName="The Mail System" Comment1="Keep in contact with your friends or they may not be there when you need them most! (Click on &lt;a href='event:11'&gt;(Social)&lt;/a&gt; and select &lt;a href='event:12'&gt;(Rankings)&lt;/a&gt;. Click on a player of choice, and select Mail.)" Comment2="Send an Email" MetalAward="720" He3Award="1520" MoneyAward="820" ItemAward="921" ItemNum="20"/>
    <Level TaskID="114" TaskName="Lv2 Space Station" Comment1="Space Station are central to keeping your colonies and infrastructure secure. Click on &lt;a href='event:10'&gt;(Space Station)&lt;/a&gt; located along the bottom of the main interface, then select Space Station, and click on Upgrade.)" Comment2="Upgrade Space Station to Lv2" MetalAward="10465" He3Award="9660" MoneyAward="13685" ItemAward="-1"/>
    <Level TaskID="106" TaskName="Space Defense 1" Comment1="Investing in a strong defense is often the most effective way to discourage would-be aggressors. Click on &lt;a href='event:10'&gt;(Space Station)&lt;/a&gt; to check the status of your Defense Network, and then go to &lt;a href='event:1'&gt;(Build)&lt;/a&gt; -> &lt;a href='event:2'&gt;(Construct Buildings)&lt;/a&gt; -> (Defense) to select and build defensive units." Comment2="Build 1 Defensive Structure" MetalAward="750" He3Award="1600" MoneyAward="880" ItemAward="-1"/>
    <Level TaskID="6" TaskName="Lv2 Metal Collector" Comment1="Higher level metal collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade a Metal Collector to Lv2" MetalAward="815" He3Award="690" MoneyAward="815" ItemAward="905" ItemNum="1" MetalLV="1"/>
    <Level TaskID="7" TaskName="Lv2 He3 Extractor" Comment1="Higher level He3 collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade an He3 Extractor to Lv2" MetalAward="730" He3Award="910" MoneyAward="730" ItemAward="906" ItemNum="1" He3LV="1"/>
    <Level TaskID="8" TaskName="Lv2 Residential Area" Comment1="Higher level residential areas have higher yield and provide greater morale for your people. It is essential for the expansion of your base." Comment2="Upgrade a Residential Area to Lv2" MetalAward="670" He3Award="620" MoneyAward="560" ItemAward="907" ItemNum="1" ResidentialLV="1"/>
    <Level TaskID="9" TaskName="Lv2 Ship Factory" Comment1="To expedite the shipbuilding process, we need more Ship Factories." Comment2="Upgrade the Ship Factory to Lv2" MetalAward="1030" He3Award="815" MoneyAward="945" ItemAward="921" ItemNum="20" ShipyardLV="1"/>
    <Level TaskID="10" TaskName="Lv2 Resource Warehouse" Comment1="To better facilitate the process of storing and maintaining resources, central management must first be at its best, and a higher level Resource Warehouse is a mandatory requirement." Comment2="Upgrade the Resource Warehouse to Lv2" MetalAward="3270" He3Award="3180" MoneyAward="4130" ItemAward="-1" StorageLV="1"/>
    <Level TaskID="11" TaskName="Lv2 Civic Center" Comment1="Colonial management is the key to further development." Comment2="Upgrade the Civic Center to Lv2" MetalAward="6644" He3Award="5800" MoneyAward="7248" CoinsAward="10" ItemAward="902" ItemNum="1" CityCenterLV="1"/>
    <Level TaskID="16" TaskName="Lv1 Radar" Comment1="An effective and functional radar is the first line of defense against pesky invaders." Comment2="Construct a Radar to Lv1" MetalAward="1800" He3Award="1600" MoneyAward="2200" ItemAward="-1" ItemNum="1" RadarLV="0"/>
    <Level TaskID="12" TaskName="Lv3 Metal Collector " Comment1="Higher level metal collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade a Metal Collector to Lv3" MetalAward="1012" He3Award="1260" MoneyAward="1012" ItemAward="-1" MetalLV="2"/>
    <Level TaskID="13" TaskName="Lv3 He3 Extractor" Comment1="Higher level He3 collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade an He3 Extractor to Lv3" MetalAward="1132" He3Award="952" MoneyAward="1132" ItemAward="921" ItemNum="20" He3LV="2"/>
    <Level TaskID="14" TaskName="Lv3 Residential Area" Comment1="Higher level residential areas have higher yield and provide greater morale for your people. It is essential for the expansion of your base." Comment2="Upgrade a Residential Area to Lv3" MetalAward="928" He3Award="856" MoneyAward="772" ItemAward="-1" ResidentialLV="2"/>
    <Level TaskID="15" TaskName="Lv3 Resource Warehouse" Comment1="To better facilitate the process of storing and maintaining resources, central management must first be at its best, and a higher level Resource Warehouse is a mandatory requirement." Comment2="Upgrade the Resource Warehouse to Lv3" MetalAward="5901" He3Award="5748" MoneyAward="7455" ItemAward="908" ItemNum="1" StorageLV="2"/>
    <Level TaskID="18" TaskName="Lv2 Weapon Research Ctr" Comment1="Under-researched weaponry is like an unsharpened blade - dull and utterly useless. Invest in your Weapon Research Center to always keep your offensive force at its best!" Comment2="Upgrade the Weapon Research Center to Lv2" MetalAward="4230" He3Award="2538" MoneyAward="3807" ItemAward="794" ItemNum="1" WeaponResearchLV="1"/>
    <Level TaskID="19" TaskName="Lv1 Recycling Plant" Comment1="Used and outdated ships must not go to waste. Take them to the Recycling Plant to keep your planet green and reclaim some resources." Comment2="Construct a Recycling Plant" MetalAward="2000" He3Award="1600" MoneyAward="2200" ItemAward="-1" ShipReclaimLV="0"/>
    <Level TaskID="20" TaskName="Lv1 Trading" Comment1="Everything comes at a price - or a profit! Build a Trading Center to buy, haggle and sell resources with other commanders." Comment2="Construct a Trading Center" MetalAward="4800" He3Award="4400" MoneyAward="6000" ItemAward="-1" TradeLV="0"/>
    <Level TaskID="35" TaskName="Lv2 Command Center" Comment1="The more capable the Commander, the higher their standards. Upgrade your Command Center to attract better candidates for leading your fleets." Comment2="Upgrade the Command Center to Lv2" MetalAward="6768" He3Award="5076" MoneyAward="5640" ItemAward="903" ItemNum="1" ComanderCenterLV="1"/>
    <Level TaskID="21" TaskName="Lv1 Alliance Center" Comment1="Owning an Alliance Center provides a central hub for interaction with other commanders and corps. Build one on your base so that you may join or create a corps of your own!" Comment2="Build an Alliance Center " MetalAward="2000" He3Award="1600" MoneyAward="2200" ItemAward="-1" UnionLV="0"/>
    <Level TaskID="22" TaskName="Lv4 Metal Collector" Comment1="Higher level metal collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade a Metal Collector to Lv4" MetalAward="1760" He3Award="2196" MoneyAward="1760" ItemAward="-1" MetalLV="3"/>
    <Level TaskID="23" TaskName="Lv4 He3 Extractor" Comment1="Higher level He3 collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade an He3 Extractor to Lv4" MetalAward="1968" He3Award="1656" MoneyAward="1968" ItemAward="-1" He3LV="3"/>
    <Level TaskID="24" TaskName="Lv4 Residential Area" Comment1="Higher level residential areas have higher yield and provide greater morale for your people. It is essential for the expansion of your base." Comment2="Upgrade a Residential Area to Lv4" MetalAward="1616" He3Award="1492" MoneyAward="1348" ItemAward="-1" ResidentialLV="3"/>
    <Level TaskID="25" TaskName="Lv3 Ship Factory" Comment1="Upgrade your Ship Factory to produce bigger and more powerful ships." Comment2="Upgrade the Ship Factory to Lv3" MetalAward="1428" He3Award="1132" MoneyAward="1308" ItemAward="921" ItemNum="20" ShipyardLV="2"/>
    <Level TaskID="104" TaskName="A Test of Courage" Comment1="Now that you have a fleet, it's time to test your strength in the Instance maps. May the force of the Intergalactic Council be with you. [Go to your Space Station, Click and choose Instance.]" Comment2="Beat the Ancestral Recall Instance" MetalAward="4400" He3Award="9200" MoneyAward="4900" ItemAward="-1" EctypeID="0"/>
    <Level TaskID="26" TaskName="Lv2 Technology Center" Comment1="Increase the level of your Technology Center to boost research speed and keep you on the forefront of the latest scientific trends." Comment2="Upgrade the Technology Center to Lv2" MetalAward="5076" He3Award="4736" MoneyAward="7332" ItemAward="902" ItemNum="1" TechCenterLV="1"/>
    <Level TaskID="27" TaskName="Lv4 Resource Warehouse" Comment1="To better facilitate the process of storing and maintaining resources, central management must first be at its best, and a higher level Resource Warehouse is a mandatory requirement." Comment2="Upgrade the Resource Warehouse to Lv4" MetalAward="7868" He3Award="7664" MoneyAward="9940" ItemAward="-1" StorageLV="3"/>
    <Level TaskID="28" TaskName="Lv4 Ship Factory" Comment1="Upgrade your Ship Factory to produce bigger and more powerful ships." Comment2="Upgrade the Ship Factory to Lv4" MetalAward="2484" He3Award="1968" MoneyAward="2280" ItemAward="-1" ShipyardLV="3"/>
    <Level TaskID="29" TaskName="Lv3 Civic Center" Comment1="Colonial management is the key to further development." Comment2="Upgrade the Civic Center to Lv3" MetalAward="10066" He3Award="8784" MoneyAward="10980" CoinsAward="10" ItemAward="-1" CityCenterLV="2"/>
    <Level TaskID="30" TaskName="Lv5 Metal Collector" Comment1="Higher level metal collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade Metals Collector  to Lv5" MetalAward="1540" He3Award="1920" MoneyAward="1540" ItemAward="-1" MetalLV="4"/>
    <Level TaskID="31" TaskName="Lv5 He3 Extractor" Comment1="Higher level He3 collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade an He3 Extractor to Lv5" MetalAward="1722" He3Award="1450" MoneyAward="1722" ItemAward="-1" He3LV="4"/>
    <Level TaskID="32" TaskName="Lv5 Residential Area " Comment1="Higher level residential areas have higher yield and provide greater morale for your people. It is essential for the expansion of your base." Comment2="Upgrade a Residential Area to Lv5" MetalAward="1414" He3Award="1304" MoneyAward="1178" ItemAward="-1" ResidentialLV="4"/>
    <Level TaskID="33" TaskName="Lv5 Resource Warehouse" Comment1="To better facilitate the process of storing and maintaining resources, central management must first be at its best, and a higher level Resource Warehouse is a mandatory requirement." Comment2="Upgrade the Resource Warehouse to Lv5" MetalAward="6886" He3Award="6704" MoneyAward="8698" ItemAward="921" ItemNum="20" StorageLV="4"/>
    <Level TaskID="34" TaskName="Lv2 Radar" Comment1="An effective and functional radar is the first line of defense against pesky invaders." Comment2="Upgrade the Radar to Lv2" MetalAward="2538" He3Award="2256" MoneyAward="3102" ItemAward="-1" RadarLV="1"/>
    <Level TaskID="36" TaskName="Lv1 Compounding Center" Comment1="It has long been established that the merging of diversity is the road to better results and greater talent. Build a Compounding Center to combine all the best qualities of various items and commanders." Comment2="Constructing a Compounding Center to Lv1" MetalAward="24" He3Award="200" MoneyAward="20" CoinsAward="10" ItemAward="-1" SynthesisLV="0"/>
    <Level TaskID="54" TaskName="Lv3 Command Center" Comment1="The more capable the Commander, the higher their standards. Upgrade your Command Center to attract better candidates for leading your fleets." Comment2="Upgrade the Command Center to Lv3" MetalAward="9576" He3Award="7182" MoneyAward="7980" ItemAward="904" ItemNum="1" ComanderCenterLV="2"/>
    <Level TaskID="37" TaskName="Lv5 Ship Factory" Comment1="Upgrade your Ship Factory to produce bigger and more powerful ships." Comment2="Upgrade the Ship Factory to Lv5" MetalAward="2174" He3Award="1722" MoneyAward="1994" ItemAward="-1" ShipyardLV="4"/>
    <Level TaskID="38" TaskName="Lv3 Weapon Research Ctr" Comment1="Under-researched weaponry is like an unsharpened blade - dull and utterly useless. Invest in your Weapon Research Center to always keep your offensive force at its best!" Comment2="Upgrade the Weapon Research Ctr to Lv3" MetalAward="7980" He3Award="4788" MoneyAward="7182" ItemAward="-1" WeaponResearchLV="2"/>
    <Level TaskID="39" TaskName="Lv2 Recycling Plant" Comment1="Used and outdated ships must not go to waste. Take them to the Recycling Plant to keep your planet green and reclaim some resources." Comment2="Upgrade the Recycling Plant to Lv2" MetalAward="3020" He3Award="2416" MoneyAward="3322" ItemAward="923" ItemNum="1" ShipReclaimLV="1"/>
    <Level TaskID="40" TaskName="Lv2 Trading" Comment1="As trade and commerce expand, the necessary facilities must keep pace in terms of capabilities and effectiveness." Comment2="Upgrade the Trading Center to Lv2" MetalAward="8448" He3Award="7744" MoneyAward="10560" ItemAward="-1" TradeLV="1"/>
    <Level TaskID="41" TaskName="Lv2 Alliance Center" Comment1="Alliances must grow over time. As they do, the facilities and management staff must also expand." Comment2="Upgrade the Alliance Center to Lv2" MetalAward="2820" He3Award="2256" MoneyAward="3102" ItemAward="921" ItemNum="20" UnionLV="1"/>
    <Level TaskID="42" TaskName="Lv6 Metal Collector" Comment1="Higher level metal collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade a Metal Collector to Lv6" MetalAward="2710" He3Award="3380" MoneyAward="2710" ItemAward="-1" MetalLV="5"/>
    <Level TaskID="43" TaskName="Lv6 He3 Extractor" Comment1="Higher level He3 collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade an He3 Extractor to Lv6" MetalAward="3030" He3Award="2552" MoneyAward="3030" ItemAward="-1" He3LV="5"/>
    <Level TaskID="44" TaskName="Lv6 Residential Area" Comment1="Higher level residential areas have higher yield and provide greater morale for your people. It is essential for the expansion of your base." Comment2="Upgrade a Residential Area to Lv6" MetalAward="2488" He3Award="2296" MoneyAward="2074" ItemAward="-1" ResidentialLV="5"/>
    <Level TaskID="45" TaskName="Lv3 Technology Center" Comment1="Increase the level of your Technology Center to boost research speed and keep you on the forefront of the latest scientific trends." Comment2="Upgrade the Technology Center to Lv3" MetalAward="7182" He3Award="6704" MoneyAward="10374" ItemAward="-1" TechCenterLV="2"/>
    <Level TaskID="46" TaskName="Lv6 Resource Warehouse" Comment1="To better facilitate the process of storing and maintaining resources, central management must first be at its best, and a higher level Resource Warehouse is a mandatory requirement." Comment2="Upgrade the Resource Warehouse to Lv6" MetalAward="12120" He3Award="11800" MoneyAward="15308" ItemAward="-1" StorageLV="5"/>
    <Level TaskID="47" TaskName="Lv6 Ship Factory" Comment1="Upgrade your Ship Factory to produce bigger and more powerful ships." Comment2="Upgrade the Ship Factory to Lv6" MetalAward="3828" He3Award="3030" MoneyAward="3508" ItemAward="902" ItemNum="1" ShipyardLV="5"/>
    <Level TaskID="48" TaskName="Lv4 Civic Center" Comment1="Colonial management is the key to further development." Comment2="Upgrade the Civic Center to Lv4" MetalAward="18360" He3Award="16023.6" MoneyAward="20029.2" CoinsAward="10" ItemAward="921" ItemNum="20" CityCenterLV="3"/>
    <Level TaskID="49" TaskName="Lv7 Metal Collector" Comment1="Higher level metal collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade Metals Collector  to Lv7" MetalAward="2878.8" He3Award="3590.4" MoneyAward="2878.8" ItemAward="-1" MetalLV="6"/>
    <Level TaskID="50" TaskName="Lv7 He3 Extractor" Comment1="Higher level He3 collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade an He3 Extractor to Lv7" MetalAward="3217.2" He3Award="2709.6" MoneyAward="3217.2" ItemAward="-1" He3LV="6"/>
    <Level TaskID="51" TaskName="Lv7 Residential Area" Comment1="Higher level residential areas have higher yield and provide greater morale for your people. It is essential for the expansion of your base." Comment2="UpgradeResidential Areato Lv7" MetalAward="2642.4" He3Award="2438.4" MoneyAward="2202" ItemAward="912" ItemNum="1" ResidentialLV="6"/>
    <Level TaskID="52" TaskName="Lv7 Resource Warehouse" Comment1="To better facilitate the process of storing and maintaining resources, central management must first be at its best, and a higher level Resource Warehouse is a mandatory requirement." Comment2="Upgrade the Resource Warehouse to Lv7" MetalAward="12871.2" He3Award="12532.8" MoneyAward="16257.6" ItemAward="915" ItemNum="1" StorageLV="6"/>
    <Level TaskID="53" TaskName="Lv3 Radar" Comment1="An effective and functional radar is the first line of defense against pesky invaders." Comment2="Upgrade the Radar to Lv3" MetalAward="4309.2" He3Award="3830.4" MoneyAward="5266.8" ItemAward="918" ItemNum="1" RadarLV="2"/>
    <Level TaskID="72" TaskName="Lv4 Command Center" Comment1="The more capable the Commander, the higher their standards. Upgrade your Command Center to attract better candidates for leading your fleets." Comment2="Upgrade the Command Center to Lv4" MetalAward="16318.8" He3Award="12238.8" MoneyAward="13598.4" ItemAward="-1" ComanderCenterLV="3"/>
    <Level TaskID="55" TaskName="Lv7 Ship Factory" Comment1="Upgrade your Ship Factory to produce bigger and more powerful ships." Comment2="Upgrade the Ship Factory to Lv7" MetalAward="4064.4" He3Award="3217.2" MoneyAward="3726" ItemAward="-1" ShipyardLV="6"/>
    <Level TaskID="56" TaskName="Lv4 Weapon Research Ctr" Comment1="Under-researched weaponry is like an unsharpened blade - dull and utterly useless. Invest in your Weapon Research Center to always keep your offensive force at its best!" Comment2="Upgrade the Weapon Research Ctr to Lv4" MetalAward="13598.4" He3Award="8158.8" MoneyAward="12238.8" ItemAward="921" ItemNum="20" WeaponResearchLV="3"/>
    <Level TaskID="57" TaskName="Lv3 Recycling Plant" Comment1="Used and outdated ships must not go to waste. Take them to the Recycling Plant to keep your planet green and reclaim some resources." Comment2="Constructing a Recycling Plant to Lv3" MetalAward="5127.6" He3Award="4102.8" MoneyAward="5641.2" ItemAward="-1" ShipReclaimLV="2"/>
    <Level TaskID="58" TaskName="Lv3 Trading" Comment1="As trade and commerce expand, the necessary facilities must keep pace in terms of capabilities and effectiveness." Comment2="Constructing a Trading Center to Lv3" MetalAward="17893.2" He3Award="16401.6" MoneyAward="22365.6" ItemAward="-1" TradeLV="2"/>
    <Level TaskID="59" TaskName="Lv3 Alliance Center" Comment1="Alliances must grow over time. As they do, the facilities and management staff must also expand." Comment2="Building an Alliance Center to Lv3" MetalAward="4788" He3Award="3830.4" MoneyAward="5266.8" ItemAward="-1" UnionLV="2"/>
    <Level TaskID="60" TaskName="Lv8 Metal Collector" Comment1="Higher level metal collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade a Metal Collector to Lv8" MetalAward="5125.2" He3Award="6391.2" MoneyAward="5125.2" ItemAward="912" ItemNum="1" MetalLV="7"/>
    <Level TaskID="61" TaskName="Lv8 He3 Extractor" Comment1="Higher level He3 collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade an He3 Extractor to Lv8" MetalAward="5727.6" He3Award="4822.8" MoneyAward="5727.6" ItemAward="915" ItemNum="1" He3LV="7"/>
    <Level TaskID="62" TaskName="Lv8 Residential Area" Comment1="Higher level residential areas have higher yield and provide greater morale for your people. It is essential for the expansion of your base." Comment2="Upgrade a Residential Area to Lv8" MetalAward="4702.8" He3Award="4340.4" MoneyAward="3919.2" ItemAward="918" ItemNum="1" ResidentialLV="7"/>
    <Level TaskID="63" TaskName="Lv4 Technology Center" Comment1="Increase the level of your Technology Center to boost research speed and keep you on the forefront of the latest scientific trends." Comment2="Upgrade the Technology Center to Lv4" MetalAward="12238.8" He3Award="11422.8" MoneyAward="17678.4" ItemAward="-1" TechCenterLV="3"/>
    <Level TaskID="64" TaskName="Lv8 Resource Warehouse" Comment1="To better facilitate the process of storing and maintaining resources, central management must first be at its best, and a higher level Resource Warehouse is a mandatory requirement." Comment2="Upgrade the Resource Warehouse to Lv8" MetalAward="22910.4" He3Award="22308" MoneyAward="28939.2" ItemAward="-1" StorageLV="7"/>
    <Level TaskID="65" TaskName="Lv8 Ship Factory" Comment1="Upgrade your Ship Factory to produce bigger and more powerful ships." Comment2="Upgrade the Ship Factory to Lv8" MetalAward="7234.8" He3Award="5727.6" MoneyAward="6632.4" ItemAward="-1" ShipyardLV="7"/>
    <Level TaskID="66" TaskName="Lv5 Civic Center" Comment1="Colonial management is the key to further development." Comment2="Upgrade the Civic Center to Lv5" MetalAward="37331.2" He3Award="32580" MoneyAward="40725.6" CoinsAward="10" ItemAward="901" ItemNum="1" CityCenterLV="4"/>
    <Level TaskID="67" TaskName="Lv9 Metal Collector" Comment1="Higher level metal collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade Metals  Collector to Lv9" MetalAward="6115.2" He3Award="7626.4" MoneyAward="6115.2" ItemAward="-1" MetalLV="8"/>
    <Level TaskID="68" TaskName="Lv9 He3 Extractor" Comment1="Higher level He3 collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade an He3 Extractor to Lv9" MetalAward="6835.2" He3Award="5756" MoneyAward="6835.2" ItemAward="904" ItemNum="1" He3LV="8"/>
    <Level TaskID="69" TaskName="Lv9 Residential Area" Comment1="Higher level residential areas have higher yield and provide greater morale for your people. It is essential for the expansion of your base." Comment2="Upgrade a Residential Area to Lv9" MetalAward="5612" He3Award="5180" MoneyAward="4676.8" ItemAward="-1" ResidentialLV="8"/>
    <Level TaskID="70" TaskName="Lv9 Resource Warehouse" Comment1="To better facilitate the process of storing and maintaining resources, central management must first be at its best, and a higher level Resource Warehouse is a mandatory requirement." Comment2="Upgrade the Resource Warehouse to Lv9" MetalAward="27340" He3Award="26620" MoneyAward="34534.4" ItemAward="912" ItemNum="1" StorageLV="8"/>
    <Level TaskID="71" TaskName="Lv4 Radar" Comment1="An effective and functional radar is the first line of defense against pesky invaders." Comment2="Upgrade the Radar to Lv4" MetalAward="8159.2" He3Award="7252.8" MoneyAward="9972.8" ItemAward="915" ItemNum="1" RadarLV="3"/>
    <Level TaskID="89" TaskName="Lv5 Command Center" Comment1="The more capable the Commander, the higher their standards. Upgrade your Command Center to attract better candidates for leading your fleets." Comment2="Upgrade the Command Center to Lv5" MetalAward="31005.6" He3Award="23254.4" MoneyAward="25837.6" ItemAward="918" ItemNum="1" ComanderCenterLV="4"/>
    <Level TaskID="73" TaskName="Lv9 Ship Factory" Comment1="Upgrade your Ship Factory to produce bigger and more powerful ships." Comment2="Upgrade the Ship Factory to Lv9" MetalAward="8633.6" He3Award="6835.2" MoneyAward="7914.4" ItemAward="-1" ShipyardLV="8"/>
    <Level TaskID="103" TaskName="Lv5 Weapon Research Ctr" Comment1="Under-researched weaponry is like an unsharpened blade - dull and utterly useless. Invest in your Weapon Research Center to always keep your offensive force at its best!" Comment2="Upgrade the Weapon Research Center to Lv5" MetalAward="25837.6" He3Award="15502.4" MoneyAward="23254.4" ItemAward="-1" WeaponResearchLV="4"/>
    <Level TaskID="74" TaskName="Lv4 Recycling Plant" Comment1="Used and outdated ships must not go to waste. Take them to the Recycling Plant to keep your planet green and reclaim some resources." Comment2="Constructing a Recycling Plant to Lv4" MetalAward="9708.8" He3Award="7767.2" MoneyAward="10680" ItemAward="921" ItemNum="20" ShipReclaimLV="3"/>
    <Level TaskID="75" TaskName="Lv4 Trading" Comment1="As trade and commerce expand, the necessary facilities must keep pace in terms of capabilities and effectiveness." Comment2="Constructing a Trading Center to Lv4" MetalAward="42227.2" He3Award="38708" MoneyAward="52784" ItemAward="-1" TradeLV="3"/>
    <Level TaskID="76" TaskName="Lv4 Alliance Center" Comment1="Alliances must grow over time. As they do, the facilities and management staff must also expand." Comment2="Building an Alliance Center to Lv4" MetalAward="9065.6" He3Award="7252.8" MoneyAward="9972.8" ItemAward="-1" UnionLV="3"/>
    <Level TaskID="77" TaskName="Lv10 Metal Collector" Comment1="Higher level metal collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade a Metal Collector to Lv10" MetalAward="11008" He3Award="13727.2" MoneyAward="11008" ItemAward="912" ItemNum="1" MetalLV="9"/>
    <Level TaskID="78" TaskName="Lv10 He3 Extractor" Comment1="Higher level He3 collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade an He3 Extractor to Lv10" MetalAward="12303.2" He3Award="10360" MoneyAward="12303.2" ItemAward="915" ItemNum="1" He3LV="9"/>
    <Level TaskID="79" TaskName="Lv10 Residential Area" Comment1="Higher level residential areas have higher yield and provide greater morale for your people. It is essential for the expansion of your base." Comment2="Upgrade a Residential Area to Lv10" MetalAward="10101.6" He3Award="9324" MoneyAward="8417.6" ItemAward="918" ItemNum="1" ResidentialLV="9"/>
    <Level TaskID="80" TaskName="Lv5 Technology Center" Comment1="Increase the level of your Technology Center to boost research speed and keep you on the forefront of the latest scientific trends." Comment2="Upgrade the Technology Center to Lv5" MetalAward="23254.4" He3Award="21704" MoneyAward="33589.6" ItemAward="-1" TechCenterLV="4"/>
    <Level TaskID="81" TaskName="Lv10 Resource Warehouse" Comment1="To better facilitate the process of storing and maintaining resources, central management must first be at its best, and a higher level Resource Warehouse is a mandatory requirement." Comment2="Upgrade the Resource Warehouse to Lv10" MetalAward="49211.2" He3Award="47916.8" MoneyAward="62161.6" ItemAward="-1" StorageLV="9"/>
    <Level TaskID="82" TaskName="Lv10 Ship Factory" Comment1="Upgrade your Ship Factory to produce bigger and more powerful ships." Comment2="Upgrade the Ship Factory to Lv10" MetalAward="15540.8" He3Award="12303.2" MoneyAward="14245.6" ItemAward="-1" ShipyardLV="9"/>
    <Level TaskID="83" TaskName="Lv6 Civic Center" Comment1="Colonial management is the key to further development." Comment2="Upgrade the Civic Center to Lv6" MetalAward="59973.06" He3Award="52339.98" MoneyAward="65425.08" ItemAward="902" ItemNum="1" CityCenterLV="5"/>
    <Level TaskID="84" TaskName="Lv11 Metal Collector" Comment1="Higher level metal collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade a Metal Collector to Lv11" MetalAward="10460.1" He3Award="13044.36" MoneyAward="10460.1" ItemAward="905" ItemNum="1" MetalLV="10"/>
    <Level TaskID="85" TaskName="Lv11 He3 Extractor" Comment1="Higher level He3 collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade an He3 Extractor to Lv11" MetalAward="11690.7" He3Award="9844.8" MoneyAward="11690.7" ItemAward="906" ItemNum="1" He3LV="10"/>
    <Level TaskID="86" TaskName="Lv11 Residential Area" Comment1="Higher level residential areas have higher yield and provide greater morale for your people. It is essential for the expansion of your base." Comment2="Upgrade a Residential Area to Lv11" MetalAward="9598.68" He3Award="8860.32" MoneyAward="7998.9" ItemAward="907" ItemNum="1" ResidentialLV="10"/>
    <Level TaskID="87" TaskName="Lv11 Resource Warehouse" Comment1="To better facilitate the process of storing and maintaining resources, central management must first be at its best, and a higher level Resource Warehouse is a mandatory requirement." Comment2="Upgrade the Resource Warehouse to Lv11" MetalAward="46763.22" He3Award="45532.62" MoneyAward="59069.22" ItemAward="912" ItemNum="1" StorageLV="10"/>
    <Level TaskID="88" TaskName="Lv5 Radar" Comment1="An effective and functional radar is the first line of defense against pesky invaders." Comment2="Upgrade the Radar to Lv5" MetalAward="12208.56" He3Award="10851.96" MoneyAward="14921.34" ItemAward="915" ItemNum="1" RadarLV="4"/>
    <Level TaskID="120" TaskName="Lv6 Command Center" Comment1="The more capable the Commander, the higher their standards. Upgrade your Command Center to attract better candidates for leading your fleets." Comment2="Upgrade Command Center to Lv6" MetalAward="46554.9" He3Award="34916.28" MoneyAward="38795.82" ItemAward="918" ItemNum="1" ComanderCenterLV="5"/>
    <Level TaskID="90" TaskName="Lv11 Ship Factory" Comment1="Upgrade your Ship Factory to produce bigger and more powerful ships." Comment2="Upgrade the Ship Factory to Lv11" MetalAward="14767.2" He3Award="11690.7" MoneyAward="13536.6" ItemAward="918" ItemNum="1" ShipyardLV="10"/>
    <Level TaskID="91" TaskName="Lv6 Weapon Research Ctr" Comment1="Under-researched weaponry is like an unsharpened blade - dull and utterly useless. Invest in your Weapon Research Center to always keep your offensive force at its best!" Comment2="Upgrade the Weapon Research Center to Lv6" MetalAward="38795.82" He3Award="23277.24" MoneyAward="34916.28" ItemAward="-1" WeaponResearchLV="5"/>
    <Level TaskID="92" TaskName="Lv5 Recycling Plant" Comment1="Used and outdated ships must not go to waste. Take them to the Recycling Plant to keep your planet green and reclaim some resources." Comment2="Constructing a Recycling Plant to Lv5" MetalAward="14526.96" He3Award="11621.4" MoneyAward="15979.74" ItemAward="900" ItemNum="1" ShipReclaimLV="4"/>
    <Level TaskID="93" TaskName="Lv5 Trading" Comment1="As trade and commerce expand, the necessary facilities must keep pace in terms of capabilities and effectiveness." Comment2="Constructing a Trading Center to Lv5" MetalAward="78700.86" He3Award="72142.56" MoneyAward="98376.18" ItemAward="-1" TradeLV="4"/>
    <Level TaskID="94" TaskName="Lv5 Alliance Center" Comment1="Alliances must grow over time. As they do, the facilities and management staff must also expand." Comment2="Building an Alliance Center to Lv5" MetalAward="13564.74" He3Award="10851.96" MoneyAward="14921.34" ItemAward="921" ItemNum="20" UnionLV="4"/>
    <Level TaskID="95" TaskName="Lv12 Metal Collector" Comment1="Higher level metal collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade a Metal Collector to Lv12" MetalAward="19037.76" He3Award="23740.92" MoneyAward="19037.76" ItemAward="-1" MetalLV="11"/>
    <Level TaskID="96" TaskName="Lv12 He3 Extractor" Comment1="Higher level He3 collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade an He3 Extractor to Lv12" MetalAward="21277.2" He3Award="17917.62" MoneyAward="21277.2" ItemAward="925" ItemNum="1" He3LV="11"/>
    <Level TaskID="97" TaskName="Lv12 Residential Area" Comment1="Higher level residential areas have higher yield and provide greater morale for your people. It is essential for the expansion of your base." Comment2="Upgrade a Residential Area to Lv12" MetalAward="17469.9" He3Award="16125.9" MoneyAward="14558.04" ItemAward="-1" ResidentialLV="11"/>
    <Level TaskID="98" TaskName="Lv6 Technology Center" Comment1="Increase the level of your Technology Center to boost research speed and keep you on the forefront of the latest scientific trends." Comment2="Upgrade the Technology Center to Lv6" MetalAward="34916.28" He3Award="32588.22" MoneyAward="50434.44" ItemAward="924" ItemNum="1" TechCenterLV="5"/>
    <Level TaskID="99" TaskName="Lv12 Resource Warehouse" Comment1="To better facilitate the process of storing and maintaining resources, central management must first be at its best, and a higher level Resource Warehouse is a mandatory requirement." Comment2="Upgrade the Resource Warehouse to Lv12" MetalAward="85109.22" He3Award="82869.36" MoneyAward="107506.14" ItemAward="904" ItemNum="1" StorageLV="11"/>
    <Level TaskID="100" TaskName="Lv12 Ship Factory" Comment1="Upgrade your Ship Factory to produce bigger and more powerful ships." Comment2="Upgrade the Ship Factory to Lv12" MetalAward="26876.64" He3Award="21277.2" MoneyAward="24636.78" ItemAward="-1" ShipyardLV="11"/>
    <Level TaskID="121" TaskName="Lv7 Civic Center" Comment1="Colonial management is the key to further development." Comment2="Upgrade the Civic Center to Lv7" MetalAward="219187" He3Award="191291" MoneyAward="119556" ItemAward="923" ItemNum="1" CityCenterLV="6"/>
    <Level TaskID="122" TaskName="Lv13 Metal Collector" Comment1="Higher level metal collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade a Metal Collector to Lv13" MetalAward="41474" He3Award="51721" MoneyAward="20737" ItemAward="-1" MetalLV="12"/>
    <Level TaskID="123" TaskName="Lv13 He3 Extractor" Comment1="Higher level He3 collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade an He3 Extractor to Lv13" MetalAward="46354" He3Award="39035" MoneyAward="23177" ItemAward="-1" He3LV="12"/>
    <Level TaskID="124" TaskName="Lv13 Residential Area" Comment1="Higher level residential areas have higher yield and provide greater morale for your people. It is essential for the expansion of your base." Comment2="Upgrade a Residential Area to Lv13" MetalAward="38059" He3Award="35131" MoneyAward="15858" ItemAward="912" ItemNum="1" ResidentialLV="12"/>
    <Level TaskID="125" TaskName="Lv13 Resource Warehouse" Comment1="To better facilitate the process of storing and maintaining resources, central management must first be at its best, and a higher level Resource Warehouse is a mandatory requirement." Comment2="Upgrade the Resource Warehouse to Lv13" MetalAward="185416" He3Award="180537" MoneyAward="117105" ItemAward="915" ItemNum="1" StorageLV="12"/>
    <Level TaskID="126" TaskName="Lv6 Radar" Comment1="An effective and functional radar is the first line of defense against pesky invaders." Comment2="Upgrade the Radar to Lv6" MetalAward="41567" He3Award="36948" MoneyAward="25402" ItemAward="918" ItemNum="1" RadarLV="5"/>
    <Level TaskID="127" TaskName="Lv7 Command Center" Comment1="The more capable the Commander, the higher their standards. Upgrade your Command Center to attract better candidates for leading your fleets." Comment2="Upgrade the Command Center to Lv7" MetalAward="159062" He3Award="119297" MoneyAward="66276" ItemAward="903" ItemNum="1" ComanderCenterLV="6"/>
    <Level TaskID="128" TaskName="Lv13 Ship Factory" Comment1="Upgrade your Ship Factory to produce bigger and more powerful ships." Comment2="Upgrade the Ship Factory to Lv12" MetalAward="58552" He3Award="46354" MoneyAward="26836" ItemAward="904" ItemNum="1" ShipyardLV="12"/>
    <Level TaskID="129" TaskName="Lv7 Weapon Research Ctr" Comment1="Under-researched weaponry is like an unsharpened blade - dull and utterly useless. Invest in your Weapon Research Center to always keep your offensive force at its best!" Comment2="Upgrade the Weapon Research Ctr to Lv7" MetalAward="132552" He3Award="79531" MoneyAward="59648" ItemAward="-1" WeaponResearchLV="6"/>
    <Level TaskID="130" TaskName="Lv6 Recycling Plant" Comment1="Used and outdated ships must not go to waste. Take them to the Recycling Plant to keep your planet green and reclaim some resources." Comment2="Upgrade the Recycling Plant to Lv6" MetalAward="49461" He3Award="39569" MoneyAward="27203" ItemAward="-1" ShipReclaimLV="5"/>
    <Level TaskID="131" TaskName="Lv6 Trading" Comment1="As trade and commerce expand, the necessary facilities must keep pace in terms of capabilities and effectiveness." Comment2="Upgrade the Trading Center to Lv6" MetalAward="333542" He3Award="305746" MoneyAward="208463" ItemAward="921" ItemNum="20" TradeLV="5"/>
    <Level TaskID="132" TaskName="Lv6 Alliance Center" Comment1="Alliances must grow over time. As they do, the facilities and management staff must also expand." Comment2="Upgrade the Alliance Center to Lv6" MetalAward="46185" He3Award="36948" MoneyAward="25402" ItemAward="-1" UnionLV="5"/>
    <Level TaskID="133" TaskName="Lv14 Metal Collector" Comment1="Higher level metal collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade a Metal Collector to Lv14" MetalAward="85291" He3Award="71824" MoneyAward="42645" ItemAward="905" ItemNum="1" MetalLV="13"/>
    <Level TaskID="134" TaskName="Lv14 He3 Extractor" Comment1="Higher level He3 collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade an He3  Extractorto Lv14" MetalAward="76313" He3Award="95167" MoneyAward="38156" ItemAward="906" ItemNum="1" He3LV="13"/>
    <Level TaskID="135" TaskName="Lv14 Residential Area" Comment1="Higher level residential areas have higher yield and provide greater morale for your people. It is essential for the expansion of your base." Comment2="Upgrade a Residential Area to Lv14" MetalAward="70029" He3Award="64642" MoneyAward="29178" ItemAward="907" ItemNum="1" ResidentialLV="13"/>
    <Level TaskID="136" TaskName="Lv7 Technology Center" Comment1="Increase the level of your Technology Center to boost research speed and keep you on the forefront of the latest scientific trends." Comment2="Upgrade the Technology Center to Lv7" MetalAward="119297" He3Award="111344" MoneyAward="86159" ItemAward="-1" TechCenterLV="6"/>
    <Level TaskID="137" TaskName="Lv14 Resource Warehouse" Comment1="To better facilitate the process of storing and maintaining resources, central management must first be at its best, and a higher level Resource Warehouse is a mandatory requirement." Comment2="Upgrade the Resource Warehouse to Lv14" MetalAward="341166" He3Award="332188" MoneyAward="215473" ItemAward="-1" StorageLV="13"/>
    <Level TaskID="138" TaskName="Lv14 Ship Factory" Comment1="Upgrade your Ship Factory to produce bigger and more powerful ships." Comment2="Upgrade the Ship Factory to Lv14" MetalAward="107736" He3Award="85291" MoneyAward="49379" ItemAward="-1" ShipyardLV="13"/>
    <Level TaskID="139" TaskName="Lv8 Civic Center" Comment1="Colonial management is the key to further development." Comment2="Upgrade the Civic Center to Lv8" MetalAward="540077" He3Award="471340" MoneyAward="294587" ItemAward="923" ItemNum="1" CityCenterLV="7"/>
    <Level TaskID="140" TaskName="Lv15 Metal Collector" Comment1="Higher level metal collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade a Metal Collector to Lv15" MetalAward="112944" He3Award="140847.6" MoneyAward="56472" ItemAward="-1" MetalLV="14"/>
    <Level TaskID="141" TaskName="Lv15 He3 Extractor" Comment1="Higher level He3 collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade an He3 Extractor to Lv15" MetalAward="126231" He3Award="106300" MoneyAward="63115" ItemAward="-1" He3LV="14"/>
    <Level TaskID="142" TaskName="Lv15 Residential Area" Comment1="Higher level residential areas have higher yield and provide greater morale for your people. It is essential for the expansion of your base." Comment2="Upgrade a Residential Area to Lv15" MetalAward="103642.8" He3Award="95670" MoneyAward="43184" ItemAward="912" ItemNum="1" ResidentialLV="14"/>
    <Level TaskID="143" TaskName="Lv15 Resource Warehouse" Comment1="To better facilitate the process of storing and maintaining resources, central management must first be at its best, and a higher level Resource Warehouse is a mandatory requirement." Comment2="Upgrade the Resource Warehouse to Lv15" MetalAward="504925" He3Award="491638" MoneyAward="318900" ItemAward="915" ItemNum="1" StorageLV="14"/>
    <Level TaskID="144" TaskName="Lv7 Radar" Comment1="An effective and functional radar is the first line of defense against pesky invaders." Comment2="Upgrade the Radar to Lv7" MetalAward="95437.6" He3Award="84833" MoneyAward="58323" ItemAward="918" ItemNum="1" ShipyardLV="14" RadarLV="6"/>
    <Level TaskID="145" TaskName="Lv8 Command Center" Comment1="The more capable the Commander, the higher their standards. Upgrade your Command Center to attract better candidates for leading your fleets." Comment2="Upgrade the Command Center to Lv8" MetalAward="366480" He3Award="274860" MoneyAward="152700" ItemAward="-1" ComanderCenterLV="7"/>
    <Level TaskID="146" TaskName="Lv15 Ship Factory" Comment1="Upgrade your Ship Factory to produce bigger and more powerful ships." Comment2="Upgrade the Ship Factory to Lv15" MetalAward="159450" He3Award="126231" MoneyAward="73081" ItemAward="904" ItemNum="1"/>
    <Level TaskID="147" TaskName="Lv8 Weapon Research Ctr" Comment1="Under-researched weaponry is like an unsharpened blade - dull and utterly useless. Invest in your Weapon Research Center to always keep your offensive force at its best!" Comment2="Upgrade the Weapon Research Ctr to Lv8" MetalAward="305400" He3Award="183240" MoneyAward="137430" ItemAward="924" ItemNum="1" WeaponResearchLV="7"/>
    <Level TaskID="148" TaskName="Lv7 Recycling Plant" Comment1="Used and outdated ships must not go to waste. Take them to the Recycling Plant to keep your planet green and reclaim some resources." Comment2="Upgrade the Recycling Plant to Lv7" MetalAward="113562" He3Award="90850" MoneyAward="62459" ItemAward="-1" ShipReclaimLV="6"/>
    <Level TaskID="149" TaskName="Lv7 Trading" Comment1="As trade and commerce expand, the necessary facilities must keep pace in terms of capabilities and effectiveness." Comment2="Upgrade the Trading Center to Lv7" MetalAward="952595" He3Award="873212" MoneyAward="595372" ItemAward="921" ItemNum="20" TradeLV="6"/>
    <Level TaskID="150" TaskName="Lv7 Alliance Center" Comment1="Alliances must grow over time. As they do, the facilities and management staff must also expand." Comment2="Upgrade the Alliance Center to Lv7" MetalAward="106041" He3Award="84833" MoneyAward="58323" ItemAward="-1" UnionLV="6"/>
    <Level TaskID="151" TaskName="Lv16 Metal Collector" Comment1="Higher level metal collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade a Metal Collector to Lv16" MetalAward="234790" He3Award="197718" MoneyAward="117395" ItemAward="905" ItemNum="1" MetalLV="15"/>
    <Level TaskID="152" TaskName="Lv16 He3 Extractor" Comment1="Higher level He3 collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade an He3 Extractor to Lv16" MetalAward="210075" He3Award="261976" MoneyAward="105037" ItemAward="906" ItemNum="1" He3LV="15"/>
    <Level TaskID="153" TaskName="Lv16 Residential Area" Comment1="Higher level residential areas have higher yield and provide greater morale for your people. It is essential for the expansion of your base." Comment2="Upgrade a Residential Area to Lv16" MetalAward="192775" He3Award="177946.4" MoneyAward="80323" ItemAward="907" ItemNum="1" ResidentialLV="15"/>
    <Level TaskID="154" TaskName="Lv8 Technology Center" Comment1="Increase the level of your Technology Center to boost research speed and keep you on the forefront of the latest scientific trends." Comment2="Upgrade the Technology Center to Lv8" MetalAward="274860" He3Award="256536" MoneyAward="198510" ItemAward="-1" TechCenterLV="7"/>
    <Level TaskID="155" TaskName="Lv16 Resource Warehouse" Comment1="To better facilitate the process of storing and maintaining resources, central management must first be at its best, and a higher level Resource Warehouse is a mandatory requirement." Comment2="Upgrade the Resource Warehouse to Lv16" MetalAward="939162" He3Award="914447" MoneyAward="593154" ItemAward="-1" StorageLV="15"/>
    <Level TaskID="156" TaskName="Lv16 Ship Factory" Comment1="Upgrade your Ship Factory to produce bigger and more powerful ships." Comment2="Upgrade the Ship Factory to Lv16" MetalAward="296577" He3Award="234790" MoneyAward="135931" ItemAward="-1" ShipyardLV="15"/>
    <Level TaskID="157" TaskName="Lv9 Civic Center" Comment1="Colonial management is the key to further development." Comment2="Upgrade the Civic Center to Lv9" MetalAward="1251630" He3Award="1092331" MoneyAward="682707" ItemAward="900" ItemNum="1" CityCenterLV="8"/>
    <Level TaskID="158" TaskName="Lv17 Metal Collector" Comment1="Higher level metal collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade a Metal Collector to Lv17" MetalAward="329293.5" He3Award="277299.9" MoneyAward="164646" ItemAward="-1" MetalLV="16"/>
    <Level TaskID="159" TaskName="Lv17 He3 Extractor" Comment1="Higher level He3 collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade an He3 Extractor to Lv17" MetalAward="294631.2" He3Award="367422.3" MoneyAward="147315" ItemAward="-1" He3LV="16"/>
    <Level TaskID="160" TaskName="Lv17 Residential Area" Comment1="Higher level residential areas have higher yield and provide greater morale for your people. It is essential for the expansion of your base." Comment2="Upgrade a Residential Area to Lv17" MetalAward="270367.5" He3Award="249570" MoneyAward="112653" ItemAward="912" ItemNum="1" ResidentialLV="16"/>
    <Level TaskID="161" TaskName="Lv17 Resource Warehouse" Comment1="To better facilitate the process of storing and maintaining resources, central management must first be at its best, and a higher level Resource Warehouse is a mandatory requirement." Comment2="Upgrade the Resource Warehouse to Lv17" MetalAward="1317174.6" He3Award="1282512" MoneyAward="831899" ItemAward="915" ItemNum="1" StorageLV="16"/>
    <Level TaskID="162" TaskName="Lv8 Radar" Comment1="An effective and functional radar is the first line of defense against pesky invaders." Comment2="Upgrade the Radar to Lv8" MetalAward="206145" He3Award="183240" MoneyAward="125977" ItemAward="918" ItemNum="1" ShipyardLV="16" RadarLV="7"/>
    <Level TaskID="163" TaskName="Lv9 Command Center" Comment1="The more capable the Commander, the higher their standards. Upgrade your Command Center to attract better candidates for leading your fleets." Comment2="Upgrade the Command Center to Lv9" MetalAward="794345.7" He3Award="595759" MoneyAward="330977" ItemAward="-1" ComanderCenterLV="8"/>
    <Level TaskID="164" TaskName="Lv17 Ship Factory" Comment1="Upgrade your Ship Factory to produce bigger and more powerful ships." Comment2="Upgrade the Ship Factory to Lv17" MetalAward="415950" He3Award="329293" MoneyAward="190643" ItemAward="924" ItemNum="1"/>
    <Level TaskID="165" TaskName="Lv9 Weapon Research Ctr" Comment1="Under-researched weaponry is like an unsharpened blade - dull and utterly useless. Invest in your Weapon Research Center to always keep your offensive force at its best!" Comment2="Upgrade the Weapon Research Center to Lv9" MetalAward="661954.8" He3Award="397172" MoneyAward="297879" ItemAward="-1" WeaponResearchLV="8"/>
    <Level TaskID="166" TaskName="Lv8 Recycling Plant" Comment1="Used and outdated ships must not go to waste. Take them to the Recycling Plant to keep your planet green and reclaim some resources." Comment2="Upgrade the Recycling Plant to Lv8" MetalAward="245294.7" He3Award="196235" MoneyAward="134912" ItemAward="904" ItemNum="1" ShipReclaimLV="7"/>
    <Level TaskID="167" TaskName="Lv8 Trading" Comment1="As trade and commerce expand, the necessary facilities must keep pace in terms of capabilities and effectiveness." Comment2="Upgrade the Trading Center to Lv8" MetalAward="2557718.4" He3Award="2344575" MoneyAward="1598574" ItemAward="921" ItemNum="20" TradeLV="7"/>
    <Level TaskID="168" TaskName="Lv8 Alliance Center" Comment1="Alliances must grow over time. As they do, the facilities and management staff must also expand." Comment2="Upgrade the Alliance Center to Lv8" MetalAward="229050" He3Award="183240" MoneyAward="125977" ItemAward="-1" UnionLV="7"/>
    <Level TaskID="169" TaskName="Lv18 Metal Collector" Comment1="Higher level metal collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade a Metal Collector to Lv18" MetalAward="619071.9" He3Award="521323" MoneyAward="309535" ItemAward="905" ItemNum="1" MetalLV="17"/>
    <Level TaskID="170" TaskName="Lv18 He3 Extractor" Comment1="Higher level He3 collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade an He3 Extractor to Lv18" MetalAward="553906.5" He3Award="690754" MoneyAward="276953" ItemAward="906" ItemNum="1" He3LV="17"/>
    <Level TaskID="171" TaskName="Lv18 Residential Area" Comment1="Higher level residential areas have higher yield and provide greater morale for your people. It is essential for the expansion of your base." Comment2="Upgrade a Residential Area to Lv18" MetalAward="508290.6" He3Award="469191" MoneyAward="211787" ItemAward="907" ItemNum="1" ResidentialLV="17"/>
    <Level TaskID="172" TaskName="Lv9 Technology Center" Comment1="Increase the level of your Technology Center to boost research speed and keep you on the forefront of the latest scientific trends." Comment2="Upgrade the Technology Center to Lv9" MetalAward="595759.2" He3Award="556041" MoneyAward="430270" ItemAward="-1" TechCenterLV="8"/>
    <Level TaskID="173" TaskName="Lv18 Resource Warehouse" Comment1="To better facilitate the process of storing and maintaining resources, central management must first be at its best, and a higher level Resource Warehouse is a mandatory requirement." Comment2="Upgrade the Resource Warehouse to Lv18" MetalAward="2476288.2" He3Award="2411122" MoneyAward="1563971" ItemAward="-1" StorageLV="17"/>
    <Level TaskID="174" TaskName="Lv18 Ship Factory" Comment1="Upgrade your Ship Factory to produce bigger and more powerful ships." Comment2="Upgrade the Ship Factory to Lv18" MetalAward="781985.7" He3Award="619071" MoneyAward="358410" ItemAward="-1" ShipyardLV="17"/>
    <Level TaskID="175" TaskName="Lv10 Civic Center" Comment1="Colonial management is the key to further development." Comment2="Upgrade the Civic Center to Lv10" MetalAward="3880052" He3Award="3386227" MoneyAward="2116392" ItemAward="923" ItemNum="1" CityCenterLV="9"/>
    <Level TaskID="176" TaskName="Lv19 Metal Collector" Comment1="Higher level metal collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade a Metal Collector to Lv19" MetalAward="1170046" He3Award="985302" MoneyAward="585023" ItemAward="-1" MetalLV="18"/>
    <Level TaskID="177" TaskName="Lv19 He3 Extractor" Comment1="Higher level He3 collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade an He3 Extractor to Lv19" MetalAward="1046883" He3Award="1305525" MoneyAward="523441" ItemAward="904" ItemNum="1" He3LV="18"/>
    <Level TaskID="178" TaskName="Lv19 Residential Area" Comment1="Higher level residential areas have higher yield and provide greater morale for your people. It is essential for the expansion of your base." Comment2="Upgrade a Residential Area to Lv19" MetalAward="960669" He3Award="886771" MoneyAward="400278" ItemAward="912" ItemNum="1" ResidentialLV="18"/>
    <Level TaskID="179" TaskName="Lv19 Resource Warehouse" Comment1="To better facilitate the process of storing and maintaining resources, central management must first be at its best, and a higher level Resource Warehouse is a mandatory requirement." Comment2="Upgrade the Resource Warehouse to Lv19" MetalAward="4680184" He3Award="4557021" MoneyAward="2955906" ItemAward="915" ItemNum="1" StorageLV="18"/>
    <Level TaskID="180" TaskName="Lv9 Radar" Comment1="An effective and functional radar is the first line of defense against pesky invaders." Comment2="Upgrade the Radar to Lv9" MetalAward="595759" He3Award="529563" MoneyAward="364075" ItemAward="918" ItemNum="1" ShipyardLV="18" RadarLV="8"/>
    <Level TaskID="181" TaskName="Lv10 Command Center" Comment1="The more capable the Commander, the higher their standards. Upgrade your Command Center to attract better candidates for leading your fleets." Comment2="Upgrade the Command Center to Lv10" MetalAward="2303602" He3Award="1727701" MoneyAward="959834" ItemAward="-1" ComanderCenterLV="9"/>
    <Level TaskID="182" TaskName="Lv19 Ship Factory" Comment1="Upgrade your Ship Factory to produce bigger and more powerful ships." Comment2="Upgrade the Ship Factory to Lv19" MetalAward="1477953" He3Award="1170046" MoneyAward="677395" ItemAward="924" ItemNum="1"/>
    <Level TaskID="183" TaskName="Lv10 Weapon Research Ctr" Comment1="Under-researched weaponry is like an unsharpened blade - dull and utterly useless. Invest in your Weapon Research Center to always keep your offensive force at its best!" Comment2="Upgrade the Weapon Research Ctr to Lv10" MetalAward="1919668" He3Award="1151801" MoneyAward="863850" ItemAward="-1" WeaponResearchLV="9"/>
    <Level TaskID="184" TaskName="Lv9 Recycling Plant" Comment1="Used and outdated ships must not go to waste. Take them to the Recycling Plant to keep your planet green and reclaim some resources." Comment2="Upgrade the Recycling Plant to Lv9" MetalAward="708901" He3Award="567121" MoneyAward="389896" ItemAward="-1" ShipReclaimLV="8"/>
    <Level TaskID="185" TaskName="Lv9 Trading" Comment1="As trade and commerce expand, the necessary facilities must keep pace in terms of capabilities and effectiveness." Comment2="Upgrade the Trading Center to Lv9" MetalAward="9182208" He3Award="8417025" MoneyAward="5738880" ItemAward="921" ItemNum="20" TradeLV="8"/>
    <Level TaskID="186" TaskName="Lv9 Alliance Center" Comment1="Alliances must grow over time. As they do, the facilities and management staff must also expand." Comment2="Upgrade the Alliance Center to Lv9" MetalAward="661954" He3Award="529563" MoneyAward="364075" ItemAward="-1" UnionLV="8"/>
    <Level TaskID="187" TaskName="Lv20 Metal Collector" Comment1="Higher level metal collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade a Metal Collector to Lv20" MetalAward="2223087" He3Award="1872073" MoneyAward="1111543" ItemAward="905" ItemNum="1" MetalLV="19"/>
    <Level TaskID="188" TaskName="Lv20 He3 Extractor" Comment1="Higher level He3 collectors have higher yield and lay the foundation for all future expansions and endeavors." Comment2="Upgrade an He3 Extractor to Lv20" MetalAward="1989078" He3Award="2480497" MoneyAward="994539" ItemAward="906" ItemNum="1" He3LV="19"/>
    <Level TaskID="189" TaskName="Lv20 Residential Area" Comment1="Higher level residential areas have higher yield and provide greater morale for your people. It is essential for the expansion of your base." Comment2="Upgrade a Residential Area to Lv20" MetalAward="1825272" He3Award="1684866" MoneyAward="760530" ItemAward="907" ItemNum="1" ResidentialLV="19"/>
    <Level TaskID="190" TaskName="Lv10 Technology Center" Comment1="Increase the level of your Technology Center to boost research speed and keep you on the forefront of the latest scientific trends." Comment2="Upgrade the Technology Center to Lv10" MetalAward="1727701" He3Award="1612521" MoneyAward="1247784" ItemAward="-1" TechCenterLV="9"/>
    <Level TaskID="191" TaskName="Lv20 Resource Warehouse" Comment1="To better facilitate the process of storing and maintaining resources, central management must first be at its best, and a higher level Resource Warehouse is a mandatory requirement." Comment2="Upgrade the Resource Warehouse to Lv20" MetalAward="8892350" He3Award="8658341" MoneyAward="5616221" ItemAward="926" ItemNum="1" StorageLV="19"/>
    <Level TaskID="192" TaskName="Lv20 Ship Factory" Comment1="Upgrade your Ship Factory to produce bigger and more powerful ships." Comment2="Upgrade the Ship Factory to Lv20" MetalAward="2808110" He3Award="2223087" MoneyAward="1287050" ItemAward="-1" ShipyardLV="19"/>
  </List>
</Task>;
      
      public function GameRes_MainTaskXml()
      {
         super();
      }
   }
}

