package
{
   public class GameRes_DefenceTechXml
   {
      
      public static var data:XML = <DefenceTech Name="防御科技">
  <List GroupID="70" Name="Tecnología de defensa aérea" Comment="Aumenta escudos, estructuras, agilidad, defensa y estabilidad base de las naves; Nivel 1: +2% a escudos, estructuras, agilidad y defensa base de la nave. +5% a la estabilidad base de las naves." Kind="0" Tech="" ImageFileName="Tech70" Title="0/2" TechMemo="">
    <Level1 GroupLV="1" Comment="Nivel actual: +2% a escudos, estructuras, agilidad y defensa base de las naves. +5% a la estabilidad base de las naves; Siguiente nivel: +5% a escudos, estructuras, agilidad y defensa base de las naves. +10% a la estabilidad base de las naves." Title="1/2" Money="2846 " Time="3240" Shield="0.02" Endure="0.02" Yare="0.02" Defend="0.02" Stability="0.05"/>
    <Level2 GroupLV="2" Comment="Nivel actual: &lt;font color='#00FF00'&gt;+5%&lt;/font&gt; a escudos, estructuras, agilidad y defensa base de las naves. &lt;font color='#00FF00'&gt;+10%&lt;/font&gt; a la estabilidad base de las naves." Title="2" Money="3295 " Time="4343" Shield="0.05" Endure="0.05" Yare="0.05" Defend="0.05" Stability="0.1"/>
  </List>
  <List GroupID="71" Name="Investigación de escudos" Comment="Aumenta los escudos base de las naves; Nivel 1: +1% a los escudos base de las naves." Kind="0" Tech="70:1" ImageFileName="Tech71" Title="0/5" TechMemo="Se necesita Tecnología de defensa aérea nv. 1.">
    <Level1 GroupLV="1" Comment="Nivel actual: aumenta un 1% los escudos base de las naves; Siguiente nivel: +2% a los escudos base de las naves." Title="1/5" Money="10392 " Time="2700" Shield="0.01"/>
    <Level2 GroupLV="2" Comment="Nivel actual: aumenta un 2% los escudos base de las naves; Siguiente nivel: +3% a los escudos base de las naves." Title="2/5" Money="12032 " Time="3619" Shield="0.02"/>
    <Level3 GroupLV="3" Comment="Nivel actual: aumenta un 3% los escudos base de las naves; Siguiente nivel: +4% a los escudos base de las naves." Title="3/5" Money="18407 " Time="8470" Shield="0.03"/>
    <Level4 GroupLV="4" Comment="Nivel actual: aumenta un 4% los escudos base de las naves; Siguiente nivel: +5% a los escudos base de las naves." Title="4/5" Money="28158 " Time="19822" Shield="0.04"/>
    <Level5 GroupLV="5" Comment="Nivel actual: aumenta un &lt;font color='#00FF00'&gt;5%&lt;/font&gt; los escudos base de las naves." Title="5" Money="43076 " Time="46389" Shield="0.05"/>
  </List>
  <List GroupID="72" Name="Tecnología de dispersión de energía" Comment="Permite que los módulos de protección sufran menos daños; Nivel 1: cada módulo de protección sufre -1 de daños." Kind="0" Tech="70:2;71:3" ImageFileName="Tech72" Title="0/3" TechMemo="Se necesitan Tecnología de defensa aérea nv. 2, Investigación de escudos nv. 1.">
    <Level1 GroupLV="1" Comment="Nivel actual: cada módulo de protección sufre -1 de daños; Siguiente nivel: cada módulo de protección sufre -2 de daños." Title="1/3" Money="46765 " Time="10800" Counteract="1"/>
    <Level2 GroupLV="2" Comment="Nivel actual: cada módulo de protección sufre -2 de daños; Siguiente nivel: cada módulo de protección sufre -3 de daños." Title="2/3" Money="54142 " Time="14476" Counteract="2"/>
    <Level3 GroupLV="3" Comment="Nivel actual: cada módulo de protección sufre &lt;font color='#00FF00'&gt;-3&lt;/font&gt; de daños." Title="3" Money="82828 " Time="33879" Counteract="3"/>
  </List>
  <List GroupID="73" Name="Protección reforzada" Comment="Hace que el enemigo tenga menos posibilidades de atravesar un escudo; Nivel 1: reduce un 3% las posibilidades de que el enemigo atraviese un escudo. " Kind="0" Tech="71:5;72:1" ImageFileName="Tech73" Title="0/2" TechMemo="Se necesitan Investigación de escudos nv. 5, Tecnología de dispersión de energía nv. 1.">
    <Level1 GroupLV="1" Comment="Nivel actual: reduce un 3% las posibilidades de que el enemigo atraviese un escudo; Siguiente nivel: reduce un 7% las posibilidades de que el enemigo atraviese un escudo." Title="1/2" Money="117576 " Time="21600" CounteractCross="0.03"/>
    <Level2 GroupLV="2" Comment="Nivel actual: reduce un &lt;font color='#00FF00'&gt;7%&lt;/font&gt; las posibilidades de que el enemigo atraviese un escudo." Title="2" Money="136122 " Time="28952" CounteractCross="0.07"/>
  </List>
  <List GroupID="74" Name="Aumentar escudo" Comment="Aumenta los escudos base de las naves; Nivel 1: +6% a los escudos base de las naves." Kind="0" Tech="72:2;73:1" ImageFileName="Tech74" Title="0/3" TechMemo="Se necesitan Tecnología de dispersión de energía nv. 2, Protección reforzada nv. 1.">
    <Level1 GroupLV="1" Comment="Nivel actual: aumenta un 6% los escudos base de las naves; Siguiente nivel: +13% a los escudos base de las naves." Title="1/3" Money="248747 " Time="39600" Shield="0.06"/>
    <Level2 GroupLV="2" Comment="Nivel actual: aumenta un 13% los escudos base de las naves; Siguiente nivel: +20% a los escudos base de las naves." Title="2/3" Money="287983 " Time="53078" Shield="0.13"/>
    <Level3 GroupLV="3" Comment="Nivel actual: aumenta un &lt;font color='#00FF00'&gt;20%&lt;/font&gt; los escudos base de las naves." Title="3" Money="440562 " Time="124221" Shield="0.2"/>
  </List>
  <List GroupID="75" Name="Reparación" Comment="Permite a las naves restaurar los Escudos por 30% al principio de cada ronda, si existe  un módulo equipado que restaura Escudos. Tambien aumenta la posibilidad de intercepción del módulo antiaéreo por 1%. Acumulable con Habilidades de Comandante. " Kind="0" Tech="72:3;74:2" ImageFileName="Tech75" Title="0/2" TechMemo="Se necesitan Tecnología de dispersión de energía nv. 3, Aumentar escudo nv. 2.">
    <Level1 GroupLV="1" Comment="Permite a las naves restaurar los Escudos por 30% al principio de cada ronda, si existe un módulo equipado que restaura Escudos. Tambien aumenta la posibilidad de intercepción del módulo antiaéreo por 1%. Acumulable con Habilidades de Comandante. Nivel Siguiente: Permite a las naves restaurar los Escudos por 60% al principio de cada ronda, si existe un módulo equipado que restaura Escudos. Tambien aumenta la posibilidad de intercepción del módulo antiaéreo por 2%. Acumulable con Habilidades de Comandante." Title="1/2" Money="540000 " Time="90000" RepairShieldBout="0.3" Intercept="0.01"/>
    <Level2 GroupLV="2" Comment="Permite a las naves restaurar &lt;font color='#00FF00'&gt;60%&lt;/font&gt;， mas Escudos al principio de cada ronda, si existe un módulo equipado que restaura Escudos. Tambien aumenta la posibilidad de intercepción del módulo antiaéreo por &lt;font color='#00FF00'&gt;+2%&lt;/font&gt;. Acumulable con Habilidades de Comandante. " Title="2" Money="625178 " Time="120632" RepairShieldBout="0.6" Intercept="0.02"/>
  </List>
  <List GroupID="76" Name="Aumentar absorción" Comment="Permite que los módulos de protección sufran menos daños; Nivel 1: cada módulo de protección sufre -2 de daños." Kind="0" Tech="71:5;72:1" ImageFileName="Tech76" Title="0/2" TechMemo="Se necesitan Investigación de escudos nv. 5, Tecnología de dispersión de energía nv. 1.">
    <Level1 GroupLV="1" Comment="Nivel actual: cada módulo de protección sufre -2 de daños; Siguiente nivel: cada módulo de protección sufre -5 de daños." Title="1/2" Money="117576 " Time="21600" Counteract="2"/>
    <Level2 GroupLV="2" Comment="Nivel actual: cada módulo de protección sufre &lt;font color='#00FF00'&gt;-5&lt;/font&gt; de daños." Title="2" Money="136122 " Time="28952" Counteract="5"/>
  </List>
  <List GroupID="77" Name="Conservación de energía" Comment="Permite que los módulos absorban daños sin usar He3; Nivel 1: +3% de posibilidades de absorber daños sin usar He3." Kind="0" Tech="72:2;76:1" ImageFileName="Tech77" Title="0/3" TechMemo="Se necesitan Tecnología de dispersión de energía nv. 2, Aumentar absorción nv. 1.">
    <Level1 GroupLV="1" Comment="Nivel actual: +3% de posibilidades de absorber daños sin usar He3; Siguiente nivel: +6% de posibilidades de absorber daños sin usar He3." Title="1/3" Money="248747 " Time="39600" NoConsumeHe3="0.03"/>
    <Level2 GroupLV="2" Comment="Nivel actual: +6% de posibilidades de absorber daños sin usar He3; Siguiente nivel: +10% de posibilidades de absorber daños sin usar He3." Title="2/3" Money="287983 " Time="53078" NoConsumeHe3="0.06"/>
    <Level3 GroupLV="3" Comment="Nivel actual: &lt;font color='#00FF00'&gt;+10%&lt;/font&gt; de posibilidades de absorber daños sin usar He3." Title="3" Money="440562 " Time="124221" NoConsumeHe3="0.1"/>
  </List>
  <List GroupID="78" Name="Barrera electrónica" Comment="Permite que la flota repela los daños sufridos contra el enemigo antes de que el escudo llegue a 0; Nivel 1: la flota repele un 5% de los daños sufridos contra el enemigo antes de que el escudo llegue a 0." Kind="0" Tech="72:3;77:2" ImageFileName="Tech78" Title="0/2" TechMemo="Se necesitan Tecnología de dispersión de energía nv. 3, Conservación de energía nv. 2.">
    <Level1 GroupLV="1" Comment="Nivel actual: la flota repele un 5% de los daños sufridos contra el enemigo antes de que el escudo llegue a 0; Siguiente nivel: la flota repele un 10% de los daños sufridos contra el enemigo antes de que el escudo llegue a 0." Title="1/2" Money="540000 " Time="90000" Reflex="0.05"/>
    <Level2 GroupLV="2" Comment="Nivel actual: la flota repele un &lt;font color='#00FF00'&gt;10%&lt;/font&gt; de los daños sufridos contra el enemigo antes de que el escudo llegue a 0." Title="2" Money="625178 " Time="120632" Reflex="0.1"/>
  </List>
  <List GroupID="79" Name="Mitigar daños" Comment="Permite que los módulos de protección absorban el doble al estar activados y reduce los daños colaterales de ataques por dispersión o que atraviesen los escudos; Nivel 1: 10% de posibilidades de absorber el doble de daños y 15% de posibilidades de reducir los daños colaterales." Kind="0" Tech="74:3;75:2;77:3;78:2" ImageFileName="Tech79" Title="0/3" TechMemo="Se necesitan Aumentar escudo nv. 3, Reparación nv. 2, Conservación de energía nv. 3, Barrera electrónica nv. 2.">
    <Level1 GroupLV="1" Comment="Nivel actual: 10% de posibilidades de absorber el doble de daños y 15% de posibilidades de reducir los daños colaterales; Siguiente nivel: 20% de posibilidades de absorber el doble de daños y 30% de posibilidades de reducir los daños colaterales." Title="1/3" Money="805152 " Time="108000" Double="0.1" ShieldLowerScattering="0.15"/>
    <Level2 GroupLV="2" Comment="Nivel actual: 20% de posibilidades de absorber el doble de daños y 30% de posibilidades de reducir los daños colaterales; Siguiente nivel: 30% de posibilidades de absorber el doble de daños y 45% de posibilidades de reducir los daños colaterales." Title="2/3" Money="932153 " Time="144758" Double="0.2" ShieldLowerScattering="0.3"/>
    <Level3 GroupLV="3" Comment="Nivel actual: &lt;font color='#00FF00'&gt;30%&lt;/font&gt; de posibilidades de absorber el doble de daños y &lt;font color='#00FF00'&gt;45%&lt;/font&gt; de posibilidades de reducir los daños colaterales." Title="3" Money="1426024 " Time="338783" Double="0.3" ShieldLowerScattering="0.45"/>
  </List>
  <List GroupID="80" Name="Análisis estructural de naves" Comment="Aumenta la estructura base de las naves; Nivel 1: +1% a la estructura base de las naves." Kind="0" Tech="70:1" ImageFileName="Tech80" Title="0/5" TechMemo="Se necesita Tecnología de defensa aérea nv. 1.">
    <Level1 GroupLV="1" Comment="Nivel actual: aumenta un 1% la estructura base de las naves; Siguiente nivel: +2% a la estructura base de las naves." Title="1/5" Money="10392 " Time="2700" Endure="0.01"/>
    <Level2 GroupLV="2" Comment="Nivel actual: aumenta un 2% la estructura base de las naves; Siguiente nivel: +3% a la estructura base de las naves." Title="2/5" Money="12032 " Time="3619" Endure="0.02"/>
    <Level3 GroupLV="3" Comment="Nivel actual: aumenta un 3% la estructura base de las naves; Siguiente nivel: +4% a la estructura base de las naves." Title="3/5" Money="18407 " Time="8470" Endure="0.03"/>
    <Level4 GroupLV="4" Comment="Nivel actual: aumenta un 4% la estructura base de las naves; Siguiente nivel: +5% a la estructura base de las naves." Title="4/5" Money="28158 " Time="19822" Endure="0.04"/>
    <Level5 GroupLV="5" Comment="Nivel actual: aumenta un &lt;font color='#00FF00'&gt;5%&lt;/font&gt; la estructura base de las naves." Title="5" Money="43076 " Time="46389" Endure="0.05"/>
  </List>
  <List GroupID="81" Name="Tecnología de refuerzo de naves" Comment="Aumenta la estabilidad de la nave; Nivel 1: aumenta un 8% la estabilidad de la nave." Kind="0" Tech="70:2;80:3" ImageFileName="Tech81" Title="0/3" TechMemo="Se necesitan Tecnología de defensa aérea nv. 2, Análisis estructural de naves nv. 3.">
    <Level1 GroupLV="1" Comment="Nivel actual: aumenta un 8% la estabilidad de la nave; Siguiente nivel: +16% a la estabilidad de la nave." Title="1/3" Money="46765 " Time="10800" Stability="0.08"/>
    <Level2 GroupLV="2" Comment="Nivel actual: aumenta un 16% la estabilidad de la nave; Siguiente nivel: +25% a la estabilidad de la nave." Title="2/3" Money="54142 " Time="14476" Stability="0.16"/>
    <Level3 GroupLV="3" Comment="Nivel actual: aumenta un &lt;font color='#00FF00'&gt;25%&lt;/font&gt; la estabilidad de la nave." Title="3" Money="82828 " Time="33879" Stability="0.25"/>
  </List>
  <List GroupID="82" Name="Resistencia" Comment="Aumenta la agilidad de la flota y reduce los daños por impactos graves provocados por el enemigo; Nivel 1: +5% a la agilidad de la flota y -7% de daños por impactos graves provocados por el enemigo." Kind="0" Tech="80:5;81:1" ImageFileName="Tech82" Title="0/2" TechMemo="Se requieren Análisis estructural de naves nv. 5, Tecnología de refuerzo de naves nv. 1.">
    <Level1 GroupLV="1" Comment="Nivel actual: +5% a la agilidad de la flota y -7% de daños por impactos graves provocados por el enemigo; Siguiente nivel: +10% a la agilidad de la flota y -15% de daños por impactos graves provocados por el enemigo." Title="1/2" Money="117576 " Time="21600" Yare="0.05" LowerBlastHurt="0.07"/>
    <Level2 GroupLV="2" Comment="Nivel actual: &lt;font color='#00FF00'&gt;+10%&lt;/font&gt; a la agilidad de la flota y &lt;font color='#00FF00'&gt;-15%&lt;/font&gt; de daños por impactos graves provocados por el enemigo." Title="2" Money="136122 " Time="28952" Yare="0.1" LowerBlastHurt="0.15"/>
  </List>
  <List GroupID="83" Name="Mejoras estructurales" Comment="Aumenta la estructura base de las naves; Nivel 1: +5% a la estructura base de las naves." Kind="0" Tech="81:2;82:1" ImageFileName="Tech83" Title="0/3" TechMemo="Se necesitan Tecnología de refuerzo de naves nv. 2, Resistencia nv. 1.">
    <Level1 GroupLV="1" Comment="Nivel actual: aumenta un 5% la estructura base de las naves; Siguiente nivel: +10% a la estructura base de las naves." Title="1/3" Money="248747 " Time="39600" Endure="0.05"/>
    <Level2 GroupLV="2" Comment="Nivel actual: aumenta un 10% la estructura base de las naves; Siguiente nivel: +15% a la estructura base de las naves." Title="2/3" Money="287983 " Time="53078" Endure="0.1"/>
    <Level3 GroupLV="3" Comment="Nivel actual: &lt;font color='#00FF00'&gt;+15%&lt;/font&gt; a la estructura base de las naves." Title="3" Money="440562 " Time="124221" Endure="0.15"/>
  </List>
  <List GroupID="84" Name="Tecnología de reparación rápida" Comment="Permite a las naves restaurar las Estructura por 30% al principio de cada ronda, si existe un módulo equipado que restaura Estructura. Tambien aumenta la posibilidad de intercepción del módulo antiaéreo por 1%. Acumulable con Habilidades de Comandante. " Kind="0" Tech="81:3;83:2" ImageFileName="Tech84" Title="0/2" TechMemo="Se necesitan Tecnología de refuerzo de naves nv. 3, Mejoras estructurales nv. 2.">
    <Level1 GroupLV="1" Comment="Permite a las naves restaurar la Estructura por 30% al principio de cada ronda, si existe un módulo equipado que restaura Estructura. Tambien aumenta la posibilidad de intercepción del módulo antiaéreo por 1%. Acumulable con Habilidades de Comandante. Nivel Siguiente: Permite a las naves restaurar los Escudos por 60% al principio de cada ronda, si existe un módulo equipado que restaura Escudos. Tambien aumenta la posibilidad de intercepción del módulo antiaéreo por 2%. Acumulable con Habilidades de Comandante." Title="1/2" Money="540000 " Time="90000" Intercept="0.01" ComebackDurability="0.3"/>
    <Level2 GroupLV="2" Comment="Permite a las naves restaurar &lt;font color='#00FF00'&gt;60%&lt;/font&gt; mas Estructura al principio de cada ronda, si existe un módulo equipado que restaura Estructura. Tambien aumenta la posibilidad de intercepción del módulo antiaéreo por &lt;font color='#00FF00'&gt;+2%&lt;/font&gt;" Title="2" Money="625178 " Time="120632" Intercept="0.02" ComebackDurability="0.6"/>
  </List>
  <List GroupID="85" Name="Mejora para blindaje de reacción" Comment="Permite que el blindaje de reacción sufra menos daños y mejora la estabilidad de la nave; Nivel 1: reduce un 10% los daños sufridos por el blindaje de reacción y aumenta un 10% la estabilidad de la nave." Kind="0" Tech="80:5;81:1" ImageFileName="Tech85" Title="0/2" TechMemo="Se requieren Análisis estructural de naves nv. 5, Tecnología de refuerzo de naves nv. 1.">
    <Level1 GroupLV="1" Comment="Nivel actual: reduce un 10% los daños sufridos por el blindaje de reacción y aumenta un 10% la estabilidad de la nave; Siguiente nivel: reduce un 20% los daños sufridos por el blindaje de reacción y aumenta un 20% la estabilidad de la nave." Title="1/2" Money="117576 " Time="21600" Stability="0.1" HarmReduction="0.1"/>
    <Level2 GroupLV="2" Comment="Nivel actual: reduce un &lt;font color='#00FF00'&gt;20%&lt;/font&gt; los daños sufridos por el blindaje de reacción y aumenta un &lt;font color='#00FF00'&gt;20%&lt;/font&gt; la estabilidad de la nave." Title="2" Money="136122 " Time="28952" Stability="0.2" HarmReduction="0.2"/>
  </List>
  <List GroupID="86" Name="Ampliación defensiva" Comment="Aumenta las defensas de las naves y consigue que los blindajes sufran menos daños; Nivel 1: +5% a la defensa de la nave y -3% de daños sufridos en cualquier blindaje. " Kind="0" Tech="81:2;85:1" ImageFileName="Tech86" Title="0/3" TechMemo="Se necesitan Tecnología de refuerzo de naves nv. 2, Mejora para blindaje de reacción nv. 1.">
    <Level1 GroupLV="1" Comment="Nivel actual: +5% a la defensa de la nave y -3% de daños sufridos en cualquier blindaje; Siguiente nivel: +10% a la defensa de la nave y -6% de daños sufridos en cualquier blindaje." Title="1/3" Money="248747 " Time="39600" Defend="0.05" ArmorHurt="1:0.03;2:0.03;3:0.03;4:0.03;5:0.03;6:0.03"/>
    <Level2 GroupLV="2" Comment="Nivel actual: +10% a la defensa de la nave y -6% de daños sufridos en cualquier blindaje; Siguiente nivel: +15% a la defensa de la nave y -10% de daños sufridos en cualquier blindaje." Title="2/3" Money="287983 " Time="53078" Defend="0.1" ArmorHurt="1:0.06;2:0.06;3:0.06;4:0.06;5:0.06;6:0.06"/>
    <Level3 GroupLV="3" Comment="Nivel actual: &lt;font color='#00FF00'&gt;+15%&lt;/font&gt; a la defensa de la nave y &lt;font color='#00FF00'&gt;-10%&lt;/font&gt; de daños sufridos en cualquier blindaje." Title="3" Money="440562 " Time="124221" Defend="0.15" ArmorHurt="1:0.1;2:0.1;3:0.1;4:0.1;5:0.1;6:0.1"/>
  </List>
  <List GroupID="87" Name="Control de dispersión" Comment="Consigue que los módulos de blindaje se reactiven y repelan daños; Nivel 1: permite que los módulos de blindaje repelan daños 2 rondas después de haberse reactivado." Kind="0" Tech="81:3;86:2" ImageFileName="Tech87" Title="0/2" TechMemo="Se necesitan Tecnología de refuerzo de naves nv. 3, Ampliación defensiva nv. 2.">
    <Level1 GroupLV="1" Comment="Nivel actual: permite que los módulos de blindaje repelan daños 2 rondas después de haberse reactivado; Siguiente nivel: permite que los módulos de blindaje repelan daños 1 ronda después de haberse reactivado." Title="1/2" Money="540000 " Time="90000" CD="2"/>
    <Level2 GroupLV="2" Comment="Nivel actual: permite que los módulos de blindaje repelan daños &lt;font color='#00FF00'&gt;1&lt;/font&gt; ronda después de haberse reactivado." Title="2" Money="625178 " Time="120632" CD="1"/>
  </List>
  <List GroupID="88" Name="Control de estabilidad" Comment="Cuando el Sístema de Control Daedelus es activado por un ataque, este nivel de aptitud da la oportunidad de aumentar estabilidad naval por 100%, reduce el daño sufrido del ataque por 40% y reduce el ataque de impacto grave del enemigo por 5%. Tambien reduce la dispersión y el daño de perforación a la durabilidad de la flota y aumenta la oportunidad de interceptar armas de vuelo; Siguiente Nivel: Provee una oportunidad de 10% de aumentar estabilidad naval por 100%, reduce el daño sufrido del ataque por 40% y reduce el ataque de impacto grave por 5%. Tambien reduce la dispersión y el daño de perforación a la durabilidad de la flota por 5% y aumenta la oportunidad de interceptar armas de vuelo por 2%." Kind="0" Tech="83:3;84:2;86:3;87:2" ImageFileName="Tech88" Title="0/3" TechMemo="Se necesitan Mejoras estructurales nv. 3, Tecnología de reparación rápida nv. 2, Ampliación defensiva nv. 3, Control de dispersión nv. 2.">
    <Level1 GroupLV="1" Comment="Cuando el Sístema de Control Daedelus es activado por un ataque, este nivel de aptitud da una oportunidad de 10% de aumentar estabilidad naval por 100%, reduce el daño sufrido del ataque por 40% y reduce el ataque de impacto grave del enemigo por 5%. Tambien reduce la dispersión y el daño de perforación a la durabilidad de la flota y aumenta la oportunidad de interceptar armas de vuelo; Siguiente Nivel: Provee una oportunidad de 20% de aumentar estabilidad naval por 100%, reduce el daño sufrido del ataque por 40% y reduce el ataque de impacto grave por 5%. Tambien reduce la dispersión y el daño de perforación a la durabilidad de la flota por 10% y aumenta la oportunidad de interceptar armas de vuelo por 4%. " Title="1/3" Money="805152 " Time="108000" Intercept="0.02" LowerBlastHurt="0.05" StabilityOdds="0.1" AugmentStability="1" LowerDamage="0.4" LowerScattering="0.05"/>
    <Level2 GroupLV="2" Comment="Cuando el Sístema de Control Daedelus es activado por un ataque, este nivel de aptitud da una oportunidad de 20% de aumentar estabilidad naval por 100%, reduce el daño sufrido del ataque por 40% y reduce el ataque de impacto grave del enemigo por 5%. Tambien reduce la dispersión y el daño de perforación a la durabilidad de la flota por 10% y aumenta la oportunidad de interceptar armas de vuelo por 4%; Siguiente Nivel: Provee una oportunidad de 30% de aumentar estabilidad naval por 100%, reduce el daño sufrido del ataque por 40% y reduce el ataque de impacto grave por 5%. Tambien reduce la dispersión y el daño de perforación a la durabilidad de la flota por 15% y aumenta la oportunidad de interceptar armas de vuelo por 6%. " Title="2/3" Money="932153 " Time="144758" Intercept="0.04" LowerBlastHurt="0.05" StabilityOdds="0.2" AugmentStability="1" LowerDamage="0.4" LowerScattering="0.1"/>
    <Level3 GroupLV="3" Comment="Cuando el Sístema de Control Daedelus es activado por un ataque, este nivel de aptitud da &lt;font color='#00FF00'&gt;30%&lt;/font&gt; una oportunidad de aumentar estabilidad naval por &lt;font color='#00FF00'&gt;100%&lt;/font&gt;, reduce el daño sufrido del ataque por &lt;font color='#00FF00'&gt;40%&lt;/font&gt; y reduce el ataque de impacto grave del enemigo por &lt;font color='#00FF00'&gt;5%&lt;/font&gt; Tambien reduce la dispersión y el daño de perforación a la durabilidad de la flota por &lt;font color='#00FF00'&gt;15%&lt;/font&gt; y aumenta la oportunidad de interceptar armas de vuelo por &lt;font color='#00FF00'&gt;+6%&lt;/font&gt;. " Title="3" Money="1426024 " Time="338783" Intercept="0.06" LowerBlastHurt="0.05" StabilityOdds="0.3" AugmentStability="1" LowerDamage="0.4" LowerScattering="0.15"/>
  </List>
  <List GroupID="89" Name="Control de energía" Comment="Reduce la cantidad de recursos necesarios para construir instalaciones defensivas; Nivel 1: reduce un 1% la cantidad de recursos necesarios para construir instalaciones defensivas." Kind="1" Tech="" ImageFileName="Tech89" Title="0/10" TechMemo="">
    <Level1 GroupLV="1" Comment="Nivel actual: reduce un 1% la cantidad de recursos necesarios para construir instalaciones defensivas; Siguiente nivel: reduce un 2% la cantidad de recursos necesarios para construir instalaciones defensivas." Title="1/10" Money="2500 " Time="500" DecreaseMetalConsume="1" DecreaseHe3Consume="1" DecreaseMoneyConsume="1"/>
    <Level2 GroupLV="2" Comment="Nivel actual: reduce un 2% la cantidad de recursos necesarios para construir instalaciones defensivas; Siguiente nivel: reduce un 3% la cantidad de recursos necesarios para construir instalaciones defensivas." Title="2/10" Money="5000 " Time="1000" DecreaseMetalConsume="2" DecreaseHe3Consume="2" DecreaseMoneyConsume="2"/>
    <Level3 GroupLV="3" Comment="Nivel actual: reduce un 3% la cantidad de recursos necesarios para construir instalaciones defensivas; Siguiente nivel: reduce un 4% la cantidad de recursos necesarios para construir instalaciones defensivas." Title="3/10" Money="10000 " Time="2000" DecreaseMetalConsume="3" DecreaseHe3Consume="3" DecreaseMoneyConsume="3"/>
    <Level4 GroupLV="4" Comment="Nivel actual: reduce un 4% la cantidad de recursos necesarios para construir instalaciones defensivas; Siguiente nivel: reduce un 5% la cantidad de recursos necesarios para construir instalaciones defensivas." Title="4/10" Money="20000 " Time="4000" DecreaseMetalConsume="4" DecreaseHe3Consume="4" DecreaseMoneyConsume="4"/>
    <Level5 GroupLV="5" Comment="Nivel actual: reduce un 5% la cantidad de recursos necesarios para construir instalaciones defensivas; Siguiente nivel: reduce un 6% la cantidad de recursos necesarios para construir instalaciones defensivas." Title="5/10" Money="40000 " Time="8000" DecreaseMetalConsume="5" DecreaseHe3Consume="5" DecreaseMoneyConsume="5"/>
    <Level6 GroupLV="6" Comment="Nivel actual: reduce un 6% la cantidad de recursos necesarios para construir instalaciones defensivas; Siguiente nivel: reduce un 7% la cantidad de recursos necesarios para construir instalaciones defensivas." Title="6/10" Money="80000 " Time="16000" DecreaseMetalConsume="6" DecreaseHe3Consume="6" DecreaseMoneyConsume="6"/>
    <Level7 GroupLV="7" Comment="Nivel actual: reduce un 7% la cantidad de recursos necesarios para construir instalaciones defensivas; Siguiente nivel: reduce un 8% la cantidad de recursos necesarios para construir instalaciones defensivas." Title="7/10" Money="160000 " Time="32000" DecreaseMetalConsume="7" DecreaseHe3Consume="7" DecreaseMoneyConsume="7"/>
    <Level8 GroupLV="8" Comment="Nivel actual: reduce un 8% la cantidad de recursos necesarios para construir instalaciones defensivas; Siguiente nivel: reduce un 9% la cantidad de recursos necesarios para construir instalaciones defensivas." Title="8/10" Money="320000 " Time="64000" DecreaseMetalConsume="8" DecreaseHe3Consume="8" DecreaseMoneyConsume="8"/>
    <Level9 GroupLV="9" Comment="Nivel actual: reduce un 9% la cantidad de recursos necesarios para construir instalaciones defensivas; Siguiente nivel: reduce un 10% la cantidad de recursos necesarios para construir instalaciones defensivas." Title="9/10" Money="640000 " Time="128000" DecreaseMetalConsume="9" DecreaseHe3Consume="9" DecreaseMoneyConsume="9"/>
    <Level10 GroupLV="10" Comment="Nivel actual: reduce un &lt;font color='#00FF00'&gt;10%&lt;/font&gt; la cantidad de recursos necesarios para construir instalaciones defensivas." Title="10" Money="1280000 " Time="256000" DecreaseMetalConsume="10" DecreaseHe3Consume="10" DecreaseMoneyConsume="10"/>
  </List>
  <List GroupID="90" Name="Construcción de defensas rápida" Comment="Aumenta la velocidad a la que se construyen instalaciones defensivas; Nivel 1: aumenta un 1% la velocidad a la que se construyen instalaciones defensivas." Kind="1" Tech="89:1" ImageFileName="Tech90" Title="0/10" TechMemo="Se necesita Control de energía nv. 1.">
    <Level1 GroupLV="1" Comment="Nivel actual: aumenta un 1% la velocidad a la que se construyen instalaciones defensivas; Siguiente nivel: aumenta un 2% la velocidad a la que se construyen instalaciones defensivas." Title="1/10" Money="3000 " Time="600" IncreaseBuilding="1"/>
    <Level2 GroupLV="2" Comment="Nivel actual: aumenta un 2% la velocidad a la que se construyen instalaciones defensivas; Siguiente nivel: aumenta un 3% la velocidad a la que se construyen instalaciones defensivas." Title="2/10" Money="6000 " Time="1200" IncreaseBuilding="2"/>
    <Level3 GroupLV="3" Comment="Nivel actual: aumenta un 3% la velocidad a la que se construyen instalaciones defensivas; Siguiente nivel: aumenta un 4% la velocidad a la que se construyen instalaciones defensivas." Title="3/10" Money="12000 " Time="2400" IncreaseBuilding="3"/>
    <Level4 GroupLV="4" Comment="Nivel actual: aumenta un 4% la velocidad a la que se construyen instalaciones defensivas; Siguiente nivel: aumenta un 5% la velocidad a la que se construyen instalaciones defensivas." Title="4/10" Money="24000 " Time="4800" IncreaseBuilding="4"/>
    <Level5 GroupLV="5" Comment="Nivel actual: aumenta un 5% la velocidad a la que se construyen instalaciones defensivas; Siguiente nivel: aumenta un 6% la velocidad a la que se construyen instalaciones defensivas." Title="5/10" Money="48000 " Time="9600" IncreaseBuilding="5"/>
    <Level6 GroupLV="6" Comment="Nivel actual: aumenta un 6% la velocidad a la que se construyen instalaciones defensivas; Siguiente nivel: aumenta un 7% la velocidad a la que se construyen instalaciones defensivas." Title="6/10" Money="96000 " Time="19200" IncreaseBuilding="6"/>
    <Level7 GroupLV="7" Comment="Nivel actual: aumenta un 7% la velocidad a la que se construyen instalaciones defensivas; Siguiente nivel: aumenta un 8% la velocidad a la que se construyen instalaciones defensivas." Title="7/10" Money="192000 " Time="38400" IncreaseBuilding="7"/>
    <Level8 GroupLV="8" Comment="Nivel actual: aumenta un 8% la velocidad a la que se construyen instalaciones defensivas; Siguiente nivel: aumenta un 9% la velocidad a la que se construyen instalaciones defensivas." Title="8/10" Money="384000 " Time="76800" IncreaseBuilding="8"/>
    <Level9 GroupLV="9" Comment="Nivel actual: aumenta un 9% la velocidad a la que se construyen instalaciones defensivas; Siguiente nivel: aumenta un 10% la velocidad a la que se construyen instalaciones defensivas." Title="9/10" Money="768000 " Time="153600" IncreaseBuilding="9"/>
    <Level10 GroupLV="10" Comment="Nivel actual: aumenta un &lt;font color='#00FF00'&gt;10%&lt;/font&gt; la velocidad a la que se construyen instalaciones defensivas." Title="10" Money="1536000 " Time="307200" IncreaseBuilding="10"/>
  </List>
  <List GroupID="91" Name="Mejora defensiva" Comment="Aumenta el valor defensivo de todas las instalaciones; Nivel 1: aumenta un 1% el valor defensivo de todas las instalaciones." Kind="1" Tech="89:3;90:3" ImageFileName="Tech91" Title="0/10" TechMemo="Se necesitan Control de energía nv. 3, Construcción de defensas rápida nv. 3.">
    <Level1 GroupLV="1" Comment="Nivel actual: aumenta un 1% el valor defensivo de todas las instalaciones; Siguiente nivel: aumenta un 2% el valor defensivo de todas las instalaciones." Title="1/10" Money="1500 " Time="300" AddDefend="0.01"/>
    <Level2 GroupLV="2" Comment="Nivel actual: aumenta un 2% el valor defensivo de todas las instalaciones; Siguiente nivel: aumenta un 3% el valor defensivo de todas las instalaciones." Title="2/10" Money="3000 " Time="600" AddDefend="0.02"/>
    <Level3 GroupLV="3" Comment="Nivel actual: aumenta un 3% el valor defensivo de todas las instalaciones; Siguiente nivel: aumenta un 4% el valor defensivo de todas las instalaciones." Title="3/10" Money="6000 " Time="1200" AddDefend="0.03"/>
    <Level4 GroupLV="4" Comment="Nivel actual: aumenta un 4% el valor defensivo de todas las instalaciones; Siguiente nivel: aumenta un 5% el valor defensivo de todas las instalaciones." Title="4/10" Money="12000 " Time="2400" AddDefend="0.04"/>
    <Level5 GroupLV="5" Comment="Nivel actual: aumenta un 5% el valor defensivo de todas las instalaciones; Siguiente nivel: aumenta un 6% el valor defensivo de todas las instalaciones." Title="5/10" Money="24000 " Time="4800" AddDefend="0.05"/>
    <Level6 GroupLV="6" Comment="Nivel actual: aumenta un 6% el valor defensivo de todas las instalaciones; Siguiente nivel: aumenta un 7% el valor defensivo de todas las instalaciones." Title="6/10" Money="48000 " Time="9600" AddDefend="0.06"/>
    <Level7 GroupLV="7" Comment="Nivel actual: aumenta un 7% el valor defensivo de todas las instalaciones; Siguiente nivel: aumenta un 8% el valor defensivo de todas las instalaciones." Title="7/10" Money="96000 " Time="19200" AddDefend="0.07"/>
    <Level8 GroupLV="8" Comment="Nivel actual: aumenta un 8% el valor defensivo de todas las instalaciones; Siguiente nivel: aumenta un 9% el valor defensivo de todas las instalaciones." Title="8/10" Money="192000 " Time="38400" AddDefend="0.08"/>
    <Level9 GroupLV="9" Comment="Nivel actual: aumenta un 9% el valor defensivo de todas las instalaciones; Siguiente nivel: aumenta un 10% el valor defensivo de todas las instalaciones." Title="9/10" Money="384000 " Time="76800" AddDefend="0.09"/>
    <Level10 GroupLV="10" Comment="Nivel actual: aumenta un &lt;font color='#00FF00'&gt;10%&lt;/font&gt; el valor defensivo de todas las instalaciones." Title="10" Money="768000 " Time="153600" AddDefend="0.1"/>
  </List>
  <List GroupID="92" Name="Control de emplazamiento" Comment="Aumenta el poder de ataque de todas las instalaciones defensivas; Nivel 1: aumenta un 1% el poder de ataque de todas las instalaciones defensivas." Kind="1" Tech="90:5" ImageFileName="Tech92" Title="0/10" TechMemo="Se necesita Construcción de defensas rápida nv. 5.">
    <Level1 GroupLV="1" Comment="Nivel actual: aumenta un 1% el poder de ataque de todas las instalaciones defensivas; Siguiente nivel: aumenta un 2% el poder de ataque de todas las instalaciones defensivas." Title="1/10" Money="2250 " Time="450" AddAssault="0.01"/>
    <Level2 GroupLV="2" Comment="Nivel actual: aumenta un 2% el poder de ataque de todas las instalaciones defensivas; Siguiente nivel: aumenta un 3% el poder de ataque de todas las instalaciones defensivas; Siguiente nivel:" Title="2/10" Money="4500 " Time="900" AddAssault="0.02"/>
    <Level3 GroupLV="3" Comment="Nivel actual: aumenta un 3% el poder de ataque de todas las instalaciones defensivas; Siguiente nivel: aumenta un 4% el poder de ataque de todas las instalaciones defensivas; Siguiente nivel:" Title="3/10" Money="9000 " Time="1800" AddAssault="0.03"/>
    <Level4 GroupLV="4" Comment="Nivel actual: aumenta un 4% el poder de ataque de todas las instalaciones defensivas; Siguiente nivel: aumenta un 5% el poder de ataque de todas las instalaciones defensivas; Siguiente nivel:" Title="4/10" Money="18000 " Time="3600" AddAssault="0.04"/>
    <Level5 GroupLV="5" Comment="Nivel actual: aumenta un 5% el poder de ataque de todas las instalaciones defensivas; Siguiente nivel: aumenta un 6% el poder de ataque de todas las instalaciones defensivas; Siguiente nivel:" Title="5/10" Money="36000 " Time="7200" AddAssault="0.05"/>
    <Level6 GroupLV="6" Comment="Nivel actual: aumenta un 6% el poder de ataque de todas las instalaciones defensivas; Siguiente nivel: aumenta un 7% el poder de ataque de todas las instalaciones defensivas; Siguiente nivel:" Title="6/10" Money="72000 " Time="14400" AddAssault="0.06"/>
    <Level7 GroupLV="7" Comment="Nivel actual: aumenta un 7% el poder de ataque de todas las instalaciones defensivas; Siguiente nivel: aumenta un 8% el poder de ataque de todas las instalaciones defensivas; Siguiente nivel:" Title="7/10" Money="144000 " Time="28800" AddAssault="0.07"/>
    <Level8 GroupLV="8" Comment="Nivel actual: aumenta un 8% el poder de ataque de todas las instalaciones defensivas; Siguiente nivel: aumenta un 9% el poder de ataque de todas las instalaciones defensivas; Siguiente nivel:" Title="8/10" Money="288000 " Time="57600" AddAssault="0.08"/>
    <Level9 GroupLV="9" Comment="Nivel actual: aumenta un 9% el poder de ataque de todas las instalaciones defensivas; Siguiente nivel: aumenta un 10% el poder de ataque de todas las instalaciones defensivas; Siguiente nivel:" Title="9/10" Money="576000 " Time="115200" AddAssault="0.09"/>
    <Level10 GroupLV="10" Comment="Nivel actual: aumenta un &lt;font color='#00FF00'&gt;10%&lt;/font&gt; el poder de ataque de todas las instalaciones defensivas." Title="10" Money="1152000 " Time="230400" AddAssault="0.1"/>
  </List>
  <List GroupID="93" Name="Construcción de defensas extrema" Comment="Aumenta la cantidad máxima de instalaciones defensivas; Nivel 1: aumenta un 1% la cantidad máxima de instalaciones defensivas." Kind="1" Tech="89:5;91:5;92:3" ImageFileName="Tech93" Title="0/10" TechMemo="Se necesitan Control de energía nv. 5, Mejora defensiva nv. 5, Control de emplazamiento nv. 3.">
    <Level1 GroupLV="1" Comment="Nivel actual: aumenta un 1% la cantidad máxima de instalaciones defensivas; Siguiente nivel: aumenta un 2% la cantidad máxima de instalaciones defensivas." Title="1/10" Money="1750 " Time="350" AddBuiltNum="0.01"/>
    <Level2 GroupLV="2" Comment="Nivel actual: aumenta un 2% la cantidad máxima de instalaciones defensivas; Siguiente nivel: aumenta un 3% la cantidad máxima de instalaciones defensivas." Title="2/10" Money="3500 " Time="700" AddBuiltNum="0.02"/>
    <Level3 GroupLV="3" Comment="Nivel actual: aumenta un 3% la cantidad máxima de instalaciones defensivas; Siguiente nivel: aumenta un 4% la cantidad máxima de instalaciones defensivas." Title="3/10" Money="7000 " Time="1400" AddBuiltNum="0.03"/>
    <Level4 GroupLV="4" Comment="Nivel actual: aumenta un 4% la cantidad máxima de instalaciones defensivas; Siguiente nivel: aumenta un 5% la cantidad máxima de instalaciones defensivas." Title="4/10" Money="14000 " Time="2800" AddBuiltNum="0.04"/>
    <Level5 GroupLV="5" Comment="Nivel actual: aumenta un 5% la cantidad máxima de instalaciones defensivas; Siguiente nivel: aumenta un 6% la cantidad máxima de instalaciones defensivas." Title="5/10" Money="28000 " Time="5600" AddBuiltNum="0.05"/>
    <Level6 GroupLV="6" Comment="Nivel actual: aumenta un 6% la cantidad máxima de instalaciones defensivas; Siguiente nivel: aumenta un 7% la cantidad máxima de instalaciones defensivas." Title="6/10" Money="56000 " Time="11200" AddBuiltNum="0.06"/>
    <Level7 GroupLV="7" Comment="Nivel actual: aumenta un 7% la cantidad máxima de instalaciones defensivas; Siguiente nivel: aumenta un 8% la cantidad máxima de instalaciones defensivas." Title="7/10" Money="112000 " Time="22400" AddBuiltNum="0.07"/>
    <Level8 GroupLV="8" Comment="Nivel actual: aumenta un 8% la cantidad máxima de instalaciones defensivas; Siguiente nivel: aumenta un 9% la cantidad máxima de instalaciones defensivas." Title="8/10" Money="224000 " Time="44800" AddBuiltNum="0.08"/>
    <Level9 GroupLV="9" Comment="Nivel actual: aumenta un 9% la cantidad máxima de instalaciones defensivas; Siguiente nivel: aumenta un 10% la cantidad máxima de instalaciones defensivas." Title="9/10" Money="448000 " Time="89600" AddBuiltNum="0.09"/>
    <Level10 GroupLV="10" Comment="Nivel actual: aumenta un &lt;font color='#00FF00'&gt;10%&lt;/font&gt; la cantidad máxima de instalaciones defensivas." Title="10" Money="896000 " Time="179200" AddBuiltNum="0.1"/>
  </List>
  <List GroupID="94" Name="Ampliación de alcance" Comment="Amplía el radio de alcance de los cañones de partículas y antiaéreos; Nivel 1: suma 1 al radio de alcance de los cañones de partículas y antiaéreos." Kind="1" Tech="90:8;92:5" ImageFileName="Tech94" Title="0/2" TechMemo="Se necesitan Construcción de defensas rápida nv. 8, Control de emplazamiento nv. 5.">
    <Level1 GroupLV="1" Comment="Nivel actual: suma 1 al radio de alcance de los cañones de partículas y antiaéreos; Siguiente nivel: suma 2 al radio de alcance de los cañones de partículas y antiaéreos." Title="1/2" Money="300000 " Time="60000" AddRange="1"/>
    <Level2 GroupLV="2" Comment="Nivel actual: suma &lt;font color='#00FF00'&gt;2&lt;/font&gt; al radio de alcance de los cañones de partículas y antiaéreos." Title="2" Money="600000 " Time="120000" AddRange="2"/>
  </List>
  <List GroupID="95" Name="Construcción de Thor" Comment="Suma 1 a la máxima cantidad de unidades Thor." Kind="1" Tech="89:8;93:5;94:1" ImageFileName="Tech95" Title="0/1" TechMemo="Se necesitan Control de energía nv. 8, Construcción de defensas extrema nv. 5, Ampliación de alcance nv. 1.">
    <Level1 GroupLV="1" Comment="Suma &lt;font color='#00FF00'&gt;1&lt;/font&gt; a la máxima cantidad de unidades Thor." Title="1" Money="800000 " Time="160000" AddThorNum="1"/>
  </List>
  <List GroupID="96" Name="Incremento de propulsión" Comment="Aumenta la velocidad de desplazamiento de todas las naves; Nivel 1: suma 1 a la velocidad de desplazamiento de todas las naves." Kind="1" Tech="92:8;95:1" ImageFileName="Tech96" Title="0/2" TechMemo="Se necesita Control de emplazamiento nv. 8, Construcción de Thor nv. 1.">
    <Level1 GroupLV="1" Comment=" Nivel actual: suma 1 a la velocidad de desplazamiento de todas las naves; Siguiente nivel: suma 2 a la velocidad de desplazamiento de todas las naves." Title="1/2" Money="400000 " Time="80000" AddMove="1"/>
    <Level2 GroupLV="2" Comment="Nivel actual: suma &lt;font color='#00FF00'&gt;2&lt;/font&gt; a la velocidad de desplazamiento de todas las naves." Title="2" Money="900000 " Time="180000" AddMove="2"/>
  </List>
</DefenceTech>;
      
      public function GameRes_DefenceTechXml()
      {
         super();
      }
   }
}

