package
{
   public class GameRes_MainTaskXml
   {
      
      public static var data:XML = <Task Name="主线任务">
  <List TaskClass="0">
    <Level TaskID="0" TaskName="Recolectar recursos" Comment1="Tu planeta abunda en recursos naturales, por lo que un buen comandante debe saber cómo administrar sus reservas.  Cosecha los bienes de tu Almacén de Recursos para crear mas espacio." Comment2="Recolecta los bienes de tu almacén de recursos." MetalAward="450" He3Award="950" MoneyAward="500" CoinsAward="20" ItemAward="921" ItemNum="20" MetalLV="0"/>
    <Level TaskID="119" TaskName="Alto y claro" Comment1="Con las antenas podrás darte a conocer en toda la galaxia a través del chat global del juego. Comunícate para saludar a tus amigos o retar a tus rivales, ¡Tu decides! Haz clic en la ventana de chat de la esquina inferior izquierda y elige Global. Escribe algo y charla con los demás." Comment2="Envía un mensaje en el chat global." MetalAward="460" He3Award="980" MoneyAward="520" ItemAward="-1"/>
    <Level TaskID="4" TaskName="Centro tecnológico (nv. 1)" Comment1="La tecnología conduce al progreso, motivo por el que la sociedad solo avanza investigando nuevas tecnologías. Construye un centro tecnológico y descubre los últimos avances científicos. Haz clic en &lt;a href='event:1'&gt;Tecnología&lt;/a&gt; en la esquina inferior derecha y selecciona &lt;a href='event:2'&gt;Construir instalación&lt;/a&gt;." Comment2="Construye un centro tecnológico." MetalAward="2250" He3Award="2100" MoneyAward="3250" ItemAward="921" ItemNum="20" TechCenterLV="0"/>
    <Level TaskID="111" TaskName="Investigación Tecnológica (nv. 1)" Comment1="Invierte en nuevos avances tecnológicos para desarollar tu base de manera eficiente.  Investiga Construcción Simultanea en tu Centro Tecnológico y aumenta el número de edificios que puedes construir a la vez." Comment2="Descubre Construcción Simultánea." MetalAward="500" He3Award="480" MoneyAward="600" ItemAward="900" ItemNum="1"/>
    <Level TaskID="107" TaskName="Producción de metal" Comment1="El hallazgo y la extracción del metal resultan vitales para establecer los cimientos de un imperio sólido y duradero. Haz clic en &lt;a href='event:1'&gt;Tecnología&lt;/a&gt; en la esquina inferior derecha, selecciona &lt;a href='event:2'&gt;Construir instalación&lt;/a&gt; y luego haz clic en Recursos para crear tu primer extractor de metal. " Comment2="Construye un extractor de metal." MetalAward="425" He3Award="530" MoneyAward="425" ItemAward="829" ItemNum="1"/>
    <Level TaskID="110" TaskName="Planos 1" Comment1="Antes de poder investigar la tecnología de un plano, deberás adquirirlo y usarlo. Haz clic en &lt;a href='event:3'&gt;Mis herramientas&lt;/a&gt; en la esquina inferior derecha, luego en &lt;a href='event:4'&gt;Inventario&lt;/a&gt; y usa el motor de supertransmisión que has adquirido." Comment2="Usa los planos de Motor de supertransmisión." MetalAward="515" He3Award="1190" MoneyAward="575" ItemAward="902" ItemNum="1"/>
    <Level TaskID="115" TaskName="Producción de He3" Comment1="El He3 resulta vital para el continuo desarrollo y avance de tus colonias, así como para construir naves espaciales. Haz clic en &lt;a href='event:1'&gt;Tecnología&lt;/a&gt; en la esquina inferior derecha, selecciona &lt;a href='event:2'&gt;Construir instalación&lt;/a&gt; y luego haz clic en Recursos para crear tu primera refinería de He3. " Comment2="Construye una refinería de He3 (niv. 1)." MetalAward="475" He3Award="400" MoneyAward="475" ItemAward="741" ItemNum="1"/>
    <Level TaskID="118" TaskName="Planos 2" Comment1="Antes de poder investigar la tecnología de un plano, deberás adquirirlo y usarlo. Haz clic en &lt;a href='event:3'&gt;Mis herramientas&lt;/a&gt; en la esquina inferior derecha, luego en &lt;a href='event:4'&gt;Inventario&lt;/a&gt; y usa los planos de la nave Estrella que has adquirido." Comment2="Usa el plano de la nave Estrella." MetalAward="520" He3Award="1150" MoneyAward="585" ItemAward="805" ItemNum="1"/>
    <Level TaskID="116" TaskName="Crear una zona residencial" Comment1="Tu planeta debería acoger una zona residencial agradable que potencie la economía de tus colonias y la producción de oro. Haz clic en &lt;a href='event:1'&gt;Tecnología&lt;/a&gt; en la esquina inferior derecha, selecciona &lt;a href='event:2'&gt;Construir instalación&lt;/a&gt; y luego haz clic en Recursos para crear tu primera zona residencial. " Comment2="Construye una zona residencial." MetalAward="390" He3Award="360" MoneyAward="325" ItemAward="921" ItemNum="20"/>
    <Level TaskID="3" TaskName="Fábrica espacial (nv. 1)" Comment1="Si quieres embarcarte en la conquista del espacio deberás crear una flota a la altura de las circunstancias. Comienza desde lo más básico: haz clic en &lt;a href='event:1'&gt;Tecnología&lt;/a&gt; en la esquina inferior derecha y selecciona &lt;a href='event:2'&gt;Construir instalación&lt;/a&gt;." Comment2="Construye una fábrica espacial." MetalAward="600" He3Award="475" MoneyAward="550" ItemAward="730" ItemNum="1" ShipyardLV="0"/>
    <Level TaskID="17" TaskName="Centro de mando (nv. 1)" Comment1="Incluso los ejércitos más temibles están abocados al fracaso sin un líder competente. Construye un centro de mando para reclutar a nuevos comandantes. Haz clic en &lt;a href='event:1'&gt;Tecnología&lt;/a&gt; en la esquina inferior derecha y selecciona &lt;a href='event:2'&gt;Construir instalación&lt;/a&gt;." Comment2="Construye un centro de mando." MetalAward="3000" He3Award="2250" MoneyAward="2500" ItemAward="812" ItemNum="1" ComanderCenterLV="0"/>
    <Level TaskID="102" TaskName="Reclutar comandantes" Comment1="Un comandante cualificado puede marcar la diferencia entre la victoria y la derrota. Recluta uno en el centro de mando para ampliar el potencial y la habilidad de tu ejército de manera exponencial." Comment2="Recluta un comandante" MetalAward="605" He3Award="1250" MoneyAward="685" ItemAward="903" ItemNum="1"/>
    <Level TaskID="1" TaskName="Diseñar una nave" Comment1="Para construir una nave poderosa, deberás elegir los módulos adecuados. Prueba a construir una nave Estrella con 4 emisores láser compactos y 3 motores de supertransmisión para aumentar su eficacia. Haz clic en &lt;a href='event:5'&gt;Milicia&lt;/a&gt; y luego en &lt;a href='event:6'&gt;Diseñar naves&lt;/a&gt; para comenzar a añadir módulos. Podrás elegir multitud de módulos, así que piénsatelo con calma." Comment2="Diseña una nave." MetalAward="585" He3Award="1235" MoneyAward="650" ItemAward="921" ItemNum="20"/>
    <Level TaskID="2" TaskName="Construir naves" Comment1="Tómate tu tiempo al diseñar cada nave, ya que tus flotas necesitarán que todos sus módulos funcionen a la perfección. Haz clic en Tecnología y luego en Construir nave para crear unidades para tu flota." Comment2="Construye una nave." MetalAward="600" He3Award="1200" MoneyAward="680" ItemAward="824" ItemNum="1"/>
    <Level TaskID="101" TaskName="Construir una flota" Comment1="La unión y coordinación de fuerzas es la clave del éxito. Construye tu primera flota seleccionando Milicia y luego Crear flota. No te olvides de nombrar un comandante al mando." Comment2="Construye una flota." MetalAward="610" He3Award="1300" MoneyAward="690" ItemAward="921" ItemNum="20"/>
    <Level TaskID="117" TaskName="Logística militar" Comment1="Procura siempre abastecer de antemano a todas tus tropas. Incluso la victoria más segura puede acabar en derrota si no preparas adecuadamente a tus flotas para la batalla. Haz clic en &lt;a href='event:5'&gt;Milicia&lt;/a&gt; en la esquina inferior derecha y selecciona &lt;a href='event:13'&gt;Abastecer flota&lt;/a&gt;. Luego haz clic en Añadir todo." Comment2="Abastece las reservas de tu flota." MetalAward="2000" He3Award="3000" MoneyAward="2000" ItemAward="902" ItemNum="1"/>
    <Level TaskID="5" TaskName="Central de armamento (nv. 1)" Comment1="La mejor defensa es un buen ataque, así que procura desarrollar tu armamento investigando nueva tecnología. Haz clic en &lt;a href='event:1'&gt;Tecnología&lt;/a&gt; y luego en &lt;a href='event:2'&gt;Construir instalación&lt;/a&gt; para crear tu central de armamento." Comment2="Construye una central de armamento." MetalAward="2500" He3Award="1500" MoneyAward="2250" ItemAward="782" ItemNum="1" WeaponResearchLV="0"/>
    <Level TaskID="105" TaskName="Mayor inventario" Comment1="A medida que tu planeta prospera, necesitarás mayor espacio en tu inventario para desarrollar todo tu potencial. Selecciona una ranura bloqueada de tu inventario y haz clic en ella para activarla. ¡Merece la pena pagar una pequeña cantidad de oro para disfrutar de mayor espacio!" Comment2="Libera una ranura de espacio de tu inventario." MetalAward="620" He3Award="1310" MoneyAward="700" ItemAward="912" ItemNum="1"/>
    <Level TaskID="108" TaskName="Lote de recursos" Comment1="Los lotes de recursos te proporcionarán metal, oro y He3 para sufragar esos enormes costes. Selecciona el que posees en tu inventario y aumenta tus reservas de recursos." Comment2="Usa un lote de recursos." MetalAward="680" He3Award="1450" MoneyAward="750" ItemAward="923" ItemNum="1"/>
    <Level TaskID="109" TaskName="Producir recursos" Comment1="Aumenta la producción de recursos colocando satélites en tu territorio para reducir costes y volverte autosuficiente. Haz clic en Mis herramientas, Territorio adyacente y luego en Tecnología. Elige uno de los satélites de recursos y colócalo en una zona libre." Comment2="Coloca satélites para producir recursos." MetalAward="700" He3Award="1480" MoneyAward="780" ItemAward="904" ItemNum="1"/>
    <Level TaskID="112" TaskName="Añadir amigos" Comment1="No pierdas la oportunidad de hacer nuevos amigos: gracias a su ayuda podrás prosperar. Haz clic en &lt;a href='event:11'&gt;Social&lt;/a&gt; y elige &lt;a href='event:12'&gt;Rankings&lt;/a&gt;. Luego haz clic en uno de los jugadores y selecciona Añadir como amigo." Comment2="Añade a un amigo en el juego." MetalAward="710" He3Award="1500" MoneyAward="800" ItemAward="-1"/>
    <Level TaskID="113" TaskName="Sistema de correo" Comment1="Mantente en contacto con tus amigos o puede que se olviden de ti cuando verdaderamente los necesites. Haz clic en &lt;a href='event:11'&gt;Social&lt;/a&gt; y elige &lt;a href='event:12'&gt;Rankings&lt;/a&gt;. Luego haz clic en uno de los jugadores y selecciona Correo." Comment2="Envía un correo electrónico." MetalAward="720" He3Award="1520" MoneyAward="820" ItemAward="921" ItemNum="20"/>
    <Level TaskID="114" TaskName="Estación espacial (nv. 2)" Comment1="La estación espacial es el centro neurálgico de tus colonias e infraestructuras. Haz clic en &lt;a href='event:10'&gt;Base espacial&lt;/a&gt; en la parte inferior de la interfaz principal, selecciona tu estación espacial y haz clic en Mejorar." Comment2="Construye una estación espacial de nivel 2." MetalAward="10465" He3Award="9660" MoneyAward="13685" ItemAward="-1"/>
    <Level TaskID="106" TaskName="Defensa espacial 1" Comment1="Para hacer frente a todos tus posibles asaltantes deberás invertir en una fuerte defensa. Haz clic en &lt;a href='event:10'&gt;Base espacial&lt;/a&gt; para comprobar el estado de tu red de defensas y luego selecciona &lt;a href='event:1'&gt;Tecnología&lt;/a&gt;, &lt;a href='event:2'&gt;Construir instalación&lt;/a&gt;, Defensa para proteger tu base con instalaciones defensivas." Comment2="Construye una instalación defensiva." MetalAward="750" He3Award="1600" MoneyAward="880" ItemAward="-1"/>
    <Level TaskID="6" TaskName="Extractor de metal (nv. 2)" Comment1="Aumenta el nivel de tus extractores de metal para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye un extractor de metal de nivel 2." MetalAward="815" He3Award="690" MoneyAward="815" ItemAward="905" ItemNum="1" MetalLV="1"/>
    <Level TaskID="7" TaskName="Refinería de He3 (nv. 2)" Comment1="Aumenta el nivel de tus refinerías de He3 para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye una refinería de He3 de nivel 2." MetalAward="730" He3Award="910" MoneyAward="730" ItemAward="906" ItemNum="1" He3LV="1"/>
    <Level TaskID="8" TaskName="Zona residencial (nv. 2)" Comment1="Las zonas residenciales de mayor nivel producen más y aumentan la moral de la ciudadanía, algo esencial para expandir tu base." Comment2="Construye una zona residencial de nivel 2." MetalAward="670" He3Award="620" MoneyAward="560" ItemAward="907" ItemNum="1" ResidentialLV="1"/>
    <Level TaskID="9" TaskName="Fábrica espacial (nv. 2)" Comment1="Necesitarás mejorar tu fábrica espacial para acelerar la construcción de tus naves." Comment2="Construye una fábrica espacial de nivel 2." MetalAward="1030" He3Award="815" MoneyAward="945" ItemAward="921" ItemNum="20" ShipyardLV="1"/>
    <Level TaskID="10" TaskName="Almacén de recursos (nv. 2)" Comment1="Para facilitar aún más el proceso de almacenamiento y mantenimiento de recursos, debes mantener la gestión central a punto. Un almacén de recursos de mayor nivel es un requisito indispensable para ello." Comment2="Construye un almacén de recursos de nivel 2." MetalAward="3270" He3Award="3180" MoneyAward="4130" ItemAward="-1" StorageLV="1"/>
    <Level TaskID="11" TaskName="Centro cívico (nv. 2)" Comment1="La clave para un próspero desarrollo está en la gestión de tus colonias." Comment2="Construye un centro cívico de nivel 2." MetalAward="6644" He3Award="5800" MoneyAward="7248" CoinsAward="10" ItemAward="902" ItemNum="1" CityCenterLV="1"/>
    <Level TaskID="16" TaskName="Radar (nv. 1)" Comment1="Un radar efectivo y en funcionamiento constituye un eficaz modo de defensa frente a los ataques enemigos." Comment2="Construye un radar." MetalAward="1800" He3Award="1600" MoneyAward="2200" ItemAward="-1" ItemNum="1" RadarLV="0"/>
    <Level TaskID="12" TaskName="Extractor de metal (nv. 3)" Comment1="Aumenta el nivel de tus extractores de metal para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye un extractor de metal de nivel 3." MetalAward="1012" He3Award="1260" MoneyAward="1012" ItemAward="-1" MetalLV="2"/>
    <Level TaskID="13" TaskName="Refinería de He3 (nv. 3)" Comment1="Aumenta el nivel de tus refinerías de He3 para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye una refinería de He3 de nivel 3." MetalAward="1132" He3Award="952" MoneyAward="1132" ItemAward="921" ItemNum="20" He3LV="2"/>
    <Level TaskID="14" TaskName="Zona residencial (nv. 3)" Comment1="Las zonas residenciales de más nivel producen más y aumentan la moral de la ciudadanía, algo esencial para expandir tu base." Comment2="Construye una zona residencial de nivel 3." MetalAward="928" He3Award="856" MoneyAward="772" ItemAward="-1" ResidentialLV="2"/>
    <Level TaskID="15" TaskName="Almacén de recursos (nv. 3)" Comment1="Para facilitar aún más el proceso de almacenamiento y mantenimiento de recursos, debes mantener la gestión central a punto. Un almacén de recursos de mayor nivel es un requisito indispensable para ello." Comment2="Construye un almacén de recursos de nivel 3." MetalAward="5901" He3Award="5748" MoneyAward="7455" ItemAward="908" ItemNum="1" StorageLV="2"/>
    <Level TaskID="18" TaskName="Central de armamento (nv. 2)" Comment1="Tener armamento obsoleto es tan inútil como usar una flecha sin afilar. ¡Invierte en tu central de armamento para mantener tu poder ofensivo siempre en lo más alto!" Comment2="Construye una central de armamento de nivel 2." MetalAward="4230" He3Award="2538" MoneyAward="3807" ItemAward="794" ItemNum="1" WeaponResearchLV="1"/>
    <Level TaskID="19" TaskName="Planta de reciclaje (nv. 1)" Comment1="No desperdicies tus naves usadas y obsoletas: llévalas a la planta de reciclaje para cuidar el medio ambiente y obtener algunos recursos a cambio." Comment2="Construye una planta de reciclaje." MetalAward="2000" He3Award="1600" MoneyAward="2200" ItemAward="-1" ShipReclaimLV="0"/>
    <Level TaskID="20" TaskName="Comercio espacial (nv. 1)" Comment1="En esta galaxia todo tiene un precio o al menos resulta rentable. Construye un Comercio espacial para comprar o poner en venta tus bienes con el resto de comandantes." Comment2="Construye un comercio espacial." MetalAward="4800" He3Award="4400" MoneyAward="6000" ItemAward="-1" TradeLV="0"/>
    <Level TaskID="35" TaskName="Centro de mando (nv. 2)" Comment1="Cuanto más competente sea un comandante, mayores serán sus aptitudes. Mejora el centro de mando para atraer a mejores candidatos para comandar tu flota." Comment2="Construye un centro de mando de nivel 2." MetalAward="6768" He3Award="5076" MoneyAward="5640" ItemAward="903" ItemNum="1" ComanderCenterLV="1"/>
    <Level TaskID="21" TaskName="Centro de federaciones (nv. 1)" Comment1="Los centros de federaciones te permitirán interactuar con otros comandantes y alianzas. Construye uno en tu base para poder unirte a una alianza o crear la tuya propia." Comment2="Construye un centro de federaciones." MetalAward="2000" He3Award="1600" MoneyAward="2200" ItemAward="-1" UnionLV="0"/>
    <Level TaskID="22" TaskName="Extractor de metal (nv. 4)" Comment1="Aumenta el nivel de tus extractores de metal para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye un extractor de metal de nivel 4." MetalAward="1760" He3Award="2196" MoneyAward="1760" ItemAward="-1" MetalLV="3"/>
    <Level TaskID="23" TaskName="Refinería de He3 (nv. 4)" Comment1="Aumenta el nivel de tus refinerías de He3 para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye una refinería de He3 de nivel 4." MetalAward="1968" He3Award="1656" MoneyAward="1968" ItemAward="-1" He3LV="3"/>
    <Level TaskID="24" TaskName="Zona residencial (nv. 4)" Comment1="Las zonas residenciales de más nivel producen más y aumentan la moral de la ciudadanía, algo esencial para expandir tu base." Comment2="Construye una zona residencial de nivel 4." MetalAward="1616" He3Award="1492" MoneyAward="1348" ItemAward="-1" ResidentialLV="3"/>
    <Level TaskID="25" TaskName="Fábrica espacial (nv. 3)" Comment1="Mejora tu fábrica espacial para producir naves mayores y más poderosas." Comment2="Construye una fábrica espacial de nivel 3." MetalAward="1428" He3Award="1132" MoneyAward="1308" ItemAward="921" ItemNum="20" ShipyardLV="2"/>
    <Level TaskID="104" TaskName="Una prueba de valentía" Comment1="Ahora que posees una flota, es hora de ponerla a prueba en una de las misiones disponibles. Por el bien del Consejo Intergaláctico, esperamos que triunfes. Haz clic en tu estación espacial y selecciona Misión. " Comment2="Completa la misión Memorias ancestrales." MetalAward="4400" He3Award="9200" MoneyAward="4900" ItemAward="-1" EctypeID="0"/>
    <Level TaskID="26" TaskName="Centro tecnológico (nv. 2)" Comment1="Mejora tu centro tecnológico para aumentar la velocidad de investigación y mantenerte al tanto de los últimos avances en el mundo de la ciencia." Comment2="Construye un centro tecnológico de nivel 2." MetalAward="5076" He3Award="4736" MoneyAward="7332" ItemAward="902" ItemNum="1" TechCenterLV="1"/>
    <Level TaskID="27" TaskName="Almacén de recursos (nv. 4)" Comment1="Para facilitar aún más el proceso de almacenamiento y mantenimiento de recursos, debes mantener la gestión central a punto. Un almacén de recursos de mayor nivel es un requisito indispensable para ello." Comment2="Construye un almacén de recursos de nivel 4." MetalAward="7868" He3Award="7664" MoneyAward="9940" ItemAward="-1" StorageLV="3"/>
    <Level TaskID="28" TaskName="Fábrica espacial (nv. 4)" Comment1="Mejora tu fábrica espacial para producir naves mayores y más poderosas." Comment2="Construye una fábrica espacial de nivel 4." MetalAward="2484" He3Award="1968" MoneyAward="2280" ItemAward="-1" ShipyardLV="3"/>
    <Level TaskID="29" TaskName="Centro cívico (nv. 3)" Comment1="La clave para un próspero desarrollo está en la gestión de tus colonias." Comment2="Construye un centro cívico de nivel 3." MetalAward="10066" He3Award="8784" MoneyAward="10980" CoinsAward="10" ItemAward="-1" CityCenterLV="2"/>
    <Level TaskID="30" TaskName="Extractor de metal (nv. 5)" Comment1="Aumenta el nivel de tus extractores de metal para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye un extractor de metal de nivel 5." MetalAward="1540" He3Award="1920" MoneyAward="1540" ItemAward="-1" MetalLV="4"/>
    <Level TaskID="31" TaskName="Refinería de He3 (nv. 5)" Comment1="Aumenta el nivel de tus refinerías de He3 para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye una refinería de He3 de nivel 5." MetalAward="1722" He3Award="1450" MoneyAward="1722" ItemAward="-1" He3LV="4"/>
    <Level TaskID="32" TaskName="Zona residencial (nv. 5)" Comment1="Las zonas residenciales de más nivel producen más y aumentan la moral de la ciudadanía, algo esencial para expandir tu base." Comment2="Construye una zona residencial de nivel 5." MetalAward="1414" He3Award="1304" MoneyAward="1178" ItemAward="-1" ResidentialLV="4"/>
    <Level TaskID="33" TaskName="Almacén de recursos (nv. 5)" Comment1="Para facilitar aún más el proceso de almacenamiento y mantenimiento de recursos, debes mantener la gestión central a punto. Un almacén de recursos de mayor nivel es un requisito indispensable para ello." Comment2="Construye un almacén de recursos de nivel 5." MetalAward="6886" He3Award="6704" MoneyAward="8698" ItemAward="921" ItemNum="20" StorageLV="4"/>
    <Level TaskID="34" TaskName="Radar (nv. 2)" Comment1="Un radar efectivo y en funcionamiento constituye un eficaz modo de defensa frente a los ataques enemigos." Comment2="Construye un radar de nivel 2." MetalAward="2538" He3Award="2256" MoneyAward="3102" ItemAward="-1" RadarLV="1"/>
    <Level TaskID="36" TaskName="Central de fusión (nv. 1)" Comment1="De todos es sabido que la mejor forma de obtener nuevos y útiles talentos es fusionando distintos elementos. Construye una central de fusión para combinar las habilidades de tus comandantes y objetos." Comment2="Construye una central de fusión." MetalAward="24" He3Award="200" MoneyAward="20" CoinsAward="10" ItemAward="-1" SynthesisLV="0"/>
    <Level TaskID="54" TaskName="Centro de mando (nv. 3)" Comment1="Cuanto más competente sea un comandante, mayores serán sus aptitudes. Mejora el centro de mando para atraer a mejores candidatos para comandar tu flota." Comment2="Construye un centro de mando de nivel 3." MetalAward="9576" He3Award="7182" MoneyAward="7980" ItemAward="904" ItemNum="1" ComanderCenterLV="2"/>
    <Level TaskID="37" TaskName="Fábrica espacial (nv. 5)" Comment1="Mejora tu fábrica espacial para producir naves mayores y más poderosas." Comment2="Construye una fábrica espacial de nivel 5." MetalAward="2174" He3Award="1722" MoneyAward="1994" ItemAward="-1" ShipyardLV="4"/>
    <Level TaskID="38" TaskName="Central de armamento (nv. 3)" Comment1="Tener armamento obsoleto es tan inútil como usar una flecha sin afilar. ¡Invierte en tu central de armamento para mantener tu poder ofensivo siempre en lo más alto!" Comment2="Construye una central de armamento de nivel 3." MetalAward="7980" He3Award="4788" MoneyAward="7182" ItemAward="-1" WeaponResearchLV="2"/>
    <Level TaskID="39" TaskName="Planta de reciclaje (nv. 2)" Comment1="No desperdicies tus naves usadas y obsoletas: llévalas a la planta de reciclaje para cuidar el medio ambiente y obtener algunos recursos a cambio." Comment2="Construye una planta de reciclaje de nivel 2." MetalAward="3020" He3Award="2416" MoneyAward="3322" ItemAward="923" ItemNum="1" ShipReclaimLV="1"/>
    <Level TaskID="40" TaskName="Comercio espacial (nv. 2)" Comment1="A medida que el comercio se expande, las instalaciones pertinentes han de mantenerse a punto en cuanto a capacidad y efectividad." Comment2="Construye un comercio espacial de nivel 3." MetalAward="8448" He3Award="7744" MoneyAward="10560" ItemAward="-1" TradeLV="1"/>
    <Level TaskID="41" TaskName="Centro de federaciones (nv. 2)" Comment1="Con el paso del tiempo, se hace necesario forjar más alianzas, lo que conlleva una ampliación de las instalaciones y el personal de gestión." Comment2="Construye un centro de federaciones de nivel 2." MetalAward="2820" He3Award="2256" MoneyAward="3102" ItemAward="921" ItemNum="20" UnionLV="1"/>
    <Level TaskID="42" TaskName="Extractor de metal (nv. 6)" Comment1="Aumenta el nivel de tus extractores de metal para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye un extractor de metal de nivel 6." MetalAward="2710" He3Award="3380" MoneyAward="2710" ItemAward="-1" MetalLV="5"/>
    <Level TaskID="43" TaskName="Refinería de He3 (nv. 6)" Comment1="Aumenta el nivel de tus refinerías de He3 para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye una refinería de He3 de nivel 6." MetalAward="3030" He3Award="2552" MoneyAward="3030" ItemAward="-1" He3LV="5"/>
    <Level TaskID="44" TaskName="Zona residencial (nv. 6)" Comment1="Las zonas residenciales de más nivel producen más y aumentan la moral de la ciudadanía, algo esencial para expandir tu base." Comment2="Construye una zona residencial de nivel 6." MetalAward="2488" He3Award="2296" MoneyAward="2074" ItemAward="-1" ResidentialLV="5"/>
    <Level TaskID="45" TaskName="Centro tecnológico (nv. 3)" Comment1="Mejora tu centro tecnológico para aumentar la velocidad de investigación y mantenerte al tanto de los últimos avances en el mundo de la ciencia." Comment2="Construye un centro tecnológico de nivel 3." MetalAward="7182" He3Award="6704" MoneyAward="10374" ItemAward="-1" TechCenterLV="2"/>
    <Level TaskID="46" TaskName="Almacén de recursos (nv. 6)" Comment1="Para facilitar aún más el proceso de almacenamiento y mantenimiento de recursos, debes mantener la gestión central a punto. Un almacén de recursos de mayor nivel es un requisito indispensable para ello." Comment2="Construye un almacén de recursos de nivel 6." MetalAward="12120" He3Award="11800" MoneyAward="15308" ItemAward="-1" StorageLV="5"/>
    <Level TaskID="47" TaskName="Fábrica espacial (nv. 6)" Comment1="Mejora tu fábrica espacial para producir naves mayores y más poderosas." Comment2="Construye una fábrica espacial de nivel 6." MetalAward="3828" He3Award="3030" MoneyAward="3508" ItemAward="902" ItemNum="1" ShipyardLV="5"/>
    <Level TaskID="48" TaskName="Centro cívico (nv. 4)" Comment1="La clave para un próspero desarrollo está en la gestión de tus colonias." Comment2="Construye un centro cívico de nivel 4." MetalAward="18360" He3Award="16023.6" MoneyAward="20029.2" CoinsAward="10" ItemAward="921" ItemNum="20" CityCenterLV="3"/>
    <Level TaskID="49" TaskName="Extractor de metal (nv. 7)" Comment1="Aumenta el nivel de tus extractores de metal para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye un extractor de metal de nivel 7." MetalAward="2878.8" He3Award="3590.4" MoneyAward="2878.8" ItemAward="-1" MetalLV="6"/>
    <Level TaskID="50" TaskName="Refinería de He3 (nv. 7)" Comment1="Aumenta el nivel de tus refinerías de He3 para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye una refinería de He3 de nivel 7." MetalAward="3217.2" He3Award="2709.6" MoneyAward="3217.2" ItemAward="-1" He3LV="6"/>
    <Level TaskID="51" TaskName="Zona residencial (nv. 7)" Comment1="Las zonas residenciales de más nivel producen más y aumentan la moral de la ciudadanía, algo esencial para expandir tu base." Comment2="Construye una zona residencial de nivel 7." MetalAward="2642.4" He3Award="2438.4" MoneyAward="2202" ItemAward="912" ItemNum="1" ResidentialLV="6"/>
    <Level TaskID="52" TaskName="Almacén de recursos (nv. 7)" Comment1="Para facilitar aún más el proceso de almacenamiento y mantenimiento de recursos, debes mantener la gestión central a punto. Un almacén de recursos de mayor nivel es un requisito indispensable para ello." Comment2="Construye un almacén de recursos de nivel 7." MetalAward="12871.2" He3Award="12532.8" MoneyAward="16257.6" ItemAward="915" ItemNum="1" StorageLV="6"/>
    <Level TaskID="53" TaskName="Radar (nv. 3)" Comment1="Un radar efectivo y en funcionamiento constituye un eficaz modo de defensa frente a los ataques enemigos." Comment2="Construye un radar de nivel 3." MetalAward="4309.2" He3Award="3830.4" MoneyAward="5266.8" ItemAward="918" ItemNum="1" RadarLV="2"/>
    <Level TaskID="72" TaskName="Centro de mando (nv. 4)" Comment1="Cuanto más competente sea un comandante, mayores serán sus aptitudes. Mejora el centro de mando para atraer a mejores candidatos para comandar tu flota." Comment2="Construye un centro de mando de nivel 4." MetalAward="16318.8" He3Award="12238.8" MoneyAward="13598.4" ItemAward="-1" ComanderCenterLV="3"/>
    <Level TaskID="55" TaskName="Fábrica espacial (nv. 7)" Comment1="Mejora tu fábrica espacial para producir naves mayores y más poderosas." Comment2="Construye una fábrica espacial de nivel 7." MetalAward="4064.4" He3Award="3217.2" MoneyAward="3726" ItemAward="-1" ShipyardLV="6"/>
    <Level TaskID="56" TaskName="Central de armamento (nv. 4)" Comment1="Tener armamento obsoleto es tan inútil como usar una flecha sin afilar. ¡Invierte en tu central de armamento para mantener tu poder ofensivo siempre en lo más alto!" Comment2="Construye una central de armamento de nivel 4." MetalAward="13598.4" He3Award="8158.8" MoneyAward="12238.8" ItemAward="921" ItemNum="20" WeaponResearchLV="3"/>
    <Level TaskID="57" TaskName="Planta de reciclaje (nv. 3)" Comment1="No desperdicies tus naves usadas y obsoletas: llévalas a la planta de reciclaje para cuidar el medio ambiente y obtener algunos recursos a cambio." Comment2="Construye una planta de reciclaje de nivel 3." MetalAward="5127.6" He3Award="4102.8" MoneyAward="5641.2" ItemAward="-1" ShipReclaimLV="2"/>
    <Level TaskID="58" TaskName="Comercio espacial (nv. 3)" Comment1="A medida que el comercio se expande, las instalaciones pertinentes han de mantenerse a punto en cuanto a capacidad y efectividad." Comment2="Construye un comercio espacial de nivel 3." MetalAward="17893.2" He3Award="16401.6" MoneyAward="22365.6" ItemAward="-1" TradeLV="2"/>
    <Level TaskID="59" TaskName="Centro de federaciones (nv. 3)" Comment1="Con el paso del tiempo, se hace necesario forjar nuevas alianzas, lo que conlleva una ampliación de las instalaciones y del personal de gestión." Comment2="Construye un centro de federaciones de nivel 3." MetalAward="4788" He3Award="3830.4" MoneyAward="5266.8" ItemAward="-1" UnionLV="2"/>
    <Level TaskID="60" TaskName="Extractor de metal (nv. 8)" Comment1="Aumenta el nivel de tus extractores de metal para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye un extractor de metal de nivel 8." MetalAward="5125.2" He3Award="6391.2" MoneyAward="5125.2" ItemAward="912" ItemNum="1" MetalLV="7"/>
    <Level TaskID="61" TaskName="Refinería de He3 (nv. 8)" Comment1="Aumenta el nivel de tus refinerías de He3 para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye una refinería de He3 de nivel 8." MetalAward="5727.6" He3Award="4822.8" MoneyAward="5727.6" ItemAward="915" ItemNum="1" He3LV="7"/>
    <Level TaskID="62" TaskName="Zona residencial (nv. 8)" Comment1="Las zonas residenciales de más nivel producen más y aumentan la moral de la ciudadanía, algo esencial para expandir tu base." Comment2="Construye una zona residencial de nivel 8." MetalAward="4702.8" He3Award="4340.4" MoneyAward="3919.2" ItemAward="918" ItemNum="1" ResidentialLV="7"/>
    <Level TaskID="63" TaskName="Centro tecnológico (nv. 4)" Comment1="Mejora tu centro tecnológico para aumentar la velocidad de investigación y mantenerte al tanto de los últimos avances en el mundo de la ciencia." Comment2="Construye un centro tecnológico de nivel 4." MetalAward="12238.8" He3Award="11422.8" MoneyAward="17678.4" ItemAward="-1" TechCenterLV="3"/>
    <Level TaskID="64" TaskName="Almacén de recursos (nv. 8)" Comment1="Para facilitar aún más el proceso de almacenamiento y mantenimiento de recursos, debes mantener la gestión central a punto. Un almacén de recursos de mayor nivel es un requisito indispensable para ello." Comment2="Construye un almacén de recursos de nivel 8." MetalAward="22910.4" He3Award="22308" MoneyAward="28939.2" ItemAward="-1" StorageLV="7"/>
    <Level TaskID="65" TaskName="Fábrica espacial (nv. 8)" Comment1="Mejora tu fábrica espacial para producir naves mayores y más poderosas." Comment2="Construye una fábrica espacial de nivel 8." MetalAward="7234.8" He3Award="5727.6" MoneyAward="6632.4" ItemAward="-1" ShipyardLV="7"/>
    <Level TaskID="66" TaskName="Centro cívico (nv. 5)" Comment1="La clave para un próspero desarrollo está en la gestión de tus colonias." Comment2="Construye un centro cívico de nivel 5." MetalAward="37331.2" He3Award="32580" MoneyAward="40725.6" CoinsAward="10" ItemAward="901" ItemNum="1" CityCenterLV="4"/>
    <Level TaskID="67" TaskName="Extractor de metal (nv. 9)" Comment1="Aumenta el nivel de tus extractores de metal para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye un extractor de metal de nivel 9." MetalAward="6115.2" He3Award="7626.4" MoneyAward="6115.2" ItemAward="-1" MetalLV="8"/>
    <Level TaskID="68" TaskName="Refinería de He3 (nv. 9)" Comment1="Aumenta el nivel de tus refinerías de He3 para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye una refinería de He3 de nivel 9." MetalAward="6835.2" He3Award="5756" MoneyAward="6835.2" ItemAward="904" ItemNum="1" He3LV="8"/>
    <Level TaskID="69" TaskName="Zona residencial (nv. 9)" Comment1="Las zonas residenciales de más nivel producen más y aumentan la moral de la ciudadanía, algo esencial para expandir tu base." Comment2="Construye una zona residencial de nivel 9." MetalAward="5612" He3Award="5180" MoneyAward="4676.8" ItemAward="-1" ResidentialLV="8"/>
    <Level TaskID="70" TaskName="Almacén de recursos (nv. 9)" Comment1="Para facilitar aún más el proceso de almacenamiento y mantenimiento de recursos, debes mantener la gestión central a punto. Un almacén de recursos de mayor nivel es un requisito indispensable para ello." Comment2="Construye un almacén de recursos de nivel 9." MetalAward="27340" He3Award="26620" MoneyAward="34534.4" ItemAward="912" ItemNum="1" StorageLV="8"/>
    <Level TaskID="71" TaskName="Radar (nv. 4)" Comment1="Un radar efectivo y en funcionamiento constituye un eficaz modo de defensa frente a los ataques enemigos." Comment2="Construye un radar de nivel 4." MetalAward="8159.2" He3Award="7252.8" MoneyAward="9972.8" ItemAward="915" ItemNum="1" RadarLV="3"/>
    <Level TaskID="89" TaskName="Centro de mando (nv. 5)" Comment1="Cuanto más competente sea un comandante, mayores serán sus aptitudes. Mejora el centro de mando para atraer a mejores candidatos para comandar tu flota." Comment2="Construye un centro de mando de nivel 5." MetalAward="31005.6" He3Award="23254.4" MoneyAward="25837.6" ItemAward="918" ItemNum="1" ComanderCenterLV="4"/>
    <Level TaskID="73" TaskName="Fábrica espacial (nv. 9)" Comment1="Mejora tu fábrica espacial para producir naves mayores y más poderosas." Comment2="Construye una fábrica espacial de nivel 9." MetalAward="8633.6" He3Award="6835.2" MoneyAward="7914.4" ItemAward="-1" ShipyardLV="8"/>
    <Level TaskID="103" TaskName="Central de armamento (nv. 5)" Comment1="Tener armamento obsoleto es tan inútil como usar una flecha sin afilar. ¡Invierte en tu central de armamento para mantener tu poder ofensivo siempre en lo más alto!" Comment2="Construye una central de armamento de nivel 5." MetalAward="25837.6" He3Award="15502.4" MoneyAward="23254.4" ItemAward="-1" WeaponResearchLV="4"/>
    <Level TaskID="74" TaskName="Planta de reciclaje (nv. 4)" Comment1="No desperdicies tus naves usadas y obsoletas: llévalas a la planta de reciclaje para cuidar el medio ambiente y obtener algunos recursos a cambio." Comment2="Construye una planta de reciclaje de nivel 4." MetalAward="9708.8" He3Award="7767.2" MoneyAward="10680" ItemAward="921" ItemNum="20" ShipReclaimLV="3"/>
    <Level TaskID="75" TaskName="Comercio espacial (nv. 4)" Comment1="A medida que el comercio se expande, las instalaciones pertinentes han de mantenerse a punto en cuanto a capacidad y efectividad." Comment2="Construye un comercio espacial de nivel 4." MetalAward="42227.2" He3Award="38708" MoneyAward="52784" ItemAward="-1" TradeLV="3"/>
    <Level TaskID="76" TaskName="Centro de federaciones (nv. 4)" Comment1="Con el paso del tiempo, se hace necesario forjar nuevas alianzas, lo que conlleva una ampliación de las instalaciones y del personal de gestión." Comment2="Construye un centro de federaciones de nivel 4." MetalAward="9065.6" He3Award="7252.8" MoneyAward="9972.8" ItemAward="-1" UnionLV="3"/>
    <Level TaskID="77" TaskName="Extractor de metal (nv. 10)" Comment1="Aumenta el nivel de tus extractores de metal para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye un extractor de metal de nivel 10." MetalAward="11008" He3Award="13727.2" MoneyAward="11008" ItemAward="912" ItemNum="1" MetalLV="9"/>
    <Level TaskID="78" TaskName="Refinería de He3 (nv. 10)" Comment1="Aumenta el nivel de tus refinerías de He3 para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye una refinería de He3 de nivel 10." MetalAward="12303.2" He3Award="10360" MoneyAward="12303.2" ItemAward="915" ItemNum="1" He3LV="9"/>
    <Level TaskID="79" TaskName="Zona residencial (nv. 10)" Comment1="Las zonas residenciales de más nivel producen más y aumentan la moral de la ciudadanía, algo esencial para expandir tu base." Comment2="Construye una zona residencial de nivel 10." MetalAward="10101.6" He3Award="9324" MoneyAward="8417.6" ItemAward="918" ItemNum="1" ResidentialLV="9"/>
    <Level TaskID="80" TaskName="Centro tecnológico (nv. 5)" Comment1="Mejora tu centro tecnológico para aumentar la velocidad de investigación y mantenerte al tanto de los últimos avances en el mundo de la ciencia." Comment2="Construye un centro tecnológico de nivel 5." MetalAward="23254.4" He3Award="21704" MoneyAward="33589.6" ItemAward="-1" TechCenterLV="4"/>
    <Level TaskID="81" TaskName="Almacén de recursos (nv. 10)" Comment1="Para facilitar aún más el proceso de almacenamiento y mantenimiento de recursos, debes mantener la gestión central a punto. Un almacén de recursos de mayor nivel es un requisito indispensable para ello." Comment2="Construye un almacén de recursos de nivel 10." MetalAward="49211.2" He3Award="47916.8" MoneyAward="62161.6" ItemAward="-1" StorageLV="9"/>
    <Level TaskID="82" TaskName="Fábrica espacial (nv. 10)" Comment1="Mejora tu fábrica espacial para producir naves mayores y más poderosas." Comment2="Construye una fábrica espacial de nivel 10." MetalAward="15540.8" He3Award="12303.2" MoneyAward="14245.6" ItemAward="-1" ShipyardLV="9"/>
    <Level TaskID="83" TaskName="Centro cívico (nv. 6)" Comment1="La clave para un próspero desarrollo está en la gestión de tus colonias." Comment2="Construye un centro cívico de nivel 6." MetalAward="59973.06" He3Award="52339.98" MoneyAward="65425.08" ItemAward="902" ItemNum="1" CityCenterLV="5"/>
    <Level TaskID="84" TaskName="Extractor de metal (nv. 11)" Comment1="Aumenta el nivel de tus extractores de metal para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye un extractor de metal de nivel 11." MetalAward="10460.1" He3Award="13044.36" MoneyAward="10460.1" ItemAward="905" ItemNum="1" MetalLV="10"/>
    <Level TaskID="85" TaskName="Refinería de He3 (nv. 11)" Comment1="Aumenta el nivel de tus refinerías de He3 para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye una refinería de He3 de nivel 11." MetalAward="11690.7" He3Award="9844.8" MoneyAward="11690.7" ItemAward="906" ItemNum="1" He3LV="10"/>
    <Level TaskID="86" TaskName="Zona residencial (nv. 11)" Comment1="Las zonas residenciales de más nivel producen más y aumentan la moral de la ciudadanía, algo esencial para expandir tu base." Comment2="Construye una zona residencial de nivel 11." MetalAward="9598.68" He3Award="8860.32" MoneyAward="7998.9" ItemAward="907" ItemNum="1" ResidentialLV="10"/>
    <Level TaskID="87" TaskName="Almacén de recursos (nv. 11)" Comment1="Para facilitar aún más el proceso de almacenamiento y mantenimiento de recursos, debes mantener la gestión central a punto. Un almacén de recursos de mayor nivel es un requisito indispensable para ello." Comment2="Construye un almacén de recursos de nivel 11." MetalAward="46763.22" He3Award="45532.62" MoneyAward="59069.22" ItemAward="912" ItemNum="1" StorageLV="10"/>
    <Level TaskID="88" TaskName="Radar (nv. 5)" Comment1="Un radar efectivo y en funcionamiento constituye un eficaz modo de defensa frente a los ataques enemigos." Comment2="Construye un radar de nivel 5." MetalAward="12208.56" He3Award="10851.96" MoneyAward="14921.34" ItemAward="915" ItemNum="1" RadarLV="4"/>
    <Level TaskID="120" TaskName="Centro de mando (nv. 6)" Comment1="Cuanto más competente sea un comandante, mayores serán sus aptitudes. Mejora el centro de mando para atraer a mejores candidatos para comandar tu flota." Comment2="Construye un centro de mando de nivel 6." MetalAward="46554.9" He3Award="34916.28" MoneyAward="38795.82" ItemAward="918" ItemNum="1" ComanderCenterLV="5"/>
    <Level TaskID="90" TaskName="Fábrica espacial (nv. 11)" Comment1="Mejora tu fábrica espacial para producir naves mayores y más poderosas." Comment2="Construye una fábrica espacial de nivel 11." MetalAward="14767.2" He3Award="11690.7" MoneyAward="13536.6" ItemAward="918" ItemNum="1" ShipyardLV="10"/>
    <Level TaskID="91" TaskName="Central de armamento (nv. 6)" Comment1="Tener armamento obsoleto es tan inútil como usar una flecha sin afilar. ¡Invierte en tu central de armamento para mantener tu poder ofensivo siempre en lo más alto!" Comment2="Construye una central de armamento de nivel 6." MetalAward="38795.82" He3Award="23277.24" MoneyAward="34916.28" ItemAward="-1" WeaponResearchLV="5"/>
    <Level TaskID="92" TaskName="Planta de reciclaje (nv. 5)" Comment1="No desperdicies tus naves usadas y obsoletas: llévalas a la planta de reciclaje para cuidar el medio ambiente y obtener algunos recursos a cambio." Comment2="Construye una planta de reciclaje de nivel 5." MetalAward="14526.96" He3Award="11621.4" MoneyAward="15979.74" ItemAward="900" ItemNum="1" ShipReclaimLV="4"/>
    <Level TaskID="93" TaskName="Comercio espacial (nv. 5)" Comment1="A medida que el comercio se expande, las instalaciones pertinentes han de mantenerse a punto en cuanto a capacidad y efectividad." Comment2="Construye un comercio espacial de nivel 5." MetalAward="78700.86" He3Award="72142.56" MoneyAward="98376.18" ItemAward="-1" TradeLV="4"/>
    <Level TaskID="94" TaskName="Centro de federaciones (nv. 5)" Comment1="Con el paso del tiempo, se hace necesario forjar nuevas alianzas, lo que conlleva una ampliación de las instalaciones y del personal de gestión." Comment2="Construye un centro de federaciones de nivel 5." MetalAward="13564.74" He3Award="10851.96" MoneyAward="14921.34" ItemAward="921" ItemNum="20" UnionLV="4"/>
    <Level TaskID="95" TaskName="Extractor de metal (nv. 12)" Comment1="Aumenta el nivel de tus extractores de metal para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye un extractor de metal de nivel 12." MetalAward="19037.76" He3Award="23740.92" MoneyAward="19037.76" ItemAward="-1" MetalLV="11"/>
    <Level TaskID="96" TaskName="Refinería de He3 (nv. 12)" Comment1="Aumenta el nivel de tus refinerías de He3 para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye una refinería de He3 de nivel 12." MetalAward="21277.2" He3Award="17917.62" MoneyAward="21277.2" ItemAward="925" ItemNum="1" He3LV="11"/>
    <Level TaskID="97" TaskName="Zona residencial (nv. 12)" Comment1="Las zonas residenciales de más nivel producen más y aumentan la moral de la ciudadanía, algo esencial para expandir tu base." Comment2="Construye una zona residencial de nivel 12." MetalAward="17469.9" He3Award="16125.9" MoneyAward="14558.04" ItemAward="-1" ResidentialLV="11"/>
    <Level TaskID="98" TaskName="Centro tecnológico (nv. 6)" Comment1="Mejora tu centro tecnológico para aumentar la velocidad de investigación y mantenerte al tanto de los últimos avances en el mundo de la ciencia." Comment2="Construye un centro tecnológico de nivel 6." MetalAward="34916.28" He3Award="32588.22" MoneyAward="50434.44" ItemAward="924" ItemNum="1" TechCenterLV="5"/>
    <Level TaskID="99" TaskName="Almacén de recursos (nv. 12)" Comment1="Para facilitar aún más el proceso de almacenamiento y mantenimiento de recursos, debes mantener la gestión central a punto. Un almacén de recursos de mayor nivel es un requisito indispensable para ello." Comment2="Construye un almacén de recursos de nivel 12." MetalAward="85109.22" He3Award="82869.36" MoneyAward="107506.14" ItemAward="904" ItemNum="1" StorageLV="11"/>
    <Level TaskID="100" TaskName="Fábrica espacial (nv. 12)" Comment1="Mejora tu fábrica espacial para producir naves mayores y más poderosas." Comment2="Construye una fábrica espacial de nivel 12." MetalAward="26876.64" He3Award="21277.2" MoneyAward="24636.78" ItemAward="-1" ShipyardLV="11"/>
    <Level TaskID="121" TaskName="Centro cívico (nv. 7)" Comment1="La clave para un próspero desarrollo está en la gestión de tus colonias." Comment2="Construye un centro cívico de nivel 7." MetalAward="219187" He3Award="191291" MoneyAward="119556" ItemAward="923" ItemNum="1" CityCenterLV="6"/>
    <Level TaskID="122" TaskName="Extractor de metal (nv. 13)" Comment1="Aumenta el nivel de tus extractores de metal para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye un extractor de metal de nivel 13." MetalAward="41474" He3Award="51721" MoneyAward="20737" ItemAward="-1" MetalLV="12"/>
    <Level TaskID="123" TaskName="Refinería de He3 (nv. 13)" Comment1="Aumenta el nivel de tus refinerías de He3 para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye una refinería de He3 de nivel 13." MetalAward="46354" He3Award="39035" MoneyAward="23177" ItemAward="-1" He3LV="12"/>
    <Level TaskID="124" TaskName="Zona residencial (nv. 13)" Comment1="Las zonas residenciales de más nivel producen más y aumentan la moral de la ciudadanía, algo esencial para expandir tu base." Comment2="Construye una zona residencial de nivel 13." MetalAward="38059" He3Award="35131" MoneyAward="15858" ItemAward="912" ItemNum="1" ResidentialLV="12"/>
    <Level TaskID="125" TaskName="Almacén de recursos (nv. 13)" Comment1="Para facilitar aún más el proceso de almacenamiento y mantenimiento de recursos, debes mantener la gestión central a punto. Un almacén de recursos de mayor nivel es un requisito indispensable para ello." Comment2="Construye un almacén de recursos de nivel 13." MetalAward="185416" He3Award="180537" MoneyAward="117105" ItemAward="915" ItemNum="1" StorageLV="12"/>
    <Level TaskID="126" TaskName="Radar (nv. 6)" Comment1="Un radar efectivo y en funcionamiento constituye un eficaz modo de defensa frente a los ataques enemigos." Comment2="Construye un radar de nivel 6." MetalAward="41567" He3Award="36948" MoneyAward="25402" ItemAward="918" ItemNum="1" RadarLV="5"/>
    <Level TaskID="127" TaskName="Centro de mando (nv. 7)" Comment1="Cuanto más competente sea un comandante, mayores serán sus aptitudes. Mejora el centro de mando para atraer a mejores candidatos para comandar tu flota." Comment2="Construye un centro de mando de nivel 7." MetalAward="159062" He3Award="119297" MoneyAward="66276" ItemAward="903" ItemNum="1" ComanderCenterLV="6"/>
    <Level TaskID="128" TaskName="Fábrica espacial (nv. 13)" Comment1="Mejora tu fábrica espacial para producir naves mayores y más poderosas." Comment2="Construye una fábrica espacial de nivel 13." MetalAward="58552" He3Award="46354" MoneyAward="26836" ItemAward="904" ItemNum="1" ShipyardLV="12"/>
    <Level TaskID="129" TaskName="Central de armamento (nv. 7)" Comment1="Tener armamento obsoleto es tan inútil como usar una flecha sin afilar. ¡Invierte en tu central de armamento para mantener tu poder ofensivo siempre en lo más alto!" Comment2="Construye una central de armamento de nivel 7." MetalAward="132552" He3Award="79531" MoneyAward="59648" ItemAward="-1" WeaponResearchLV="6"/>
    <Level TaskID="130" TaskName="Planta de reciclaje (nv. 6)" Comment1="No desperdicies tus naves usadas y obsoletas: llévalas a la planta de reciclaje para cuidar el medio ambiente y obtener algunos recursos a cambio." Comment2="Construye una planta de reciclaje de nivel 6." MetalAward="49461" He3Award="39569" MoneyAward="27203" ItemAward="-1" ShipReclaimLV="5"/>
    <Level TaskID="131" TaskName="Comercio espacial (nv. 6)" Comment1="A medida que el comercio se expande, las instalaciones pertinentes han de mantenerse a punto en cuanto a capacidad y efectividad." Comment2="Construye un comercio espacial de nivel 6." MetalAward="333542" He3Award="305746" MoneyAward="208463" ItemAward="921" ItemNum="20" TradeLV="5"/>
    <Level TaskID="132" TaskName="Centro de federaciones (nv. 6)" Comment1="Con el paso del tiempo, se hace necesario forjar nuevas alianzas, lo que conlleva una ampliación de las instalaciones y del personal de gestión." Comment2="Construye un centro de federaciones de nivel 6." MetalAward="46185" He3Award="36948" MoneyAward="25402" ItemAward="-1" UnionLV="5"/>
    <Level TaskID="133" TaskName="Extractor de metal (nv. 14)" Comment1="Aumenta el nivel de tus extractores de metal para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye un extractor de metal de nivel 14." MetalAward="85291" He3Award="71824" MoneyAward="42645" ItemAward="905" ItemNum="1" MetalLV="13"/>
    <Level TaskID="134" TaskName="Refinería de He3 (nv. 14)" Comment1="Aumenta el nivel de tus refinerías de He3 para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye una refinería de He3 de nivel 14." MetalAward="76313" He3Award="95167" MoneyAward="38156" ItemAward="906" ItemNum="1" He3LV="13"/>
    <Level TaskID="135" TaskName="Zona residencial (nv. 14)" Comment1="Las zonas residenciales de más nivel producen más y aumentan la moral de la ciudadanía, algo esencial para expandir tu base." Comment2="Construye una zona residencial de nivel 14." MetalAward="70029" He3Award="64642" MoneyAward="29178" ItemAward="907" ItemNum="1" ResidentialLV="13"/>
    <Level TaskID="136" TaskName="Centro tecnológico (nv. 7)" Comment1="Mejora tu centro tecnológico para aumentar la velocidad de investigación y mantenerte al tanto de los últimos avances en el mundo de la ciencia." Comment2="Construye un centro tecnológico de nivel 7." MetalAward="119297" He3Award="111344" MoneyAward="86159" ItemAward="-1" TechCenterLV="6"/>
    <Level TaskID="137" TaskName="Almacén de recursos (nv. 14)" Comment1="Para facilitar aún más el proceso de almacenamiento y mantenimiento de recursos, debes mantener la gestión central a punto. Un almacén de recursos de mayor nivel es un requisito indispensable para ello." Comment2="Construye un almacén de recursos de nivel 14." MetalAward="341166" He3Award="332188" MoneyAward="215473" ItemAward="-1" StorageLV="13"/>
    <Level TaskID="138" TaskName="Fábrica espacial (nv. 14)" Comment1="Mejora tu fábrica espacial para producir naves mayores y más poderosas." Comment2="Construye una fábrica espacial de nivel 14." MetalAward="107736" He3Award="85291" MoneyAward="49379" ItemAward="-1" ShipyardLV="13"/>
    <Level TaskID="139" TaskName="Centro cívico (nv. 8)" Comment1="La clave para un próspero desarrollo está en la gestión de tus colonias." Comment2="Construye un centro cívico de nivel 8." MetalAward="540077" He3Award="471340" MoneyAward="294587" ItemAward="923" ItemNum="1" CityCenterLV="7"/>
    <Level TaskID="140" TaskName="Extractor de metal (nv. 15)" Comment1="Aumenta el nivel de tus extractores de metal para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye un extractor de metal de nivel 15." MetalAward="112944" He3Award="140847.6" MoneyAward="56472" ItemAward="-1" MetalLV="14"/>
    <Level TaskID="141" TaskName="Refinería de He3 (nv. 15)" Comment1="Aumenta el nivel de tus refinerías de He3 para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye una refinería de He3 de nivel 15." MetalAward="126231" He3Award="106300" MoneyAward="63115" ItemAward="-1" He3LV="14"/>
    <Level TaskID="142" TaskName="Zona residencial (nv. 15)" Comment1="Las zonas residenciales de más nivel producen más y aumentan la moral de la ciudadanía, algo esencial para expandir tu base." Comment2="Construye una zona residencial de nivel 15." MetalAward="103642.8" He3Award="95670" MoneyAward="43184" ItemAward="912" ItemNum="1" ResidentialLV="14"/>
    <Level TaskID="143" TaskName="Almacén de recursos (nv. 15)" Comment1="Para facilitar aún más el proceso de almacenamiento y mantenimiento de recursos, debes mantener la gestión central a punto. Un almacén de recursos de mayor nivel es un requisito indispensable para ello." Comment2="Construye un almacén de recursos de nivel 15." MetalAward="504925" He3Award="491638" MoneyAward="318900" ItemAward="915" ItemNum="1" StorageLV="14"/>
    <Level TaskID="144" TaskName="Radar (nv. 7)" Comment1="Un radar efectivo y en funcionamiento constituye un eficaz modo de defensa frente a los ataques enemigos." Comment2="Construye un radar de nivel 7." MetalAward="95437.6" He3Award="84833" MoneyAward="58323" ItemAward="918" ItemNum="1" ShipyardLV="14" RadarLV="6"/>
    <Level TaskID="145" TaskName="Centro de mando (nv. 8)" Comment1="Cuanto más competente sea un comandante, mayores serán sus aptitudes. Mejora el centro de mando para atraer a mejores candidatos para comandar tu flota." Comment2="Construye un centro de mando de nivel 8." MetalAward="366480" He3Award="274860" MoneyAward="152700" ItemAward="-1" ComanderCenterLV="7"/>
    <Level TaskID="146" TaskName="Fábrica espacial (nv. 15)" Comment1="Mejora tu fábrica espacial para producir naves mayores y más poderosas." Comment2="Construye una fábrica espacial de nivel 15." MetalAward="159450" He3Award="126231" MoneyAward="73081" ItemAward="904" ItemNum="1"/>
    <Level TaskID="147" TaskName="Central de armamento (nv. 8)" Comment1="Tener armamento obsoleto es tan inútil como usar una flecha sin afilar. ¡Invierte en tu central de armamento para mantener tu poder ofensivo siempre en lo más alto!" Comment2="Construye una central de armamento de nivel 8." MetalAward="305400" He3Award="183240" MoneyAward="137430" ItemAward="924" ItemNum="1" WeaponResearchLV="7"/>
    <Level TaskID="148" TaskName="Planta de reciclaje (nv. 7)" Comment1="No desperdicies tus naves usadas y obsoletas: llévalas a la planta de reciclaje para cuidar el medio ambiente y obtener algunos recursos a cambio." Comment2="Construye una planta de reciclaje de nivel 7." MetalAward="113562" He3Award="90850" MoneyAward="62459" ItemAward="-1" ShipReclaimLV="6"/>
    <Level TaskID="149" TaskName="Comercio espacial (nv. 7)" Comment1="A medida que el comercio se expande, las instalaciones pertinentes han de mantenerse a punto en cuanto a capacidad y efectividad." Comment2="Construye un comercio espacial de nivel 7." MetalAward="952595" He3Award="873212" MoneyAward="595372" ItemAward="921" ItemNum="20" TradeLV="6"/>
    <Level TaskID="150" TaskName="Centro de federaciones (nv. 7)" Comment1="Con el paso del tiempo, se hace necesario forjar nuevas alianzas, lo que conlleva una ampliación de las instalaciones y del personal de gestión." Comment2="Construye un centro de federaciones de nivel 7." MetalAward="106041" He3Award="84833" MoneyAward="58323" ItemAward="-1" UnionLV="6"/>
    <Level TaskID="151" TaskName="Extractor de metal (nv. 16)" Comment1="Aumenta el nivel de tus extractores de metal para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye un extractor de metal de nivel 16." MetalAward="234790" He3Award="197718" MoneyAward="117395" ItemAward="905" ItemNum="1" MetalLV="15"/>
    <Level TaskID="152" TaskName="Refinería de He3 (nv. 16)" Comment1="Aumenta el nivel de tus refinerías de He3 para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye una refinería de He3 de nivel 16." MetalAward="210075" He3Award="261976" MoneyAward="105037" ItemAward="906" ItemNum="1" He3LV="15"/>
    <Level TaskID="153" TaskName="Zona residencial (nv. 16)" Comment1="Las zonas residenciales de más nivel producen más y aumentan la moral de la ciudadanía, algo esencial para expandir tu base." Comment2="Construye una zona residencial de nivel 16." MetalAward="192775" He3Award="177946.4" MoneyAward="80323" ItemAward="907" ItemNum="1" ResidentialLV="15"/>
    <Level TaskID="154" TaskName="Centro tecnológico (nv. 8)" Comment1="Mejora tu centro tecnológico para aumentar la velocidad de investigación y mantenerte al tanto de los últimos avances en el mundo de la ciencia." Comment2="Construye un centro tecnológico de nivel 8." MetalAward="274860" He3Award="256536" MoneyAward="198510" ItemAward="-1" TechCenterLV="7"/>
    <Level TaskID="155" TaskName="Almacén de recursos (nv. 16)" Comment1="Para facilitar aún más el proceso de almacenamiento y mantenimiento de recursos, debes mantener la gestión central a punto. Un almacén de recursos de mayor nivel es un requisito indispensable para ello." Comment2="Construye un almacén de recursos de nivel 16." MetalAward="939162" He3Award="914447" MoneyAward="593154" ItemAward="-1" StorageLV="15"/>
    <Level TaskID="156" TaskName="Fábrica espacial (nv. 16)" Comment1="Mejora tu fábrica espacial para producir naves mayores y más poderosas." Comment2="Construye una fábrica espacial de nivel 16." MetalAward="296577" He3Award="234790" MoneyAward="135931" ItemAward="-1" ShipyardLV="15"/>
    <Level TaskID="157" TaskName="Centro cívico (nv. 9)" Comment1="La clave para un próspero desarrollo está en la gestión de tus colonias." Comment2="Construye un centro cívico de nivel 9." MetalAward="1251630" He3Award="1092331" MoneyAward="682707" ItemAward="900" ItemNum="1" CityCenterLV="8"/>
    <Level TaskID="158" TaskName="Extractor de metal (nv. 17)" Comment1="Aumenta el nivel de tus extractores de metal para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye un extractor de metal de nivel 17." MetalAward="329293.5" He3Award="277299.9" MoneyAward="164646" ItemAward="-1" MetalLV="16"/>
    <Level TaskID="159" TaskName="Refinería de He3 (nv. 17)" Comment1="Aumenta el nivel de tus refinerías de He3 para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye una refinería de He3 de nivel 17." MetalAward="294631.2" He3Award="367422.3" MoneyAward="147315" ItemAward="-1" He3LV="16"/>
    <Level TaskID="160" TaskName="Zona residencial (nv. 17)" Comment1="Las zonas residenciales de más nivel producen más y aumentan la moral de la ciudadanía, algo esencial para expandir tu base." Comment2="Construye una zona residencial de nivel 17." MetalAward="270367.5" He3Award="249570" MoneyAward="112653" ItemAward="912" ItemNum="1" ResidentialLV="16"/>
    <Level TaskID="161" TaskName="Almacén de recursos (nv. 17)" Comment1="Para facilitar aún más el proceso de almacenamiento y mantenimiento de recursos, debes mantener la gestión central a punto. Un almacén de recursos de mayor nivel es un requisito indispensable para ello." Comment2="Construye un almacén de recursos de nivel 17." MetalAward="1317174.6" He3Award="1282512" MoneyAward="831899" ItemAward="915" ItemNum="1" StorageLV="16"/>
    <Level TaskID="162" TaskName="Radar (nv. 8)" Comment1="Un radar efectivo y en funcionamiento constituye un eficaz modo de defensa frente a los ataques enemigos." Comment2="Construye un radar de nivel 8." MetalAward="206145" He3Award="183240" MoneyAward="125977" ItemAward="918" ItemNum="1" ShipyardLV="16" RadarLV="7"/>
    <Level TaskID="163" TaskName="Centro de mando (nv. 9)" Comment1="Cuanto más competente sea un comandante, mayores serán sus aptitudes. Mejora el centro de mando para atraer a mejores candidatos para comandar tu flota." Comment2="Construye un centro de mando de nivel 9." MetalAward="794345.7" He3Award="595759" MoneyAward="330977" ItemAward="-1" ComanderCenterLV="8"/>
    <Level TaskID="164" TaskName="Fábrica espacial (nv. 17)" Comment1="Mejora tu fábrica espacial para producir naves mayores y más poderosas." Comment2="Construye una fábrica espacial de nivel 17." MetalAward="415950" He3Award="329293" MoneyAward="190643" ItemAward="924" ItemNum="1"/>
    <Level TaskID="165" TaskName="Central de armamento (nv. 9)" Comment1="Tener armamento obsoleto es tan inútil como usar una flecha sin afilar. ¡Invierte en tu central de armamento para mantener tu poder ofensivo siempre en lo más alto!" Comment2="Construye una central de armamento de nivel 9." MetalAward="661954.8" He3Award="397172" MoneyAward="297879" ItemAward="-1" WeaponResearchLV="8"/>
    <Level TaskID="166" TaskName="Planta de reciclaje (nv. 8)" Comment1="No desperdicies tus naves usadas y obsoletas: llévalas a la planta de reciclaje para cuidar el medio ambiente y obtener algunos recursos a cambio." Comment2="Construye una planta de reciclaje de nivel 8." MetalAward="245294.7" He3Award="196235" MoneyAward="134912" ItemAward="904" ItemNum="1" ShipReclaimLV="7"/>
    <Level TaskID="167" TaskName="Comercio espacial (nv. 8)" Comment1="A medida que el comercio se expande, las instalaciones pertinentes han de mantenerse a punto en cuanto a capacidad y efectividad." Comment2="Construye un comercio espacial de nivel 8." MetalAward="2557718.4" He3Award="2344575" MoneyAward="1598574" ItemAward="921" ItemNum="20" TradeLV="7"/>
    <Level TaskID="168" TaskName="Centro de federaciones (nv. 8)" Comment1="Con el paso del tiempo, se hace necesario forjar nuevas alianzas, lo que conlleva una ampliación de las instalaciones y del personal de gestión." Comment2="Construye un centro de federaciones de nivel 8." MetalAward="229050" He3Award="183240" MoneyAward="125977" ItemAward="-1" UnionLV="7"/>
    <Level TaskID="169" TaskName="Extractor de metal (nv. 18)" Comment1="Aumenta el nivel de tus extractores de metal para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye un extractor de metal de nivel 18." MetalAward="619071.9" He3Award="521323" MoneyAward="309535" ItemAward="905" ItemNum="1" MetalLV="17"/>
    <Level TaskID="170" TaskName="Refinería de He3 (nv. 18)" Comment1="Aumenta el nivel de tus refinerías de He3 para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye una refinería de He3 de nivel 18." MetalAward="553906.5" He3Award="690754" MoneyAward="276953" ItemAward="906" ItemNum="1" He3LV="17"/>
    <Level TaskID="171" TaskName="Zona residencial (nv. 18)" Comment1="Las zonas residenciales de más nivel producen más y aumentan la moral de la ciudadanía, algo esencial para expandir tu base." Comment2="Construye una zona residencial de nivel 18." MetalAward="508290.6" He3Award="469191" MoneyAward="211787" ItemAward="907" ItemNum="1" ResidentialLV="17"/>
    <Level TaskID="172" TaskName="Centro tecnológico (nv. 9)" Comment1="Mejora tu centro tecnológico para aumentar la velocidad de investigación y mantenerte al tanto de los últimos avances en el mundo de la ciencia." Comment2="Construye un centro tecnológico de nivel 9." MetalAward="595759.2" He3Award="556041" MoneyAward="430270" ItemAward="-1" TechCenterLV="8"/>
    <Level TaskID="173" TaskName="Almacén de recursos (nv. 18)" Comment1="Para facilitar aún más el proceso de almacenamiento y mantenimiento de recursos, debes mantener la gestión central a punto. Un almacén de recursos de mayor nivel es un requisito indispensable para ello." Comment2="Construye un almacén de recursos de nivel 18." MetalAward="2476288.2" He3Award="2411122" MoneyAward="1563971" ItemAward="-1" StorageLV="17"/>
    <Level TaskID="174" TaskName="Fábrica espacial (nv. 18)" Comment1="Mejora tu fábrica espacial para producir naves mayores y más poderosas." Comment2="Construye una fábrica espacial de nivel 18." MetalAward="781985.7" He3Award="619071" MoneyAward="358410" ItemAward="-1" ShipyardLV="17"/>
    <Level TaskID="175" TaskName="Centro cívico (nv. 10)" Comment1="La clave para un próspero desarrollo está en la gestión de tus colonias." Comment2="Construye un centro cívico de nivel 10." MetalAward="3880052" He3Award="3386227" MoneyAward="2116392" ItemAward="923" ItemNum="1" CityCenterLV="9"/>
    <Level TaskID="176" TaskName="Extractor de metal (nv. 19)" Comment1="Aumenta el nivel de tus extractores de metal para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye un extractor de metal de nivel 19." MetalAward="1170046" He3Award="985302" MoneyAward="585023" ItemAward="-1" MetalLV="18"/>
    <Level TaskID="177" TaskName="Refinería de He3 (nv. 19)" Comment1="Aumenta el nivel de tus refinerías de He3 para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye una refinería de He3 de nivel 19." MetalAward="1046883" He3Award="1305525" MoneyAward="523441" ItemAward="904" ItemNum="1" He3LV="18"/>
    <Level TaskID="178" TaskName="Zona residencial (nv. 19)" Comment1="Las zonas residenciales de más nivel producen más y aumentan la moral de la ciudadanía, algo esencial para expandir tu base." Comment2="Construye una zona residencial de nivel 19." MetalAward="960669" He3Award="886771" MoneyAward="400278" ItemAward="912" ItemNum="1" ResidentialLV="18"/>
    <Level TaskID="179" TaskName="Almacén de recursos (nv. 19)" Comment1="Para facilitar aún más el proceso de almacenamiento y mantenimiento de recursos, debes mantener la gestión central a punto. Un almacén de recursos de mayor nivel es un requisito indispensable para ello." Comment2="Construye un almacén de recursos de nivel 19." MetalAward="4680184" He3Award="4557021" MoneyAward="2955906" ItemAward="915" ItemNum="1" StorageLV="18"/>
    <Level TaskID="180" TaskName="Radar (nv. 9)" Comment1="Un radar efectivo y en funcionamiento constituye un eficaz modo de defensa frente a los ataques enemigos." Comment2="Construye un radar de nivel 9." MetalAward="595759" He3Award="529563" MoneyAward="364075" ItemAward="918" ItemNum="1" ShipyardLV="18" RadarLV="8"/>
    <Level TaskID="181" TaskName="Centro de mando (nv. 10)" Comment1="Cuanto más competente sea un comandante, mayores serán sus aptitudes. Mejora el centro de mando para atraer a mejores candidatos para comandar tu flota." Comment2="Construye un centro de mando de nivel 10." MetalAward="2303602" He3Award="1727701" MoneyAward="959834" ItemAward="-1" ComanderCenterLV="9"/>
    <Level TaskID="182" TaskName="Fábrica espacial (nv. 19)" Comment1="Mejora tu fábrica espacial para producir naves mayores y más poderosas." Comment2="Construye una fábrica espacial de nivel 19." MetalAward="1477953" He3Award="1170046" MoneyAward="677395" ItemAward="924" ItemNum="1"/>
    <Level TaskID="183" TaskName="Central de armamento (nv. 10)" Comment1="Tener armamento obsoleto es tan inútil como usar una flecha sin afilar. ¡Invierte en tu central de armamento para mantener tu poder ofensivo siempre en lo más alto!" Comment2="Construye una central de armamento de nivel 10." MetalAward="1919668" He3Award="1151801" MoneyAward="863850" ItemAward="-1" WeaponResearchLV="9"/>
    <Level TaskID="184" TaskName="Planta de reciclaje (nv. 9)" Comment1="No desperdicies tus naves usadas y obsoletas: llévalas a la planta de reciclaje para cuidar el medio ambiente y obtener algunos recursos a cambio." Comment2="Construye una planta de reciclaje de nivel 9." MetalAward="708901" He3Award="567121" MoneyAward="389896" ItemAward="-1" ShipReclaimLV="8"/>
    <Level TaskID="185" TaskName="Comercio espacial (nv. 9)" Comment1="A medida que el comercio se expande, las instalaciones pertinentes han de mantenerse a punto en cuanto a capacidad y efectividad." Comment2="Construye un comercio espacial de nivel 9." MetalAward="9182208" He3Award="8417025" MoneyAward="5738880" ItemAward="921" ItemNum="20" TradeLV="8"/>
    <Level TaskID="186" TaskName="Centro de federaciones (nv. 9)" Comment1="Con el paso del tiempo, se hace necesario forjar nuevas alianzas, lo que conlleva una ampliación de las instalaciones y del personal de gestión." Comment2="Construye un centro de federaciones de nivel 9." MetalAward="661954" He3Award="529563" MoneyAward="364075" ItemAward="-1" UnionLV="8"/>
    <Level TaskID="187" TaskName="Extractor de metal (nv. 20)" Comment1="Aumenta el nivel de tus extractores de metal para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye un extractor de metal de nivel 20." MetalAward="2223087" He3Award="1872073" MoneyAward="1111543" ItemAward="905" ItemNum="1" MetalLV="19"/>
    <Level TaskID="188" TaskName="Refinería de He3 (nv. 20)" Comment1="Aumenta el nivel de tus refinerías de He3 para obtener más recursos y sentar las bases para futuras expansiones y aventuras." Comment2="Construye una refinería de He3 de nivel 20." MetalAward="1989078" He3Award="2480497" MoneyAward="994539" ItemAward="906" ItemNum="1" He3LV="19"/>
    <Level TaskID="189" TaskName="Zona residencial (nv. 20)" Comment1="Las zonas residenciales de más nivel producen más y aumentan la moral de la ciudadanía, algo esencial para expandir tu base." Comment2="Construye una zona residencial de nivel 20." MetalAward="1825272" He3Award="1684866" MoneyAward="760530" ItemAward="907" ItemNum="1" ResidentialLV="19"/>
    <Level TaskID="190" TaskName="Centro tecnológico (nv. 10)" Comment1="Mejora tu centro tecnológico para aumentar la velocidad de investigación y mantenerte al tanto de los últimos avances en el mundo de la ciencia." Comment2="Construye un centro tecnológico de nivel 10." MetalAward="1727701" He3Award="1612521" MoneyAward="1247784" ItemAward="-1" TechCenterLV="9"/>
    <Level TaskID="191" TaskName="Almacén de recursos (nv. 20)" Comment1="Para facilitar aún más el proceso de almacenamiento y mantenimiento de recursos, debes mantener la gestión central a punto. Un almacén de recursos de mayor nivel es un requisito indispensable para ello." Comment2="Construye un almacén de recursos de nivel 20." MetalAward="8892350" He3Award="8658341" MoneyAward="5616221" ItemAward="926" ItemNum="1" StorageLV="19"/>
    <Level TaskID="192" TaskName="Fábrica espacial (nv. 20)" Comment1="Mejora tu fábrica espacial para producir naves mayores y más poderosas." Comment2="Construye una fábrica espacial de nivel 20." MetalAward="2808110" He3Award="2223087" MoneyAward="1287050" ItemAward="-1" ShipyardLV="19"/>
  </List>
</Task>;
      
      public function GameRes_MainTaskXml()
      {
         super();
      }
   }
}

