package
{
   public class GameRes_InstanceXml
   {
      
      public static var data:XML = <Instance Name="戰鬥副本" MC="CopydianPlan" LineColor="0x00BFED">
	<Ectype0 ID="1" X="36" Y="30" Name="01. Memorias ancestrales" Repeat="2" Type="3" MaxUser="1" UserTeam="3" NeedID="-1" UserShip="90000" Count="6" EctypeID="0" MaxGate="1" Exp="180" Treasure="1500" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Desde tiempos inmemoriales, los avances tecnológicos han sido un arma de doble filo. Durante miles de años, el planeta Tierra se ha esquilmado hasta agotar sus recursos. Esto ha provocado catastróficos cambios sísmicos que han liberado al Universo una energía primigenia hasta ahora contenida en las entrañas del planeta. De este proceso han surgido temibles campos de fuerza, los agujeros negros, en planetas ricos en minerales y de gran valor estratégico."/>
	<Ectype1 ID="2" X="78" Y="66" Name="02. Zona muerta" Repeat="3" Type="3" MaxUser="1" UserTeam="4" NeedID="0" UserShip="120000" Count="6" EctypeID="1" MaxGate="1" Exp="500" Treasure="1501" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="El planeta R, un lugar cuyos horrores resulta imposible describir con palabras. En cualquier momento, el caos puede desatarse en los campos magnéticos que lo rodean y provocar que las naves en sus proximidades implosionen. Así, flotas enteras desaparecen sin dejar rastro en cuestión de segundos."/>
	<Ectype2 ID="3" X="30" Y="138" Name="03. Valentía" Repeat="3" Type="3" MaxUser="1" UserTeam="4" NeedID="1" UserShip="120000" Count="6" EctypeID="2" MaxGate="1" Exp="1000" Treasure="1502" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Los piratas espaciales han hecho de este planeta su hogar durante décadas pese a sus hostiles condiciones climáticas y abrasadoras arenas. Se trata de luchadores veteranos, conocidos por su resistencia y fiereza. Debes tenerlos bajo tu control si aspiras a adueñarte de la galaxia algún día."/>
	<Ectype3 ID="4" X="96" Y="114" Name="04. Emboscada" Repeat="3" Type="3" MaxUser="1" UserTeam="5" NeedID="2" UserShip="150000" Count="6" EctypeID="3" MaxGate="1" Exp="1540" Treasure="1503" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Permanece alerta y con todo listo para entrar en acción en cualquier momento, pues los piratas son astutos y te superan ampliamente en número. Nuestros recursos se encuentran en peligro en diversas ubicaciones y disminuyen de forma alarmante. Nuestras pérdidas aumentan con enorme rapidez en comparación a nuestros logros. Nos encontramos en una situación desesperada."/>
	<Ectype4 ID="5" X="150" Y="42" Name="05. Autodefensa" Repeat="3" Type="3" MaxUser="1" UserTeam="5" NeedID="3" UserShip="150000" Count="6" EctypeID="4" MaxGate="1" Exp="1820" Treasure="1504" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Este sistema defensivo fue toda una leyenda en su época, pues gozaba de los últimos avances tecnológicos de aquel entonces. Puede que el imperio que albergó haya desaparecido hace tiempo, pero el sistema ha pervivido hasta nuestros días y constituye una formidable barrera con la que disuadir posibles ataques."/>
	<Ectype5 ID="6" X="162" Y="108" Name="06. Hacia la victoria" Repeat="3" Type="3" MaxUser="1" UserTeam="6" NeedID="4" UserShip="180000" Count="6" EctypeID="5" MaxGate="1" Exp="2310" Treasure="1505" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Por norma general, los miembros del Sindicato se relacionan con todo tipo de negocios y acciones ilegales a lo largo y ancho de la galaxia, siempre con objeto de satisfacer sus malvados planes fruto de unas mentes perturbadas. ¿Serás capaz de hacer que todo el peso de la ley caiga sobre ellos?"/>
	<Ectype6 ID="7" X="150" Y="168" Name="07. Aniquilación" Repeat="3" Type="3" MaxUser="1" UserTeam="8" NeedID="5" UserShip="240000" Count="6" EctypeID="6" MaxGate="1" Exp="3220" Treasure="1506" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Bip-bip-bip... Nos está llegando una transmisión en clave. El mensaje descifrado contiene un informe estratégico enviado por exploradores en primera línea de combate. El enemigo planea un ataque y las coordenadas del mismo son..."/>
	<Ectype7 ID="8" X="72" Y="186" Name="08. Odisea" Repeat="3" Type="3" MaxUser="1" UserTeam="8" NeedID="6" UserShip="240000" Count="6" EctypeID="7" MaxGate="1" Exp="4340" Treasure="1507" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Se ha perdido la cuenta de cuántos héroes lo han intentado sin éxito. Los pocos que lo han logrado se marcharon con los bolsillos repletos de riquezas. ¿Vas a convertirte en leyenda o en un mero dato estadístico?"/>
	<Ectype8 ID="9" X="36" Y="258" Name="09. Duelo" Repeat="3" Type="3" MaxUser="1" UserTeam="8" NeedID="7" UserShip="240000" Count="6" EctypeID="8" MaxGate="1" Exp="5250" Treasure="1508" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Los siete líderes supremos de la galaxia están a punto de reunirse para llevar a cabo unas negociaciones interplanetarias. Por desgracia, un conocido grupo terrorista está reuniendo efectivos con la única intención de exterminar a los participantes en esta reunión de paz. Si se salen con la suya, el caos reinará en la galaxia. ¿Podrás detenerlos?"/>
	<Ectype9 ID="10" X="30" Y="324" Name="10. Perdición" Repeat="3" Type="3" MaxUser="1" UserTeam="10" NeedID="8" UserShip="300000" Count="6" EctypeID="9" MaxGate="1" Exp="6300" Treasure="1509" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="En el año 206, una nave de pequeñas dimensiones realizó un aterrizaje de emergencia en un planeta inhabitado con 48 pasajeros a bordo. Sin medios para subsistir o pedir ayuda, dichos pasajeros aguardan su destino final en estas yermas tierras."/>
	<Ectype10 ID="11" X="66" Y="366" Name="11. Edén" Repeat="3" Type="3" MaxUser="1" UserTeam="10" NeedID="9" UserShip="300000" Count="6" EctypeID="10" MaxGate="1" Exp="8400" Treasure="1510" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Nuestros radares han detectado la presencia de una flota desconocida. Tras un análisis inicial, todo apunta a que no vienen en son de paz. Como más vale prevenir que lamentar, ha llegado el momento de prepararse para un enfrentamiento violento. "/>
	<Ectype11 ID="12" X="84" Y="300" Name="12. Vivo o muerto" Repeat="3" Type="3" MaxUser="1" UserTeam="10" NeedID="10" UserShip="300000" Count="6" EctypeID="11" MaxGate="1" Exp="10500" Treasure="1511" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Un peligroso convicto ha logrado escapar de una prisión de máxima seguridad y se cree que se ha aliado con una conocida banda de piratas. Bajo el liderazgo de este criminal, los piratas se han convertido en una fuerza armada sin precedentes dispuesta a sembrar el caos y la inestabilidad en toda la galaxia. Hay que detenerlos."/>
	<Ectype12 ID="13" X="138" Y="348" Name="13. Cementerio espacial" Repeat="3" Type="3" MaxUser="1" UserTeam="10" NeedID="11" UserShip="300000" Count="6" EctypeID="12" MaxGate="1" Exp="14000" Treasure="1512" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Las sombras envuelven este tenebroso paraje repleto de naves abandonadas durante milenios que encuentran su descanso eterno en este lugar prohibido. En este cementerio de titanes hay un perenne halo de muerte y destrucción."/>
	<Ectype12 ID="14" X="204" Y="372" Name="14. R. C. A." Repeat="3" Type="3" MaxUser="1" UserTeam="10" NeedID="12" UserShip="300000" Count="6" EctypeID="13" MaxGate="1" Exp="17500" Treasure="1513" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Todo comandante ha de tomar parte en un enfrentamiento de verdad antes de graduarse en la Academia Castrense Suprema. Este año, el rendimiento en combate afectará a la evaluación general de los comandantes en el momento de su graduación. Los enemigos a los que deberán enfrentarse en la prueba R. C. A. son temibles, ¡así que cuidado!"/>
	<Ectype12 ID="15" X="138" Y="240" Name="15. Vuelo libre" Repeat="3" Type="3" MaxUser="1" UserTeam="12" NeedID="13" UserShip="3000000" Count="6" EctypeID="14" MaxGate="1" Exp="21000" Treasure="1514" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="La historia nos deja asuntos inconclusos. Hace años, un grupo gobernó de forma tiránica la galaxia y, durante este periodo, el yugo de la opresión cayó sobre multitud de ciudadanos. A pesar de que la tiranía es ya cosa del pasado, algunos de estos ciudadanos han intentado aplacar su ira contenida con ataques a flotas en tránsito por la galaxia."/>
	<Ectype12 ID="16" X="210" Y="216" Name="16. Romper el hechizo" Repeat="3" Type="3" MaxUser="1" UserTeam="12" NeedID="14" UserShip="3000000" Count="6" EctypeID="15" MaxGate="1" Exp="24500" Treasure="1515" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="La guerra dividió la galaxia en dos imperios independientes. A caballo entre ambos nos encontramos con multitud de grupos malintencionados que se niegan a ofrecer su lealtad a ninguno de los dos. Es necesario someterlos si queremos unir de nuevo la galaxia."/>
	<Ectype12 ID="17" X="228" Y="156" Name="17. Galaxia de fortuna" Repeat="3" Type="3" MaxUser="1" UserTeam="12" NeedID="15" UserShip="3000000" Count="6" EctypeID="16" MaxGate="1" Exp="28000" Treasure="1516" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Disfruta de una copa de buen vino antes de comenzar esta aventura. Creo que será un viaje fantástico, aunque puede que se presenten peligros desconocidos. Haz lo que esté en tu mano para acabar con tus enemigos."/>
	<Ectype12 ID="18" X="210" Y="84" Name="18. Agujero negro" Repeat="3" Type="3" MaxUser="1" UserTeam="12" NeedID="16" UserShip="3000000" Count="6" EctypeID="17" MaxGate="1" Exp="31500" Treasure="1517" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="La reina Ana lleva desaparecida cinco años. El universo está lleno de misterios: hace cinco años, cuando la reina Ana atravesaba Missipi, este se encogió de repente y se convirtió en un agujero negro que se tragó a la soberana. Este fenómeno sigue siendo a día de hoy un temible misterio."/>
	<Ectype12 ID="19" X="258" Y="36" Name="19. El regreso de la matriz" Repeat="3" Type="3" MaxUser="1" UserTeam="12" NeedID="17" UserShip="3000000" Count="6" EctypeID="18" MaxGate="1" Exp="35000" Treasure="1518" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Cuando el planetoide Yolyano empezó a moverse de forma estable en la órbita lunar, se inició en la galaxia una era de armonía. Sin embargo, Yolyano se desvió de dicha órbita, lo que provocó la aparición de una zona de matriz sinuosa con abundantes recursos. Quien se haga con esta zona acabará irremediablemente por dominar la galaxia."/>
	<Ectype12 ID="20" X="330" Y="30" Name="20. Espiral" Repeat="3" Type="3" MaxUser="1" UserTeam="12" NeedID="18" UserShip="3000000" Count="6" EctypeID="19" MaxGate="1" Exp="38500" Treasure="1519" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="La Zona Z es uno de los misterios de la galaxia. Esta zona alberga multitud de planetas que reflejan la luz del sol la mayor parte del tiempo y, por ello, es en realidad un lugar de aspecto hermoso. Sin embargo, prácticamente todo aquel que se adentra en la Zona Z desaparece sin dejar rastro... ¡Qué lugar tan terrible!"/>
	<Ectype12 ID="21" X="348" Y="66" Name="21. Presteza" Repeat="3" Type="3" MaxUser="1" UserTeam="15" NeedID="19" UserShip="3000000" Count="6" EctypeID="20" MaxGate="1" Exp="42000" Treasure="1520" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Una rápida actuación trae consigo ventajas en cualquier combate. Los piratas Doltt siempre han sido prestos en combate, ¿serás capaz de superarlos?"/>
	<Ectype12 ID="22" X="282" Y="96" Name="22. Encuentro" Repeat="3" Type="3" MaxUser="1" UserTeam="15" NeedID="20" UserShip="3000000" Count="6" EctypeID="21" MaxGate="1" Exp="45500" Treasure="1521" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Ten cuidado con los sanguinarios piratas Selm. No te enfrentes a ellos de forma temeraria y procura mantener la calma cuando te topes con sus naves. "/>
	<Ectype12 ID="23" X="330" Y="132" Name="23. Salvación" Repeat="3" Type="3" MaxUser="1" UserTeam="15" NeedID="21" UserShip="3000000" Count="6" EctypeID="22" MaxGate="1" Exp="49000" Treasure="1522" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Un grupo de expedicionarios ha sufrido un ataque pirata al aproximarse a su planeta base, el planeta X, por lo que se han visto forzados a aterrizar en él. Están agotados, heridos y disponen de poco oxígeno, entre otros problemas. ¡Rescátalos cuanto antes!"/>
	<Ectype12 ID="24" X="276" Y="186" Name="24. Merodeador" Repeat="3" Type="3" MaxUser="1" UserTeam="15" NeedID="22" UserShip="3000000" Count="6" EctypeID="23" MaxGate="1" Exp="52500" Treasure="1523" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Hay muchos piratas astutos que quizás no disponen del armamento más avanzado o no actúan con brutalidad, pero que sí disponen de dispositivos antiradar de vanguardia. Por ello, han conseguido saquear muchas caravanas comerciales. Organiza tus tropas de forma adecuada y acaba con ellos."/>
	<Ectype12 ID="25" X="264" Y="246" Name="25. Enfrentamiento I" Repeat="3" Type="3" MaxUser="1" UserTeam="15" NeedID="23" UserShip="3000000" Count="6" EctypeID="24" MaxGate="1" Exp="56000" Treasure="1524" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="No hay tiempo para seguir reflexionando: nuestras últimas ofensivas contra los piratas les han enojado sobremanera, de modo que hasta han organizado un contraataque a gran escala."/>
	<Ectype12 ID="26" X="210" Y="294" Name="26. Enfrentamiento II" Repeat="3" Type="3" MaxUser="1" UserTeam="15" NeedID="24" UserShip="3000000" Count="6" EctypeID="25" MaxGate="1" Exp="59500" Treasure="1525" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Nuestro último combate se saldó con muchas víctimas en el bando pirata. Ahora están reuniendo fuerzas para proceder al contraataque, de modo que esta vez debemos darles una lección que no olviden. ¡Despliega un ataque y acaba con este molesto tira y afloja cuando antes!"/>
	<Ectype12 ID="27" X="264" Y="354" Name="27. Pacto roto" Repeat="3" Type="3" MaxUser="1" UserTeam="15" NeedID="25" UserShip="3000000" Count="6" EctypeID="26" MaxGate="1" Exp="63000" Treasure="1526" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="El planeta M es rico en recursos que además vende para obtener beneficios. Este planeta ha firmado un pacto con los piratas para evitar que les ataquen a cambio de pagar unas cuotas de protección. Sin embargo, los piratas no cesan de aumentar dichas cuotas anuales, así que entre ambas partes no se produce un acuerdo. Los piratas han capturado ahora al gobernante del planeta M y urge su liberación."/>
	<Ectype12 ID="28" X="324" Y="246" Name="28. Insurrección" Repeat="3" Type="3" MaxUser="1" UserTeam="15" NeedID="26" UserShip="3000000" Count="6" EctypeID="27" MaxGate="1" Exp="66500" Treasure="1527" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Poco a poco, la tribu Tukubu ha dejado atrás la decadencia del pasado siglo para intentar ocupar territorios inhabitados y conseguir así recursos con los que desarrollarse. Por desgracia, desde hace tiempo se encuentran bajo la opresión de los piratas y aún no han reunido fuerzas suficientes para derrotarlos."/>
	<Ectype12 ID="29" X="336" Y="300" Name="29. Planes de desarrollo" Repeat="3" Type="3" MaxUser="1" UserTeam="15" NeedID="27" UserShip="3000000" Count="6" EctypeID="28" MaxGate="1" Exp="70000" Treasure="1528" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Todos los ejércitos con buena voluntad han firmado un plan destinado a favorecer el desarrollo. Sin embargo, será imposible poner dicho plan en práctica hasta que el mayor grupo de piratas de la galaxia sea eliminado."/>
	<Ectype12 ID="30" X="342" Y="366" Name="30. Gloria" Repeat="3" Type="3" MaxUser="1" UserTeam="15" NeedID="28" UserShip="3000000" Count="6" EctypeID="29" MaxGate="1" Exp="73500" Treasure="1529" Comment="Destruye todas las naves enemigas en esta ronda." Comment2="Mogrini es uno de los dignatarios con más prestigio de la galaxia. Por desgracia para él, en una ocasión fue capturado por los piratas, que a punto estuvieron de matarlo. Este desafortunado incidente, causa de deshonor, está a menudo en boca de todos a pesar de la excelente labor de Mogrini. Por su parte, el dignatario ha centrado sus esfuerzos en prepararse para acabar con los piratas y limpiar así su buen nombre."/>
</Instance>;
      
      public function GameRes_InstanceXml()
      {
         super();
      }
   }
}

